Добавляет в доку статью о селекторе по тегу
Y-Doka/y-doka.site pull request #188
Opened 2020-11-29 13:10 UTC by ezhkov

2020-11-29 20:37 UTC, pepelsbey requested changes

2020-11-29 20:37 UTC, pepelsbey commented on src/posts/css/doka/tag-selector.md
> +  border-bottom: 1px dashed coral; /* Имитировали пунктирное подчеркивание при помощи нижней границы */
```suggestion
  border-bottom: 1px dashed coral; /* Имитировали пунктирное подчеркивание при помощи нижней рамки */
```

2020-11-29 20:37 UTC, pepelsbey commented on src/posts/css/doka/tag-selector.md
> +Селектор по тегу находит элемент на странице по имени тега
```suggestion
Селектор по тегу находит элемент на странице по имени тега.
```

2020-11-29 20:37 UTC, pepelsbey commented on src/posts/css/doka/tag-selector.md
> +❗ Старайтесь не злоупотреблять селектором по тегу из-за его очень широкого охвата. Правила, написанные для тега, будут применены ко всем таким тегам на странице вне зависимости от вложенности и задан
```suggestion
❗ Старайтесь не злоупотреблять селектором по тегу из-за его очень широкого охвата. Правила, написанные для тега, будут применены ко всем таким тегам на странице вне зависимости от вложенности и заданных атрибутов. Это может привести к нежелательным последствиям. Яркий пример — мы задали стиль подчеркивания для всех ссылок при помощи селектора по тегу:
```

2020-11-30 02:45 UTC, solarrust commented on src/posts/css/doka/tag-selector.md
> +🛠 Чаще всего этот селектор применяется в самом начале работы над страницей, чтобы переопределить встроенные стили браузера для некоторых тегов. Например, сразу определить стили для тегов заголовков и
Было бы здорово, если бы ты добавил примеры к этим двум советам. Возьми какие-нибудь стандартные правила.

2020-12-01 18:44 UTC, ezhkov commented on src/posts/css/doka/tag-selector.md
> +🛠 Чаще всего этот селектор применяется в самом начале работы над страницей, чтобы переопределить встроенные стили браузера для некоторых тегов. Например, сразу определить стили для тегов заголовков и
Готово

2020-12-02 00:44 UTC, solarrust approved these changes

2020-12-14 09:31 UTC, solarrust commented on src/posts/css/doka/tag-selector.md
> +title: Селектор по тегу (div {})
Оберни, пожалуйста, title в кавычки.

2020-12-19 10:14 UTC, solarrust commented on src/posts/css/doka/tag-selector.md
> +title: Селектор по тегу (div {})
```suggestion
title: "Селектор по тегу (div {})"
```

2020-12-19 10:14 UTC, solarrust commented on src/posts/css/doka/tag-selector.md
> +❗ Старайтесь не злоупотреблять селектором по тегу из-за его очень широкого охвата. Правила, написанные для тега, будут применены ко всем таким тегам на странице вне зависимости от вложенности и задан
```suggestion
:::callout❗ 
Старайтесь не злоупотреблять селектором по тегу из-за его очень широкого охвата. Правила, написанные для тега, будут применены ко всем таким тегам на странице вне зависимости от вложенности и заданных атрибутов. Это может привести к нежелательным последствиям. 
:::

Яркий пример — мы задали стиль подчеркивания для всех ссылок при помощи селектора по тегу:
```

2020-12-19 10:15 UTC, solarrust commented
@pepelsbey как бы ты предложил назвать эту статью дл сохранения консистентности?

2020-12-19 10:19 UTC, pepelsbey commented
Мне кажется в этом месте мы достигли кризиса нейминга: мы не можем понятно назвать статью кодом, кажется нужно ввести слова. Я подумаю и предложу.

2020-12-25 11:24 UTC, solarrust commented
@pepelsbey есть идеи по названию этой статьи? Пора бы смёржить =)

2020-12-25 11:27 UTC, pepelsbey commented
Я бы пока сделал `tag` или `element` (первое используется у нас, второе фактически точнее), а отдельно бы созвонился обсудить #404 и как нам быть с неймингом.

2020-12-28 11:42 UTC, solarrust commented
@ezhkov поправишь название? И будем мёржить

2020-12-29 06:31 UTC, ezhkov commented
А может быть 

> @ezhkov поправишь название? И будем мёржить

Мы сейчас про какое именно название? Про поле `title`? Типа: `title: "Селектор по тегу (tag)"`?

2020-12-29 08:40 UTC, pepelsbey commented
Учитывая, что у нас сейчас нет системы, то я бы назвал понятно «Селектор по тегу», иначе просто «tag» не будет понятно. А потом созвониться авторами и обсудить систему именования.

2020-12-29 08:42 UTC, solarrust commented on src/posts/css/doka/tag-selector.md
> +title: "Селектор по тегу (div {})"
```suggestion
title: "Селектор по тегу"
```

2020-12-29 08:44 UTC, solarrust commented
@pepelsbey на подумать: называть статьи "как положено" — "селектор по тегу", "селектор по атрибуту", "селектор потомков" и так далее

2021-01-12 12:15 UTC, pepelsbey approved these changes

2021-01-14 16:17 UTC, merged