Новая дока по <legend>
Y-Doka/y-doka.site pull request #193
Opened 2020-11-30 04:09 UTC by Realetive

2020-11-30 04:17 UTC, solarrust commented on src/posts/html/doka/legend.md
> +author: vladimir
Тут надо вписать актуальную информацию

2020-11-30 04:17 UTC, solarrust commented on src/posts/html/doka/legend.md
> +Добавляет заголовок в `<fieldset>`, который по умолчанию оформляется брузером как текст, органично вписанный в рамку (стиль оформления зависит от браузера и операционной системы).
Давай добавим скрины с разницей оформления в разных браузерах

2020-11-30 04:17 UTC, solarrust commented on src/posts/html/doka/legend.md
> +`<fieldset>` позволяет описать содержимое `<fieldset>`, но семантически он не является «представителем» h1-h6-заголовков, хотя выполняет схожую функцию, только без здния иерархии, а лишь характеризуя
здния — опечатка

2020-11-30 04:17 UTC, solarrust commented on src/posts/html/doka/legend.md
> +
Давай в этот раздел в виде списка вынесем что легенда должна быть первой, а если она не одна, то применится только первый и про выравнивание. А пример стилизации вынесем в блок "В работе"

2020-11-30 04:17 UTC, solarrust commented on src/posts/html/doka/legend.md
> +<p class="codepen" data-height="347" data-theme-id="light" data-default-tab="css,result" data-user="Realetive" data-slug-hash="BaLybry" data-preview="true" style="height: 347px; box-sizing: border-bo
Внутри примера: если display и text-align для legend не применяется, то зачем их прописывать в CSS?

2020-11-30 04:55 UTC, Realetive commented on src/posts/html/doka/legend.md
> +Добавляет заголовок в `<fieldset>`, который по умолчанию оформляется брузером как текст, органично вписанный в рамку (стиль оформления зависит от браузера и операционной системы).
М. б. тогда и в `<formfield>` продублировать?

2020-11-30 04:57 UTC, Realetive commented on src/posts/html/doka/legend.md
> +<p class="codepen" data-height="347" data-theme-id="light" data-default-tab="css,result" data-user="Realetive" data-slug-hash="BaLybry" data-preview="true" style="height: 347px; box-sizing: border-bo
Проверял — забыл убрать. А м. б. оставить, но дополнить комментариями, что «эти свойства не будут иметь ожидаемого эффекта — используйте атрибут» ?

2020-11-30 05:13 UTC, solarrust commented on src/posts/html/doka/legend.md
> +Добавляет заголовок в `<fieldset>`, который по умолчанию оформляется брузером как текст, органично вписанный в рамку (стиль оформления зависит от браузера и операционной системы).
Можно, да

2020-11-30 05:14 UTC, solarrust commented on src/posts/html/doka/legend.md
> +<p class="codepen" data-height="347" data-theme-id="light" data-default-tab="css,result" data-user="Realetive" data-slug-hash="BaLybry" data-preview="true" style="height: 347px; box-sizing: border-bo
Не стоит путать людей 😏

2021-01-12 12:14 UTC, pepelsbey commented
@Realetive допилишь? :)

2021-01-12 12:27 UTC, Realetive commented
@pepelsbey да, конечно. Я ещё «новогодничаю» до четверга.

2021-01-25 07:46 UTC, solarrust commented
@Realetive нужно добить в ближайшее время

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +Добавляет заголовок в `<fieldset>`, который по умолчанию оформляется брузером как текст, органично вписанный в рамку (стиль оформления зависит от браузера и операционной системы).
Лучше то, что в скобках отдельным предложением написать.

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +```
Пенчик бы с визуальным отображением

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +Добавляет заголовок в `<fieldset>`, который по умолчанию оформляется брузером как текст, органично вписанный в рамку (стиль оформления зависит от браузера и операционной системы).
Ссылочку на статью про `<fieldset>` надо бы добавить

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +`<fieldset>` позволяет описать содержимое `<fieldset>`, но семантически он не является «представителем» h1-h6-заголовков, хотя выполняет схожую функцию, только без задания иерархии, а лишь характериз
Давай разобьём на пару-тройку предложений, а то воздуха не хватает прочитать.

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +**Важно**, чтобы `<legend>` был первым дочерним элементом внутри `<fieldset>`.
это бы в :::callout обернуть. [Как тут](https://y-doka.site/css/doka/attribute-selector/#%5Battr%3Dvalue%5D-или-%5Battr%3D%22value%22%5D)

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +**Важно**, чтобы `<legend>` был первым дочерним элементом внутри `<fieldset>`.
А ниже показать пару примеров: один правильный и второй неправильный. Чтобы наглядно было видно в каком месте ломается, если не соблюсти правило.

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +У `<legend>` нет никаких «своих» атрибутов, ему доступны все *глобальные атрибуты*. Но для выравнивания текста по краю или по центру не обойтись без атрибута `align` (CSS-свойство `text-align` работа
Дать ссылочку на статью про глобальные атрибуты.

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +У `<legend>` нет никаких «своих» атрибутов, ему доступны все *глобальные атрибуты*. Но для выравнивания текста по краю или по центру не обойтись без атрибута `align` (CSS-свойство `text-align` работа
То, что в скобочках надо вынести в отдельное предложение и поставить первым. А дальше уже про атрибут `align`.

2021-02-02 04:30 UTC, solarrust commented on src/posts/html/doka/legend.md
> +<table>
Маркдауновская таблица не сработает тут?

2021-02-02 09:35 UTC, pepelsbey requested changes
Стоит
- Убрать про align
- Заменить таблицы на figure

2021-02-02 09:35 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +У `<legend>` нет никаких «своих» атрибутов, ему доступны все *глобальные атрибуты*. Но для выравнивания текста по краю или по центру не обойтись без атрибута `align` (CSS-свойство `text-align` работа
Важно упомянуть, что атрибут `align`  нестандартный, его нет в спецификации, его поведение непредсказуемо и его не рекомендуется использовать. Чтобы выровнять `<legend>`, нужно его растянуть на всю ширину и тогда `text-align` [заработает](https://codepen.io/pepelsbey/pen/WNovEQK).

2021-02-02 09:35 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +<table>
Удивительно, но в этой статье таблицы используются для того, чтобы поставить рядом две картинки с подписями. У меня флэшбэки из начала нулевых, _зошто_. Может быть мы используем нормальные теги `<figure>` и поставим задачу придумать тип картинок «стоят рядом»? Это нужно в стилях делать.

2021-02-02 17:37 UTC, Realetive commented
Можно и без растягивания ширины — `<legend>` имеет блочный контекст, но уникальную инлайн-блочную контекстую модель содержимого, которая и создаёт неповторимую обводку от `<fieldset>` — это и хотел продемонстрировать в демке. Про `align`, да, пример лучше убрать — перепишу на CSS и добавлю пояснение, как выровнять содержимое без задания фиксированной ширины и почему `text-align` не работает.

2021-02-02 17:47 UTC, Realetive commented on src/posts/html/doka/legend.md
> +<table>
Я больше думал про отображение на GitHub'е, чем о «семантике ради семантики». Нам важна «совместимость» с GitHub-отображением? Хотя, мне идея с `<figure>` тоже больше нравится.

2021-02-02 20:29 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +<table>
Мы вообще не рассматриваем отображение на Гитхабе как цель, насколько я понимаю. Да, удобно, что маркдаун хорошо рендерится в ридми, но читать нас будут на сайте и ради этого использовать таблицы не стоит.

2021-02-02 21:13 UTC, Realetive commented on src/posts/html/doka/legend.md
> +<table>
Понял. Исправлю.

2021-02-08 08:41 UTC, solarrust commented
@Realetive надо добить сегодня. Пожалуйста!

2021-02-18 03:30 UTC, Realetive commented on src/posts/html/doka/legend.md
> +:::
Странно, но у меня почему-то не срабатывает `:::callout`…

```suggestion
:::callout 💡
**Важно**, чтобы `<legend>` был первым дочерним элементом внутри `<fieldset>`. Если внутри `<fieldset>` будет больше одного `<legend>`, отобразится только первый, все остальные отобразятся как обычные блочные элементы:
:::
```

2021-02-22 17:03 UTC, pepelsbey requested changes
Предложил пару мелочей и убрать «переносные» значения слов, они вполне прямые.

2021-02-22 17:03 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +За счёт особой формы «обтекания» рамкой текста, это можно использовать для характерной стилизации блока и заголовка:
```suggestion
За счёт особой формы обтекания рамкой текста, это можно использовать для характерной стилизации блока и заголовка:
```

2021-02-22 17:03 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +designers:
Мы договорились без пустых полей

```suggestion
```

2021-02-22 19:01 UTC, Realetive commented on src/posts/html/doka/legend.md
> +:::
Иконка — ок, но теперь первое предложение какое-то оборванное.

2021-02-23 00:03 UTC, pepelsbey commented on src/posts/html/doka/legend.md
> +:::
Ой, глупил. Поправил :)

2021-02-23 09:20 UTC, pepelsbey approved these changes

2021-02-23 09:47 UTC, solarrust approved these changes

2021-02-23 09:47 UTC, merged