[WIP]: Добавляет статью о рекурсии
Y-Doka/y-doka.site pull request #206
Opened 2020-11-30 19:25 UTC by bespoyasov

2020-12-01 20:53 UTC, nlopin requested changes

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +Повторяющиеся операции могут быть довольно сложными и включать в себя несколько подзадач. Такое, например, часто встречается в математике.
```suggestion
Повторяющиеся операции могут быть сложными и включать в себя несколько подзадач. Такое, например, часто встречается в математике.
```

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +- Отлаживать рекурсию значительно сложнее, чем цикл. (А если функция написана плохо — то и просто читать.)
я бы это на первое место поставил

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +- Циклом гораздо сложнее обходить вложенные структуры данных, как например каталоги файлов.
```suggestion
- Циклом гораздо сложнее обходить вложенные структуры данных. Например, каталоги файлов.
```

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +- При работе с общими ресурсами или асинхронными задачами чаще удобнее использовать рекурсивные функции из-за замыканий.
Добавь ссылку на замыкания

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +Давайте теперь попробуем решить одну и ту же задачу с использованием цикла и рекурсии, чтобы увидеть разницу в подходах. Будем писать функцию для нахождения факториала.
```suggestion
Давайте решим одну и ту же задачу с использованием цикла и рекурсии, чтобы увидеть разницу в подходах. Будем писать функцию для нахождения факториала.
```

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +_Факториал числа_ — это произведение всех чисел от единицы до этого числа.
Добавь пример, пожалуйста

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +<aside class="callout">
Давай этот калаут уберем, я не понял, зачем он. или объясни

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +Одна из двух составляющих рекурсии — это повторяющиеся операции. В примере с возведением в степень — это умножение.
Давай выше скажем, что рекурсивные функции состоят из двух штук: базового случая и повторяющихся операций-подзадач.

Сейчас переход от примера к деталям резкий

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +## Структуры данных и обходы
Кажется название раздела не очень ложится. Смотри, что сейчас получается:
* Рекурсия и программирование
* рекурсия и циклы
* структуры данных?

Мне нравится материал, но я бы перекомпоновал в такую стркутуру разделов:
* Рекурсия в программировании
* рекурсия и циклы
* Когда использовать рекурсию
* Когда использовать циклы

что думаешь?

2020-12-01 20:53 UTC, nlopin commented on src/posts/js/long/recursion.md
> +## Рекурсия в программировании
надо сказать, что рекурсия в программировани === функция

2020-12-02 09:14 UTC, bespoyasov commented on src/posts/js/long/recursion.md
> +## Структуры данных и обходы
Я думаю, лучше сделать так:
- Рекурсия в программировании;
- Цикл и рекурсия;
- Рекурсивные структуры данных;
- Когда использовать рекурсию;
- Когда использовать цикл.

Иначе теряется важная часть материала, потому что рекурсия — это не только функции, но ещё и структуры данных.

Обновил.

2020-12-02 09:14 UTC, bespoyasov commented on src/posts/js/long/recursion.md
> +## Рекурсия в программировании
Это будет фактической ошибкой; кроме функций есть рекурсивные структуры данных. 

Я перенёс предыдущий абзац в начало этого раздела. Про структуры заранее писать не стал, чтобы не наваливать слишком много сразу. 

Во введении раздела о структурах «налил клея», чтобы связать самое начало и раздел:
«Раньше мы упомянули, что в программировании _чаще всего_ под рекурсией понимают функцию, которая вызывает сама себя. Но кроме рекурсивных функций ещё есть рекурсивные структуры данных».

2020-12-02 09:27 UTC, nlopin requested changes
Микро замечания остались, давай обсудим. 

Я хочу сделать временные схемки получше, чтобы не мержить в мастер фотки. Добавлю сам и дам тебе знать

2020-12-02 09:27 UTC, nlopin commented on src/posts/js/long/recursion.md
> +## Рекурсия в программировании
Согласен

2020-12-02 09:27 UTC, nlopin commented on src/posts/js/long/recursion.md
> +<aside class="callout">
давай буллетами сделаем. Много колаутов === нет колаутов

2020-12-02 09:27 UTC, nlopin commented on src/posts/js/long/recursion.md
Я бы добавил, что по умолчанию лучше всегда использовать цикл и переходить к рекурсии только когда она оправдана

2020-12-02 10:19 UTC, bespoyasov commented on src/posts/js/long/recursion.md
Я наоборот перехожу от рекурсии к циклу, лишь когда это оправдано — например, когда рекурсия не читается. 
Возможно, это потому что я чаще работаю с ФП, но всё же.

> переходить к рекурсии только когда она оправдана

А когда она оправдана?
Не могу придумать эвристику, при которой бы от цикла переходил к рекурсии, а не наоборот.

Я последние два раздела скорее вижу, как ситуации, когда «вот прям» стоит предпочесть один способ второму. Умолчаний я бы давать никаких не стал.

Дискас?

2020-12-02 10:23 UTC, bespoyasov commented on src/posts/js/long/recursion.md
> +<aside class="callout">
✅

2020-12-02 12:21 UTC, nlopin commented on src/posts/js/long/recursion.md
у меня скорее подход наоборот — пиши цикл там, где точно не нужна рекурсия. Он дешевле и читается линейно. В функциональных языках циклов нет и там рекурсия воспринимается нормально. 

Представим начинающего разработчика. Мы точно хотим ему сказать, что нужно предпочитать рекурсии циклам? Можно ничего не говорить, это тоже вариант

2020-12-02 12:26 UTC, nlopin approved these changes
Не мержи, я добавлю картинки

2020-12-02 12:28 UTC, bespoyasov commented on src/posts/js/long/recursion.md
Я за подход «не давать никаких умолчаний»; в статье я показываю, что есть, какие плюсы и минусы. 

Что разработчики захотят использовать — это уже другая зона ответственности. Мы не можем говорить, «как правильно», потому что никак не правильно 😃

В командных проектах им будет лучше использовать то, что принято в команде. В собственных — что нравится больше. Не хочется случайно отбить желание попробовать рекурсию (или цикл), сказав, что рекурсия сосёт (или цикл 😃).

2020-12-02 12:29 UTC, bespoyasov commented on src/posts/js/long/recursion.md
Если я где-то в статье предпочитаю одно другому, то укажи, пожалуйста — я исправлю. (Мне кажется, я такого не допускал.)

2020-12-02 12:30 UTC, bespoyasov commented
Йеп, помню 🙂

2020-12-02 13:16 UTC, nlopin commented on src/posts/js/long/recursion.md
Везде все корректно. Закрываю эту ветку дискуссии. Было полезно

2020-12-06 17:04 UTC, merged