Added contributors block
Y-Doka/y-doka.site pull request #213
Opened 2020-12-01 18:28 UTC by usmanyunusov

2020-12-01 19:50 UTC, nlopin commented
Спасибо за контрибьюшн! 

![](https://media.giphy.com/media/l4JyOCNEfXvVYEqB2/giphy.gif)

2020-12-03 20:29 UTC, nlopin requested changes
Мне нравится. Нужно поправить только svg

@solarrust помоги со стилями пожалуста

2020-12-03 20:29 UTC, nlopin commented on src/includes/contributors/contributors-all.njk
> +                        <path d="M12 0C5.37375 0 0 5.37375 0 12C0 18.6262 5.37375 24 12 24C18.6262 24 24 18.6262 24 12C24 5.37375 18.6262 0 12 0ZM17.4792 9.35625C17.4844 9.47438 17.4872 9.59297 17.48
Давай все svg вынесем в отдельный файл и будем подключать инклудом. Сейчас они создают много шума

2020-12-04 07:07 UTC, solarrust commented on src/includes/contributors/contributors-all.njk
> +                        <path d="M12 0C5.37375 0 0 5.37375 0 12C0 18.6262 5.37375 24 12 24C18.6262 24 24 18.6262 24 12C24 5.37375 18.6262 0 12 0ZM17.4792 9.35625C17.4844 9.47438 17.4872 9.59297 17.48
Поддерживаю

2020-12-04 07:27 UTC, solarrust commented
1. Было бы очень круто сделать появление / скрытие блока с авторами плавным, чтобы страница резко не дёргалась. 
2. Давай завяжем отступы и размеры на относительных единицах? 
3. К соц.ссылочкам внутрь нужно положить скрытые подсказочки текстовые для скринридеров, а то в них нет текста, нечего читать. 
4. В блоке с одним автором `contributors__socials` сделан дивом, а в блоке с множеством авторов у итемов `contributors__socials` почему-то `span`. 🤔

@furtivite есть ли у нас адаптив для этого блока? На мобилке сложнонажимаемо получается

2020-12-04 07:51 UTC, furtivite commented
@solarrust у нас нет адаптива по этому блоку, я сейчас его тоже в срочные закину тогда.

2020-12-04 17:29 UTC, usmanyunusov commented
@furtivite, @nlopin завел новую папку people, так внутри папки includes нельзя создавать коллекции (данные просто не видны).

Чуть позже доделаю предложения @solarrust

2020-12-05 15:34 UTC, pepelsbey commented
@usmanyunusov кажется у вас нет плагина EditorConfig в редакторе, поставите? А то в файлах нет [финального перевода строки](https://github.com/Y-Doka/y-doka.site/blob/master/.editorconfig#L37).

<img width="464" alt="image" src="https://user-images.githubusercontent.com/105274/101247140-82f13f00-3728-11eb-8e5a-03c1d93f833c.png">

Надо бы уже доделать и смёржить [тесты](https://github.com/Y-Doka/y-doka.site/pull/62).

2020-12-06 12:01 UTC, pepelsbey requested changes

2020-12-06 12:01 UTC, pepelsbey commented on src/includes/contributors/contributors.njk
> +              {% include 'svg/twitter.njk' %}
```suggestion
              {% include 'assets/icons/twitter.svg' %}
```
Я бы лучше написал так и положил картинки в `assets/icons`, это позволит хранить иконки в нужном месте и как SVG-файлы. Системные инклюды Eleventy для шаблонов, а тут декоративная графика всякая.

2020-12-06 18:17 UTC, usmanyunusov commented on src/includes/contributors/contributors.njk
> +              {% include 'svg/twitter.njk' %}
@pepelsbey иконки разместил в отдельную папку

2020-12-06 20:12 UTC, nlopin approved these changes
На мой взгляд все ок. 

Я не уверен, какие относительные единицы мы хотим видеть `em` или `rem`. @solarrust давай смержим этот пиар и сформулируем принципы верстки в этом репозитории

2020-12-07 08:11 UTC, solarrust approved these changes

2020-12-07 08:12 UTC, furtivite approved these changes

2020-12-07 09:16 UTC, solarrust approved these changes

2020-12-07 09:18 UTC, furtivite approved these changes

2020-12-07 10:40 UTC, pepelsbey commented
@nlopin нет такого выбора «емы или ремы», есть выбор «пиксели или ремы» (для основы), а емы нужны всегда. В этом случае, они обеспечивают привязку размеров иконки к размеру шрифта — очень правильно.

2020-12-11 08:52 UTC, pepelsbey approved these changes

2020-12-11 08:53 UTC, merged

2020-12-11 08:53 UTC, pepelsbey commented
Тут пока случайные картинки в профилях (буквально random), может их заменить, перед мёржем?