Добавляет руководство для авторов
Y-Doka/y-doka.site pull request #307
Opened 2020-12-06 10:42 UTC by furtivite

Подготовлено руководство, которое позволит сразу писать тексты в нужном стиле.

2020-12-06 12:10 UTC, nlopin approved these changes

2020-12-06 12:15 UTC, pepelsbey requested changes

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +# WRITING.md
```suggestion
# Руководство для авторов
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +Дока всегда развивается. Ты можешь писать статьи, помогать с разработкой или редактированием. Ты можешь всё! Прекрасный мир open source 🧚‍♀️
```suggestion
Дока всегда развивается. Ты можешь писать статьи, помогать с разработкой или редактированием. Ты можешь всё! Прекрасный мир опенсорса 🧚‍♀️
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +Прочитайте [Руководство контрибьютора](https://github.com/Y-Doka/y-doka.site/blob/master/CONTRIBUTING.md), чтобы сделать первый пул-реквест
```suggestion
Прочитайте [руководство контрибьютора](https://github.com/Y-Doka/y-doka.site/blob/master/CONTRIBUTING.md), чтобы сделать первый пул-реквест.
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +Рекомендуем прочитать книгу [Максима Ильяхова и Людмилы Сарычевой Пиши, сокращай"](https://book.glvrd.ru/).
```suggestion
Рекомендуем прочитать книгу [«Пиши, сокращай»](https://book.glvrd.ru/) Максима Ильяхова и Людмилы Сарычевой.
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +    — Лучше всего "вы"
```suggestion
    — Гендерно-нейтрально или на «вы», если не получается («вы» всегда с маленькой)
    — Можно обращаться на «ты» в примерах «В работе»
    — Лучше всего «вы»
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +7. Если уже есть статья, с более подробным описанием упоминаемого функционала, стоит сделать ссылку на неё
```suggestion
7. Если уже есть более подробная статья о том же, стоит сделать ссылку на неё
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +8. Если для выполнения кода нужно специальное ПО или операционная система, укажите какая
```suggestion
8. Если для выполнения кода нужно специальный софт или окружение, укажите какое
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +    В разделе "В работе" можно быть менее формальным. Тут можно написать про конкретные практики применения, но весь негатив будет жёстко вычищаться редактором.
```suggestion
    В разделе «В работе» можно быть менее формальным. Тут можно написать про конкретные практики применения, но весь негатив будет жёстко вычищаться редактором.
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +    <!-- ТАК ДЕЛАТЬ НЕЛЬЗЯ -->
А точно нужно кричать капсом? Мы вроде такие стильные здесь, может хватит восклицания?
```
    <!-- Так делать нельзя! -->
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +    Если, всё же, использовали HTML, оставьте до и после него пустую строку. Это нужно, чтобы 11ty смог скомпилировать страницу ниже этого кода.
```suggestion
    Если вы всё же использовали HTML, то чтобы вложенный маркдаун обработался, нужно отбить вложенный контент пустыми строками.
```

2020-12-06 12:15 UTC, pepelsbey commented on WRITING.md
> +8. Если нужен пример кода, используем [БЭМ](https://ru.bem.info/) и [AirBnB Code Style Guide](https://github.com/airbnb/javascript)
```suggestion
8. Если нужен пример кода, то для HTML и CSS используем [БЭМ](https://ru.bem.info/), а для JavaScript — [AirBnB Code Style Guide](https://github.com/airbnb/javascript)
```

2020-12-06 12:19 UTC, pepelsbey commented
Есть такой «генеральский» падеж, который любят авторитарные руководители или наглые люди:

— Проходим быстрее, не задерживаемся!
— Тут встаём в кружок и делаем счастливые лица!

Я бы постарался его избежать во всех текстах: это звучит старомодно и даже грубовато. Я понимаю, что подразумеваяется «(мы) не делаем лишних отступов», но иногда звучит «так, не делаем лишних отступов».

Я бы лучше писал «не делайте лишних отступов», это точно будет лучше и прямо обращается к читателю.

2020-12-08 19:04 UTC, furtivite commented on WRITING.md
> +    <!-- ТАК ДЕЛАТЬ НЕЛЬЗЯ -->
Ну раз нельзя, то, предполагалось, что это точно должно было быть видно, поэтому когда-то давно договорились выделять крупно. 

@nlopin @solarrust что думаете?

2020-12-08 19:08 UTC, furtivite commented on WRITING.md
> +    Если, всё же, использовали HTML, оставьте до и после него пустую строку. Это нужно, чтобы 11ty смог скомпилировать страницу ниже этого кода.
Если вам нужен HTML, то чтобы движок правильно обработал страницу, между маркдауном и HTML-кодом нужна пустая строка. 

Может так?

2020-12-08 19:52 UTC, pepelsbey commented on WRITING.md
> +    Если, всё же, использовали HTML, оставьте до и после него пустую строку. Это нужно, чтобы 11ty смог скомпилировать страницу ниже этого кода.
Норм!

2020-12-08 19:56 UTC, solarrust commented on WRITING.md
> +    <!-- ТАК ДЕЛАТЬ НЕЛЬЗЯ -->
Мне не принципиально, главное чтобы перед неправильным куском кода было предупреждение что это неправильно.

2020-12-10 17:33 UTC, solarrust approved these changes

2020-12-21 15:05 UTC, pepelsbey requested changes

2020-12-21 15:05 UTC, pepelsbey commented on WRITING.md
> +7. Если уже есть статья, с более подробным описанием упоминаемого функционала, стоит сделать ссылку на неё
А что не так с этим предложением? Мне фраза «подробным описанием упоминаемого функционала» кажется слишком сложной. Ильяхову бы не понравилось.

2020-12-21 15:05 UTC, pepelsbey commented on WRITING.md
> +9. Если нужны эмодзи, используем. [Можно взять отсюда](https://ru.piliapp.com/emoji/list/).
Это самая сомнительная часть: непонятна мысль, которая здесь выражается. Эмодзи **нужно** использовать или **можно** использовать? Кажется, как будто разрешает. Я бы убрал, пока нет точной рекомендации когда и как использовать. Чтобы это не прозвучало как «ВЕЗДЕ! БОЛЬШЕ».

2020-12-21 15:09 UTC, furtivite commented on WRITING.md
> +9. Если нужны эмодзи, используем. [Можно взять отсюда](https://ru.piliapp.com/emoji/list/).
@pepelsbey давай напишем так: 

9. Эмодзи можно использовать в разумных пределах. Необходимые возьмите [здесь](https://ru.piliapp.com/emoji/list/).

Просто мы уже используем эмодзи, отказываться от них странно, мы же добрая дока и всё такое, и все понимают, что стиль ссмщиков нам не подходит.

2020-12-21 15:56 UTC, pepelsbey approved these changes

2020-12-21 15:56 UTC, pepelsbey commented
:shipit:

2020-12-21 20:53 UTC, merged