Добавляет черновик статьи о подгрузке контента по скроллу
Y-Doka/y-doka.site pull request #316
Opened 2020-12-08 11:17 UTC by bespoyasov

Закрывает https://github.com/Y-Doka/y-doka.site/issues/197.

- [ ] Я в этой статье уже использую ссылки на `throttle` и `debounce`. Когда мы их добавим, надо будет проверить, что не ссылки не превратились в тыкву 😅

2020-12-08 13:29 UTC, nlopin commented
Очень много кода получилось. Я статью не осилил :(

У меня есть несколько идей:
* очень не хватает схем, чтобы понять общую картину
* опустить историю про сервер или убрать ее под toggle
* про URL мы говорим, что это проблема, но тут же сообщаем, что решать ее полностью не будем. Предлагаю тогда сделать раздел, в котором расскажем, что еще можно накрутить поверх базового функционала, но не реализовывать ничего оттуда.

2020-12-08 15:43 UTC, bespoyasov commented
> Отдельно большая задача на следующий год — как-то разделить код и объяснения кода. Сейчас мы это делаем с помощью комментариев и получается больше комментов, чем кода. Код становится сложно читать

Всё уже придумано 😉
https://bespoyasov.ru/ttt-tdd/

2020-12-08 16:43 UTC, bespoyasov commented
Нашёл: https://wattenberger.com/blog/react-hooks.

2020-12-10 21:33 UTC, nlopin requested changes

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +title: Подгрузка контента по скроллу
```suggestion
title: Подгрузка контента при прокрутке
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +### Длинное время исполнения
```suggestion
### Долгое время исполнения
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +### Меньшее удобство работы
```suggestion
### Неудобно для работы
```

Странная фраза кмк

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Стратегий борьбы с лишним кодом много [код-сплиттинг](/posts/js/long/web-app-works/#код-сплиттинг) и минификация, оптимизация изображений, кэширование, рефакторинг и удаление старого кода. С контенто
```suggestion
Стратегий борьбы с лишним кодом много: [код-сплиттинг](/posts/js/long/web-app-works/#код-сплиттинг) и минификация, оптимизация изображений, кэширование, рефакторинг и удаление старого кода.
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +С одной стороны мы так же не хотим загружать то, что пользователю не нужно, с другой стороны мы не можем знать, что именно пользователю понадобится. Мы не можем предсказать, на какую страницу пользов
```suggestion
С контентом ситуация и похожа, и непохожа одновременно. С одной стороны, мы так же не хотим загружать то, что пользователю не нужно, с другой стороны — мы не знаем, что именно пользователю понадобится и не можем предсказать, на какую страницу пользователь решит перейти. Да и сам контент может постоянно меняться — как в соцсетях.
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +С одной стороны мы так же не хотим загружать то, что пользователю не нужно, с другой стороны мы не можем знать, что именно пользователю понадобится. Мы не можем предсказать, на какую страницу пользов
Перенес предложение из предыдщего абзаца. Потому что оно относится к теме этого абзаца

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Их и сейчас можно встретить, например на Google.com:
```suggestion
Их и сейчас можно встретить, например, на Google.com:
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Как в [статье с примером реализации `debounce`](/posts/js/long/debounce), первым делом мы сделаем заглушку для сервера, чтобы имитировать запросы к нему. Для краткости мы скроем шаг с созданием.
Я вот думаю, нужна ли здесь отсылка к статье, которая нерелевантна? Все, что их связывает — это факт, что мы в обеих писали заглушку сервера.

Давай перефразируем без отсылки?

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Мы хотим подгружать новый контент, когда пользователь докручивает до конца страницы. Здесь мы можем выделить несколько задач. М
```suggestion
Мы хотим подгружать новый контент, когда пользователь докручивает до конца страницы. Здесь можно выделить несколько задач:
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +- Нам нужно следить за положением прокрутки. Когда мы приближаемся к концу страницы, нам нужно отсылать запрос.
```suggestion
- Следить за положением прокрутки. Когда мы приближаемся к концу страницы, нужно запрашивать следующую порцию данных
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Дальше из этой вёрстки мы можем сделать шаблон для будущих свитов, которые мы будем загружать с сервера. Шаблон нам нужен, потому что с сервера мы будем загружать только данные. Как эти данные должны
```suggestion
Из этой вёрстки мы сделаем шаблон для будущих свитов, которые мы будем загружать с сервера. Шаблон нужен, потому что с сервера мы будем загружать только данные. Как эти данные должны отображаться, сервер не знает. Шаблон будет нужен именно для этого — чтобы браузер мог правильно отобразить данные на странице.
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Если мы добавим этот кусок кода на страницу, визуально ничего не изменится, но у нас появится возможность «штамповать» новые свиты с помощью JS-кода. Подробнее об этом мы поговорим чуть ниже.
```suggestion
Если мы добавим этот код на страницу, то визуально ничего не изменится, но у нас появится возможность «штамповать» новые свиты с помощью JS-кода. Подробнее об этом мы поговорим чуть ниже.
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Теперь сделаем эту функцию обработчиком события скролла и ресайза:
```suggestion
Теперь сделаем эту функцию обработчиком события прокрутки и изменения размера окна:
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Как мы помним из [статьи о `throttle`](/posts/js/long/throttle/), нам стоит немного притормаживать такие операции, чтобы они выполнялись чуть реже и таким образом меньше нагружали браузер.
Давай перефразируем, чтобы отсылка осталась, но не было «как мы помним». У нас нет никаких гарантий, что человек прочитал эту статью. 

Хорошо будет что-то в стиле «Частые события, такие, как прокрутка, происходят с большой частотой. Стандартный подход для таких событий [`throttle`](link) — обрабатывать одно событие и потом делать паузу.»

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Функция `appendPost` использует внутри себя `composePost`, напишем и её тоже:
```suggestion
Функция `appendPost` использует внутри себя `composePost`. Напишем и её тоже:
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +  // Обращаемся к нашему шаблону, который создали ранее:
```suggestion
  // Обращаемся к шаблону, который создали ранее:
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Если мы сейчас попробуем запустить приложение, оно будет работать. Но при прокрутке к концу страницы вместо одной порции контента будет присылать несколько. (И никогда не закончит это делать 😁)
```suggestion
Если сейчас запустить приложение, то оно будет работать. Но при прокрутке к концу страницы вместо одной порции контента будет присылать несколько. (И никогда не закончит это делать 😁)
```

2020-12-10 21:33 UTC, nlopin commented on src/posts/js/long/infinite-scroll.md
> +Чтобы решить эти проблемы нам нужно завести переменные, которые будут следить за [состоянием приложения](/posts/js/long/web-app-works/#состояние-приложения):
```suggestion
Чтобы решить эти проблемы, нужно завести переменные, которые будут следить за [состоянием приложения](/posts/js/long/web-app-works/#состояние-приложения):
```

2020-12-10 21:34 UTC, nlopin commented
Давай придерживаться словаря и вместо скролл/скрол писать «прокрутка»

2020-12-11 08:26 UTC, bespoyasov commented on src/posts/js/long/infinite-scroll.md
> +### Меньшее удобство работы
Здесь я пытался в согласование заголовков:
- Дорогой трафик;
- Долгое время исполнения;
- Меньшее удобство работы.

Я перепишу иначе.

2020-12-11 08:31 UTC, bespoyasov commented on src/posts/js/long/infinite-scroll.md
> +Как в [статье с примером реализации `debounce`](/posts/js/long/debounce), первым делом мы сделаем заглушку для сервера, чтобы имитировать запросы к нему. Для краткости мы скроем шаг с созданием.
Done.

2020-12-11 08:32 UTC, bespoyasov commented on src/posts/js/long/infinite-scroll.md
> +### Меньшее удобство работы
Переписал в виде полных предложений.

2020-12-11 08:33 UTC, bespoyasov commented on src/posts/js/long/infinite-scroll.md
> +Как мы помним из [статьи о `throttle`](/posts/js/long/throttle/), нам стоит немного притормаживать такие операции, чтобы они выполнялись чуть реже и таким образом меньше нагружали браузер.
Done.

2020-12-11 08:38 UTC, bespoyasov commented
CI ругается на форматирование в другом файле. Он не относится к этому PR, думаю, лучше это отдельно поправить в мастере или отдельным PR.

2020-12-12 20:54 UTC, nlopin approved these changes
Классно переделал заголовки 👍

2020-12-12 20:55 UTC, merged