Добавляет статью о селекторе по атрибуту
Y-Doka/y-doka.site pull request #325
Opened 2020-12-09 20:01 UTC by ezhkov

2020-12-10 06:05 UTC, solarrust reviewed
Оставила комменты по статье. Давай пообсуждаем =)

2020-12-10 06:05 UTC, solarrust commented on src/posts/css/doka/attribute-selector.md
> + (Advert и advert — это разные значения с точки зрения браузера)
Давай про регистрозависимость вынесем куда-то в заметное место

2020-12-10 06:05 UTC, solarrust commented on src/posts/css/doka/attribute-selector.md
> +/* Теперь уберутся все три картинки */
"Уберутся куда подальше" 😄

2020-12-10 06:05 UTC, solarrust commented on src/posts/css/doka/attribute-selector.md
> +При помощи селектора по трибуту круто стилизовать ссылки, основываясь на значении атрибута `href`. Можно визуально разделять ссылки, ведущие на соседние страницы сайта, и ссылки, ведущие на другие са
```suggestion
При помощи селектора по атрибуту круто стилизовать ссылки, основываясь на значении атрибута `href`. Можно визуально разделять ссылки, ведущие на соседние страницы сайта, и ссылки, ведущие на другие сайты:
```

2020-12-10 06:05 UTC, solarrust commented on src/posts/css/doka/attribute-selector.md
> +<script async src="https://cpwebassets.sfo2.cdn.digitaloceanspaces.com/assets/embed/ei.js"></script>
```suggestion

```

Если в статье несколько пенов, то можно оставить загрузку скрипта только у последнего чтобы снизить количество запросов.

2020-12-10 06:09 UTC, solarrust commented
Пока читала возникла мысль: может быть сделаем пен, в котором в разметке будут разные элементы с атрибутами и при выборе определённого селектора будут подсвечиваться (или к ним будут применяться определённые стили) те элементы, которые селектор выбирает? Кажется так будет нагляднее.

2020-12-10 23:35 UTC, pepelsbey requested changes

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +Селектор ниже _найдёт_ все цитаты (`bockquote`) с атрибутом `cite`:
```suggestion
Селектор ниже _найдёт_ все цитаты (`blockquote`) с атрибутом `cite`:
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +<blockquote cite="А.С.Пушкин">
```suggestion
<blockquote cite="А. С. Пушкин">
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr~=value]` — селектор выбирает все элементы, значение атрибута `attr` которых — это перечень слов, разделенных пробелом, и среди этих слов есть такое, чьё значение равно `value`
```suggestion
`[attr~=value]` — селектор выбирает все элементы, значение атрибута `attr` которых — это перечень слов, разделенных пробелом, и среди этих слов есть такое, чьё значение равно `value`.
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr|=value]` — селектор выберет все элементы, значение атрибута `attr` которых либо в точности равно `value`, либо начинается с `value`, за которым следует символ дефиса `-` (U+002D). Подобный вар
```suggestion
`[attr|=value]` — селектор выберет все элементы, значение атрибута `attr` которых либо в точности равно `value`, либо начинается с `value`, за которым следует символ дефиса `-` (U+002D). Подобный вариант селектора чаще всего используется для выбора по коду языка (например `en-US` или `en-GB`).
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr^=value]` — селектор выберет все элементы, значение атрибута `attr` которых **наичнается** с `value`
```suggestion
`[attr^=value]` — селектор выберет все элементы, значение атрибута `attr` которых **начинается** с `value`.
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr$=value]` — селектор выберет все элементы, значение атрибута `attr` которых **оканчивается** на `value`
```suggestion
`[attr$=value]` — селектор выберет все элементы, значение атрибута `attr` которых **оканчивается** на `value`.
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +<a href="https://apple.it">Apple Italy</a>
```suggestion
<a href="https://apple.com/">Apple US</a>
<a href="https://apple.com/ru">Apple Russia</a>
<a href="https://apple.com/it">Apple Italy</a>
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +}
```suggestion
a::after {
  content: "🇺🇸";
}
a[href$="/ru"]::after {
  content: "🇷🇺";
}
a[href$="/it"]::after {
  content: "🇮🇹";
}
```
Так более жизненно (на самом деле такие ссылки)

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr operator value i]` — если добавить в скобки после значения атрибута `i` или `I`, то браузер будет игнорировать регистр сиволов
```suggestion
`[attr operator value i]` — если добавить в скобки после значения атрибута `i` или `I`, то браузер будет игнорировать регистр сиволов.
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +}
```suggestion
a[href="https://example.org"] {
  background-color: blue;
}
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +/* <a> elements whose class attribute contains the word "logo" */
```suggestion
/* Теги <a>, у которых атрибут class содержит слово logo */
```

2020-12-10 23:35 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +`[attr*=value]` — селектор выберет все элементы атрибут `attr` которых содержит в себе значение `value`
```suggestion
`[attr*=value]` — селектор выберет все элементы атрибут `attr` которых содержит в себе значение `value`.
```

2020-12-13 13:30 UTC, ezhkov commented
> Пока читала возникла мысль: может быть сделаем пен, в котором в разметке будут разные элементы с атрибутами и при выборе определённого селектора будут подсвечиваться (или к ним будут применяться определённые стили) те элементы, которые селектор выбирает? Кажется так будет нагляднее.

Я тоже думал об этом. На странице нужно показывать прямо HTML-код и подсвечивать элементы, да. Это довольно заморочно в реализации, может мы пока создадим issue на создание такого примера?

2020-12-13 19:48 UTC, ezhkov commented on src/posts/css/doka/attribute-selector.md
> +Этот тип селектора помогает нам стилизовать элементы, опираясь либо на наличие самого атрибута, либо на его значение. Мы можем стилизовать элементы, опираясь на следующие варианты записи селектора:
Поправлено

2020-12-13 19:48 UTC, ezhkov commented on src/posts/css/doka/attribute-selector.md
> + (Advert и advert — это разные значения с точки зрения браузера)
Вынес в callout

2020-12-13 19:49 UTC, ezhkov commented on src/posts/css/doka/attribute-selector.md
> +/* Теперь уберутся все три картинки */
Поправил формулировку)

2020-12-14 10:53 UTC, solarrust commented
Завела задачу #354

2020-12-14 11:05 UTC, pepelsbey requested changes

2020-12-14 11:05 UTC, pepelsbey commented on src/posts/css/doka/attribute-selector.md
> +title: Селектор по атрибуту (div[attr=""] {})
```suggestion
title: '[attr]'
```


У нас сейчас почти везде статьи называются примером кода:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/105274/102073854-f70ca080-3e14-11eb-82c0-27da5a821394.png">

Это отдельная тема для дискуссии, но пока я бы продолжил следовать принципу.

Плюс кавычки — одиночные потому, что внутри двойные.

2020-12-18 21:24 UTC, pepelsbey reviewed
Предлагаю здесь тоже разбить длинные примеры с комментариями на короткие с подписями.

2020-12-20 16:01 UTC, ezhkov commented
> Предлагаю здесь тоже разбить длинные примеры с комментариями на короткие с подписями.

Поправлено

Закрывает #71

2020-12-20 21:39 UTC, pepelsbey approved these changes

2020-12-21 09:44 UTC, solarrust approved these changes

2020-12-21 09:45 UTC, merged