Добавить кросс-ссылки #41
Y-Doka/y-doka.site pull request #330
Opened 2020-12-10 18:35 UTC by maximumsweet

1. Добавил кросс-ссылки;
2. Исправил некоторые ошибки;
3. Добавил несколько ссылок на сторонние ресурсы, по некоторым темам.

2020-12-10 20:57 UTC, nlopin approved these changes
Огнище! Спасибо за помощь

2020-12-11 05:46 UTC, solarrust commented
Привет! 
Спасибо огромное за помощь! 
Один момент: мы стараемся не давать ссылки на внешние ресурсы. В итоге у нас будут описаны все необходимые свойства и мы проставим ссылки на них. 
В ходе обсуждения мы пришли к выводу, что стоит давать только ссылки на документацию, но не на другие, подобные нам, ресурсы. Типа MDN. 

@furtivite призываю!

2020-12-11 06:00 UTC, furtivite commented on src/posts/css/doka/first-class_second-class.md
> +Подробнее можно прочитать в статье [Специфичность в CSS](https://developer.mozilla.org/ru/docs/Web/CSS/Specificity)
Тут допустимо оставить ссылку на статью про специфичность, наша ещё не написана, но есть issue #155. Я добавлю туда подзадачу: когда будет статья, заменить эту ссылку.

2020-12-11 06:14 UTC, furtivite requested changes
Привет! 
Очень объёмная работа! Огромное спасибо. 
Я соглашусь с @solarrust, что лучше, конечно давать ссылки на наши внутренние статьи, но, если такой статьи нет, а тема достаточно сложная для начинающих, как со специфичностью, или непонятная для обывателя, как фавиконы, допустимо проставить ссылку на MDN или Вики, но надо сразу тогда пометить issue, чтобы потом заменили ссылку. 

Осталось только поправить ссылку на статью, про относительные единицы, у нас есть своя статья на тему 😉

2020-12-11 06:14 UTC, furtivite commented on src/posts/css/doka/font-size.md
> +Ещё есть другая относительная единица измерения `rem`. Она, в отличие от `em`, берёт за базовое значение не размер шрифта родительского элемента, а размер шрифта на странице, который указывается в `<
Ссылку можно заменить на [нашу статью](https://y-doka.site/posts/css/doka/rem-em/)

2020-12-11 06:14 UTC, furtivite commented on src/posts/html/doka/head.md
> +Эта информация не отображается на странице браузера. Пользователи увидят только заголовок окна страницы — его задаёт тег `<title>`, ну и [фавикон](https://ru.wikipedia.org/wiki/Favicon), если вы его
Решим issue #128 заменим ссылку, я думаю.

2020-12-11 06:14 UTC, furtivite commented on src/posts/js/doka/element-style.md
> +С помощью него можно управлять стилем элемента. [Специфичность](https://developer.mozilla.org/ru/docs/Web/CSS/Specificity) этого свойства такая же, как у атрибута `style`.
Тут допустимо оставить ссылку на статью про специфичность, наша ещё не написана, но есть issue #155. Я добавлю туда подзадачу: когда будет статья, заменить эту ссылку.

2020-12-11 17:04 UTC, maximumsweet commented
Привет! Ссылку поправил.

2020-12-11 18:05 UTC, solarrust approved these changes

2020-12-11 18:50 UTC, furtivite approved these changes

2020-12-11 18:52 UTC, furtivite commented
Спасибо за твои коммиты. 

![Captain Jack](https://user-images.githubusercontent.com/50330458/101942637-e7b20b00-3bfa-11eb-8638-bff46fe6f605.gif)

P.S.: Да, в статьях ещё есть пустые места для кросс-ссылок, но там, действительно, пока не написаны статьи, на которые можно было сослаться.

2020-12-11 18:52 UTC, merged