Отсортировывает статьи по алфавиту, #191
Y-Doka/y-doka.site pull request #360
Opened 2020-12-15 20:14 UTC by usmanyunusov

2020-12-15 22:24 UTC, nlopin commented on src/includes/postlists/js/tools.njk
> +  {%- for post in collections.jsTools | sortByKey('title') -%}
Кажется можно обойтись встроенным в nunjucks [фильтром sort](https://mozilla.github.io/nunjucks/templating.html#sort-arr-reverse-casesens-attr):
```
  {%- for post in collections.jsTools | sort(fallse, true, 'title') -%}
```

Пробовал такое?

2020-12-16 08:00 UTC, usmanyunusov commented on src/includes/postlists/js/tools.njk
> +  {%- for post in collections.jsTools | sortByKey('title') -%}
@nlopin пробовал. В объекте `htmlDoka` нет ключа `title`. Он находится внутри объекта `htmlDoka.data`. Следовательно сортировка не будет работать

2020-12-16 20:31 UTC, nlopin requested changes
Все классно, но нужна еще сортировка в навигационных страницах в папке `src/pages/nav-pages`

Это натолкнуло меня на мысль, что было бы круто не сортировать коллекцию вручную каждый раз, а сделать это единожды. Думаешь, такое можно реализовать? тогда и не нужно будет править во всех файлах, которые работают с коллекциями статей

2020-12-16 20:31 UTC, nlopin commented on utils/filters.js
> +          return a.data[key] === b.data[key]
Давай воспользуемся функцией [`localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) вместо ручного сравнения.

2020-12-17 07:02 UTC, usmanyunusov commented on utils/filters.js
> +          return a.data[key] === b.data[key]
@nlopin Могу предложить такой вариант. 
```
  // Sortables collections
  new Array(
    "htmlDoka",
    "htmlLong",
    "cssDoka",
    "cssLong",
    "jsDoka",
    "jsLong",
    "jsTools"
  ).forEach((collectionsName) => {
    config.addCollection(collectionsName, (collection) => {
      return collection
        .getFilteredByTag(collectionsName)
        .sort((a, b) => a.data.title.localeCompare(b.data.title))
    })
  })
  ```

2020-12-17 07:31 UTC, nlopin commented on utils/filters.js
> +          return a.data[key] === b.data[key]
да, давай так 👍

2020-12-17 12:44 UTC, usmanyunusov commented on utils/filters.js
> +          return a.data[key] === b.data[key]
@nlopin готово

2020-12-17 13:04 UTC, nlopin approved these changes
Офигенно! Спасибо 👍

2020-12-17 13:04 UTC, merged