Добавляет статью про Agile
Y-Doka/y-doka.site pull request #367
Opened 2020-12-17 10:20 UTC by igorkamyshev

fixes #195

2020-12-17 10:44 UTC, pepelsbey commented
Как говорится, не бывает неприличных слов, но вот у меня очень большия сомнения про «сорта Agile». К сожалению, в памяти сразу всплывает ассоциация про «сорта говна» (дико извиняюсь) и заголовок могут считать как что-то пассивно-агрессивное. Достаточно сменить «сорта» на «типы» или «виды» и сразу станет проще.

2020-12-18 09:13 UTC, nlopin requested changes
Классный материал

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +Основа метода — **бэклог** — список всех возможных задач, которые должны быть сделаны для развития продукта. В бэклог обычно попадают не только бизнесовые задачи, направленные на развитие продукта, н
Надо будет сделать статью «Технический долг» (#372)

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +Основа метода — **бэклог** — список всех возможных задач, которые должны быть сделаны для развития продукта. В бэклог обычно попадают не только бизнесовые задачи, направленные на развитие продукта, н
```suggestion
Основа метода — **бэклог** — список всех возможных задач, которые должны быть сделаны для развития продукта. В бэклог попадают не только бизнесовые задачи, направленные на развитие продукта, но и технический долг. Периодически команда просматривает этот список и определяет приоритет задач, этот процесс называется **грумингом**. 

После груминга команда совместными усилиями планирует итерацию разработки продукта с жестко заданной длительностью (обычно от 1 до 4 недель), в которою попадают задачи из бэклога с наивысшим приоритетом. Такие итерации называют **спринтами**. 

В конце каждого спринта команда показывает результат своей работы заказчику (внутреннему или внешнему) на **демо**. После демо новую версию продукта обычно доставляют пользователям (**релиз**).
```

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +SCRUM — это очень подробно описанная методология, которая содержит в себе много подробностей обо всех аспектах проекта. В ней описаны правила составления беклога, оценки сложности задач, способны кон
```suggestion
SCRUM — это очень подробно описанная методология, которая содержит много рекомендаций и указаний для всех этапов проекта. В ней описаны правила составления беклога, оценки сложности задач, способны контроля скорости работы и так далее. Все это описано на официальном сайте фреймворка — [Scrum.org](https://www.scrum.org/)
```

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +SCRUM — это очень подробно описанная методология, которая содержит в себе много подробностей обо всех аспектах проекта. В ней описаны правила составления беклога, оценки сложности задач, способны кон
тут можно как-то иначе переделать, но в изначальнов варианте тавтология «подбробно описанная...много подробностей»

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +Многие команды считают SCRUM излишне нагружённым и модифицируют его под свои нужды — берут одни концепции и отказываются от других.
Я бы еще сказал, что есть компании, которые строго следуют методологии и в них за процессом наблюдает специальный человек SCRUM мастер

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +Канбан появился сильно раньше, чем другие гибкие методологии, его придумали в Toyota в 1960-х годах и изначально применяли к производству автомобилей. С начала 2000-х годов канбан перекочевал в индус
```suggestion
Канбан появился сильно раньше, чем другие гибкие методологии. Его придумали в Toyota в 1960-х годах и изначально применяли к производству автомобилей. С начала 2000-х канбан перекочевал в индустрию разработки программ и применяется многими командами.
```

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +Важно понимать, что Agile — это не серебряная пуля. Многие компаниям и командам не походят гибкие методологии. Любой метод управления проектами должен отвечать потребностям бизнеса и удовлетворять ко
Давай тут приведем примеры. Я бы сказал, что заказная/проектная разработка — это классический вотерфол, даже если мы его нарежем на спринты. Продуктовая разработка — про гибкие методологии.

Мы не сказали ничего про опенсорс, там вообще используются методологии разработки?

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +## Не-гибкие методологии
Нужно поменять заголовок, чтобы он луччше отражал содержание. Основная мысль раздела: «Методология подбирается под конкретный проект/продукт»

2020-12-18 09:13 UTC, nlopin commented on src/posts/js/tools/agile.md
> +## Не-гибкие методологии
В этом разделе, я бы тут еще сказал, что agile это такой базворд и маркетинговый термин

2021-01-12 12:17 UTC, pepelsbey commented
@igorkamyshev доделаем? :)

2021-01-15 12:30 UTC, igorkamyshev commented on src/posts/js/tools/agile.md
> +Важно понимать, что Agile — это не серебряная пуля. Многие компаниям и командам не походят гибкие методологии. Любой метод управления проектами должен отвечать потребностям бизнеса и удовлетворять ко
Дописал. А вот про опен-сорс я не знаю. И даже не уверен, что вообще можно что-то однозначное сказать. Кажется, нужно дополнительное исследование 🤓

2021-01-15 12:32 UTC, igorkamyshev commented
@nlopin можно смотреть

2021-01-18 22:09 UTC, nlopin approved these changes
Кайфанул ❤️

2021-01-18 22:10 UTC, merged