Добавляет статью про Webpack
Y-Doka/y-doka.site pull request #368
Opened 2020-12-17 10:23 UTC by igorkamyshev

fixes #194

2020-12-17 10:54 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +```
В JSON нельзя комментарии, об этом даже Гитхаб кричит, может обойтись вложенным блоком `"scripts"` и без внешних скобок? Будет понятно, что это вложенный блок, а не весь файл.

2020-12-17 10:54 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +```jsx
Тут ни одного примера на JSX, всё JS, но все примеры так помечены

2020-12-17 10:54 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +- `webpack-cli` (Webpack Command Line Interface) — небольшая обертка, которая помогает удобно и просто запускать Webpack из командной строки.
```suggestion
- `webpack-cli` (Command Line Interface) — небольшая обертка, которая помогает удобно и просто запускать Webpack из командной строки.
```

Я бы оставил расшифровку только CLI, с Webpack и так всё ясно.

2020-12-17 10:54 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +<!doctype html>
```suggestion
<!DOCTYPE html>
```
Мы в статье про доктайп пишем в таком виде, я бы сохранил последовательность.

2020-12-17 10:54 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +- `HotModuleReplacementPlugin` — позволяет делать изменения в коде и видеть изменения в браузере без полной перезагрузки страницы, это делает разработку более кофмортной;
Есть такой трюк: если писать `<tag>` вместо `tag`, то при чтении сразу понятно, что речь про тег, а не переменную, класс, метод или что-то ещё. Можно даже иногда опускать слово тег.
 
```suggestion
- `MiniCssExtractPlugin` — по умолчанию все стили, которые обработал Webpack попадают в JS-файл и потом вставляются в тег `<style>`, этот плагин извлекает все стили в отдельный CSS-файл, которые можно подключить к странице через тег `<link>`;
- `HotModuleReplacementPlugin` — позволяет делать изменения в коде и видеть изменения в браузере без полной перезагрузки страницы, это делает разработку более кофмортной;
```

2020-12-17 13:47 UTC, nlopin requested changes
Давай поработаем над структурой. Сейчас по контенту все идет плавно, но по заголовкам выглядит как с места в карьер:
1. Кратко
2. Конфигурация
3. Отслеживание изменений
4. Как понять
5. Лоадеры
6. Плагины

Давай немного отступим от стандартной структуры и сделаем как-то так (названия заголовков можно менять):
* Кратко
* Базовое использование
* Отслеживание изменений в проекте
* Расширение (то, что сейчас «Как понять»)
    * Лоадеры
    * Плагины

В этой статье точно надо делать раздел «В работе» и давать базовые советы, потому что вебпак сложный. Про использование `path` (видел в комментах), может пару слов про отладку или как разбить конфиг на несколько файлов.

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Теперь создадим JS-файл, который будет использоваться как входная точка и вызовем в нем функции приложения:
Давай развернем понятие «входная точка». Новичкам будет непонятно

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +- `webpack-cli` (Webpack Command Line Interface) — небольшая обертка, которая помогает удобно и просто запускать Webpack из командной строки.
```suggestion
- `webpack-cli` (Webpack Command Line Interface) — обертка для запуска Webpack из командной строки.
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Теперь достаточно создать простой конфигурационный файл:
```suggestion
Теперь достаточно создать конфигурационный файл `webpack.config.js` в корне проекта:
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +    // имяфайла
```suggestion
    // имя файла со сброкой
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +```json
```suggestion
```bash
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Если открыть этот файл в браузере, то в консоли появится приветствие и прощание.
надо добавить скришот

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +
тут нужна принципиальная схема работы

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +- `style-loader` — позволяет импортировать CSS-файлы и внедряет стили в DOM;
```suggestion
- `style-loader` — импортирует CSS-файлы и внедряет стили в DOM;
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +- `babel-loader` — преобразует JavaScript для разных браузеров, позволяет писать код на современном JS, но исполнять его даже в старых браузерах.
Давай сделаем акцент на современный JS → старый JS?

Что-то типа:
```suggestion
- `babel-loader` — преобразует позволяет писать код на современном JS, но исполнять его даже в старых браузерах. 
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Плагин — невероятно мощный способ расширить или изменить функциональность Webpack. Если лоадер ограничен только одной функцией (он принимает содержимое файла и должен вернуть изменённое содержимое),
```suggestion
Плагин — мощный способ расширить или изменить функциональность Webpack. Если лоадер ограничен только одной функцией (принимает содержимое файла и должен вернуть изменённое содержимое), то плагин может делать все что угодно.
```

2020-12-17 13:47 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Для Webpack написано огромное число плагинов — для работы со стилями, улучшения опыта разработки и упрощения жизни инженеров, для автоматизации рутинных операций и много других. Вот несколько, которы
`улучшения опыта разработки` звучит не по-русски. Я бы перевел Developer Experience как «удобство разработки», потому что опыт это про что-то прошлое.

2021-01-12 12:17 UTC, pepelsbey commented
@igorkamyshev доделаем? Кажется немного осталось.

2021-01-15 11:07 UTC, pepelsbey requested changes

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +}
```suggestion
"scripts": {
  "build": "webpack",
  "watch": "webpack --watch"
}
```

Можно сильно упростить и сфокусировать пример, плюс избежать комментариев, которых в JSON нет

- Выше сказано, что это package.json
- Не обязательно повторять всю структуру

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
```suggestion
```js
```

Выше сказано, что это за файл. И это JS, а не JSX

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
```suggestion
```js
```

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
```suggestion
```js
```

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +npm install --dev webpack webpack-cli
```suggestion
```sh
npm install --dev webpack webpack-cli
```

2021-01-15 11:07 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +// index.js
```suggestion
Теперь создадим файл `index.js`, который будет использоваться как входная точка и вызовем в нем функции приложения:

```js
```

2021-01-15 11:09 UTC, igorkamyshev commented on src/posts/js/tools/webpack.md
> +}
Этот комментарий был выше, Вадим, спасибо. Я запушу правки чуточку позже.

2021-01-15 11:09 UTC, igorkamyshev commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
Да, ты писал об этом выше. Спасибо. Я запушу эти правки чуточку позже.

2021-01-15 11:10 UTC, igorkamyshev commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
Да, ты писал об этом выше. Спасибо. Я запушу эти правки чуточку позже.

2021-01-15 11:10 UTC, igorkamyshev commented on src/posts/js/tools/webpack.md
> +// index.js
Да, ты писал об этом выше. Спасибо. Я запушу эти правки чуточку позже.

2021-01-15 11:10 UTC, igorkamyshev commented on src/posts/js/tools/webpack.md
> +// webpack.config.js
Да, ты писал об этом выше. Спасибо. Я запушу эти правки чуточку позже.

2021-01-15 11:12 UTC, pepelsbey commented
@igorkamyshev наверное не стоит резолвить те комментарии, которые пока не решены в коде, ок? А то сложновато возвращаться к ревью. «Resolve» — это когда исправлено и уже не актуально.

2021-01-15 11:13 UTC, igorkamyshev commented
@pepelsbey дил. Я сделаю мэншон, когда стоит возвращаться к ревью, ок?

2021-01-15 11:14 UTC, pepelsbey commented
@igorkamyshev сконвертировал в черновик, раз такое дело

2021-01-15 11:15 UTC, igorkamyshev commented
@pepelsbey  класс!

2021-01-18 22:01 UTC, nlopin approved these changes
@igorkamyshev мелочи по тексту добавил

2021-01-19 05:33 UTC, igorkamyshev commented
@nlopin спасибо, стало лучше, это правда 🙏

2021-01-19 06:16 UTC, nlopin approved these changes

2021-01-19 13:29 UTC, nlopin commented on src/posts/js/tools/webpack.md
> +Webpack начинает свою работу со входной точки — первого JS-файла. В нем он находит все _импорты_, по которым собирает файлы с исходным кодом проекта. Во всех найденных файлах снова ищет импорты и так
```suggestion
Webpack начинает свою работу со входной точки — первого JS-файла. В нем он находит все _импорты_, по которым собирает файлы с исходным кодом проекта. Во всех найденных файлах снова ищет импорты и так пока импорты не закончатся. В итоге, у Webpack оказывается список всех файлов проекта и информация, как эти файлы связаны. Затем в дело вступают плагины и лоадеры. Для каждого файла Webpack найдет все подходящие (на основе конфигурации) лоадеры и обработает ими файл.
```

2021-01-19 13:30 UTC, nlopin commented
@pepelsbey твой ход ♟

2021-01-19 17:33 UTC, pepelsbey requested changes
- Сделать примеры компактнее: вертикальнее и горизонтальнее
- Вынести названия файлов в описание из комментариев

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +```
```suggestion
```js
path.resolve("/foo/bar", "./baz") // "/foo/bar/baz"
path.resolve("/foo/bar", "/tmp/file/") // "/tmp/file"

// Если текущая рабочая директора /home/user
path.resolve("www", "static_files/png", "../gif/image.gif")
// "/home/use/www/static_files/gif/image.gif"
```
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +```
Переносит название файла в описание

```suggestion
В базовом случае использовать Webpack довольно просто. Представим, что в нашем приложении есть файл `application.js` с функциями, необходимыми для работы:

```js
function sayHello() {
  console.log("Hello!")
}

function sayBye() {
  console.log("Bye!")
}

// экспортируем эти функции, чтобы воспользоваться ими в другом месте
export { sayHello, sayBye }
```
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +}
```suggestion
// path — встроенный в Node.js модуль
const path = require("path")

module.exports = {
  // указываем путь до входной точки
  entry: "./src/index.js",
  // описываем куда следует поместить результат работы
  output: {
    // путь до директории (важно использовать path.resolve)
    path: path.resolve(__dirname, "dist"),
    // имя файла со сброкой
    filename: "bundle.js"
  }
}
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +import { sayHello, sayBye } from "./application"
```suggestion
Теперь создадим файл `index.js`, который будет использоваться как входная точка и вызовем в нем функции приложения:

```js
import { sayHello, sayBye } from "./application"
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +}
```suggestion
module.exports = {
  plugins: [new HtmlWebpackPlugin()]
}
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +}
- Переносит комментарий на отдельную строку (код не переносится)
- Убирает «всякое» `// ...` для компактности

```suggestion
// Webpack предоставляет несколько плагинов в основном пакете
const { ProgressPlugin } = require("webpack")

module.exports = {
  plugins: [
    // при сборке этот плагин будет отображать прогресс в консоле
    new ProgressPlugin()
  ]
}
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +}
Конфиги и так развесистые, а тут 5 лишних строк `// ...`, которые не очень помогают. Добавить код можно ведь не только в этих точках, а где угодно. Лучше сфокусироваться на том, что показываем.

Плюс опечатка примяемые — применяемые.

```suggestion
module.exports = {
  // в этом массиве будут перечислены все применяемые лоадеры
  module: {
    rules: [
      {
        // это правило будет применяться ко всем файлам,
        // имя которых подойдет под это регулярное выражение
        test: /\.css$/,
        // список лоадеров, которые применяться к файлу
        use: [
          { loader: "style-loader" },
          {
            loader: "css-loader",
            // лоадеру можно передать параметры
            options: { modules: true }
          }
        ]
      }
    ]
  }
}
```

2021-01-19 17:33 UTC, pepelsbey commented on src/posts/js/tools/webpack.md
> +[Подробная документация по модулю `path`.](https://nodejs.org/docs/latest-v14.x/api/path.html)
```suggestion
[Подробная документация по модулю `path`](https://nodejs.org/docs/latest-v14.x/api/path.html).
```

2021-01-19 20:30 UTC, nlopin commented
Мне нравится подход Вадима. Возьмем на вооружение

2021-01-19 21:17 UTC, pepelsbey approved these changes

2021-01-19 21:37 UTC, merged