Fix/Двигает маскота
Y-Doka/y-doka.site pull request #370
Opened 2020-12-17 18:35 UTC by furtivite

- Подвигал маскота, сделал его картинкой, которая не едет на разных дисплеях
- Удалена ошибка из консоли, вызванная некорректным вызовом фона для дива маскота

2020-12-17 18:36 UTC, furtivite commented
Походу чуть напутал в ветках, изменение "execution orders" нужно отменить -__-

2020-12-17 19:40 UTC, solarrust approved these changes

2020-12-17 20:05 UTC, pepelsbey commented on src/layouts/main.njk
> +        src="/assets/images/mainpage/mascot-doka.png"
А для каких случаев здесь подключается растровый фолбэк? Я не знаю ни одного релевантного браузера, который не умеет SVG.

2020-12-17 20:07 UTC, pepelsbey commented on src/layouts/main.njk
> +      <source srcset="/assets/images/mainpage/mascot-doka.svg" type="image/svg+xml">
Одиночный `<img />` и одиночный `<source>` (без слэша) — нам бы уже определиться, как мы пишем.

2020-12-17 20:08 UTC, pepelsbey requested changes
Кажется немного переинженерено )

2020-12-17 20:29 UTC, furtivite commented on src/layouts/main.njk
> +        src="/assets/images/mainpage/mascot-doka.png"
@pepelsbey супер-крайний случай, на всякий)

2020-12-17 20:35 UTC, pepelsbey commented on src/layouts/main.njk
> +        src="/assets/images/mainpage/mascot-doka.png"
Ну то есть несуществующий. Это код ни разу не запустится, зачем его шипить?

2020-12-18 07:49 UTC, nlopin commented on src/layouts/main.njk
> +      <source srcset="/assets/images/mainpage/mascot-doka.svg" type="image/svg+xml">
Вадим, это можно как-то форсить валидаторами? Давай прикрутим, а то определиться-то мы можем, но руками проверять устанем

2020-12-18 07:49 UTC, nlopin commented on src/layouts/main.njk
> +        src="/assets/images/mainpage/mascot-doka.png"
В подтверждение словам Вадима:
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/1469636/102588518-d5116780-410d-11eb-97e9-1cd13e4a7a24.png">

2020-12-18 07:49 UTC, nlopin commented on src/posts/js/doka/execution-order.md
> +name: execution-order
🥰

2020-12-18 07:56 UTC, nlopin commented on src/assets/styles/base/_mainpage.scss
> +    height: calc(100vh - 208px);;
```suggestion
    height: calc(100vh - 208px);
```

2020-12-18 11:57 UTC, pepelsbey commented on src/layouts/main.njk
> +      <source srcset="/assets/images/mainpage/mascot-doka.svg" type="image/svg+xml">
@nlopin есть [linthtml](https://github.com/linthtml/linthtml), заведу задачу

2020-12-20 11:25 UTC, nlopin commented
@furtivite ты не забыл про этот пул реквест?

2020-12-20 21:58 UTC, pepelsbey commented
Вместо комментов просто запушил правки:
- Убрал ненужный код из стилей
- Убрал остатки picture, которые были не нужны

2020-12-20 22:01 UTC, pepelsbey approved these changes

2020-12-20 22:53 UTC, nlopin approved these changes

2020-12-20 22:54 UTC, merged