Статья про теги таблицы
Y-Doka/y-doka.site pull request #371
Opened 2020-12-17 21:25 UTC by solarrust

Решила объединить задачи #80 #82 #81 #76 #77 #78 и #79 в одну статью. 

Статья шла сложно, таблицы не сказать чтобы сильно увлекательная тема. @ezhkov @Realetive @pepelsbey буду очень благодарна за ваше ревью и подсказки где и что ещё можно добавить, а также за советы в блок "В работе".

2020-12-17 21:47 UTC, pepelsbey reviewed
Кажется, что метафора «растягивания» ячеек далека от знакомой по Excel метафоре «объединения» ячеек — кажется так понятнее. Предложил в одном месте замену.

2020-12-17 21:47 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +_`th` расшифровывается как «table header» и переводится «заголовки таблицы»_
```suggestion
_`th` расшифровывается как «table header» и переводится «заголовок таблицы»_
```

2020-12-17 21:47 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Но если говорить серьёзно, то эти теги помогают лучше читать и без того запутанный код таблицы и отделять <s>зёрна от плевел</s> заголовки и строку итога от основного тела таблицы.
> заголовки и строку итога

Звучит как очень специфичный пример, лучше как-то универсальнее.

```suggestion
Но если говорить серьёзно, то эти теги помогают лучше читать разметку сложных таблиц и отделять <s>зёрна от плевел</s> структурные части таблицы друг от друга. Например: сложную шапку от тела с данными и всё это от результатов подсчёта в подвале.
```

2020-12-17 21:47 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +К тому же правильно свёрстанная таблица может отобразиться в поисковике в виде сниппета
```suggestion
К тому же правильно свёрстанная таблица может отобразиться в поисковике в виде сниппета.
```

2020-12-17 21:47 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Обернём все айфоны в один `<tbody>` и добавим пару Андройдов, чтобы показать, что может быть больше одного блока данных:
```suggestion
Обернём все айфоны в один `<tbody>` и добавим пару андроидов, чтобы показать, что может быть больше одного блока данных:
```

2020-12-17 21:47 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Помимо [глобальных атрибутов](/html/doka/global-attrs/) при работе с таблицами вам могут очень пригодиться атрибуты `colspan` и `rowspan`. Оба этих атрибута предназначены для растягивания ячеек. `col
```suggestion
Помимо [глобальных атрибутов](/html/doka/global-attrs/), при работе с таблицами вам могут очень пригодиться атрибуты `colspan` и `rowspan`. Оба этих атрибута предназначены для объединения ячеек. `colspan` для объединения ячейки на 2 или более столбцов, а `rowspan` для объединения на 2 или более рядов.
```

2020-12-17 21:49 UTC, pepelsbey commented
Ещё немного непоследовательно то `tr`, то `<tr>`. Я хотел отдельно обсудить правило всегда заворачивать теги в угловые скобки для лучшей наглядности: у нас есть и атрибуты, и классы — полезно отличать их визуально.

2020-12-18 06:39 UTC, solarrust commented
@pepelsbey спасибо за правки! 
А по поводу `tr` и `<tr>`: писала статью в два подхода, между ними как раз увидела твой комментарий про скобки. Потому в первой части их нет, а во второй есть =)
Приведу к единому стилю.

2020-12-22 20:29 UTC, solarrust commented
Дописала блоки "Подсказки" и "В работе". @pepelsbey @ezhkov @Realetive , пожалуйста, поревьюйте

2020-12-22 20:53 UTC, pepelsbey requested changes

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Задать границы элементам `<tr>`, `<thead>`, `<tfoot>` и `<tbody>` нельзя, поэтому задавайте их селекторам `table`, `th` или `td`.
```suggestion
Задать границы элементам `<tr>`, `<thead>`, `<tfoot>` и `<tbody>` нельзя, поэтому задавайте их тегам `<table>`, `<th>` или `<td>`.
```
Разделение на теги и селекторы в одном предложении немного путает. Лучше говорить об одном, а про селекторы не принципиально.

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +🛠 Частый дизайнерский приём — подсветка строк таблицы через одну.
```suggestion
🛠 Частый дизайнерский приём — подсветка строк таблицы через одну. Это помогает считывать длинные таблицы, глазу есть за что зацепиться.
```
Думаю, будет полезно объяснить зачем это нужно.

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +  position: -webkit-sticky;
```suggestion
  position: -webkit-sticky;
  position: sticky;
```

Первое правило ~бойцовского клуба~ префиксов — свойство без префикса идёт последним.

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Например, сделаем каждую вторую строку с серым фоном. Для этого понадобится всего одно CSS-правило:
```suggestion
Например, сделаем каждую вторую строку с серым фоном. Для этого понадобится всего одно CSS-правило с псевдоклассом [`:nth-child()`](/css/doka/child/):
```

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +  position: -webkit-sticky;
```suggestion
  position: -webkit-sticky;
  position: sticky;
```

2020-12-22 20:53 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +Если сайт должен хорошо работать в старых браузерах обязательно проверьте поддержку `sticky` на [сайте CanIuse](https://caniuse.com/css-sticky)
```suggestion
Если сайт должен хорошо работать в старых браузерах, обязательно проверьте поддержку `sticky` на [Can I use…](https://caniuse.com/css-sticky).
```

2020-12-23 08:10 UTC, pepelsbey approved these changes

2020-12-23 10:08 UTC, merged

2020-12-24 05:34 UTC, Realetive commented on src/posts/html/doka/tables.md
> +  position: -webkit-sticky;
А зачем вообще префикс? Это «стандартизированное» свойство (тем более, префиксный вариант требуется только в устаревших браузерах).

2020-12-24 10:04 UTC, pepelsbey commented on src/posts/html/doka/tables.md
> +  position: -webkit-sticky;
Кстати, да.