Добавил статью про Element.classList
Y-Doka/y-doka.site pull request #373
Opened 2020-12-18 09:45 UTC by Windrushfarer

fixes #189

2020-12-18 12:45 UTC, pepelsbey requested changes
Расставил заголовки, ну и «т.к» пишется «т. к.» или хотя бы «т.к.»

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +```jsx
Но это же `js`, а не `jsx`

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +🛠 Можно превратить в обычный массив для итерации
Очень похоже на начало интересного совета, но не хватает подробностей

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +**Имена клаcсов**
```suggestion
### Имена клаcсов
```

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +**Element.classList.toggle** –– метод можно использовать чтобы включать или выключать класс. Если при вызове `.toggle()` переданный класс уже есть на элементе, то он будет убран. Если класса не было
```suggestion
### `Element.classList.toggle`

Метод можно использовать чтобы включать или выключать класс. Если при вызове `.toggle()` переданный класс уже есть на элементе, то он будет убран. Если класса не было — то добавлен.
```

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +**Element.classList.add** –– метод используется для добавления класса к элементу. В качестве параметра нужно передавать строку с именем класса.
```suggestion
### `Element.classList.add`

Метод используется для добавления класса к элементу. В качестве параметра нужно передавать строку с именем класса.
```

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +**Element.classList.remove** –– метод используется для удаления класса у элемента. В качестве параметра нужно передавать строку с именем класса.
```suggestion
### `Element.classList.remove`

 Метод используется для удаления класса у элемента. В качестве параметра нужно передавать строку с именем класса.
```

2020-12-18 12:45 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +**Element.classList.replace** –– метод позволяет заменить одно значение класса другим. Метод принимает 2 аргумента:
```suggestion
### `Element.classList.replace`

Метод позволяет заменить одно значение класса другим. Метод принимает 2 аргумента:
```

2020-12-18 12:47 UTC, pepelsbey commented on src/posts/js/doka/element-classlist.md
> +Управлять классами элемента –– одна из распространенных задач, потому браузеры предоставляют встроенные средства для решения такой задачи. Сам по себе `Element.classList` является специальным объекто
```suggestion
Управлять классами элемента — одна из распространенных задач, потому браузеры предоставляют встроенные средства для решения такой задачи. Сам по себе `Element.classList` является специальным объектом, который хранит информацию о текущих классах и содержит методы для работы с ними. Еще `Element.classList` называются псевдомассивом, т.к разработчик может обращаться к классам по индексам, как в массиве. При этом новые классы добавляются в конец, а при удалении все классы (и соответственно их индексы) смещаются.
```

2020-12-18 14:41 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +🛠 Можно превратить в обычный массив для итерации
Ой-ой, забыл закоммитить последнее изменение как раз с подробным описанием.

2020-12-18 14:41 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +```jsx
По привычке, поправлю. Хотя на синтаксис не влияет.

2020-12-18 21:23 UTC, pepelsbey reviewed
Один коммит применяет заголовки, другой отменяет. Были сомнения? :)

2020-12-18 21:55 UTC, nlopin requested changes
Отличный материал! Нужно немного причесать и будет отличненько

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +## Как это понять
```suggestion
## Как понять
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +## Базовый пример
```suggestion
## Пример
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Управлять классами элемента –– одна из распространенных задач, потому браузеры предоставляют встроенные средства для решения такой задачи. Сам по себе `Element.classList` является специальным объекто
```suggestion
Управлять классами элемента –– одна из распространенных задач, потому браузеры предоставляют встроенные средства для решения такой задачи. `Element.classList` — это специальный объект, который хранит информацию о текущих классах элемента и содержит методы для работы с ними. `Element.classList` является псевдомассивом, поэтому разработчик может обращаться к классам по индексам, как в массиве. При этом новые классы добавляются в конец, а при удалении все классы (и соответственно их индексы) смещаются.
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Управлять классами элемента –– одна из распространенных задач, потому браузеры предоставляют встроенные средства для решения такой задачи. Сам по себе `Element.classList` является специальным объекто
Не стоит ли утащить рассказ про псевдомассив в раздел «В работе»? Это не самая частая операция с `classList`

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +У `Element.classList` есть множество методов, но здесь мы рассмотрим только наиболее часто используемые, которые пригодятся в практике.
```suggestion
У `Element.classList` есть множество методов, но мы рассмотрим только часто используемые.
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +У `Element.classList` есть множество методов, но здесь мы рассмотрим только наиболее часто используемые, которые пригодятся в практике.
Подсократил немного. «часто используемые» уже означает, что они на практике используются

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Можно так же передать несколько строк-параметров, тогда добавится несколько классов
```suggestion
Можно так же передать несколько строк-параметров, тогда добавится несколько классов:
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +💡 При добавлении можно не боятся, что на элемент добавится один тот же класс два раза. Если вызвать метод `.add` и передать в параметры уже существующий класс, то он не добавится второй раз.
```suggestion

:::callout 💡
Можно не боятся, что один тот же класс добавится два раза. Если вызвать метод `.add` и передать уже существующий класс, то он не добавится второй раз.
 :::

```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +💡 При добавлении можно не боятся, что на элемент добавится один тот же класс два раза. Если вызвать метод `.add` и передать в параметры уже существующий класс, то он не добавится второй раз.
У нас есть специальный синтаксис для callout

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Аналогично добавлению в `.remove()` можно передать несколько параметров и удалится несколько классов.
```suggestion
В `.remove()` можно передать несколько параметров и удалится несколько классов
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Аналогично добавлению в `.remove()` можно передать несколько параметров и удалится несколько классов.
Меня сбило с толку слово добавление и `remove`  в одном предложении. Кажеься можно просто его удалить без потери смысла

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +button.classList.replace("hidden", "visible")
давай добавим еще инфу, что этот вызов вернет `true`,  и добавим пример, где он вернет `false`

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +**Element.classList.add** –– метод используется для добавления класса к элементу. В качестве параметра нужно передавать строку с именем класса.
Давай попробуем заголовки, так может быть легче сканировать статью. 

```
### Element.classList.add

Метод используется для добавления класса к элементу. В качестве параметра нужно передавать строку с именем класса.
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +// т.к. класс есть то он будет убран
```suggestion
// так как класс есть, то он будет убран
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +Метод `.toggle()` принимает только один класс для переключения, опционально вторым аргументом можно передать boolean-значение, тогда метод будет работать как `.add()`, если передать `true` или как `.
```suggestion
Метод `.toggle()` принимает только один класс для переключения. Опционально вторым аргументом можно передать boolean-значение: метод будет работать как `.add()`, если передать `true`, и как `.remove()`, если передать `false`.
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +```
тут должны быть примеры с `toggle`

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +☝️ Стоит помнить что классом не может быть строка содержащая пробелы, потому, при попытке передать в параметрах такую строку, будет выброшена ошибка. Это правило касается любого метода для работы с к
```suggestion

:::callout ☝️
Классом не может быть строка содержащая пробелы. При попытке передать в параметрах такую строку, будет выброшена ошибка. Это правило касается любого метода в `classList`.
:::

```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +☝️ Стоит помнить что классом не может быть строка содержащая пробелы, потому, при попытке передать в параметрах такую строку, будет выброшена ошибка. Это правило касается любого метода для работы с к
Чуть поджал и вставил callout

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +`Element.classList` даёт возможность просматривать и манипулировать классами элемента.
```suggestion
`Element.classList` даёт возможность просматривать и манипулировать [классами](/html/doka/class/) элемента.
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +// Метод не сработает и будет выброшена ошибка!
```suggestion
// Метод не сработает и будет выброшена ошибка: Uncaught DOMException: String contains an invalid character
```

2020-12-18 21:55 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +## В работе
Давай здесь расскажем про [`className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className)

2020-12-18 22:10 UTC, nlopin commented
Еще давай будем точными в терминологии. Сейчас мы взаимозаменяемо используем термины `параметр` и `аргумент` и в индустрии никто тоже особо не парится с деталями (это ок). Но так как мы учим, то в таких вещах нужно быть точным.

* Параметры — это то, что мы указываем при объявлении функции. Функция может быть параметризованная и не параметризованная.
* Аргументы — конкретные значения, которые мы передаем при вызове параметризованной функции.

Поэтому мы не можем говорить передаем первым/вторым параметром что-либо. Передаются аргументы. Посмотри на этот момент статью, пожалуйста

2020-12-19 13:30 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +## В работе
Хорошая идея, думаю стоит.

2020-12-19 15:02 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
>  **Имена клаcсов**
нужен ли тут заголовок? и может эту часть перенести в раздел «в работе»

2020-12-19 15:10 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +```jsx
```suggestion
```js
```

2020-12-19 15:10 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +;<header class="head theme-light">content</header>
здесь не должен быть комментарий?

2020-12-19 15:10 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +С помощью этого поля можно легко менять класс элемента, просто подставив новое значение. Если добавляете несколько классов, то из нужно обязательно указывать через пробел.
```suggestion
С помощью этого поля можно легко менять класс элемента — достаточно происвоить ему новое значение. Если добавляете несколько классов, то их нужно обязательно указывать через пробел.

Такой способ хорош, когда элемент иммеет 1-2 класса. Если классов больше, то удобнее использовать `classList`
```

2020-12-19 18:08 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +```jsx
У меня в коде есть элемент, зачем ставить JS, здесь как раз подсветка ломается (по крайней мере в маркдауне, если для сборщика разницы нет, то ок)

2020-12-19 18:08 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +;<header class="head theme-light">content</header>
Какой?

2020-12-19 18:10 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +С помощью этого поля можно легко менять класс элемента, просто подставив новое значение. Если добавляете несколько классов, то из нужно обязательно указывать через пробел.
Опечатки приму, а вот добавленный комментарий насчет 1-2 класса мне кажется немного сомнительный. Я бы лучше добавил что например для какой-то частой работы с классами или для более декларативного стиля лучше использовать `classList`

2020-12-19 18:19 UTC, Windrushfarer commented on src/posts/js/doka/element-classlist.md
> +;<header class="head theme-light">content</header>
Здесь кажется только ; надо убрать лишнее

2020-12-19 18:25 UTC, pepelsbey approved these changes

2020-12-19 18:47 UTC, nlopin commented on src/posts/js/doka/element-classlist.md
> +С помощью этого поля можно легко менять класс элемента, просто подставив новое значение. Если добавляете несколько классов, то из нужно обязательно указывать через пробел.
Согласен

2020-12-19 21:10 UTC, nlopin approved these changes

2020-12-19 21:12 UTC, merged