Добавляет статью о селекторе по классу
Y-Doka/y-doka.site pull request #377
Opened 2020-12-18 14:42 UTC by ezhkov

2020-12-18 15:05 UTC, ezhkov commented
Закрывает #70

2020-12-18 15:05 UTC, solarrust reviewed
Планируешь ли написать блок "В работе"?

2020-12-18 15:05 UTC, solarrust commented on src/posts/css/doka/class-selector.md
> +/* Если элементу добавить класс "warning", то перед текстом будет иконка с желтым треугольником */
```suggestion
/* Если элементу добавить класс "warning", то перед текстом будет иконка с жёлтым треугольником */
```

Не игнорируй буковку Ё =)

2020-12-18 15:11 UTC, ezhkov commented
> Планируешь ли написать блок "В работе"?

Пожалуй, да

2020-12-18 15:13 UTC, solarrust commented on src/posts/css/doka/class-selector.md
> +<input id="input" type="text" placeholder="Только кириллица" />
```suggestion
<input id="input" type="text" placeholder="Только кириллица">
```

2020-12-18 21:19 UTC, pepelsbey requested changes

2020-12-18 21:19 UTC, pepelsbey commented on src/posts/css/doka/class-selector.md
> +```css
Если можно не писать длинные тексты внутри примеров кода — лучше не писать. Они там серые, мелкие, моноширинные. Иногда нет выбора (объяснение структуры кода), но чаще — можно. Здесь и в других примерах лучше разделить один большой пример кода на мелкие с подписями.

***

```css
.article-title {
  margin-bottom: 1.6em;
}
```
Будут найдены все элементы с атрибутом `class="article-title"`.

2020-12-20 14:55 UTC, ezhkov commented on src/posts/css/doka/class-selector.md
> +```css
Согласен. Внёс соответствующие правки

2020-12-20 21:44 UTC, pepelsbey approved these changes

2020-12-21 09:46 UTC, solarrust approved these changes

2020-12-21 09:46 UTC, merged