Добавил пример для border-radius в блок «В работе»
Y-Doka/y-doka.site pull request #380
Opened 2020-12-19 00:41 UTC by Realetive

2020-12-19 20:40 UTC, pepelsbey requested changes

2020-12-19 20:40 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +🛠Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы ещё больше чем на `50%`, чтобы сохранить закруглённость (а не вытягивать бл
Сейчас фраза звучит как будто если сделать «ещё больше» (то есть 60%, 100%), то всё починится. Но это не так :) Кажется тут теряется важная мысль о том, как формируется border-radius в процентах. Она подменяется простым «делай больше и не думай». Может лучше рассказать, относительно чего 50%?

2020-12-20 09:58 UTC, Realetive commented on src/posts/css/doka/border-radius.md
> +🛠Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы ещё больше чем на `50%`, чтобы сохранить закруглённость (а не вытягивать бл
Да, согласен. @solarrust, можно я допишу в «Как это понять»?

2021-01-25 07:46 UTC, solarrust commented
@Realetive нужно добить на этой неделе

2021-01-29 10:04 UTC, Realetive commented
@solarrust дополнил описание и пример.

2021-02-02 04:30 UTC, solarrust commented
@pepelsbey призываю!

2021-02-02 09:21 UTC, pepelsbey requested changes

2021-02-02 09:21 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +selector {
```suggestion
.ellipse {
  border-radius: 5em / 50%;
}
```

Такая запись совсем не означает, что наше скругление будет равно результату деления 5em на какой-то размер, а эквивалентна такой записи:

```css
.ellipse {
```

Лучше записывать классы реалистичнее, а то начнутся вопрос «что за тег selector?»

2021-02-02 09:21 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +  border-bottom-left-radius:  5em 50%;
```suggestion
  border-top-left-radius: 5em 50%;
  border-top-right-radius: 5em 50%;
  border-bottom-right-radius: 5em 50%;
  border-bottom-left-radius: 5em 50%;
```

Понимаю, что так наглядно, но обычно в проектах не принято рисовать красоту на отступах. И нам бы тоже писать более реалистичный код.

2021-02-02 09:21 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы ещё больше чем на `50%`, чтобы сохранить закруглённость (а не вытягивать б
Из формулировки может создаться впечатление, что ты предлагаешь задавать скругление в процентах, просто больше. Кажется, как будто сработает `border-radius: 100%`, но демка говорит о другом.

Плюс в демке псевдоэлементы написаны как псевдоклассы: `:after` > `::after`.

2021-02-02 09:23 UTC, pepelsbey requested changes

2021-02-02 09:23 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +selector {
```suggestion
.ellipse {
```

Лучше записывать классы реалистичнее, а то начнутся вопрос «что за тег selector?»

2021-02-02 09:23 UTC, pepelsbey commented on src/posts/css/doka/border-radius.md
> +selector {
```suggestion
.ellipse {
```

2021-02-08 08:39 UTC, solarrust commented
@Realetive добей, пожалуйста, сегодня

2021-02-18 07:30 UTC, solarrust commented on src/posts/css/doka/border-radius.md
> +🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы не в процентах (потому что тогда скругление будет считаться от ширины и вы
Длинное предложение с несколькими скобочками. Давай попробуем разбить на короткие и понятные.

2021-02-18 16:50 UTC, Realetive commented on src/posts/css/doka/border-radius.md
> +🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы не в процентах (потому что тогда скругление будет считаться от ширины и вы
Вот так, @solarrust ?

```suggestion
🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы не в процентах (потому что тогда скругление будет считаться от ширины и высоты), а в абсолютных единицах (например, пикселях). Число лучше указать больше, чем возможная максимальная высота или ширина (например, `border-radius: 9999px`), чтобы сохранить закруглённость (а не вытягивать блок в «яйцо»):
```

2021-02-18 17:23 UTC, solarrust commented on src/posts/css/doka/border-radius.md
> +🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы не в процентах (потому что тогда скругление будет считаться от ширины и вы
Как тебе такой вариант?

```suggestion
🛠 Если вы не уверены, что блок всегда будет квадратным, то для подстраховки можно указывать закругление в абсолютных единицах.  Причём указать значение, бо́льшее чем максимальная ширина и высота блока. Например, `border-radius: 9999px`. 
Если в этой ситуации указывать закругление в процентах, то значение будет считаться от ширины и высоты. Что приведёт к вытягиванию блока в _яйцо_:
```

2021-02-18 17:46 UTC, Realetive commented on src/posts/css/doka/border-radius.md
> +🛠 Если есть вероятность, что размер блока может быть «непостоянно квадратным», то можно перестраховаться и «закруглить» углы не в процентах (потому что тогда скругление будет считаться от ширины и вы
![zheleznyy-chelovek_14831284_big_](https://user-images.githubusercontent.com/2073959/108398623-45ca2280-722a-11eb-9710-46e5f9d92daf.jpeg)

2021-02-22 18:24 UTC, pepelsbey approved these changes

2021-02-22 19:01 UTC, solarrust approved these changes

2021-02-22 19:02 UTC, merged