Добавляет статью о псевдоклассах
Y-Doka/y-doka.site pull request #410
Opened 2020-12-23 03:01 UTC by Realetive

2020-12-23 08:25 UTC, solarrust requested changes
Дабавила мелкие правки. 
В целом статья пока выглядит как просто перечисление существующих псевдоклассов с кратким описанием. Но эти описания, к сожалению, практически ничего не объясняют. Да, на часть псевдоклассов есть расширенные статьи, но на часть статей может не появится ещё долго. И нужно чтобы из этой статьи можно было понять хотя бы основной принцип работы псевдокласса. 

Пожалуйста, попробуй сделать описания чуть более понятными и добавь примеры.

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Псвдоклассы — особый вид селектора, который уточняет тип или состояние (какой-то качественный признак) — при наведении курсора, порядок следования и другие.
Два тире в одном предложении.

```suggestion
Псевдоклассы — особый вид селектора, который уточняет тип или состояние. Обычно это какой-то качественный признак:  реакция на наведение курсора, порядок следования и другие.
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Таблица, которая подсвечивает выбранную строку при наведении курсора
```suggestion
CSS для подсветки строки таблицы при наведении курсора:
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Благодаря псевдоклассам мы можем контролировать «динамические» параметры селекторов, т. е. эти свойства сработают тогда, когда у селектора «сработает» дополнительный признак, не зависящий от уровня в
```suggestion
Благодаря псевдоклассам мы можем контролировать _динамические_ параметры селекторов, то есть эти свойства сработают тогда, когда селектор **подходит** под дополнительный признак, не зависящий от уровня вложенности.
```

В целом какое-то сложное предложение вышло. Можно попроще, как ты считаешь?

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:active` ([основная статья](./active.md))
```suggestion
### `:active` ([основная статья](/posts/css/doka/active))
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:any-link` / `:link` ([основная статья](./link.md)) / `:visited` ([основная статья](./visited.md))
```suggestion
### `:any-link` / `:link` ([основная статья](/posts/css/doka/link)) / `:visited` ([основная статья](/posts/css/doka/visited))
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:checked` ([основная статья](./checked.md))
```suggestion
### `:checked` ([основная статья](/posts/css/doka/checked))
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:focus` ([основная статья](./focus.md)) / `:focus-within`
```suggestion
### `:focus` ([основная статья](/posts/css/doka/focus)) / `:focus-within`
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Признак того, что документ азвернули на всё окно (с помощью JavaScript)
```suggestion
Признак того, что документ развернули на всё окно (с помощью JavaScript).
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Селекторы элемента по его положению относительно родителя (первый, последний, n-ый, единственный)
```suggestion
Селекторы элемента по его положению относительно родителя (первый, последний, n-ый, единственный).
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:has()` ([основная статья](./has.md))
```suggestion
### `:has()` ([основная статья](/posts/css/doka/has))
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Элемент, который сейчас находится в фокусе (с помощью клавиши `Tab`). А `:focus-within` ещё обозначает элемент, внутри которого находится элемент в фокусе.
```suggestion
Элемент, который сейчас находится в фокусе (с помощью клавиши Tab). А `:focus-within` ещё обозначает элемент, внутри которого находится элемент в фокусе.
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:hover` ([основная статья](./hover.md))
```suggestion
### `:hover` ([основная статья](/posts/css/doka/hover))
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +  - селекторы
Сюда нужно будет вынести все псевдоклассы, чтобы статью можно было найти, набрав имя одного из них в поиске

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +`:optional` — находит любой `<input>`, у которого не устновлен атрибут `required` — т. е. находит необязтельные поля ввода. А `:required` — наоборот, те `<input>`, у которых есть этот атрибут.
```suggestion
`:optional` находит любой `<input>`, у которого не устновлен атрибут `required` — то есть находит необязтельные поля ввода. А `:required` — наоборот, те `<input>`, у которых есть этот атрибут.
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по <a href="#:target">#:target</a>, а когда упоминание этого `id
```suggestion
Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по `<a href="#:target">#:target</a>`, а когда упоминание этого `id` будет в строке браузера, применятся стили, описанные в `:target`).
```

2020-12-23 08:25 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Псевдоклассы не обязательно описываются вместе с элементом — если он не указан, селектор будет обозначать любой доступный элемент, который *может иметь* этот псевдокласс (при активации нужного состоя
```suggestion
💡 Псевдоклассы не обязательно описываются вместе с элементом — если он не указан, селектор будет обозначать любой доступный элемент, который *может иметь* этот псевдокласс (при активации нужного состояния).
```

2020-12-23 08:27 UTC, pepelsbey requested changes

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +name: pseudoclasses
Я бы поделил название страницы на два слова: это по-русски псевдокласс пишется в одно слово (что не помогает его читаемости, честно говоря), а по-английски это два слова и лучше бы так.

```suggestion
name: pseudo-classes
```

Аналогично я бы поменял название страницы с псевдоэлементами.

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Селектор может и отсутсвовать — тогда правило применится ко всем элементам, которые могут иметь признак этого псевдокласса (например, запись `:focus {}` применится к любому элементу, который будет вы
Фокус-навигация это скорее выдуманный термин, тут лучше либо про сфокусированный элемент сказать, либо про навигацию с клавиатуры развернуть.

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +### `:any-link` / `:link` ([основная статья](./link.md)) / `:visited` ([основная статья](./visited.md))
```suggestion
### `:any-link`, `:link` ([основная статья](./link.md)), `:visited` ([основная статья](./visited.md))
```

Перечисление через запятую гораздо привычнее, мягче и уже встроено в язык. Слэши одни тяжёлые и многозначные.

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +### `:first-child` / `:last-child` / `:nth-child()` / `:nth-last-child()` / `:only-child`
Тоже есть статья

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +### `:first-of-type` / `:nth-of-type()` / `:last-of-typ`e /` :nth-last-of-type()` / `:only-of-type`
Тоже есть статья

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Элемент, который сейчас находится в фокусе (с помощью клавиши `Tab`). А `:focus-within` ещё обозначает элемент, внутри которого находится элемент в фокусе.
```suggestion
Элемент, который сейчас находится в фокусе (с помощью клавиши <kbd>Tab</kbd>). А `:focus-within` ещё обозначает элемент, внутри которого находится элемент в фокусе.
```
Имя клавиши — это не код, я бы попробовал начать переходить к правильному выделению, [см. спеку](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-kbd-element).

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Печатные селекторы (применятся при выведении документа на печать), обозначающие левую (`:left`) или правую (`:right`) страницы.
Учитывая отстутствующую поддержку и нулевую пользу на практике… может скипнуть? )

2020-12-23 08:27 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по <a href="#:target">#:target</a>, а когда упоминание этого `id
```suggestion
Селектор, который применится к элементу, `id` которого используется как якорная ссылка на фрагмент (например, на текущий блок можо сослаться по `<a href="#target">#target</a>`, а когда упоминание этого `id` будет в строке браузера, применятся стили, описанные в `:target`).
```

Двоеточие в id путает, предлагаю называть эти ссылки якорями, есть такая традиция.

2020-12-24 02:52 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +Печатные селекторы (применятся при выведении документа на печать), обозначающие левую (`:left`) или правую (`:right`) страницы.
Все, кроме Firefox: https://caniuse.com/mdn-css_selectors_right

2020-12-24 04:01 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по <a href="#:target">#:target</a>, а когда упоминание этого `id
Хотел намеренно оставить ссылкой, а не примером кода, чтобы пример ссылки на фрагмент был интерактивным (ссылаясь на себя же).

2020-12-24 04:02 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +name: pseudoclasses
@solarrust , что думаешь?

2020-12-24 04:09 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +### `:any-link` / `:link` ([основная статья](./link.md)) / `:visited` ([основная статья](./visited.md))
Попробовал у себя в редакторе — субъективно читаемость с запятыми стала хуже, непонятно, что это разные блоки слов, всё сливается:

![Снимок экрана 2020-12-24 в 7 09 07](https://user-images.githubusercontent.com/2073959/103059689-e39cca80-45b6-11eb-8180-031a7d8afb50.png)

Сейчас:

![Снимок экрана 2020-12-24 в 7 07 21](https://user-images.githubusercontent.com/2073959/103059707-f1eae680-45b6-11eb-94d2-4ac64b246721.png)

2020-12-24 04:11 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по <a href="#:target">#:target</a>, а когда упоминание этого `id
Это было намеренно — это должна была быть ссылка, а не код. Чтобы не дублировать обсуждение, посмотри, пожалуйста, https://github.com/Y-Doka/y-doka.site/pull/410#discussion_r548372276

2020-12-24 11:36 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как #-ссылка на фрагмент (например, на текущий блок можо сослаться по <a href="#:target">#:target</a>, а когда упоминание этого `id
Но он таким не был, не парсился как ссылка. Был как инлайн-код, только без внешнего выделения

2020-12-24 11:38 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:any-link` / `:link` ([основная статья](./link.md)) / `:visited` ([основная статья](./visited.md))
Пока что в подобных случаях везде используем слэши. Предлагаю обсудить этот момент коллективно. Пока я за вариант со слэшами

2020-12-24 19:52 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Печатные селекторы (применятся при выведении документа на печать), обозначающие левую (`:left`) или правую (`:right`) страницы.
@Realetive доверять таблицам поддержки от MDN нельзя: кажется Safari до сих пор не поддерживает `@page`, а без этой директивы этот псевдокласс не работает. А там написано Safari 5.1, что бы это ни значило. В итоге только Chrome, но поднимите руку, кто пробовал этот псевдокласс на практике и готов ручаться, что он работает. Я предлагаю это обсудить отдельно — как нам быть со спеками для печати.

2020-12-24 23:01 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +Печатные селекторы (применятся при выведении документа на печать), обозначающие левую (`:left`) или правую (`:right`) страницы.
Согласен. CSS для печати — отдельная инфраструктура, как «Вёрстка писем». Пожалуй, действительно скипну эту категорию.

2021-01-25 07:47 UTC, solarrust commented
@Realetive в каком состоянии эта статья? Если можно ревьюить и потенциально мёржить, то переведи, пожалуйста, в статус активного PR или черновика

2021-01-29 10:51 UTC, pepelsbey requested changes

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +  - :invalid
Думаю двоеточи здесь не нужны, что скажешь @nlopin? Мало ли кто будет искать без двоеточия и не найдёт.

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Позволяет находить элементы формы по состоянию их атрибута `disabled`. _Почти_ эквивалентны селекторам по атрибуту (`[disabled] {}` и `:not([disabled])` соответсвенно), но более гибкие, т. к. среагир
```suggestion
Позволяют находить элементы формы по состоянию их атрибута `disabled`. _Почти_ эквивалентны селекторам по атрибуту (`[disabled]` и `:not([disabled])` соответственно), но более гибкие, т. к. среагируют на унаследованное состояние `disabled`. Если есть `<fieldset disabled>`, то отключаются вложенные в него контролы форм.
```

Немного упростил объяснение и поправил пример.

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Для `<input>` indeterminate-состояние в HTML можно задать только через JavaScript.
```suggestion
Для `<input>` состояние `indeterminate` в HTML можно задать только через JavaScript.
```

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +Селектор по языку содержимого текста. В HTML есть атрибут lang, который указывает на язык содержимого, этот псевдокласс позволяет обратиться к элементу по содержимому этого атрибута:
```suggestion
Селектор по языку содержимого текста. В HTML есть атрибут `lang`, который указывает на язык содержимого, этот псевдокласс позволяет обратиться к элементу по содержимому этого атрибута.
```

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +}
```suggestion

Например, в арабском языке нет переносов:

```css
:lang(ar) {
  hyphens: none;
}
```

Лучше избегать текста внутри примеров кода: комментарии в подсветке нечитаемые, переносов нет.

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +
```suggestion
Находит элемент, которые **не соответсвует** селектору, который передан в качестве аргумента. Очень мощный псевдокласс, позволяющий писать эффективные CSS-селекторы.

Выделим красной рамкой все `<img>`, которым забыли прописать атрибут `alt`:

```css
```

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +💡 Псевдоклассы не обязательно описываются вместе с элементом — если он не указан, селектор будет обозначать любой доступный элемент, который *может иметь* этот псевдокласс (при активации нужного сост
```suggestion
💡 Псевдоклассы не обязательно описываются вместе с элементом — если он не указан, селектор будет обозначать любой доступный элемент, который _может иметь_ этот псевдокласс (при активации нужного состояния).
```

Лучше последовательно применять курсив, до сих пор был _

2021-01-29 10:51 UTC, pepelsbey commented on src/posts/css/doka/pseudoclasses.md
> +
```suggestion
💡 Псевдокласс может быть описан у любого элемента при написании селектора, т. е. если задать его родителю, то можно стилизовть дочерний элемент при изменении состояния у родителя.

Если курсор находится внутри `<nav>`, увеличить размер шрифта у вложенных ссылок:

```css
```

2021-01-29 10:56 UTC, Realetive commented
@pepelsbey, принял, спасибо.

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +name: pseudo-classes
Имя не совпадает с именем файла. Из-за этого 404 ошибка при переходе на статью.

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +title: Псевдоклассы
Заверни, пожалуйста, в кавычки.

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Благодаря псевдоклассам мы можем контролировать _динамические_ параметры селекторов, то есть эти свойства сработают тогда, когда селектор **подходит** под дополнительный признак, не зависящий от уров
```suggestion
Благодаря псевдоклассам мы можем контролировать _динамические_ параметры селекторов. Эти свойства сработают когда селектор **подходит** под дополнительный признак.
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Селектор может и отсутствовать — тогда правило применится ко всем элементам, которые могут иметь признак этого псевдокласса (например, запись `:focus {}` применится к любому элементу, который будет в
```suggestion
Селектор может и отсутствовать. Тогда правило применится ко всем элементам, которые могут иметь признак этого псевдокласса. Например, CSS-правило `:focus {}` применится к любому элементу, который будет выделен с помощью навигации по клавише <kbd>Tab</kbd> с клавиатуры.
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +<!-- TODO: перелинковать со статьями, которые уже написаны -->
Если это уже сделано, то тудушку можно удалять =)

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Применяется ко всем элементам,которые могут иметь атрибут `href` (`<a>`, `<area>` и `<link>`). `:link` характеризует ещё не посещённые страницы, `:visited` — наоборот, посещённые (в рамках одного дом
```suggestion
Применяется ко всем элементам, которые могут иметь атрибут `href` (`<a>`, `<area>` и `<link>`). `:link` характеризует ещё не посещённые страницы, `:visited` — наоборот, посещённые (в рамках одного домена).
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Находит элемент формы (`<input type="radio">`, `<input type="checkbox">`, `<option>`, `<button>`), установленный по умолчанию для группы связаных элементов (например, в случае с `<input type="checkbo
Запуталась пока читала это предложение. Воздуха в лёгких не хватает. Пожалуйста, разбей на несколько маленьких и менее запутанных =)

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +### `:empty`
Почти замёржена статья про этот псевдоэлемент. Можно привентивно поставить ссылку.

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Применяется к элементам, у которых внутри нет других тегов или текста. Например, можно проверить, что у кнопки не задан текст или иконка, чтобы задать минимальные размеры (хотя, для этого можно испол
```suggestion
Применяется к элементам, у которых внутри нет других тегов или текста. Например, можно проверить, что у кнопки не задан текст или иконка, чтобы задать минимальные размеры:
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Позволяет уточнить селектор, передав в аргумент отношение к элементу, к которому применятся псевдокласс `:has()`. К сожалению, пока с поддержкой всё очень плохо — ни один браузер ещё не внедрил его п
```suggestion
Позволяет уточнить селектор, передав в аргумент отношение к элементу, к которому применятся псевдокласс `:has()`. В январе 2021 года нет поддержки ни в одном бразере. Проверяйте актуальное состояние на [caniuse.com](https://caniuse.com).
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Элементы, который могут находиться в «промежуточном» состоянии:
```suggestion
Элементы, которые могут находиться в «промежуточном» состоянии:
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +`:optional` находит любой `<input>`, у которого не устновлен атрибут `required` — то есть находит необязтельные поля ввода. А `:required` — наоборот, те `<input>`, у которых есть этот атрибут.
```suggestion
`:optional` находит любой `<input>`, у которого не установлен атрибут `required` — то есть находит необязтельные поля ввода. А `:required` — наоборот, те `<input>`, у которых есть этот атрибут.
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Находит элементы, недоступные (`:read-only`) или наоборот (`:read-write`) для редактирования (например, в зависимости от наличия атрибута `disabled` или `readonly`).
```suggestion
Находит элементы, недоступные (`:read-only`) или наоборот (`:read-write`) для редактирования. Например, ориентируется на наличие атрибута `disabled` или `readonly`.
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Соответсвует корневому тегу-элементу документа. Для HTML это, соответсвенно, `<html>`, для SVG — `<svg>`, но выше по специфичности, чем просто селектор по тегу.
```suggestion
Соответсвует корневому тегу-элементу документа. Для HTML это, соответсвенно, `<html>`, для SVG — `<svg>`. Специфичность селектора `:root` выше, чем у селектора по тегу.
```

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +Селектор, который применится к элементу, `id` которого используется как якорная ссылка на фрагмент (например, на текущий блок можо сослаться по `<a href="#target">#:target</a>`, а когда упоминание эт
Очень сложное предложение, не поняла =(

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +💡 Псевдокласс может быть описан у любого элемента при написании селектора, т. е. если задать его родителю, то можно стилизовть дочерний элемент при изменении состояния у родителя.
Не поняла, о чём тут речь пока не посмотрела пример. Надо попроще.

2021-01-29 12:40 UTC, solarrust commented on src/posts/css/doka/pseudoclasses.md
> +<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>
Если в статье несколько пенов, то подключать скрипт можно только у последнего. У остальных удалить. Чтобы при загрузке страницы не тянуть лишнего.

2021-01-29 13:03 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +name: pseudo-classes
@solarrust меняю тогда имя файла на оригинально-каноничное pseudo-classes.md

2021-01-29 13:07 UTC, Realetive commented on src/posts/css/doka/pseudoclasses.md
> +<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>
Они тогда из кэша возьмутся, не будет лишних загрузок.

2021-01-29 15:36 UTC, nlopin commented on src/posts/css/doka/pseudoclasses.md
> +  - :invalid
мы ищем по подстрокам, в таком варианте найдем и с двоеточие, и без. Если уберем `:`, то поиск с двоеточием ничего не найдет

2021-02-02 04:21 UTC, solarrust commented
@Realetive можно ревьюить?

2021-02-02 07:58 UTC, Realetive commented
@solarrust да.

2021-02-02 20:18 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +```
На мой взгляд, пример не очень жизненный. Нет, он конечно поражает воображение, но хотелось бы чего-то, что упростит решение какой-то ежедневной задачи. Тут у Мириам есть [хороший тредик](https://twitter.com/MiriSuzanne/status/1356684692800512002). Плюс описание лучше всегда выносить из кода.

2021-02-08 08:40 UTC, solarrust commented
@Realetive добей, пожалуйста, сегодня.

2021-02-22 16:51 UTC, pepelsbey requested changes
Осталась пара опечаток, правки в примере и всё :)

2021-02-22 16:51 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +```
Удаляет предыдущий пример и расширяет описание примера:

````suggestion
Вместо длинного перечисления всех вариантов вложенности:

```css
h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
  /* … */
}
```

…можно перечислить первую часть селектора внутри `:is()` и не повторять вторую часть:

```css
:is(h1, h2, h3, h4, h5, h6) a {
  /* … */
}
```
````

2021-02-22 16:51 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Позволяет найти элементы по направлению текста в нём (например, в арабском направление письма идёт справа на лево). К сожалению, пока свойство поддерживается только в Firefox.
```suggestion
Позволяет найти элементы по направлению текста в нём (например, в арабском направление письма идёт справа налево). К сожалению, пока свойство поддерживается только в Firefox.
```

2021-02-22 16:51 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +```
````suggestion
Cкроем панель управления у плеера, если он развёрнут на весь экран:

```css
.player:fullscreen .player__controls {
  display: none;
}
```
````

2021-02-22 16:51 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Соответсвует корневому тегу-элементу документа. Для HTML это, соответсвенно, `<html>`, для SVG — `<svg>`. Специфичность селектора `:root` выше, чем у селектора по тегу.
```suggestion
Соответствует корневому тегу-элементу документа. Для HTML это, соответсвенно, `<html>`, для SVG — `<svg>`. Специфичность селектора `:root` выше, чем у селектора по тегу.
```

2021-03-30 08:19 UTC, solarrust commented
@pepelsbey приходи! 👐

2021-03-30 10:19 UTC, pepelsbey requested changes
Может и про `:where()` добавим, раз уж такое дело? Он уже [раскатился по браузерам](https://caniuse.com/mdn-css_selectors_where).

2021-03-30 10:19 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Позволяет найти элементы по направлению текста в нём (например, в арабском направление письма идёт справа налево). К сожалению, пока свойство поддерживается только в Firefox.
```suggestion
Позволяет найти элементы по направлению текста в нём (например, в арабском направление письма идёт справа налево). К сожалению, пока свойство [поддерживается только в Firefox](https://caniuse.com/css-dir-pseudo).
```

2021-03-30 10:19 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Селекторы элемента по его положению относительно родителя (первый, последний, n-ый, единственный).
```suggestion
Селекторы элемента по его положению относительно родителя (первый, последний, n-й, единственный).
```

2021-03-30 10:19 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Позволяет уточнить селектор, передав в аргумент отношение к элементу, к которому применятся псевдокласс `:has()`. В январе 2021 года нет поддержки ни в одном бразере. Проверяйте актуальное состояние
```suggestion
Позволяет уточнить селектор, передав в аргумент отношение к элементу, к которому применятся псевдокласс `:has()`. В январе 2021 года [нет поддержки ни в одном бразере](https://caniuse.com/css-has).
```

2021-03-30 10:19 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +- `<progress>`.
```suggestion
Элементы, которые могут находиться в «промежуточном» состоянии:

- `<input type="checkbox">`, отображающий, что не все пункты вложенной группы были выделены;
- группа `<input type="radio">` с одинаковым `name`, но у которой ни один элемент не установлен в `checked`;
- `<progress>`.
```

2021-03-30 10:19 UTC, pepelsbey commented on src/posts/css/doka/pseudo-classes.md
> +Экспериментальный селектор (пока в черновиках спецификции). Позволяет сгруппировть схожие селекторы вместо последовательного перечисления через запятую. При группировке большого количества селекторов
```suggestion
Позволяет сгруппировть схожие селекторы вместо последовательного перечисления через запятую. При группировке большого количества селекторов это может существенно сократить, а главное — упростить написание:
```
[Уже не экспериментальный](https://caniuse.com/css-matches-pseudo)

2021-03-30 10:20 UTC, pepelsbey commented
@solarrust несколько мелких правок и предложение добавить `:where()`, но ты сама смотри, что лучше: смёржить сейчас и дописать потом или быстро добавить.

2021-03-30 12:06 UTC, Realetive commented on src/posts/css/doka/pseudo-classes.md
> +Экспериментальный селектор (пока в черновиках спецификции). Позволяет сгруппировть схожие селекторы вместо последовательного перечисления через запятую. При группировке большого количества селекторов
🎉

2021-03-30 12:54 UTC, solarrust commented
Давайте смёржим и потом докинем про `where()`, оно пока в курсе не встречается.

2021-03-31 22:59 UTC, pepelsbey approved these changes

2021-04-01 16:08 UTC, solarrust approved these changes

2021-04-01 16:13 UTC, merged