Добавляет статью про псевдокласс :has()
Y-Doka/y-doka.site pull request #411
Opened 2020-12-23 07:00 UTC by Realetive

2020-12-23 08:16 UTC, pepelsbey requested changes

2020-12-23 08:16 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +```
Это лучше разделить на блоки с подписями, комментарии гораздо сложнее читать, они обычно не переносятся на узких экранах и рисуются бледно-серым в подсветке.

2020-12-23 08:16 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +Псевдокласс `:has()` позволяет уточнить селектор, передав в аргумент отношение к элементу, к которому применятся этот псевдокласс. Можно, например, выбрать такой селектор `A`, внутри которого есть пр
> Можно, например, выбрать такой селектор…

Вот эту часть совсем не понял. Тут лучше показать простой селектор `:has()` и объяснить, что он значит. Задача этого интро максимально просто объяснить.

2020-12-23 08:16 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +```
Сами примеры, к сожалению, не объясняют, зачем тут `:has()`, ведь проще написать `dt + dt` (может речь про `dd`?), `a img`, `* > section h2`. Тут лучше взять примеры прямо из спецификации, они гораздо нагляднее.

2020-12-24 01:50 UTC, Realetive commented on src/posts/css/doka/has.md
> +```
`dt + dt` применится ко второму `<dt>` (хотел показать как раз инверсию каскада). Про остальные примеры — согласен, спасибо, перепишу.

2021-01-25 07:49 UTC, solarrust commented
@Realetive как дела с этим PR? В каком состоянии статья?

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +name: has()
Не совпадает с именем файла. Навигация сломается

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +  - :has()
Есть в заголовке. В поиск попадёт

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +Псевдокласс `:has()` позволяет выбрать элемент, уточнив поиск аргументом-селектором, который находится внутри этого элемента.
Кратко, но не до конца понятно =) Не обязательно обходится одним предложением. Лучше 2-3, но чтобы из них правдо были понятны юз кейсы этого псевдокласса.

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +В отличие от соседнего селектора `+` (`dt + dt`) будет выбран не второй элемент, а первый, т. е. `:has()` позволяет буквально инвертировать каскад.
инвертировать каскад — сложна 🥲

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +Селектор-аргумент описывает вложенные (дочерние) элементы.
Так вложенные или дочерние?

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +Селектор-аргумент описывает вложенные (дочерние) элементы.
И до сих пор так и не понятно где тут в этой конструкции селектор-аргумент. Это нигде не поясняется.

2021-02-02 04:19 UTC, solarrust commented on src/posts/css/doka/has.md
> +🛠 До появления псевдокласса `:has()` единственная возможность управлять проверкой вложенного селектора была с помощью JavaScript.
Надо пример того, что раньше делалось на JS, а теперь можно будет обойтись только `:has()`.

2021-02-08 08:36 UTC, solarrust commented
@Realetive пожалуйста, добей сегодня

2021-02-17 17:18 UTC, Realetive commented on src/posts/css/doka/has.md
> +🛠 До появления псевдокласса `:has()` единственная возможность управлять проверкой вложенного селектора была с помощью JavaScript.
Пока нельзя — поддержки нет и не планируется. Пример на JavaScript будет весьма нетривиальным, т. к. больше зависит от задачи поиска (соседний элемент или вложенный) и явно выходит за тему статьи.

Пример `.class:has(+ .other-class)`: https://codepen.io/Realetive/pen/LYbygJJ

2021-02-17 17:39 UTC, Realetive commented on src/posts/css/doka/has.md
> +🛠 До появления псевдокласса `:has()` единственная возможность управлять проверкой вложенного селектора была с помощью JavaScript.
Пример с `a:hover:has(img)`: https://codepen.io/Realetive/pen/xxRdmjE

2021-02-19 15:47 UTC, pepelsbey requested changes
Описание настойчиво ограничивает has сценарием вложенности, но это не совсем так. Это скорее дополнение, расширение селектора. Ну и уточнил, что он пока не поддерживается ни в одном браузере.

И тут вопрос к @solarrust: как мы относимся к технологиям, которые пока нигде не работают? :) Даже демку пока не сделать — негде проверить, даже за флагом.

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Селектор `[selector]` слишком напоминает выборку по атрибуту, ну и в значении `has` нет квадратных скобок. Лучше последовательно: `selector` и `selector`. Плюс убрал «родителя», иначе возникает иллюзия, что он должен быть вложен, но он может просто стоять рядом.

````suggestion
```css
selector:has(selector) {
  /* … */
}
```

Первый `selector` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Второй `selector`, он же аргумент в `:has()`, описывает селектор относительно первого селектора.
````

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +По сути псевдокласс `:has()` позволяет «заглянуть» внутрь селектора и сделать проверку дочерних элементов по правилу-селектору, но применить правило именно к родительскому элементу.
Тут снова подчёркивается родительско-дочерний характер селектора, хотя это не так. Предложил вариант:

```suggestion
По сути псевдокласс `:has()` позволяет уточнить основной селектор дополнительным селектором любой сложности.
```

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +💡 Использование `:has()` не влияет на специфичность, т. е. при рассчёте «веса» селектора учитывается только «родительский селектор», к которому применяется этот псевдокласс.
```suggestion
💡 Использование `:has()` не влияет на специфичность, т. е. при рассчёте «веса» селектора учитывается только целевой селектор, к которому применяется этот псевдокласс.
```

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +В отличие от соседнего селектора `+` (`dt + dt`) будет выбран не второй элемент, а первый, т. е. `:has()` позволяет буквально _инвертировать каскад_ — правило применится не к последнему селектору, а
Ситуация проверки `dt + dd` более понятна, чем `dt + dt`, так что немного поменял теги. Ну и это не инвертируется каскад (порядок применения стилей), а инвертирует селектор.

````suggestion
Правила применятся только к такому `<dt>`, за которым сразу следует другой элемент `<dd>`:

```css
dt:has(+ dd) {
  /* … */
}
```

В отличие от соседнего селектора `+` (`dt + dd`) будет выбран не второй элемент, а первый, т. е. `:has()` позволяет буквально _инвертировать селектор_ — правило применится не к последнему селектору, а к тому, который указан перед `:has()`.
````

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +У этого псевдокласса пока всё очень печально с поддержкой — [следим за обновлениями](https://caniuse.com/css-has) и с нетерпением ждём новостей!
Чуть более прямолинейно (и честно) про поддержку

```suggestion
Этого псевдокласс пока не поддерживается ни в одном браузере, даже за флагом, так что [следим за обновлениями](https://caniuse.com/css-has) и с нетерпением ждём новостей!
```

2021-02-19 15:47 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +Псевдокласс `:has()` позволяет выбрать элемент, уточнив поиск аргументом-селектором, который находится внутри этого элемента. При этом правило применится только к тому селектору, который был описан *
Убирает про вложенность

```suggestion
Псевдокласс `:has()` позволяет выбрать элемент, уточнив основной селектор дополнительным, при этом не увеличив его вес. В отличие от привычных селекторов, правило применится только к тому селектору, который был описан **до** `:has()`.
```

2021-02-19 15:50 UTC, solarrust commented
> Описание настойчиво ограничивает has сценарием вложенности, но это не совсем так. Это скорее дополнение, расширение селектора. Ну и уточнил, что он пока не поддерживается ни в одном браузере.
> 
> И тут вопрос к @solarrust: как мы относимся к технологиям, которые пока нигде не работают? :) Даже демку пока не сделать — негде проверить, даже за флагом.

Отвечаю на вопрос: `:has()` упоминается в программе как ожидаемая технология. Было бы круто дать ссылочку на нашу статью, чтобы человек понял принцип работы. Отсюда эта тема и появилась в плане =)

2021-02-19 15:53 UTC, pepelsbey commented
Ага, норм. Тогда поправить бы некоторые формулировки и в путь :) Всё предложил.

> Отвечаю на вопрос: `:has()` упоминается в программе как ожидаемая технология. Было бы круто дать ссылочку на нашу статью, чтобы человек понял принцип работы. Отсюда эта тема и появилась в плане =)

2021-02-19 17:01 UTC, Realetive commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Декларация в `[ ]` — это [стандарт](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) для необязательных параметров.

2021-02-19 17:03 UTC, Realetive commented on src/posts/css/doka/has.md
> +По сути псевдокласс `:has()` позволяет «заглянуть» внутрь селектора и сделать проверку дочерних элементов по правилу-селектору, но применить правило именно к родительскому элементу.
Спасибо. Я мозг сломал — никак не мог это правильно выразить. Сам при чём понимаю, что «родительский» — не совсем корректная формулировка, но переклинило на «родительский» и уж ничего не смог поделать.

2021-02-22 18:27 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Да я понимаю, что стандарт. Но человек смотрит на CSS-код и видит CSS-селектор. И сложно его в этом винить :) Не было бы Доки, если бы всё, что «стандарт» можно было легко и понятно читать. Наша задача как раз писать понятно.

2021-03-02 10:03 UTC, Realetive commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Может, как-то разделить `selector` и `selector`? Мне на ум приходит разве-что `selector:has(has-selector)`.

2021-03-02 13:33 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Думаю, проще: `selector1` и `selector2`, по примеру видно где какой из них находится.

2021-03-02 18:09 UTC, Realetive commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
```suggestion
selector1:has(selector2) {
  /* … */
}
```

`selector1` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент `selector2` в `:has()` описывает селектор относительно `selector1`.
```

2021-03-03 14:50 UTC, pepelsbey requested changes

2021-03-03 14:50 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Важно избавиться от метафоры «родителя», она запутает.

```suggestion
`selector1` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент `selector2` в `:has()` описывает селектор относительно своей точки отсчёта — `selector1`.
```

2021-03-03 14:50 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +По сути псевдокласс `:has()` позволяет «заглянуть» внутрь селектора и сделать проверку дочерних элементов по правилу-селектору, но применить правило именно к родительскому элементу.
У нас здесь снова «родительский элемент». Чем не понравилась предложенная формулировка? Давай совсем уйдём от родительства — это путает.

2021-03-03 14:50 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +Этого псевдокласс пока не поддерживается ни в одном браузере, даже за флагом, так что [следим за обновлениями](https://caniuse.com/css-has) и с нетерпением ждём новостей!
```suggestion
Этот псевдокласс пока не поддерживается ни в одном браузере, даже за флагом, так что [следим за обновлениями](https://caniuse.com/css-has) и с нетерпением ждём новостей!
```

2021-03-03 14:50 UTC, pepelsbey commented on src/posts/css/doka/has.md
> +💡 Использование `:has()` не влияет на специфичность, т. е. при рассчёте «веса» селектора учитывается только целевой селектор, к которому применяется этот псевдокласс.
Выше уже вес без кавычек, тут тоже уже можно.

```suggestion
💡 Использование `:has()` не влияет на специфичность, т. е. при рассчёте веса селектора учитывается только целевой селектор, к которому применяется этот псевдокласс.
```

2021-03-03 21:08 UTC, Realetive commented on src/posts/css/doka/has.md
> +`[selector]` — необязательный селектор (если не указан — правило применится ко всем подходящим элементам). Аргумент в `:has()` описывает селектор относительно своего «родителя».
Что-то у меня всё смешалось. Когда батчил изменения, парсер съел часть текста и что-то я не оттуда накопировал старое описание про родителей.

2021-03-04 09:22 UTC, pepelsbey approved these changes
Ееее! Мы это сделали 🥇

2021-03-04 09:25 UTC, solarrust commented
Аллилуйя!

2021-03-04 09:26 UTC, solarrust approved these changes

2021-03-04 09:26 UTC, merged