Добавляет статью про элемент '<select>'
Y-Doka/y-doka.site pull request #412
Opened 2020-12-23 17:51 UTC by ezhkov

Закрывает #84

2020-12-23 21:23 UTC, pepelsbey commented
А может смёржить статьи про `<select>` и `<option>`? В каждой из них есть примеры с другим тегом и я не помню, чтобы были ситуации, когда они используются отдельно. У нас, например, готовится статься про таблицы — одна, про все элементы — мы не пишем про каждый. @solarrust что скажешь?

2020-12-23 21:25 UTC, solarrust commented
@pepelsbey Тег `option` ещё и в `datalist` используется. Поэтому логично вынести её отдельно и ссылаться в двух других статьях.

2020-12-23 21:34 UTC, pepelsbey requested changes

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Элемент `<select>` используется, когда нужно показать выпадающий список
```suggestion
Элемент `<select>` используется, когда нужно показать выпадающий список.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +###`autofocus`
```suggestion
### `autofocus`
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +###`disabled`
```suggestion
### `disabled`
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Бэктики отлично работают вместо `&lt;`, здесь и везде.

```suggestion
Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера `<fieldset>` или [`<form>`](/html/doka/form). Если ни у одного предка вверх по дереву этот атрибут не задан, то выпадающий список доступен для взаимодействия.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +###`form`
```suggestion
### `form`
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +###`multiple`
```suggestion
### `multiple`
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +###`size`
```suggestion
### `size`
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Указывает, должен ли обязательно быть выбран какой-то пункт выпадающего списка, значение атрибута `value` которого — это не пустая строка. Атрибут учитывается при валидации фор
```suggestion
Атрибут булевого типа. Указывает, должен ли обязательно быть выбран какой-то пункт выпадающего списка, значение атрибута `value` которого — это не пустая строка. Атрибут учитывается при валидации формы при отправке. Если поле не заполнить, то при попытке отправки формы браузер покажет ошибку.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Включает возможность выбора сразу нескольких пунктов списка. Если атрибут задан, то внешний вид списка поменяется с однострочного на многострочный с возможностью скроллинга
```suggestion
Атрибут булевого типа. Включает возможность выбора сразу нескольких пунктов списка. Если атрибут задан, то внешний вид списка поменяется с однострочного на многострочный с возможностью скроллинга.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Числовой атрибут. Если включен атрибут `multiple`, то это число указывает на количество видимых пунктов списка
```suggestion
Числовой атрибут. Если включен атрибут `multiple`, то это число указывает на количество видимых пунктов списка.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Выпадающий список — это один из элементов формы, почти не поддающихся стилизации. Мы можем немного изменить внешний вид самого элемента `<select>`, но выпадающий список опций вообще не стилизуется. М
```suggestion
Выпадающий список — это один из элементов формы, почти не поддающихся стилизации. Мы можем немного изменить внешний вид самого элемента `<select>`, но выпадающий список опций вообще не стилизуется. Многие дизайнеры любят рисовать нестандартные выпадающие списки в угоду красоте, но реализация таких списков очень трудоёмка и невозможна на чистом HTML и CSS. Рекомендуется для выпадающих списков оставлять родной вид, потому что такие списки обладают рядом преимуществ перед нестандартными. Например, выпадающий список опций может выходить за границы окна браузера, давая пользователю возможность выбрать нужный элемент.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +💡 Выбрать несколько элементов списка, когда включен атрибут `multiple`, можно, используя клавиши `Ctrl`, `Cmd` и `Shift`. Клавиши `Ctrl` (Windows, Linux) и `Cmd` (Mac OS) работают одинаково. Мы зажим
Клавиши — это не код, для них есть классный тег :) `<kbd>`

```suggestion
💡 Выбрать несколько элементов списка, когда включен атрибут `multiple`, можно, используя клавиши <kbd>Ctrl</kbd>, <kbd>Cmd</kbd> и <kbd>Shift</kbd>. Клавиши <kbd>Ctrl</kbd> (Windows, Linux) и <kbd>Cmd</kbd> (Mac OS) работают одинаково. Мы зажимаем эту клавишу на клавиатуре, а затем кликаем мышкой в нужные пункты списка. Этим способом можно выбрать несколько пунктов, находящихся на разном расстоянии друг от друга. Если выбрать пункт списка, зажать клавишу <kbd>Shift</kbd> и выбрать любой другой, то будут выбраны последовательно все пункты списка между этими двумя.
```

2020-12-23 21:34 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Внутри тега `<select>` могут использоваться только теги [&lt;option&gt;](/html/doka/option) и [&lt;optgroup&gt;](/html/doka/optgroup)
```suggestion
Внутри тега `<select>` могут использоваться только теги [&lt;option&gt;](/html/doka/option) и [&lt;optgroup&gt;](/html/doka/optgroup).
```

2020-12-23 21:35 UTC, pepelsbey commented
@solarrust логично!

2020-12-24 10:15 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
К сожалению, с бэктиками нельзя отличить ссылку от НЕ-ссылки:

![CleanShot 2020-12-24 at 13 12 19](https://user-images.githubusercontent.com/568355/103081952-18764500-45ea-11eb-9f25-4bc62a3f4913.png)

2020-12-24 10:30 UTC, pepelsbey commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Да, но это проблема стилей сайта, которую не стоит решать в отдельной статье. Об этом можно поставить задачу, а текст и код написать так, чтобы было правильно и как в остальных статьях.

2020-12-24 10:38 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Да, я согласен. Внёс исправления. Спасибо

2020-12-24 11:20 UTC, solarrust commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Завела задачу #420

2020-12-24 11:32 UTC, solarrust commented on src/posts/html/doka/select.md
> +В примере выше показано типовое использование элемента `<select>`. Это своего рода обёртка над списком опций, которые задаются тегом [&lt;option&gt;](/html/doka/option). Чтобы иметь возможность отпра
```suggestion
В примере выше показано типовое использование элемента `<select>`. Это своего рода обёртка над списком опций, которые задаются тегом [`<option>`](/html/doka/option). Чтобы иметь возможность отправить выбранное значение на сервер, необходимо выполнить несколько условий:
```

2020-12-24 11:32 UTC, solarrust commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Есть статья про `fieldset`

2020-12-24 11:32 UTC, solarrust commented on src/posts/html/doka/select.md
> +Имя выпадающего списка. При отправке формы значение атрибута `name` будет ключом в отправляемом объекте
```suggestion
Имя выпадающего списка. При отправке формы значение атрибута `name` будет ключом в отправляемом объекте.
```

2020-12-24 11:32 UTC, solarrust commented on src/posts/html/doka/select.md
> +Выпадающий список — это один из элементов формы, почти не поддающихся стилизации. Мы можем немного изменить внешний вид самого элемента `<select>`, но выпадающий список опций вообще не стилизуется. М
Давай добавим совет про то, как сделать первый пункт серым. Типа чтобы "выберите свой город" был серым. 
И ещё совет о том, как сделать нестандартные стрелочки.

2020-12-24 12:57 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Атрибут булевого типа. Если задан, то выпадающий список отключается для взаимодействия с пользователем. Если атрибут не задан, то он может быть унаследован у одного из предков (например у контейнера
Добавил ссылку

2020-12-24 13:25 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Выпадающий список — это один из элементов формы, почти не поддающихся стилизации. Мы можем немного изменить внешний вид самого элемента `<select>`, но выпадающий список опций вообще не стилизуется. М
Думаю, про первый пункт лучше написать в статье про `<option>`. Там всё таки задействован атрибут disabled именно у тега `option`

2020-12-24 19:40 UTC, pepelsbey approved these changes

2020-12-25 11:16 UTC, solarrust reviewed
Супер-мелкие правочки =)

2020-12-25 11:16 UTC, solarrust commented on src/posts/html/doka/select.md
> +В данном случае мы оборачиваем наш `<select>` дополнительным блоком, чтобы задействовать псевдолемент [`::after`](/css/doka/after/) этого блока. К сожалению, `<select>` относится к такому типу элемен
```suggestion
В данном случае мы оборачиваем наш `<select>` дополнительным блоком, чтобы задействовать псевдэолемент [`::after`](/css/doka/after/) этого блока. К сожалению, `<select>` относится к такому типу элементов, у которых нет своих псевдоэлементов [`::before`](/css/doka/before/) и [`::after`](/css/doka/after/).
```

2020-12-25 11:16 UTC, solarrust commented on src/posts/html/doka/select.md
> +Используем свойство [`appearance`](/css/doka/appearance/), чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не
```suggestion
Используем свойство `appearance`, чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не забываем про позиционирование, а также отключаем у псевдоэлемента взаимодействие с мышкой, иначе при клике на него выпадающий список раскрываться не будет.
```

Такой статьи пока нет =(

2020-12-25 14:26 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Используем свойство [`appearance`](/css/doka/appearance/), чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не
Вот тут момент для обсуждения, как мне кажется. Сейчас статьи нет, потом появится, а про кросс-сылку все забудут(( 
Я бы предложил сразу добавлять ссылки на будущие статьи. В идеале вообще хотелось бы какой-то механизм добавления ссылку на issue прямо на 404 странице. Типа, "Такой статьи ещё нет, но есть issue на создание. Поучаствуйте!". И ссылка на issue. Это пока фантазии, но мне кажется, было бы круто такое реализовать

2020-12-26 07:12 UTC, Realetive commented on src/posts/html/doka/select.md
> +Используем свойство [`appearance`](/css/doka/appearance/), чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не
Про 404 с предложением написать эту статью — отличная идея. Но нужно будет проассоциировать такие 404-е с соответсвующими issue. Или до готовности статьи ставить ссылку не на доку, а на issue (иначе 2 энтузиаста могут начать писать статью, не скооперировавшись в issue — получится 2 конфликтующие статьи).

2020-12-28 11:40 UTC, solarrust commented on src/posts/html/doka/select.md
> +Используем свойство [`appearance`](/css/doka/appearance/), чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не
Нет, не стоит добавлять ссылки на несуществующие статьи. Как минимум потому что в итоге статья может иметь другой адрес или свойство / тег, будут являться частью другой, большой статьи. 
В данный момент проще всего пойти в задачу по несуществующей статье и написать там заметку, что нужно вставить ссылку в ту-то статью после написания.

2020-12-29 06:36 UTC, ezhkov commented on src/posts/html/doka/select.md
> +Используем свойство [`appearance`](/css/doka/appearance/), чтобы отключить браузерную стрелку справа. В качестве стрелки ставим псевдоэлемент [`::after`](/css/doka/after/) от родительского блока. Не
Поправлено

2020-12-29 08:35 UTC, solarrust approved these changes

2020-12-29 08:35 UTC, merged