Добавляет статью про элемент '<option>'
Y-Doka/y-doka.site pull request #415
Opened 2020-12-23 19:37 UTC by ezhkov

Закрывает #378

2020-12-23 21:35 UTC, pepelsbey requested changes

2020-12-23 21:35 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +Тегом `<option>` размечается каждый элемент выпадающего списка [&lt;select&gt;](/html/doka/select/), группы опций [&lt;optgroup&gt;](/html/doka/optgroup/) или перечня [&lt;datalist&gt;](/html/doka/da
У нас кажется такой вариант (без мнемоники) нормально отрабатывает внутри ссылок. Здесь и везде.

```suggestion
Тегом `<option>` размечается каждый элемент выпадающего списка [`<select>`](/html/doka/select/), группы опций [`<optgroup>`](/html/doka/optgroup/) или перечня [`<datalist>`](/html/doka/datalist/).
```

2020-12-23 21:35 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +###`selected`
```suggestion
### `selected`
```

2020-12-23 21:35 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +###`label`
```suggestion
### `label`
```

2020-12-23 21:35 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +###`disabled`
```suggestion
### `disabled`
```

2020-12-24 10:23 UTC, ezhkov commented on src/posts/html/doka/option.md
> +Тегом `<option>` размечается каждый элемент выпадающего списка [&lt;select&gt;](/html/doka/select/), группы опций [&lt;optgroup&gt;](/html/doka/optgroup/) или перечня [&lt;datalist&gt;](/html/doka/da
Прокомментировал [тут](https://github.com/Y-Doka/y-doka.site/pull/412#discussion_r548480297)

2020-12-24 10:38 UTC, ezhkov commented on src/posts/html/doka/option.md
> +Тегом `<option>` размечается каждый элемент выпадающего списка [&lt;select&gt;](/html/doka/select/), группы опций [&lt;optgroup&gt;](/html/doka/optgroup/) или перечня [&lt;datalist&gt;](/html/doka/da
Внёс исправления

2020-12-24 11:17 UTC, solarrust commented on src/posts/html/doka/option.md
> +Тег `<option>` используется в интерактивных элементах управления для верстки одиночного пункта списка.
```suggestion
Тег `<option>` используется в интерактивных элементах управления для вёрстки одиночного пункта списка.
```

2020-12-24 11:17 UTC, solarrust commented on src/posts/html/doka/option.md
> +Атрибут булевого типа. Если задан, то пункт списка нельзя выбрать. Часто браузеры выделяют такой элемент управления серым цветом, и на нем не срабатывают события клика или фокуса. Даже если атрибут н
```suggestion
Атрибут булевого типа. Если задан, то пункт списка нельзя выбрать. Часто браузеры выделяют такой элемент управления серым цветом, и на нём не срабатывают события клика или фокуса. Даже если атрибут не задан, элемент всё равно может быть отключён, если находится внутри тега [`<optgroup>`](/html/doka/optgroup/) с заданным атрибутом `disabled`.
```

2020-12-24 11:17 UTC, solarrust commented on src/posts/html/doka/option.md
> +
Давай добавим кодпен с визуальной демонстрацией этого примера

2020-12-24 11:17 UTC, solarrust commented on src/posts/html/doka/option.md
> +К сожалению браузер не предоставляет никаких средств для нормальной стилизации элемента `<option>`, и это доставляет очень много головной боли фронтенд-разработчикам :(
Давай расскажем какие свойства можно менять. 
Про хаки с созданием несемантичных конструкций не будем писать =)

2020-12-24 13:37 UTC, ezhkov commented on src/posts/html/doka/option.md
> +
Он есть ниже. Там демонстрация всех атрибутов

2020-12-24 13:54 UTC, ezhkov commented on src/posts/html/doka/option.md
> +К сожалению браузер не предоставляет никаких средств для нормальной стилизации элемента `<option>`, и это доставляет очень много головной боли фронтенд-разработчикам :(
Никакие нельзя) Но рассказал про стилизацию multiple-списка

2020-12-24 19:41 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +К сожалению браузер не предоставляет никаких средств для нормальной стилизации элемента `<option>`, и это доставляет очень много головной боли фронтенд-разработчикам :(
Ну как, в некоторых браузерах можно менять параметры шрифта, но обычно выглядит это плохо.

2020-12-24 19:47 UTC, pepelsbey approved these changes

2020-12-25 07:17 UTC, ezhkov commented on src/posts/html/doka/option.md
> +К сожалению браузер не предоставляет никаких средств для нормальной стилизации элемента `<option>`, и это доставляет очень много головной боли фронтенд-разработчикам :(
Не знаю, насколько корректно рассказывать про один браузер. Насколько мне известно, только FF умеет изменять пару свойств.

2020-12-25 10:18 UTC, pepelsbey commented on src/posts/html/doka/option.md
> +К сожалению браузер не предоставляет никаких средств для нормальной стилизации элемента `<option>`, и это доставляет очень много головной боли фронтенд-разработчикам :(
Safari тоже умеет менять свойства шрифта, насколько я помню. Но результат получается такой стрёмный, что я бы просто промолчал :)

2020-12-25 11:06 UTC, solarrust approved these changes

2020-12-25 11:07 UTC, merged