Поправляет блокирующие запросы, #48
Y-Doka/y-doka.site pull request #419
Opened 2020-12-24 07:05 UTC by usmanyunusov

2020-12-24 10:03 UTC, pepelsbey requested changes

2020-12-24 10:03 UTC, pepelsbey commented on src/assets/styles/base/_inter-font.scss
> +  src: url("/assets/fonts/Inter/Inter-ThinItalic.woff2?v=3.15") format("woff2"),
А может назовём шрифты строчными? Раз уж занялись. Есть проблема на разных системах с регистром файлов: например, на macOS, если переименовать README в readme, то файл не поменяется. А на других ОС может поменяться. Тут заодно можно убрать префикс Inter, если он уже есть в названии папки :) Аналогично в других местах.

2020-12-25 05:17 UTC, usmanyunusov commented on src/assets/styles/base/_fonts.scss
> +@import "inter-font";
@pepelsbey готово 👍

2020-12-25 05:17 UTC, usmanyunusov commented
@pepelsbey  готово 👍

2020-12-25 10:08 UTC, pepelsbey commented
@usmanyunusov к сожалению, с camelCase такая же проблема, как с Title-Case, без проблем будет только kebab-case. Немного дожать бы :)

2020-12-28 07:06 UTC, usmanyunusov commented
@pepelsbey избавился от от camelCase

2020-12-28 22:45 UTC, pepelsbey approved these changes

2020-12-28 22:45 UTC, pepelsbey commented
- Подмёржил разного, подружил с мастером
- Удалил лишние шрифты после переименования
- Удалил лишние импорты в других шаблонах

Кажется всё хорошо :)

2021-01-13 17:36 UTC, nlopin approved these changes

2021-01-13 17:37 UTC, merged