Добавил статью про touch
Y-Doka/y-doka.site pull request #424
Opened 2020-12-25 10:22 UTC by Windrushfarer

Fixes #190

2020-12-25 22:52 UTC, nlopin requested changes

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +[События](/js/doka/events/) `touch` обрабатывают пользовательские касания на HTML элементе. В зависимости от того, какое действие пользователь произвел (прикоснулся, начал двигать пальцем и т.д.) про
Давай будем явными и сразу сказажем, что речь идет об устройствах с тач-экранами и стилусами. Пользовательские касания не всеми будут распознаны верно.

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +[События](/js/doka/events/) `touch` обрабатывают пользовательские касания на HTML элементе. В зависимости от того, какое действие пользователь произвел (прикоснулся, начал двигать пальцем и т.д.) про
Вместо неявного «какого-то действия» предлагаю сразу в явном виде сжато рассказать о событиях с помощью маркированного списка:

* `touchstart` — срабатывает при первом касании
* `touchend` — тогда-то 
* ...
*

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +Подписаться на событие, когда пользователь водит пальцем по элементу
Я бы еще привел аналогию с событием `mousemove`, у нас оно пока не описано, но добавим в список

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +Когда пользователь работает с компьютером, то чаще всего взаимодействие с элементами (например клик) на экране происходит с помощью курсора. Для обработки клика нам хватает встроенного сообытия [clic
```suggestion
Когда пользователь работает с компьютером, то чаще всего взаимодействие с элементами на экране происходит с помощью курсора. Для обработки клика нам хватает встроенного сообытия [*click*](/js/doka/element-click/). Событие *click* так же работает, если пользователь работает с интерфейсом через смартфон или планшет и взаимодействует с помощью касаний по экрану. 

Однако, на мобильных устройствах есть не только нажатия, но и жесты, и мультитач. Чтобы дать разработчикам возможность обрабатывать тактие сложные действия пользователей, браузеры стали предоставлять низкоуровнение API для обработки touch-событий. С их помощью можно построить интерфейсы с обработкой мультитача и жестов.
```

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +Когда пользователь работает с компьютером, то чаще всего взаимодействие с элементами (например клик) на экране происходит с помощью курсора. Для обработки клика нам хватает встроенного сообытия [clic
разбил на два абзаца и немного переформулировал. Мне кажется важнее сказать *зачем* нужен такой низкоуровневый интерфейс.

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +- `touchend` - вызовется когда пользователь убрал палец с элемента, т.е закончил прикосновение
```suggestion
- `touchend` - вызовется когда пользователь убрал палец с элемента (закончил прикосновение)
```

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +- `touchcancel` - вызовется, если событие было прервано, например, если будет слишком много одноверменных точек прикосновения либо палец ушел за пределы экрана
> либо палец ушел за пределы экрана

экрана или элемента?

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +Самое событие касания `TouchEvent` содержит несколько полезных полей, про которые стоит знать:
```suggestion
Событие касания `TouchEvent`, которое передается в обработчик, содержит несколько полезных полей, про которые стоит знать:
```

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +В демо ниже можно посмотреть как использовать типы событий касаний и поля события, чтобы сделать простую рисовалку. Демку лучше попробовать через смартфо, т.к. касания с помощью мыши недоступны.
```suggestion
Рисовалка ниже использует поля события и типы событий касаний. Испольщуйте смартфон, так как касания не работают на мыши.
```

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +## В работе
Давай еще добавим верхнеуровнево, как с помощью такого апи делают обработку жестов?

2020-12-25 22:52 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +## В работе
Давай еще добавим верхнеуровнево, как с помощью такого апи делают обработку жестов?

2020-12-29 11:56 UTC, Windrushfarer commented on src/posts/js/doka/element-touch.md
> +Подписаться на событие, когда пользователь водит пальцем по элементу
@nlopin Может тогда привести аналогии и с другими? `mousedown`, `mouseup` и т.д.

2020-12-29 11:56 UTC, Windrushfarer commented on src/posts/js/doka/element-touch.md
> +- `touchcancel` - вызовется, если событие было прервано, например, если будет слишком много одноверменных точек прикосновения либо палец ушел за пределы экрана
И то и другое на самом деле :) добавлю

2020-12-29 12:58 UTC, nlopin commented on src/posts/js/doka/element-touch.md
> +Подписаться на событие, когда пользователь водит пальцем по элементу
Давай

2021-01-02 13:00 UTC, nlopin approved these changes

2021-01-02 13:01 UTC, merged