Добавил статью про expressions vs statements
Y-Doka/y-doka.site pull request #431
Opened 2020-12-26 00:05 UTC by Windrushfarer

Здесь определенно стоит поработать с картинками схем, т.к я подготовил их в 2х размере для ретины и не особо оптимизировал размеры. Потому в самой статье они сейчас выглядят громадными

2020-12-26 00:07 UTC, Windrushfarer commented
@nlopin насыпал схем и картинок, посмотри на их содержимое пожалуйста. Кажется получилось то, что ты предполагал.

2020-12-26 00:20 UTC, pepelsbey requested changes

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +# Кратко
Нужно всю систему заголовков сдвинуть на 1 уровень: h2, h3 — а то h1 уже есть у страницы.

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +После ввода числа, консоль нам ответит тем же самым числом. Поздравляю, это было самое простое выражение. Интепрератор JavaScript выполнил его и вернул результат последней (и в данном случае единстве
```suggestion
После ввода числа, консоль нам ответит тем же самым числом. Поздравляю, это было самое простое выражение. Интерпретатор JavaScript выполнил его и вернул результат последней (и в данном случае единственной) операции.
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +На самом деле в JavaScript есть выражение, которое позволяет возвращать значение по условие. Таким выражением является тернарный оператор, т.к он, как любое выражение, возвращает значение.
```suggestion
На самом деле в JavaScript есть выражение, которое позволяет возвращать значение по условие. Таким выражением является тернарный оператор, т.к. он, как любое выражение, возвращает значение.
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +И точно так же, объединяя инструкцию с другими выражениями мы получаем более осмысленную программу. ![Схема зацикленного блока](/assets/images/posts/js/expressions-vs-statements/loop-statement.png)
```suggestion
И точно так же, объединяя инструкцию с другими выражениями мы получаем более осмысленную программу.

![Схема зацикленного блока](/assets/images/posts/js/expressions-vs-statements/loop-statement.png)
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +В JavaScript все инструкции можно поделить на несколько категорий: управление потоком выполнения (ключевые слова [if/else](/js/doka/if-else), [switch](/js/doka/switch), `throw` и т.д.), итерации (клю
```suggestion
В JavaScript все инструкции можно поделить на несколько категорий: управление потоком выполнения (ключевые слова [`if` и `else`](/js/doka/if-else), [`switch`](/js/doka/switch), `throw` и т.д.), итерации (ключевые слова [`for`](/js/doka/for), [`while`](/js/doka/while) и т.д.), объявление значений (ключевые слова [`var`](/js/doka/var-let), [`let`](/js/doka/var-let), [`const`](/js/doka/const)), функции (ключевые слова [`function`](/js/doka/function), [`return`](/js/doka/return) и т.д.) и прочие (ключевые слова `debugger`, `import`, `export`). Перечисления всхе инстркций в этой статье не будет, надеюсь их суть понятна.
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +// Вызов функции это выражение, а в скобках можно передат какое-то выражение, но инструкцию нельзя
Лучше избегать длинных текстов внутри кода, их сложно читать по нескольким причинам.

```suggestion
Вызов функции это выражение, а в скобках можно передать какое-то выражение, но инструкцию нельзя.

```js
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +Последовательные инструкции можно разделять оператором точка с запятой `;`
```suggestion
Последовательные инструкции можно разделять оператором точка с запятой `;`.
```

2020-12-26 00:20 UTC, pepelsbey commented on src/posts/js/doka/expressions-vs-statements.md
> +x(), z() // вернется значение 2, потому z() выполнился последним
```suggestion
x(), z() // вернется значение 2, потому, что z() выполнился последним
```

2020-12-27 21:08 UTC, nlopin requested changes
Добавил свои комментарии. 

Нужно избегать неопределенных прилагательных «какой-то», «некоторый». Они вносят неопределенность, а мы здесь, чтобы порешивать вопросики и давать максимально конкретные ответы.

- [x] Переименовать схему`src/assets/images/posts/js/expressions-vs-statements/exressions.png ` → `src/assets/images/posts/js/expressions-vs-statements/expressions.png `

2020-12-27 21:08 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +Пример выше выглядит мало того, что странно, так еще он не будет работать. В качестве аргумента при вызове можно передавать значение (что является выражением) или какое-то составное выражение, которо
```suggestion
Пример выше не будет работать. В качестве аргумента при вызове можно передавать простое выражение (например, конкретную строку `"Elon Musk"` или число `5`), либо составное выражение, которое вычислит и вернет значение (например, вызов другой функции `getCurrentUser`).
```

2020-12-27 21:08 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +Пример выше выглядит мало того, что странно, так еще он не будет работать. В качестве аргумента при вызове можно передавать значение (что является выражением) или какое-то составное выражение, которо
Нужно избегать оценочных суждений. То, что выглядит странно для нас, не выглядит странно для начинающего. У новичков еще нет наработанных «идиом» кода и весь код выглядит одинаково непонятно

2020-12-27 21:08 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +getBioAbout("Sherlock" + " " + "Holmes")
```suggestion
getBioAbout("Elon Musk")
getBioAbout("Sherlock" + " " + "Holmes")
getBioAbout(getCurrentUser())
```

2020-12-27 21:08 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +getBioAbout("Sherlock" + " " + "Holmes")
докинул примеров

2020-12-27 21:08 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +А вот выражения можно разделять через оператор запятая `,`. В этом случае все выражения выполнятся по порядку слева направо, но результат вернется только от последнего в цепочке.
скажем, что обычно так не делают?

2020-12-29 11:25 UTC, Windrushfarer commented on src/posts/js/doka/expressions-vs-statements.md
> +![Схема последовательных выражений](/assets/images/posts/js/expressions-vs-statements/expressions.png)
Аналогично как и для предыдущих, показать как схематично могут выглядеть составные выражения. Эта для закрепления. Или после первых двух уже лишняя?

2020-12-29 11:43 UTC, Windrushfarer commented on src/posts/js/doka/expressions-vs-statements.md
> +// Вызов функции это выражение, а в скобках можно передат какое-то выражение, но инструкцию нельзя
Вообще убрал коммент и немного перефразировал пояснение после кода

2020-12-29 11:45 UTC, Windrushfarer commented on src/posts/js/doka/expressions-vs-statements.md
> +В JavaScript все инструкции можно поделить на несколько категорий: управление потоком выполнения (ключевые слова [if/else](/js/doka/if-else), [switch](/js/doka/switch), `throw` и т.д.), итерации (клю
@pepelsbey @nlopin 
Сделал списком. Однако мне не очень нравится как будет выглядеть если обернуть ссылок в инлайновые фрагменты кода, тогда непонятно ссылки это или нет. Вадим предлагал все обернуть в блочки кода, я бы так не делал, но тогда будут смешиваться ссылки и другие ключевые слова без ссылок, но при этом их тоже хочется выделить. Что думаете тут еще можно сделать?

2020-12-29 11:46 UTC, Windrushfarer commented on src/posts/js/doka/expressions-vs-statements.md
> +Для этого в языках программирования существуют различные **инструкции**, которые сами по себе выражением не являются, но при этом позволяет нам правильно настраивать операции.
Перефразировал

2021-01-05 21:51 UTC, nlopin approved these changes

2021-01-05 21:52 UTC, nlopin commented on src/posts/js/doka/expressions-vs-statements.md
> +В JavaScript все инструкции можно поделить на несколько категорий: управление потоком выполнения (ключевые слова [if/else](/js/doka/if-else), [switch](/js/doka/switch), `throw` и т.д.), итерации (клю
я сделал все как инлайновый код. не страшно, если пара будет некликабельными

2021-01-05 21:54 UTC, merged