Добавляет статью про text-rendering
Y-Doka/y-doka.site pull request #441
Opened 2020-12-29 20:28 UTC by ezhkov

Закрывает #103

2020-12-30 06:18 UTC, solarrust reviewed
Уф, сложная для понимания тема. Очень хочется картиночек с примерами лигатур и кернинга там, где ты впервые пишешь об этих сочетаниях.

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +author: ezhkov_d основного автора
```suggestion
author: ezhkov_d
```

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +Рендеринг текста - это процесс отрисовки символов шрифта в пиксельной сетке. При этом для лобеспечения более естественного вида текста браузер может выполнять дополнительные вычисления и модификации
```suggestion
Рендеринг текста — это процесс отрисовки символов шрифта в пиксельной сетке. При этом для обеспечения более естественного вида текста браузер может выполнять дополнительные вычисления и модификации символов: изменять **кернинг** (межсимвольное расстояние), объединять пары и даже тройки символов в **лигатуры**.
```

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +Яркий пример кернинговой пары - сочетание символов **AV** или **VA**. Яркий пример лигатур - сочетание символов **fi**, **fl**, **at** и тп. Не все шрифты имеют богатый набор кернинговых пар или лига
```suggestion
Яркий пример кернинговой пары — сочетание символов **AV** или **VA**. Ярким примером лигатур являются сочетания символов **fi**, **fl**, **at**. Не все шрифты имеют богатый набор кернинговых пар или лигатуры, поэтому употребление свойства `text-rendering` уместно не для каждого дизайна.
```

И добавить бы картинок сюда с иллюстрацией кернинговой пары и лигатуры, о которых ты пишешь.

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +Рендеринг текста — сложный процесс, и браузеру приходится решать, как именно оптимизировать вывод символов: где-то скорректировать кернинг, где-то собрать символы в лигатуры, а где-то обеспечить геом
```suggestion
Рендеринг текста это сложный процесс, и браузеру приходится решать, как именно оптимизировать вывод символов: где-то скорректировать кернинг, где-то собрать символы в лигатуры, а где-то обеспечить геометрическую точность отрисовки символа. Свойство `text-rendering` указывает, что именно должен оптимизировать браузер во время рендеринга.
```

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +В примере показаны различные шрифты для понимания терминов **лигатура** и **кернинговая пара**/
```suggestion
В примере показаны различные шрифты для понимания терминов **лигатура** и **кернинговая пара**.
```

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +Когда мы масштабируем текст, браузер вычисляет итоговый размер символа, опираясь на размер шрифта и текущий масштаб, после чего запрашивает шрифт вычисленного размера у операционной системы. Иногда с
```suggestion
Когда мы масштабируем текст, браузер вычисляет итоговый размер символа, опираясь на размер шрифта и текущий масштаб, после чего запрашивает шрифт вычисленного размера у операционной системы. Иногда сочетание «размер-масштаб» может выдать дробное итоговое значение (например, размер шрифта 12 при масштабе 110% даст в итоге 13.2), которого просто не существует в системе. Тогда браузер округляет размер до ближайшего целого (13) и запрашивает его в системе. Это приводит к ступенчатому изменению размера шрифта.
```

2020-12-30 06:18 UTC, solarrust commented on src/posts/css/doka/text-rendering.md
> +Когда браузер "рассчитал" внешний вид символа, он должен корректно отрисовать символ в пиксельной сетке экрана монитора. Процесс заполнения пикселей после расчётов для видимой отрисовки чего угодно н
```suggestion
Когда браузер «рассчитал» внешний вид символа, он должен корректно отрисовать символ в пиксельной сетке экрана монитора. Процесс заполнения пикселей после расчётов для видимой отрисовки чего угодно называется **рендеринг**.
```

2020-12-30 06:18 UTC, solarrust commented
@pepelsbey приходи почитать =)

2020-12-30 09:31 UTC, ezhkov commented on src/posts/css/doka/text-rendering.md
> +Рендеринг текста — сложный процесс, и браузеру приходится решать, как именно оптимизировать вывод символов: где-то скорректировать кернинг, где-то собрать символы в лигатуры, а где-то обеспечить геом
Перед «это» всё равно нужно тире)

2020-12-30 17:25 UTC, pepelsbey requested changes

2020-12-30 17:25 UTC, pepelsbey commented on src/posts/css/doka/text-rendering.md
> +<p class="legible">I'm filling this page</p>
```suggestion
<p class="legible">I’m filling this page</p>
```

2020-12-30 17:25 UTC, pepelsbey commented on src/posts/css/doka/text-rendering.md
> +## Как пишется
Стоит где-то пометить значение по умолчанию

2020-12-30 17:25 UTC, pepelsbey commented on src/posts/css/doka/text-rendering.md
> +Основной приоритет при рендеринге текста — геометрическая точность. В некоторых шрифтах кернинг изменяется не пропорционально изменению размера шрифта. Это может приводить к не самому лучшему внешнем
```suggestion
Основной приоритет при рендеринге текста — геометрическая точность. В некоторых шрифтах кернинг изменяется не пропорционально изменению размера шрифта. Это может приводить к не самому лучшему внешнему виду текста. При установке `text-rendering: geometricPrecision` браузер начинает вычислять кернинг, основываясь на геометрической точности в положении символов, благодаря чему в некоторых случаях внешний вид текста может существенно улучшиться.
```

2020-12-30 17:25 UTC, pepelsbey commented on src/posts/css/doka/text-rendering.md
> +Когда мы масштабируем текст, браузер вычисляет итоговый размер символа, опираясь на размер шрифта и текущий масштаб, после чего запрашивает шрифт вычисленного размера у операционной системы. Иногда с
```suggestion
Когда мы масштабируем текст, браузер вычисляет итоговый размер символа, опираясь на размер шрифта и текущий масштаб, после чего запрашивает шрифт вычисленного размера у операционной системы. Иногда сочетание размера и масштаба может выдать дробное итоговое значение (например, размер шрифта 12 при масштабе 110% даст в итоге 13,2), которого просто не существует в системе. Тогда браузер округляет размер до ближайшего целого (13) и запрашивает его в системе. Это приводит к ступенчатому изменению размера шрифта.
```

- Заменяет «размер-масштаб» на более читаемое и простое сочетание через «и»
- Правит разделитесь в дроби, но если хочется точку (то есть код), то лучше добавить пиксели `13.2px`

2021-01-14 16:30 UTC, pepelsbey commented on src/posts/css/doka/text-rendering.md
> +Ярким примером лигатур являются сочетания символов **fi**, **fl**, **at**. ![Пример лигатур](/assets/images/posts/text-rendering/ligatures.png)
```suggestion
<figure>
  <img src="/assets/images/posts/text-rendering/kerning.png" width="260" height="247" alt="Пример кернинговых пар">
  <figcaption>
    Яркий пример кернинговой пары — сочетание символов <strong>AV</strong> или <strong>VA</strong>.
  </figcaption>
</figure>

<figure>
  <img src="/assets/images/posts/text-rendering/ligatures.png" width="500" height="463" alt="Пример лигатур">
  <figcaption>
    Яркий пример кернинговой пары — сочетание символов <strong>fi</strong>, <strong>fl</strong>, <strong>at</strong>.
  </figcaption>
</figure>
```

По сути, это картинка с подписью, может так и оформим?

2021-01-14 16:44 UTC, ezhkov commented on src/posts/css/doka/text-rendering.md
> +Ярким примером лигатур являются сочетания символов **fi**, **fl**, **at**. ![Пример лигатур](/assets/images/posts/text-rendering/ligatures.png)
Я только за. Все время забываю, что мы можем обычные теги использовать)

2021-01-14 20:48 UTC, pepelsbey approved these changes

2021-01-25 07:52 UTC, solarrust approved these changes

2021-01-25 07:52 UTC, merged