Правит подвал
Y-Doka/y-doka.site pull request #447
Opened 2021-01-11 07:34 UTC by furtivite

1. Добавляет верный инклюд в подвал страниц без асайда
2. Убирает размеры шрифта и строки, зашитые в подвале, теперь они будут управляться родительским элементом, в зависимости от того, где подвал расположен, и ничего не сломается
3. Меняет забытый класс 'mainpage__support' на 'footer__git' за пределами главной страницы, чтобы всё было по БЭМ
4. Переименовывает файл, потому что разница между двумя вариантами подвала только в наличии ссылки "О проекте"

2021-01-11 09:28 UTC, pepelsbey commented
Раз уж занялись футером, может сделать один шаблон и уже внутри проверять, выводить ли ссылку? А то как-то слишком много повторов.

2021-01-12 09:46 UTC, nlopin requested changes
Давай заодно в относительные единицы отрефакторим

2021-01-12 10:21 UTC, pepelsbey commented
@nlopin может быть лучше сфокусируем пулреквест на одной задаче? Учитывая, что по коду как попало (такие единицы, сякие), то мы здесь ничего принципиально не поменяем.

2021-01-12 12:22 UTC, pepelsbey approved these changes

2021-01-12 12:56 UTC, nlopin commented
> @nlopin может быть лучше сфокусируем пулреквест на одной задаче? Учитывая, что по коду как попало (такие единицы, сякие), то мы здесь ничего принципиально не поменяем.

Я большой сторонник правила бойскаутов (на Руси еще называют «божественное касание»): оставлять код после себя чище, чем он был. Если мы решили перейти на относительные единицы, то почему бы не сделать это в тех местах, которых мы касаемся прямо сейчас? Так мы сделаем последующий рефакторинг не таким большим и страшным.

Это правило имеет ограничение: не трогать код вне изменяемого набора файлов.

2021-01-12 13:08 UTC, pepelsbey commented
@nlopin, оставлять за собой чище — классно, но если ты приходишь в пулреквест, где поправили отступ, а там заодно сделали рефакторинг, то это напоминает историю с бананом, гориллой и всеми джунглями. Такое сложно ревьюить и пулреквесты зависают надолго, обрастают конфликтами.

2021-01-12 14:24 UTC, nlopin commented
Этот PR уже содержит 4 изменения. Я не понимаю, чем пятое изменение выбивается из этого ряда. Правим стили, связанные с футером, так давайте поправим полностью и забудем про них

2021-01-12 14:37 UTC, pepelsbey commented
Мой вопрос скорее о том, что относительные единицы измерения (ремы) — это система. Она подразумевает, что ты задаёшь на корневом элементе (html) значение и дальше используешь размеры относительно него. У нас стоит на html какое-то корневое значение, мы уже придумали, как его использовать? Просто написать всё в ремах в рамках этого пулреквеста — это не решить задачу, как по мне.

2021-01-12 14:39 UTC, pepelsbey commented
Если бы мы, скажем, договорились ставить кавычки в `url("…")`, то в рамках этого пулреквеста было бы нормально их добавить. Но тут задача больше и её кажется не начали решать, помимо обсуждения.

2021-01-12 21:43 UTC, nlopin approved these changes

2021-01-12 21:44 UTC, nlopin commented
Я возможно не понимаю, как работают с ремами, предлагаю отдельно это обсуждать. Разблокировал пул реквест

2021-01-13 10:05 UTC, merged