Добавляет статью про псевдокласс :required
Y-Doka/y-doka.site pull request #459
Opened 2021-01-20 13:29 UTC by ezhkov

Закрывает #111

2021-01-25 08:15 UTC, solarrust commented
Кратко, но понятно, только очень сухо =(
Давай добавим примеры. Например, что будет если указать этот псевдокласс для селектора, не относящегося к полям формы? Будет какой-то эффект?
Есть ли стандартный паттерн для выделения обязательных полей? Например, та же звёздочка. Можно её реализовать через селектор по псевоклассу?

2021-01-27 06:26 UTC, ezhkov commented
> Кратко, но понятно, только очень сухо =(
> Давай добавим примеры. Например, что будет если указать этот псевдокласс для селектора, не относящегося к полям формы? Будет какой-то эффект?
> Есть ли стандартный паттерн для выделения обязательных полей? Например, та же звёздочка. Можно её реализовать через селектор по псевоклассу?

Про паттерн написал, но звездочку через псевдокласс в нормальной верстке лучше не делать. Это та же проблема, что с псевдоклассами `:valid / :invalid`. Менять структуру формы в угоду отображения звездочки - не лучшая идея)

2021-01-27 09:01 UTC, solarrust commented
@pepelsbey твой выход =)

2021-01-27 10:17 UTC, pepelsbey requested changes

2021-01-27 10:17 UTC, pepelsbey commented on src/posts/css/doka/required.md
> +Поле ввода, обязательное для заполнения, будет иметь зеленую границу.
Надо быть внимательнее к «красным», «зелёным» и прочим объяснениям от цвета в примерах и демках. Например, режим высокой контрастности сделает такое выделение невидимым для пользователя, дальтоники тоже не увидят явной разницы (включая разработчиков). Я бы переделал демку, чтобы в ней появлялась обводка (outline), а не просто менялся цвет рамки.

2021-01-27 10:17 UTC, pepelsbey commented on src/posts/css/doka/required.md
> +    <input type="text" id="first_name" required />
Мы решили не закрывать одиночные теги в примерах, см. [tag-self-close: never](https://github.com/Y-Doka/y-doka.site/blob/master/.linthtmlrc.yaml#L14).

2021-01-27 15:50 UTC, ezhkov commented on src/posts/css/doka/required.md
> +Поле ввода, обязательное для заполнения, будет иметь зеленую границу.
outline в дополнение к бордеру?

2021-01-27 16:01 UTC, pepelsbey commented on src/posts/css/doka/required.md
> +Поле ввода, обязательное для заполнения, будет иметь зеленую границу.
Может лучше рамку оставить как есть и просто добавлять обводку? Чтобы она визуально появлялась, как событие, новый объект, который привлекает внимание.

2021-01-27 16:06 UTC, ezhkov commented on src/posts/css/doka/required.md
> +    <input type="text" id="first_name" required />
Слеши расставляет pre-commit хук ((

2021-01-28 17:26 UTC, pepelsbey approved these changes

2021-01-28 17:28 UTC, solarrust commented on src/posts/css/doka/required.md
> +HTML
```suggestion

```

2021-01-28 17:28 UTC, solarrust commented on src/posts/css/doka/required.md
> +CSS
```suggestion

```

2021-01-28 17:28 UTC, solarrust commented on src/posts/css/doka/required.md
> +Поле ввода, обязательное для заполнения, будет иметь синюю обводку.
```suggestion
Обязательное для заполнения поле ввода будет иметь синюю обводку.
```

2021-01-28 17:28 UTC, solarrust commented on src/posts/css/doka/required.md
> +Если нужно как-то выделить элементы форм, обязательные к заполнению, можно использовать в селекторе псевдокласс `:required`.
```suggestion
Если нужно как-то выделить обязательные для заполнения элементы форм можно использовать в селекторе псевдокласс `:required`.
```

2021-01-28 17:28 UTC, solarrust commented on src/posts/css/doka/required.md
> +💡 В реальных формах, как правило, поля, обязательные к заполнению, выделяют не так явно, как в примерах выше. Обычно после текстового описания обязательного поля ставят звёздочку. В примере ниже, кро
```suggestion
💡 Как правило, в реальных формах обязательные к заполнению поля выделяют не так явно, как в примерах выше. Обычно после текстового описания обязательного поля ставят звёздочку. В примере ниже, кроме того, показано, как можно стилизовать подсказку к полю.
```

2021-01-29 16:23 UTC, solarrust approved these changes

2021-01-29 16:23 UTC, merged