Design: добавляет демо в статьи CSS
Y-Doka/y-doka.site pull request #467
Opened 2021-01-27 14:27 UTC by skorobaeus

Закрывает #263 #262 #258 #256 #255 #253 #252 #251 #250 #249 #248 #245 #238 #237 #233 #230 #228

2021-01-27 15:43 UTC, pepelsbey commented on src/demos/list-style-type/index.njk
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
А нам точно нужно 128 КБ React + React DOM чтобы просто по таймеру и ховеру менять тип списка? Я конечно не программист, но кажется это пишется за 50 строк кода.

@nlopin что скажешь?

2021-01-27 15:45 UTC, pepelsbey commented on src/demos/list-style-type/index.njk
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
Тут ещё момент сложности: любому, кто захочет поправить CSS-демку нужно знать React, чтобы изменить HTML. Мне кажется мы зря задираем порог входа здесь.

2021-01-27 15:53 UTC, pepelsbey requested changes
Лучше записывать `::before` в современном синтаксисе псевдоэлементов, чтобы не путать их с псевдоклассами типа `:hover`.

2021-01-27 15:53 UTC, pepelsbey commented on src/demos/border-radius/counter.css
> +.text:before {
```suggestion
.text::before {
```

2021-01-27 15:53 UTC, pepelsbey commented on src/demos/list-style-type/empty-content.css
> +li:before {
```suggestion
li::before {
```

2021-01-27 15:53 UTC, pepelsbey commented on src/demos/quotes/index.css
> +span:before {
```suggestion
span::before {
```

2021-01-27 21:03 UTC, nlopin commented on src/demos/list-style-type/index.njk
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
Согласен. В этом случае реакт мне видится лишним. @skorobaeus попробуем сделать без него? 

Похоже получится немного нетривиально из-за жонглирования и таймаутом, и ховером. Напиши мне, если нужна помощь

2021-01-27 21:07 UTC, nlopin commented
Мне очень сложно внимательно просмотреть 121 файл за раз. @skorobaeus сможешь делать пул реквесты поменьше? Так мы и апрувить, и мержить будем быстрее. 

Предлагаю заводить по PR на демку, но можно и небольшими пачками 2-3 демо.

2021-01-28 09:01 UTC, skorobaeus commented on src/demos/list-style-type/index.njk
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
Это код @Realetive. Мне тоже кажется, что реакт здесь избыточен, но я не стала переписывать, т.к. у меня ещё полсотни статей под оформление в приоритете :) Могу заняться, но попозже.

2021-01-28 09:06 UTC, skorobaeus commented
> Мне очень сложно внимательно просмотреть 121 файл за раз. @skorobaeus сможешь делать пул реквесты поменьше? Так мы и апрувить, и мержить будем быстрее.
> 
> Предлагаю заводить по PR на демку, но можно и небольшими пачками 2-3 демо.

Хорошо, поняла :)

2021-01-28 10:32 UTC, nlopin commented on src/demos/list-style-type/index.njk
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
давай тогда вмержим и сделаем задачу на исправление?

2021-01-28 17:15 UTC, solarrust commented
1. Статья про `visibility`: добавить бы демку к коду в блоке "В работе".
2. Статья про `text-decoration`: в тексте есть фраза "Стиль линии можно указать отдельно при помощи свойства text-decoration-style. Пример". Слово "Пример" — ссылочка на кодпен. Давай вставим прямо в текст? Ниже аналогичная ситуация со следующим блоком кода.
3. Статья про `text-decoration`: пример в разделе "Подсказки", хорошо бы перенести стили и разметку из примера в текст.
4. Статья про `padding`: у примере есть фраза "Но начинали они всегда краёв" — пропущена "с".
5. Статья про `object-fit`: как на твой взгляд, может быть сделаем контейнер для картинок меньше, чтобы разница между значениями была очевиднее? Например, заквадратим его больше.
6. Статья `list-style-tyle`: под большим интерактивным примером есть строка "Примеры разных значений list-style-type". Хорошо бы её вынести над примером и сделать _заголовком_ / как-то внешне выделить.
7. Та же статья, раздел "Список без счётчика": давай проиллюстрируем блоки кода?
8. Та же статья: может в разделе "В работе" добавим скрин из FF? Напиши, если мимо и не тебе =)
9. Статья про `height`: давай в блоке "Пример" перенесём результат работы кода под сам этот код (первый пример).
10. Статья про `content`: обыграть бы как-то пример с выводом ссылки в печатный документ. 
11. Статья `box-shadow`: блок "В работе", там где клёвые множественные тени. В первом блоке кода давай сдвинем значение для свойства `box-shadow`. Почему-то потерялся отступ =)
12. ПРИЗНАНИЕ В ЛЮБВИ ЗА СКЕОМОРФНУЮ КНОПОЧКУ 😍
13. Статья про `border-radius`: в первом примере потерялась (не видна) внутренняя тень и лёгкое изменение цвета не оч вписывается в текст "интересную реакцию на нажатие".
14. Та же статья: может в блоке "В работе" сделаем что-то вроде пинчика уведомления на иконке? Хз как объяснить точнее 😅 Вот этот бесячий красный круглешок. Напиши, если не понятно — покидаю рефы.

Спасибо тебе за твою работу, ты очень сильно улучшаешь наши материальчики, переводя кривенькие намётки на примеры в красивые штуки в едином стиле! 

Присоединюсь к @nlopin что было бы удобнее смотреть PR'чики поменьше. И с пометочками работать будет проще.

2021-02-02 04:10 UTC, solarrust commented
@skorobaeus привет! Скажи, плиз, когда получиться пофиксить демки по комментам?

2021-02-02 07:25 UTC, skorobaeus commented
> @skorobaeus привет! Скажи, плиз, когда получиться пофиксить демки по комментам?

@solarrust Сейчас сижу занимаюсь, пару дней нужно, думаю

2021-02-04 15:26 UTC, skorobaeus commented
@solarrust Готово.

> ~~1. Статья про `visibility`: добавить бы демку к коду в блоке "В работе".~~

\+

> ~~2. Статья про `text-decoration`: в тексте есть фраза "Стиль линии можно указать отдельно при помощи свойства text-decoration-style. Пример". Слово "Пример" — ссылочка на кодпен. Давай вставим прямо в текст? Ниже аналогичная ситуация со следующим блоком кода.~~

Встроила демки. В текст разметку и стили добавлять пока не стала, т.к., мне кажется, статья из-за этого сильно растягивается, плюс в тексте есть расшифровка значений свойства, и ещё в самой демке фактически написан код. Олсо см. следующий пункт.

> ~~3. Статья про `text-decoration`: пример в разделе "Подсказки", хорошо бы перенести стили и разметку из примера в текст.~~

Перенесла стили полностью. Вроде бы, всё, что осталось непояснённым в предыдущих примерах, поясняется теперь в этом. 

> ~~4. Статья про `padding`: у примере есть фраза "Но начинали они всегда краёв" — пропущена "с".~~

\+

> ~~5. Статья про `object-fit`: как на твой взгляд, может быть сделаем контейнер для картинок меньше, чтобы разница между значениями была очевиднее? Например, заквадратим его больше.~~

Меня прямо мучает эта демка, в ней что-то неуловимо не так. Я позднее буду переделывать её и ещё несколько других такого же рода демок (где много вариантов) под единый стилёк, учту твой комментарий про пропорции. Спасибо.

> ~~6. Статья `list-style-tyle`: под большим интерактивным примером есть строка "Примеры разных значений list-style-type". Хорошо бы её вынести над примером и сделать _заголовком_ / как-то внешне выделить.~~

Перенесла, сделала заголовком h3.

> ~~7. Та же статья, раздел "Список без счётчика": давай проиллюстрируем блоки кода?~~

\+

> ~~8. Та же статья: может в разделе "В работе" добавим скрин из FF? Напиши, если мимо и не тебе =)~~

\+

> ~~9. Статья про `height`: давай в блоке "Пример" перенесём результат работы кода под сам этот код (первый пример).~~

\+

> ~~10. Статья про `content`: обыграть бы как-то пример с выводом ссылки в печатный документ.~~

Добавила скриншот.

> ~~11. Статья `box-shadow`: блок "В работе", там где клёвые множественные тени. В первом блоке кода давай сдвинем значение для свойства `box-shadow`. Почему-то потерялся отступ =)~~

\+

> ~~12. ПРИЗНАНИЕ В ЛЮБВИ ЗА СКЕОМОРФНУЮ КНОПОЧКУ 😍~~

<3

> ~~13. Статья про `border-radius`: в первом примере потерялась (не видна) внутренняя тень и лёгкое изменение цвета не оч вписывается в текст "интересную реакцию на нажатие".~~

Смена цвета это ховер. При нажатии кнопка утапливается — сейчас так модно хД — как раз за счёт внутренней тени. Поменяла формулировку и сделала эффект более выраженным: https://i.gyazo.com/9e4adac8f5031f171e6c5871718de86e.gif 

> ~~14. Та же статья: может в блоке "В работе" сделаем что-то вроде пинчика уведомления на иконке? Хз как объяснить точнее 😅 Вот этот бесячий красный круглешок. Напиши, если не понятно — покидаю рефы.~~

Поняла, сделала :)

2021-02-04 15:44 UTC, solarrust commented
Cтатья про content: картинка побилась =(

В остальном всё бомбически!

2021-02-04 16:25 UTC, solarrust approved these changes

2021-02-04 16:26 UTC, solarrust commented
Конфликт вылез, надо будет пофиксить.

2021-02-05 06:15 UTC, skorobaeus commented
> Конфликт вылез, надо будет пофиксить.

@solarrust Странный конфликт, я его не совсем понимаю. Это один файл, который нужно удалить. При мердже веток локально он благополучно удаляется. А отсюда без пуша в мастер я не могу конфликт разрешить, кажется (?)

2021-02-08 08:54 UTC, solarrust commented
@skorobaeus вмёржила мастер. Конфликт пропал. Проверь, что ничего не поломалось из твоих демок.
@pepelsbey пожалуйста, поревьюй.

2021-02-08 10:14 UTC, skorobaeus commented
> @skorobaeus вмёржила мастер. Конфликт пропал. Проверь, что ничего не поломалось из твоих демок.

@solarrust Всё в порядке 👀

2021-02-10 13:26 UTC, pepelsbey requested changes
Поправил то, что быстро правится. Задал вопросы и предложил там, где сомневался.

2021-02-10 13:26 UTC, pepelsbey commented on src/demos/text-decoration/basic.njk
> +</div>
Обёртка и класс не используются, дропаем?

```suggestion
<p class="none">Диакритические знаки — различные надстрочные, подстрочные, реже внутристрочные знаки, применяемые не как самостоятельные обозначения звуков, а для изменения или уточнения значения других знаков.</p>
<p class="underline">В типографике диакритические знаки это элементы письменности, модифицирующие начертание знаков и обычно набираемые отдельно.</p>
<p class="line-through">Диакритическими знаками не могут считаться части букв, если у них нет определённой функции: например, диакритическим знаком не является зачёркивание в А и Ѳ.</p>
<p class="overline">Черта сверху — типографический знак горизонтальной линии, нарисованной сразу над текстом. В математической нотации черта сверху долгое время используется для vinculum, объединения определённых символов. Также знак используется с римскими цифрами, показывая умножение цифры на тысячу.</p>
```

2021-02-10 13:26 UTC, pepelsbey commented on src/demos/text-decoration/color.njk
> +</div>
```suggestion
<p class="none">К диакритикам прибегают в случае, если букв алфавита не хватает для передачи звуков речи или же для смыслоразличения. Основной альтернативой диакритикам при звукоразличении служат сочетания двух (диграфы), трёх (триграфы) и более букв для обозначения одного звука.</p>
<p class="underline dotted blue">Дополнение подчеркивается пунктирной линией. Это второстепенный член предложения, который обозначает предмет и отвечает на вопросы косвенных падежей: кого? чего? кому? чему? кого? что? кем? чем? о ком? о чём?</p>
<p class="line-through double red">Эпанортозис (рус. поправление) — фигура речи: фигура, посредством которой какая-либо мысль сначала высказывается, а затем отменяется, для того чтобы высказать или эту же мысль точнее или полнее, или другую мысль.</p>
<p class="overline wavy green">В большинстве языков тильда сверху соответствует знаку, произошедшему из букв N и V, которые в средневековой скорописи часто писались над строкой (над предыдущей буквой) и в начертании выродились в волнистую линию.</p>
```

2021-02-10 13:26 UTC, pepelsbey commented on src/demos/text-decoration/style-color.njk
> +</div>
```suggestion
<p class="none">В греческой политонической орфографии тильда над гласной обозначает облечённое ударение  и является шрифтовым вариантом круглой шапочки над буквой. </p>
<p class="underline dotted blue">В графике польского рукописного шрифта строчная буква L с тильдой над ней используется вместо буквы Ł, означающей твёрдый звук [л], переходящий в неслоговое [у].</p>
<p class="line-through double red">В текстах на венгерском языке тильда может использоваться в качестве суррогатного заменителя двойного акута над буквами O и U, если тот недоступен по техническим ограничениям.</p>
<p class="overline wavy green">В языках C/C++, Java, Python, Verilog и др. тильда — одноместный префиксный оператор, означающий побитовое отрицание (в отличие от логического отрицания, обозначаемого восклицательным знаком).</p>
```

2021-02-10 13:26 UTC, pepelsbey commented on src/demos/text-decoration/style.njk
> +</div>
```suggestion
<p class="none">Тильда над буквой Ñ в испанском языке употребляется для обозначения мягкого звука, близкого к «нь».</p>
<p class="underline dotted">Õ — в эстонском языке обозначает неогубленный гласный заднего ряда средне-верхнего подъёма.</p>
<p class="line-through double">Ã и Õ — в португальском языке обозначают носовое произношение гласных.</p>
<p class="overline wavy">В некоторых системах фонетической транскрипции (в том числе в МФА) тильда над гласной вообще является показателем носового произношения.</p>
```

2021-02-10 13:26 UTC, pepelsbey commented on src/posts/css/doka/box-shadow.md
> +<div class="box circle"></div>
В демке нет стилей для `square`, дропнем класс или он описательный?

```suggestion
<div class="box"></div>
<div class="box circle"></div>
```

2021-02-10 13:26 UTC, pepelsbey commented on src/posts/css/doka/text-decoration.md
> +</div>
```suggestion
<p class="none">К диакритикам...</p>
<p class="underline">Дополнение подчеркивается...</p>
<p class="line-through">Эпанортозис...</p>
<p class="overline">В большинстве языков...</p>
```

2021-02-11 09:23 UTC, skorobaeus commented on src/demos/object-fit/every.css
> +
Остался артефакт от старой версии, удаляем, конечно

2021-02-11 09:26 UTC, skorobaeus commented on src/posts/css/doka/box-shadow.md
> +<div class="box circle"></div>
Задумывался как описательный :D

2021-02-11 09:30 UTC, skorobaeus commented
Предложения приняла 🙏

2021-02-15 13:34 UTC, pepelsbey approved these changes

2021-02-15 15:41 UTC, merged

2021-02-15 15:43 UTC, solarrust commented
![MHJl](https://user-images.githubusercontent.com/13676514/107967084-bd474a00-6fbd-11eb-9f4c-9c0d1fca5926.gif)