Добавляет статью про псевдокласс :empty
Y-Doka/y-doka.site pull request #468
Opened 2021-01-28 12:04 UTC by ezhkov

Закрывает #106

2021-01-29 10:29 UTC, pepelsbey requested changes

2021-01-29 10:29 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +Если результатов поиска нет, то блок с результатами отображаться не будет.
Непонятная структура: она отрендерится как параграф, наверное стоит и записать её так же. Ну или как список, если это он.

```suggestion
В примере выше результаты поиска будут вставлены в блок с классом `search-results`. Ему задан верхний отступ и рамка. Если результатов нет, то блок останется пустым и будет скрыт. Не будет ни рамки, ни отступа. Если результатов поиска нет, то блок с результатами отображаться не будет.
```

2021-01-29 10:29 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +Без использования псевдокласса `:empty` у нас на экране будет пустой элемент с верхним отступом и границей
```suggestion
Без использования псевдокласса `:empty` у нас на экране будет пустой элемент с верхним отступом и границей.
```

2021-01-29 10:29 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +будут являться потомками.
```suggestion
Потомками элемента могут являться как другие теги, так и текстовый контент, включая пробелы. А вот HTML-комментарии не будут являться потомками.
```

2021-01-29 10:29 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +только комментарий, который также не считается за потомка.
```suggestion
В первом случае внутри тега нет ничего, что могло бы считаться потомком. Во втором случае внутри тега присутствует только комментарий, который также не считается за потомка.
```

2021-01-29 10:29 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +могут присутствовать у пустого элемента.
Тут кажется то ли настройки редактора отбивать строки после лимита, то ли непонятно. Думаю, не стоит это переносить в текст, лучше оставлять в редакторе.

```suggestion
В реальных проектах этот селектор сильно помогает, когда нет возможности управлять элементом, но точно знаешь, что иногда он может быть пустым. Использование псевдокласса `:empty` позволяет убрать лишние отступы или границы, которые могут присутствовать у пустого элемента.
```

2021-01-29 16:16 UTC, solarrust approved these changes

2021-02-02 04:10 UTC, solarrust commented
@pepelsbey призываю!

2021-02-02 09:41 UTC, pepelsbey requested changes

2021-02-02 09:41 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +<div class="search-results"></div>
```suggestion
<form class="search-form" action="">
  ...
</form>
<div class="search-results"></div>
```
Кажется обёртка здесь лишняя и усложняет.

2021-02-02 09:41 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +Без использования псевдокласса `:empty` у нас на экране будет пустой элемент с верхним отступом и границей.
```suggestion
Без использования псевдокласса `:empty` у нас на экране будет пустой элемент с верхним отступом и рамкой.
```

2021-02-02 09:41 UTC, pepelsbey commented on src/posts/css/doka/empty.md
> +В реальных проектах этот селектор сильно помогает, когда нет возможности управлять элементом, но точно знаешь, что иногда он может быть пустым. Использование псевдокласса `:empty` позволяет убрать ли
```suggestion
В реальных проектах этот селектор сильно помогает, когда нет возможности управлять элементом, но точно знаешь, что иногда он может быть пустым. Использование псевдокласса `:empty` позволяет убрать лишние отступы или рамки, которые могут присутствовать у пустого элемента.
```

2021-02-02 20:15 UTC, pepelsbey approved these changes

2021-02-03 03:04 UTC, merged