добавляет статью про устаревшие теги
Y-Doka/y-doka.site pull request #472
Opened 2021-01-29 08:36 UTC by furtivite

2021-01-29 13:17 UTC, solarrust reviewed
@furtivite надо бы расставить ссылочки на статьи про теги, которые предлагаются в качестве альтернативы, если они есть.

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +Веб-технологии не стоят на месте, появляются новые теги и CSS-свойства. Но некоторые теги «устаревают» и их использование уже не является хорошей практикой, а есть и такие, которые уже не поддерживаю
```suggestion
По мере развития веб-технологий появляются новые теги и CSS-свойства. Но некоторые теги «устаревают» и их использование уже не является хорошей практикой. Есть и такие, которые уже не поддерживаются браузером или никогда не были частью спецификации W3C.
```

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +Для стилизации текста. Да, до полноценной поддержки браузерами стилизации текста с помощью CSS это был единственный способ изменить цвет, шрифт или размер. К сожалению, для вёрстки писем под клиенты,
```suggestion
До полноценной поддержки браузерами стилизации текста с помощью CSS это был единственный способ изменить цвет, шрифт или размер. К сожалению, для вёрстки писем под клиенты, не поддерживающие CSS, это остаётся единственной возможностью изменить внешний вид текста.
```

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +Хорошим тоном считается использование «склеивание» союзов и предлогов с последующим словом, единиц измерения.
```suggestion
Хорошим тоном считается использование «склеивания» союзов и предлогов с последующим словом, единиц измерения.
```

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +```
Можно добавить про Типограф, который помогает всё это не расставлять руками.

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +Для автоматического воспроизведения музыкального файла. В отличие от современного использования встраивания аудио-контента с помощью `<embed>` или `<audio>`, не отображает на странице кнопок управлен
```suggestion
Для автоматического воспроизведения музыкального файла. В отличие от современного использования встраивания аудио-контента с помощью `<embed>` или `<audio>`, не отображает на странице кнопок управления («стоп», «пауза», «громкость»). Такая «бесконтрольность» допускала злоупотребление этим эффектом. Поддержка тега была реализована только в Internet Explorer
```

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +```html
Надо отделить CSS от HTML

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +HTML
```suggestion

```

2021-01-29 13:17 UTC, solarrust commented on src/posts/html/long/deprecated-tags.md
> +CSS
```suggestion

```

2021-02-08 07:36 UTC, solarrust commented
@Realetive внеси последние правки, пожалуйста.

2021-02-08 19:09 UTC, solarrust approved these changes

2021-02-08 19:10 UTC, solarrust commented
@pepelsbey глянь, пожалуйста.

2021-02-09 16:40 UTC, solarrust commented
@furtivite у меня вот сомнения, нужно ли эту статью в раздел лонгридов класть 🤔

2021-02-18 06:57 UTC, furtivite commented on src/posts/html/long/deprecated-tags.md
> +Для больших объёмов текста проще воспользоваться программами-типографами, которые могут автоматически расставить символы неразрывного пробела, например «Типограф» [на сайте](https://www.artlebedev.ru
Очень много типографов, плюс разные кавычки, когда мы говорим о типографах — это странно.

```suggestion
Для больших объёмов текста проще воспользоваться программами-типографами, которые могут автоматически расставить символы неразрывного пробела, например «Типограф» [на сайте](https://www.artlebedev.ru/typograf/) Артемия Лебедева или „Типограф“ на [typograf.ru](https://www.typograf.ru).
```

2021-02-18 16:05 UTC, Realetive commented on src/posts/html/long/deprecated-tags.md
> +Для больших объёмов текста проще воспользоваться программами-типографами, которые могут автоматически расставить символы неразрывного пробела, например «Типограф» [на сайте](https://www.artlebedev.ru
Это их фирменное описание. Лебедевский — в «ёлочках», typograf.ru — в „лапках“. Это не ошибка или опечатка, это калька с оригинального написания.

2021-02-18 16:28 UTC, furtivite commented on src/posts/html/long/deprecated-tags.md
> +Для больших объёмов текста проще воспользоваться программами-типографами, которые могут автоматически расставить символы неразрывного пробела, например «Типограф» [на сайте](https://www.artlebedev.ru
> @furtivite у меня вот сомнения, нужно ли эту статью в раздел лонгридов класть 🤔

Я бы в доку это, не в лонгриды. КМК

2021-02-22 18:14 UTC, pepelsbey requested changes
Порезал кавычки, предложил варианты получше, поправил несколько ошибок.

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +Для «контролируемого» воспроизведения аудиофайлов —  `<embed>` или `<audio>`.
```suggestion
Для контролируемого воспроизведения аудиофайлов —  `<embed>` или `<audio>`.
```

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +Достаточно популярный тег даже в наши дни, например, при вёрстке писем — почтовые клиенты сильно консервативны и порой для них это единственный способ центрирования.
Развернул, что именно не так. И убрал «для них», а то как будто сами клиенты стилизуют.

```suggestion
Достаточно популярный тег даже в наши дни, например, при вёрстке писем — почтовые клиенты могут не поддерживать или просто вырезать стили и порой это единственный способ центрирования.
```

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +Для выравнивания содержимого по центру «родителя».
```suggestion
Для выравнивания содержимого по центру родительского блока.
```

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +    Этот вложенный блок отцентрирован по вертикали.
```suggestion
    Этот вложенный блок отцентрирован по горизонтали.
```

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +Современных аналогов нет, можно сымитировать анимацию с помощью JavaScript и/или CSS.
Это не программирование (меньше или равно), можно проще — и читается проще :)

```suggestion
Современных аналогов нет, можно сымитировать анимацию с помощью JavaScript или CSS.
```

2021-02-22 18:14 UTC, pepelsbey commented on src/posts/html/long/deprecated-tags.md
> +Авторы спецификаций постоянно ведут работу над улучшением «пользовательского» и «разработческого опыта» (UX и DX), потенциально «вредные» теги (`<blink>`, `<marquee>`, `<bgsound>`) удаляются из специ
```suggestion
Авторы спецификаций постоянно ведут работу над улучшением пользовательского и разработческого опыта (UX и DX), потенциально вредные теги (`<blink>`, `<marquee>`, `<bgsound>`) удаляются из спецификации, заменяются на более семантичные (`<del>` вместо `<strike>`) или переносят управление на уровень CSS (`<nobr>`, `<center>`). Некоторые из таких тегов можно встретить в коде и сейчас, но разработчики браузеров не гарантируют, что в скором времени сохранится их поддержка — их лучше заменить на современный аналог или пересмотреть, на сколько целесообразно его использование в принципе.
```

2021-02-22 18:28 UTC, Realetive commented on src/posts/html/long/deprecated-tags.md
> +```
Видимо, да. Спасибо.

2021-02-22 23:57 UTC, pepelsbey approved these changes

2021-02-23 07:47 UTC, merged