Добавляет статью про теги для списка определений <dl>, <dt> и <dd>
Y-Doka/y-doka.site pull request #473
Opened 2021-01-29 09:04 UTC by furtivite

2021-01-29 13:01 UTC, solarrust commented on src/posts/html/doka/dl-dd-dt.md
> +💡 При верстке перечня метаданных (пар «ключ-значение») удобно разделитель вносить в псевдоэлемент, а не писать текстом рядом с каждым ключом:
```suggestion
💡 При вёрстке перечня метаданных (пар «ключ-значение») удобно разделитель вносить в псевдоэлемент, а не писать текстом рядом с каждым ключом:
```

2021-01-29 13:01 UTC, solarrust commented on src/posts/html/doka/dl-dd-dt.md
> +💡 В отличие от списков [`<ul>`](/html/doka/ul/) и [`<ol>`]() группы терминов и определений можно оборачивать в `<div>`
Пустая ссылка на ol и нет ссылки на div.

2021-01-29 13:06 UTC, furtivite commented on src/posts/html/doka/dl-dd-dt.md
> +Элемент `<dl>` аналогично элементам [<ul>](https://www.notion.so/ul-9efeb21db79a4ea6b7128533e7879f55) и [<ol>](https://www.notion.so/ol-0e106adf027e4aaf9c964027618f29f1) является внешней оберткой для
Поправил

2021-01-29 13:06 UTC, furtivite commented on src/posts/html/doka/dl-dd-dt.md
> +💡 В отличие от списков [`<ul>`](/html/doka/ul/) и [`<ol>`]() группы терминов и определений можно оборачивать в `<div>`
Поправил

2021-01-29 13:09 UTC, furtivite commented on src/posts/html/doka/dl-dd-dt.md
> +
Вроде сделано

2021-01-29 15:49 UTC, solarrust approved these changes

2021-01-29 17:19 UTC, pepelsbey requested changes

2021-01-29 17:19 UTC, pepelsbey commented on src/posts/html/doka/dl-dd-dt.md
> +Тегом `<dd>` верстается определение термина, либо значение в паре «ключ-значение». Следом за этим тегом может идти как ещё один тег `<dd>`(если у термина несколько определений), так и тег `<dt>`(след
```suggestion
Тегом `<dd>` верстается определение термина, либо значение в паре «ключ-значение». Следом за этим тегом может идти как ещё один тег `<dd>` (если у термина несколько определений), так и тег `<dt>` (следующий термин).
```

2021-01-29 17:19 UTC, pepelsbey commented on src/posts/html/doka/dl-dd-dt.md
> +Элемент `<dl>` аналогично элементам [<ul>](/html/doka/ul/) и [<ol>](/html/doka/ol/) является внешней оберткой для элементов списка.
```suggestion
Элемент `<dl>` аналогично элементам [`<ul>`](/html/doka/ul/) и [`<ol>`](/html/doka/ol/) является внешней оберткой для элементов списка.
```

2021-01-29 17:19 UTC, pepelsbey commented on src/posts/html/doka/dl-dd-dt.md
> +Элемент `<dt>` используется для вёрстки термина либо ключа в паре «ключ-значение». Как правило, следом за ним идёт либо ещё один тег `<dt>`(если есть необходимость сверстать несколько терминов с одни
```suggestion
Элемент `<dt>` используется для вёрстки термина либо ключа в паре «ключ-значение». Как правило, следом за ним идёт либо ещё один тег `<dt>` (если есть необходимость сверстать несколько терминов с одним определением), либо тег `<dd>`.
```

2021-01-29 17:19 UTC, pepelsbey commented on src/posts/html/doka/dl-dd-dt.md
> +💡 В отличие от списков [`<ul>`](/html/doka/ul/) и [`<ol>`](/html/doka/ol/) группы терминов и определений можно оборачивать в [`<div>`](/html/doka/div/)
```suggestion
💡 В отличие от списков [`<ul>`](/html/doka/ul/) и [`<ol>`](/html/doka/ol/) группы терминов и определений, с недавних пор и по просьбе разработчиков, можно оборачивать в [`<div>`](/html/doka/div/).
```
Подчёркивает, что это не всего было так и кто на это повлиял.

2021-01-29 17:19 UTC, pepelsbey commented on src/posts/html/doka/dl-dd-dt.md
> +    занимается Mozilla Corporation
```suggestion
    свободный браузер на движке Gecko,
    разработкой и распространением которого
    занимается Mozilla Corporation
```
Чтобы был шанс прочитать текст на мобилке, например

2021-02-01 09:44 UTC, pepelsbey approved these changes

2021-02-01 09:44 UTC, merged