Добавляет статью про aside
Y-Doka/y-doka.site pull request #474
Opened 2021-01-29 09:19 UTC by furtivite

2021-01-29 12:33 UTC, pepelsbey requested changes

2021-01-29 12:33 UTC, pepelsbey commented on src/posts/html/doka/aside.md
> +```
Сомнительный пример, это больше похоже на тизер статьи и `<article>`. Я бы лучше дал пример с `<main>` и `<aside>`, о котором говорится в интро. Когда в главном — целевой контент страницы, а в побочном — релеватные новости, соцсети, реклама.

2021-01-29 12:33 UTC, pepelsbey commented on src/posts/html/doka/aside.md
> +
```suggestion
```

Если нет атрибутов, то лучше не перечислять все глобальные. Уже начали убирать подобное из других статей.

2021-01-29 12:33 UTC, pepelsbey commented on src/posts/html/doka/aside.md
> +💡 Нет никаких ограничений на положение в контексте тега `<aside>`, но «самое место» ему на одном *визуальном уровне* с `<main>` и `<article>`.
```suggestion
💡 Нет никаких ограничений на положение в контексте тега `<aside>`, но самое место ему на одном _структурном уровне_ с `<main>` и `<article>`.
```
Не стоит стесняться, Дока — самое место смелых фраз :)
Также «структурный» здесь подходит лучше, визуально, после стилей, может быть что угодно.

2021-01-29 12:33 UTC, pepelsbey commented on src/posts/html/doka/aside.md
> +![Grid-сетка для Angular](/assets/images/posts/aside/aside.jpg)
Смущает JPEG для картинки с 16 цветами от силы

2021-01-29 12:33 UTC, pepelsbey commented on src/posts/html/doka/aside.md
> +Самый простой вариант — наш сайт, имеющий две колонки (на десктопных и планшетных экранах): правую — с основным контентом, и «боковую» левую — с навигацией. Вот как раз эта область не имеет прямого о
```suggestion
Самый простой вариант — наш сайт, имеющий две колонки (на десктопных и планшетных экранах): правую — с основным контентом, и боковую левую — с навигацией. Вот как раз эта область не имеет прямого отношения к самому содержимому статьи, но отлично дополняет пользовательский опыт: если вам нужно будет выбрать новый документ или что-то найти (т. к. в ней располагается навигация и поиск).
```
Убирает кавычки, всё в прямом смысле и на самом деле.

2021-01-29 12:36 UTC, furtivite commented on src/posts/html/doka/aside.md
> +```
@Realetive, @solarrust, думаю, что к вам.

2021-01-29 12:38 UTC, furtivite commented on src/posts/html/doka/aside.md
> +
@pepelsbey, мы совсем убираем или можно оставить как

```markdown
## Атрибуты
У `<aside>` нет никаких специфических атрибутов, он поддерживает все глобальные атрибуты
```

2021-01-29 12:41 UTC, Realetive commented on src/posts/html/doka/aside.md
> +```
Ту тогда лучше вообще не кодом, а картинкой.

2021-01-29 12:43 UTC, Realetive commented on src/posts/html/doka/aside.md
> +
Когда писалась эта статья, отдельной страницы с глобальными не было. Я бы заменил на «У `<aside>` нет никаких специфических атрибутов, он поддерживает все [глобальные атрибуты](#)»

2021-01-29 12:52 UTC, Realetive commented on src/posts/html/doka/aside.md
> +```
<img width="1346" alt="emc_img_screenshot_main" src="https://user-images.githubusercontent.com/2073959/106277343-f8215200-6249-11eb-9287-daf64c26a641.png">

2021-01-29 12:53 UTC, solarrust commented on src/posts/html/doka/aside.md
> +![Grid-сетка для Angular](/assets/images/posts/aside/aside.jpg)
Надо поставить задачку дизайнерам на перерисовку.

2021-01-29 15:42 UTC, solarrust commented on src/posts/html/doka/aside.md
> +![Grid-сетка для Angular](/assets/images/posts/aside/aside.jpg)
Заказала 💫

2021-02-08 07:39 UTC, solarrust commented on src/posts/html/doka/aside.md
> +```
В блоке с примером по сложившейся традиции мы даём кусок кода, который можно использовать. Его можно дополнить картинкой, но сам код тоже нужен.

2021-02-08 08:35 UTC, solarrust commented
@pepelsbey @Realetive @furtivite чекните, внесла правки в статью.

2021-02-08 09:36 UTC, solarrust commented on src/posts/html/doka/aside.md
> +Блок с дополнительным содержимым. Необязательно имеет отношение к главному ([`<main>`](/html/doka/main/)) контенту сайта. Часто используется для боковой колонки на сайте.
```suggestion
Блок с дополнительным содержимым. Он может не иметь отношения к главному ([`<main>`](/html/doka/main/)) контенту сайта. Часто используется для боковой колонки на сайте.
```

2021-02-09 11:49 UTC, pepelsbey approved these changes

2021-02-09 16:33 UTC, solarrust approved these changes

2021-02-09 16:33 UTC, merged