Добавляет статью про <address>
Y-Doka/y-doka.site pull request #475
Opened 2021-01-29 10:48 UTC by furtivite

- Там уже проставлена ссылка на `<aside>` из #474

2021-01-29 12:18 UTC, pepelsbey requested changes

2021-01-29 12:18 UTC, pepelsbey commented on src/posts/html/doka/address.md
> +На странице может присутствовать контактная информация разного рода: почтовые адреса, адреса электронной почты, номера телефона, ссылки на соцсети, географические координаты, адреса URL и так далее.
```suggestion
На странице может присутствовать контактная информация разного рода: почтовые адреса, адреса электронной почты, номера телефона, ссылки на соцсети, географические координаты, адреса URL и так далее. Такую информацию мы размечаем тегом `<address>`. Желательно также, чтобы помимо этой информации присутствовало также имя человека, или имена людей, либо название организации. В общем, этот тег может использоваться в совершенно разных видах: от представления контактной информации о компании в шапке сайта до прямого указания на автора статьи внутри тега [`<article>`](/html/doka/article/)
```
Чуть упрощает стиль :)

2021-01-29 12:18 UTC, pepelsbey commented on src/posts/html/doka/address.md
> +- Нельзя вкладывать теги `<address>` друг в друга
```suggestion
- Нельзя вкладывать теги `<address>` друг в друга
- Нельзя вкладывать в параграф с текстом, это не фразовый элемент
```

2021-01-29 12:23 UTC, pepelsbey commented
Я бы ещё упомянул, что `<address>` имеет стили по умолчанию — курсив.

2021-01-29 12:33 UTC, furtivite commented
> Я бы ещё упомянул, что `<address>` имеет стили по умолчанию — курсив.

Тоже добавил

2021-01-29 15:32 UTC, solarrust approved these changes

2021-02-01 09:43 UTC, pepelsbey approved these changes

2021-02-01 09:45 UTC, merged