Добавляет статью про свойство appearance
Y-Doka/y-doka.site pull request #483
Opened 2021-02-01 17:32 UTC by ezhkov

Закрывает #97

2021-02-01 17:33 UTC, ezhkov commented
Не стал перечислять в статье прям все значения. Их там штук 50, не уверен, что нужно

2021-02-01 21:15 UTC, pepelsbey commented
FYI: [Unprefixing appearance to ship web-compatible styling of form elements](https://bocoup.com/work/unprefixing-appearance-to-ship-web-compatible-styling-of-form-elements), может пригодится.

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +2. Чтобы применить специфичные для платформы стили к элементам, у которых этих стилей нет. В этом случае, если нам нужно, чтобы поле ввода выглядело как поле поиска, мы можем задать `appearance: sear
```suggestion
2. Чтобы применить специфичные для платформы стили к элементам без этих стилей. Из простого поля поиска можно сделать поле поиска при помощи `appearance: searchfield`. Но сходство будет только внешним:
```

Как тебе такой вариант?

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +```css
Давай разобъём на несколько блоков кода, а то, что сейчас в комментариях, сделаем текстом перед этими блоками кода.

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +```
Стоит упомянуть, что это далеко не все значения, а самые используемые (?). И дать ссылку на полный список значений. Или скрыть его в тогл

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +💡 Свойства `-webkit-appearance` и `-moz-appearance` — это нестандартные свойства, доступные только в браузерах на определённых движках. Свойство `-webkit-appearance` работает в браузерах на движках W
Вот эта подсказка — копия с сайта https://xsltdev.ru/css/appearance/
Давай вместо неё напишем блок кода для всех браузеров и поясним, зачем так много. Заодно дадим отсылку к вендорным префиксам. Когда-нибудь и про них напишем =)

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="html,result" data-user="ezhkov" data-slug-hash="eYBmqWm" style="height: 265px; box-sizing: border-box; display: flex; alig
В примере есть свойство с префиксом `-ms-appearance`, а в статье про него ничего нет.

2021-02-02 04:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +
Тут можно буквально 1-2 предложения про разницу стандартных стилей на разных ОС / в разных браузерах.

2021-02-02 05:09 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +Если пример открыть НЕ в мобильном браузере, то разница не заметна.
Сорри, пропустила картинку. Исходное замечание не актуально. Только уж очень маленькие скрины =) 
https://cln.sh/b9MD0I

2021-02-03 15:43 UTC, ezhkov commented on src/posts/css/doka/appearance.md
> +Свойство `appearance` задаёт внешний вид элемента формы в зависимости от платформы и темы операционной системы пользователя.
Изменил формулировку

2021-02-03 19:09 UTC, ezhkov commented
Внёс правки с учётом обсуждения в чате

2021-02-03 19:20 UTC, solarrust reviewed
Сущая мелочь 🙌

2021-02-03 19:20 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +Если задать `appearance: none`, то происходит "сброс" внешнего вида элемента. Приведение его к общему знаменателю во всех браузерах и всех операционных системах.
```suggestion
Если задать `appearance: none`, то происходит «сброс» внешнего вида элемента. Приведение его к общему знаменателю во всех браузерах и всех операционных системах.
```

2021-02-03 19:20 UTC, solarrust commented on src/posts/css/doka/appearance.md
> +Если пример открыть НЕ в мобильном браузере, то разница не заметна, так как в десктопных браузерах внешний вид полей ввода довольно унифицирован.
```suggestion
Если пример открыть НЕ в мобильном браузере, то разница не заметна, так как в десктопных браузерах внешний вид полей ввода более или менее унифицирован.
```

2021-02-05 18:15 UTC, solarrust commented
@pepelsbey глянешь?

2021-02-23 19:58 UTC, solarrust commented
@pepelsbey пинг

2021-02-24 21:02 UTC, pepelsbey requested changes
У меня к этой статье только один главный вопрос: пишем про значения, про принцип работы, а потом раз!

> В настоящее время используется в основном `appearance: none` для сброса системных стилей, остальные значения не работают практически ни в одном браузере.

Нужно только `appearance: none`. Я бы об этом прямо в интро сказал, там где «Кратко». Это слишком важная информация, чтобы её прятать.

2021-03-04 19:38 UTC, pepelsbey approved these changes
Чуть подправил формат вставки картинок и написал полезные альты.

2021-03-04 19:59 UTC, solarrust approved these changes

2021-03-04 19:59 UTC, merged