Добавляет пост о стиле кода
Y-Doka/y-doka.site pull request #493
Opened 2021-02-02 15:12 UTC by bespoyasov

Закрывает https://github.com/Y-Doka/y-doka.site/issues/489.

2021-02-02 15:13 UTC, bespoyasov commented
Добавил черновик поста. Что добавить?

2021-02-02 20:33 UTC, pepelsbey requested changes

2021-02-02 20:33 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +// рассматривается, как конец строки.
Мы в вёрстке стараемся выносить текст из примеров кода, его сложнее читать:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/105274/106657716-6bf68e00-65ad-11eb-94c6-9907abb93750.png">

2021-02-02 20:33 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +  <img src="/assets/images/posts/js/code-style/bad-script.jpg"/>
```suggestion
  <img src="/assets/images/posts/js/code-style/bad-script.jpg" width="2039" height="1222" alt="Пример плохого почерка">
```
К слову о стиле кода :) Мы договорились не писать закрывающие слэши, а также картинкам важно задавать атрибуты с размерами и альт с описанием. Мы, вероятно, автоматизируем расстановку размеров и добавим стили, которые адекватно вписывают картинки, но пока вот так. Размеры, кроме прочего, нужны для лучшего перфоманса страниц.

2021-02-02 20:33 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +</figure>
Странно, что где-то код дан картинками, а где-то текстом. Может быть будем избегать картинок с текстом?

2021-02-02 20:33 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +</figure>
Опять же, можно поставить задачу: нужны примеры кода, чтобы можно было сравнить. Можем сделать на табах такое. Но это не повод делать картинки с кодом.

2021-02-02 21:28 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +</figure>
Код набран картинками там, где я не могу использовать "неправильное" по мнению Prettier форматирование. 

Он автоматически заменяет весь код на "правильный". По той же причине я не могу показать изменение кода в табах. 

Нам либо надо запретить Prettier лезть в маркдаун-файлы, либо придумать что-то ещё.

2021-02-02 21:34 UTC, bespoyasov commented
Всё остальное завтра обработаю 🙂

2021-02-02 21:36 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +</figure>
Я бы отменил Prettier для маркдаунов, он иногда чрезмерно «умный».

2021-02-02 22:26 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +</figure>
Вот меня тоже за плохие доктайпы Prettier наказал, сделав их хорошими — @nlopin отменил Prettier для `{html,css}/*md`, но кажется нам нужно в игнор `*.md`. Кажется писать документацию без плохих примеров нельзя. А расставлять кругом игноры для Prettier почему-то не хочется.

2021-02-02 23:51 UTC, nlopin requested changes
Классная получилась структура.

Обратил внимание, что мы не даем ссылки на примеры стилей. Давай сошлемся на несколько основных? 

Разнообразные:
* https://airbnb.io/javascript/
* https://github.com/rwaldron/idiomatic.js
* https://google.github.io/styleguide/jsguide.html

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Единый стиль написания кода избавляет команду от лишней работы и позволяет сосредоточиться на задачах более высокого уровня. Если единого стиля нет, то работа над теми же задачами начинает занимать в
меня смущает фраза «более высокого уровня». Я понимаю ее, но не уверен, что она понятна начинающим. Более высокого уровня, чем что?

Мне кажется в этом контексте будет норм сказать «сосредоточиться на задаче». Что думаешь?

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Единый стиль написания кода избавляет команду от лишней работы и позволяет сосредоточиться на задачах более высокого уровня. Если единого стиля нет, то работа над теми же задачами начинает занимать в
Добавим еще, что на английском это назвается codestyle?

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Кроме таких задач мы сталкиваемся и с более низкоуровневыми проблемами: как назвать функцию или переменную, куда положить файл, как разбить модуль на несколько, табы или пробелы в конце концов :–)
```suggestion
Кроме таких задач мы сталкиваемся и с низкоуровневыми проблемами: как назвать функцию или переменную, куда положить файл, как разбить модуль на несколько, табы или пробелы в конце концов :–)
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Стиль кода — это набор правил, принятых в проекте, которые определяют, как именно писать код. Они могут включать прямые рекомендации, примеры кода, ссылки на лучшие практики, «рецепты», что делать в
```suggestion
Стиль кода — это набор правил, как писать код в проекте. Они могут включать прямые рекомендации, примеры кода, ссылки на лучшие практики, «рецепты», что делать в спорных ситуациях.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Единый стиль кода помогает избавиться от низкоуровневых проблем, оставляя больше ресурсов на решение проблем высокого уровня. Часть задач мы можем даже автоматизировать, что тоже облегчает работу. Ра
```suggestion
Единый стиль кода помогает избавиться от низкоуровневых проблем, оставляя больше ресурсов на решение проблем высокого уровня. Стиль можно применять автоматически, что тоже облегчает работу. Рассмотрим основные плюсы единого стиля.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +</figure>
*ушел убирать prettier*

@bespoyasov добавляй текстом

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +// рассматривается, как конец строки.
добавил эту договоренность в рекомендации (#496)

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Без единого стиля кода высок риск начать обсуждать на ревью, ставить ли точку с запятой и использовать ли пробелы вместо табов. Это не несёт полезной нагрузки, но отнимает силы и время участников, из
Это ключевой момент, он как-то скомкано получился. Давай уберем слова связанные с вероятностью «высок риск», «может не выявить». 

На моем опыте эта вероятность близится к 100% , если нет автопроверок. Человек приходит ревьюить, набрасывает несколько замечаний по стилю и уходил довольным

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Такое ревью начинает казаться участникам бессмысленным, перестаёт казаться приоритетной задачей, что ещё сильнее может замедлить процесс — не все люди готовы заниматься чем-то, что кажется им бесполе
```suggestion
Участники перестанут видеть смысл в таком ревью, оно перестанет быть приоритетной задачей. Это ещё сильнее замедлит процесс, так как не все люди готовы заниматься чем-то, что кажется им бесполезным. Подобные ревью могут накалить отношения между участниками и привести к конфликту.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Такое ревью начинает казаться участникам бессмысленным, перестаёт казаться приоритетной задачей, что ещё сильнее может замедлить процесс — не все люди готовы заниматься чем-то, что кажется им бесполе
Можно еще какое-нибудь сравнение придумать. Мне в голову приходит бабка, которая всегда чем-нибудь недовольна 😂

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Когда код написан одинаково во всём проекте, нам проще переключаться между модулями, файлами, целыми сервисами и частями проекта. Чем проще нам работать с разными частями, тем проще и быстрее мы може
```suggestion
Когда код написан одинаково во всём проекте, нам проще переключаться между модулями, файлами, целыми сервисами и частями проекта. Чем проще работать с разными частями, тем проще и быстрее мы можем работать с проектом в целом.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Если код, который мы пишем «не лично наш», у нас меньше причин его «защищать» на ревью. Это уменьшает вероятность конфликтов и упрощает поиск ошибок. Мы всё ещё можем отстаивать свои решения, но мы ч
```suggestion
Если код, который мы пишем «не лично наш», у нас меньше причин его «защищать» на ревью. Это уменьшает вероятность конфликтов и упрощает поиск ошибок. Мы всё ещё можем отстаивать свои решения, но мы чувствуем меньше трения, если надо их поменять.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +В обезличенном коде, как правило, меньше сложных и заумных конструкций. Такой код проще читать начинающим разработчикам, что уменьшает бас-фактор (bus-factor), а это делает проект более живучим.
может автобусный фактор? Вики говорит про [Фактор автобуса](https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BA%D1%82%D0%BE%D1%80_%D0%B0%D0%B2%D1%82%D0%BE%D0%B1%D1%83%D1%81%D0%B0)

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Правила оформления кода упрощают его чтение, но это не особо поможет, если за выполнением правил надо следить вручную. Чтобы не отвлекаться на проверку стиля кода, сообщество придумало инструменты, к
```suggestion
Правила оформления кода упрощают чтение, но это не поможет, если за выполнением правил нужно следить вручную. Чтобы не отвлекаться на проверку стиля кода, сообщество придумало инструменты, которые автоматизируют такие проверки.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +</figure>
Давай напишем пока текстом до и после кастомной версткой?

(отключаю prettier)

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +### Линтеры
Надо сослаться на статью [«Статический анализ»](https://y-doka.site/js/tools/static-analysis/)

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Форматтеры по сути следят за синтаксисом (точки с запятой, кавычки, табы). Для более высокоуровневых правил есть линтеры.
```suggestion
Форматтеры следят за синтаксисом (точки с запятой, кавычки, табы). Для более высокоуровневых правил есть линтеры или статические анализаторы кода.
```

2021-02-02 23:51 UTC, nlopin commented on src/posts/js/long/code-style.md
> +## Недостатки единого стиля кода
для меня главная боль — сначала все должны договориться о стиле

2021-02-02 23:53 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Одни из самых популярных среди JS-разработчиков — это [EditorConfig](https://editorconfig.org) и [Prettier](https://prettier.io). Второй можно даже [попробовать онлайн](https://prettier.io/playground
на примере доки выяснили, что EditorConfig не умеет автоформатировать, только ругаться.

Из форматтеров можно упомянуть https://standardjs.com/ как альтернативу prettier

2021-02-03 08:34 UTC, nlopin commented
@bespoyasov вмержи себе мастер, отключил prettier для статей (#500)

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +// рассматривается, как конец строки.
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +  <img src="/assets/images/posts/js/code-style/bad-script.jpg"/>
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +</figure>
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +</figure>
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Единый стиль написания кода избавляет команду от лишней работы и позволяет сосредоточиться на задачах более высокого уровня. Если единого стиля нет, то работа над теми же задачами начинает занимать в
✅✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Кроме таких задач мы сталкиваемся и с более низкоуровневыми проблемами: как назвать функцию или переменную, куда положить файл, как разбить модуль на несколько, табы или пробелы в конце концов :–)
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Стиль кода — это набор правил, принятых в проекте, которые определяют, как именно писать код. Они могут включать прямые рекомендации, примеры кода, ссылки на лучшие практики, «рецепты», что делать в
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Единый стиль кода помогает избавиться от низкоуровневых проблем, оставляя больше ресурсов на решение проблем высокого уровня. Часть задач мы можем даже автоматизировать, что тоже облегчает работу. Ра
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Без единого стиля кода высок риск начать обсуждать на ревью, ставить ли точку с запятой и использовать ли пробелы вместо табов. Это не несёт полезной нагрузки, но отнимает силы и время участников, из
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Такое ревью начинает казаться участникам бессмысленным, перестаёт казаться приоритетной задачей, что ещё сильнее может замедлить процесс — не все люди готовы заниматься чем-то, что кажется им бесполе
Я полностью переписал абзац.

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Когда код написан одинаково во всём проекте, нам проще переключаться между модулями, файлами, целыми сервисами и частями проекта. Чем проще нам работать с разными частями, тем проще и быстрее мы може
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Если код, который мы пишем «не лично наш», у нас меньше причин его «защищать» на ревью. Это уменьшает вероятность конфликтов и упрощает поиск ошибок. Мы всё ещё можем отстаивать свои решения, но мы ч
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +В обезличенном коде, как правило, меньше сложных и заумных конструкций. Такой код проще читать начинающим разработчикам, что уменьшает бас-фактор (bus-factor), а это делает проект более живучим.
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Правила оформления кода упрощают его чтение, но это не особо поможет, если за выполнением правил надо следить вручную. Чтобы не отвлекаться на проверку стиля кода, сообщество придумало инструменты, к
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +### Линтеры
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Форматтеры по сути следят за синтаксисом (точки с запятой, кавычки, табы). Для более высокоуровневых правил есть линтеры.
✅

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +## Недостатки единого стиля кода
А, ну да.

2021-02-03 09:25 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Одни из самых популярных среди JS-разработчиков — это [EditorConfig](https://editorconfig.org) и [Prettier](https://prettier.io). Второй можно даже [попробовать онлайн](https://prettier.io/playground
✅

2021-02-03 10:28 UTC, nlopin requested changes

2021-02-03 10:28 UTC, nlopin commented on src/posts/js/long/code-style.md
> +console.log(2)
такой код в prettier склеится в одну строку (смотрел в плейграунде), как в твоем примере выше

Давай поставим точку с запятой в этой строке `console.log(2);`

2021-02-03 10:28 UTC, nlopin commented on src/posts/js/long/code-style.md
> +console.log(2)
```suggestion
console.log(2);
```

2021-02-03 10:28 UTC, nlopin commented on src/posts/js/long/code-style.md
> +[1, 2].map(num => num * 2);
В последних версиях преттиера код станет таким (смотрел в плейграунде):

```suggestion
console.log(2);
[1, 2].map((num) => num * 2);
```

2021-02-03 10:28 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Автоматические форматтеры [снимают с разработчиков головную боль форматирования кода](/js/tools/static-analysis/):
Промазал со ссылкой, в этой статье говорится только про линтеры

2021-02-03 10:28 UTC, nlopin commented on src/posts/js/long/code-style.md
> +Договариваться о стиле коде — это спорить о вкусах. Не всегда можно привести объективные аргументы в пользу любимого стиля. Точка с запятой влияет на интерпретацию, а вот табы или пробелы — нет. В лю
```suggestion
Договариваться о стиле кода — это спорить о вкусах. Не всегда можно привести объективные аргументы в пользу любимого стиля. Точка с запятой влияет на интерпретацию, а вот табы или пробелы — нет. В любом случае, лучше один раз договориться на старте проекта, чем потом каждый раз спорить в комментариях к ревью.
```

2021-02-03 10:53 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +console.log(2)
Я переписал эту часть полностью.

2021-02-03 10:54 UTC, bespoyasov commented on src/posts/js/long/code-style.md
> +Автоматические форматтеры [снимают с разработчиков головную боль форматирования кода](/js/tools/static-analysis/):
Уже поправил.

2021-02-03 21:31 UTC, nlopin commented on src/posts/js/long/code-style.md
> +console.log(2)[1, 2].map(num => num * 2);
У меня вот так форматирует

```suggestion
console.log(2)[(1, 2)].map((num) => num * 2);
```

![image](https://user-images.githubusercontent.com/1469636/106811861-3914ce80-666f-11eb-8ff7-a8fd76b92d5b.png)

2021-02-04 21:18 UTC, nlopin approved these changes

2021-02-15 16:41 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +```
Разворачивает блок кода с комментариями в текст:

````suggestion
Однако, точка с запятой — это не только дело вкуса. Отсутствие `;` в некоторых местах может сильно изменить поведение кода. К примеру, у нас есть вот такой вызов функции и какая-то работа с массивом сразу после:

```js
console.log(2)
[1, 2].map(num => num * 2)
```

Из-за отсутствия `;` на 1-й строке этот код на самом деле становится таким:

```js
console.log(2)[1, 2].map(num => num * 2)
```

Что приводит к ошибке:

```
Uncaught TypeError: Cannot read property '2' of undefined.
```
````

2021-02-15 16:41 UTC, pepelsbey commented on src/posts/js/long/code-style.md
> +В обезличенном коде, как правило, меньше сложных и заумных конструкций. Такой код проще читать начинающим разработчикам, что уменьшает автобусный фактор (bus-factor), а это делает проект более живучи
Дефис не нужен https://en.wikipedia.org/wiki/Bus_factor

```suggestion
В обезличенном коде, как правило, меньше сложных и заумных конструкций. Такой код проще читать начинающим разработчикам, что уменьшает автобусный фактор (bus factor), а это делает проект более живучим.
```

2021-02-15 17:55 UTC, pepelsbey approved these changes

2021-02-15 17:55 UTC, pepelsbey commented
Ура!

2021-02-15 18:38 UTC, merged