Обновлённые стили для бокового меню
Y-Doka/y-doka.site pull request #498
Opened 2021-02-03 05:11 UTC by solarrust

* Чуть подправила стили для сайдбара
* Добавила новые маркеры и лейбы с количеством статей для Лонгридов и Инструментов

@pepelsbey есть мысль, что на гридах получится сделать менюшку, которая при открытии будет занимать максимум высоты, не мешая при этом остальным пунктам. Но у меня нет опыта работы с гридами. Может есть мысли?

2021-02-03 05:13 UTC, solarrust commented
@nlopin мы можем как-то определять новые статьи? В макете для этого предусмотрен стиль, но я не догадываюсь как отделить новую статью от всех прочих.

2021-02-03 08:24 UTC, pepelsbey commented
@solarrust, не глядя и нашару, сам принцип :)

```css
.menu {
  display: grid;
}

.menu--html {
  grid-template-rows:
    1fr 2em 2em;
}

.menu--css {
  grid-template-rows:
    2em 1fr 2em;
}

.menu--css {
  grid-template-rows:
    2em 2em 1fr;
}
```

```html
<div class="menu menu--html">
  <ul>HTML</ul>
  <ul>CSS</ul>
  <ul>JS</ul>
</div>
```

2021-02-03 10:32 UTC, nlopin commented
> @nlopin мы можем как-то определять новые статьи? В макете для этого предусмотрен стиль, но я не догадываюсь как отделить новую статью от всех прочих.

Все зависит от того, что мы вкладываем в слово «новая статья». Можно пробовать определять это для каждого пользователя индивидуально, но кажется нам важнее редакторский контроль над этой меткой. 

Можно добавлять тег `new` в статью и докидывать нужный класс при генерации меню и самой статьи.

2021-02-03 11:12 UTC, solarrust commented
@pepelsbey пока что не получилось добиться нужного поведения. 

@nlopin есть риск, что _новых_ статей расплодится и выделение их в списке прочих потеряет смысл. Пока оставим это на потом, до момента появления Главреда, который будет за этим смотреть =)

Предлагаю вмёржить

2021-02-03 21:44 UTC, pepelsbey requested changes
А давай дропнем всё, что закомментировано в стилях? Заготовки лучше хранить в задачах, в коде они потом забываются и мусорят. В остальном — всё ок.

2021-02-04 09:04 UTC, pepelsbey requested changes
😉

2021-02-04 09:04 UTC, pepelsbey commented on src/assets/styles/components/_aside.scss
> +        //width: 0.3125em;
Псст

2021-02-04 09:04 UTC, pepelsbey commented on src/assets/styles/components/_aside.scss
> +        //background-color: $nb-grey-background;
Псст

2021-02-04 09:24 UTC, solarrust commented on src/assets/styles/components/_aside.scss
> +        //background-color: $nb-grey-background;
🤔

2021-02-04 09:55 UTC, pepelsbey approved these changes

2021-02-04 13:11 UTC, merged