Разделяет гайд по флексбоксам на отдельные страницы
Y-Doka/y-doka.site pull request #508
Opened 2021-02-05 08:01 UTC by solarrust

@pepelsbey как и обсуждали с тобой, создала отдельные страницы для каждого из свойств, относящихся к флексбоксам. Взяла инфу из гайда и немного дополнила. 
Посмотри, пожалуйста, ок / не ок.

2021-02-05 13:43 UTC, pepelsbey commented
В целом — лайк! Но почитаю подробнее :)

2021-02-05 14:05 UTC, nlopin commented
Я правильно понял, что это дополнительные материалы к гайду по флексу?

2021-02-05 14:06 UTC, solarrust commented
@nlopin мы решили, что нам нужны отдельные страницы под каждые свойства для SEO. В гайде есть ещё всякие фишки и доп.материалы. На отдельных страницах только минимум инфы.

2021-02-05 15:55 UTC, pepelsbey commented
Ни секунды не думал про SEO, тут скорее удобство: дать ссылку на конкретное свойство, не стесняться написать про него подробно и т.п. Ну и в случае с флексами и гридами у них есть общая спека Box Alignment, в которой они шарят кучу свойств и тут просто нет другого выхода :)

2021-02-05 16:01 UTC, solarrust commented
@pepelsbey я думала о SEO. При поиске отдельных свойств лучше показывать в выдаче отдельную страницу для конкретного свойства. Плюс увеличиваем количество вхождений в поиск.

2021-02-08 08:55 UTC, solarrust commented
@pepelsbey жду ревью =)

2021-02-09 17:03 UTC, pepelsbey requested changes
Насобирал по мелочам и несколько среднего размера вопросов.

Ничего криминального :)

2021-02-09 17:03 UTC, pepelsbey commented on src/posts/css/doka/justify-content.md
> +- `end` — элементы прижимаются к краю, противоположному началу направления чтения на том языке, на котором отображается сайт. Например, при горизонтальной основной оси на русском языке элементы прижм
Здесь тоже стоит сгруппировать объяснение под списком. Так проще читать и не будет повторов.

2021-02-09 17:03 UTC, pepelsbey commented on src/posts/css/doka/justify-content.md
> +- `right` — элементы прижмутся к правому краю. В случае, если указано свойство `flex-direction: column`, то значение срабатывает как `start`.
Аналогично и здесь. Иначе тяжёлый список.

2021-02-09 17:03 UTC, pepelsbey commented on src/posts/css/doka/justify-content.md
> +💡 Значения `start` / `left` / `right` / `end` до сих пор не реализованы в Chrome.
```suggestion
💡 Значения `start`, `left`, `right`, `end` до сих пор не реализованы в Chrome.
```
Обычное перечисление в предложении :)

2021-02-09 17:06 UTC, solarrust commented on src/posts/css/doka/align-content.md
> +Свойство распределяет свободное пространство по дополнительной оси между строками флекс-элементов.
Да, вторая ось везде названа дополнительной. Завела ишью #518

2021-02-09 17:18 UTC, solarrust commented on src/posts/css/doka/justify-content.md
> +- `end` — элементы прижимаются к краю, противоположному началу направления чтения на том языке, на котором отображается сайт. Например, при горизонтальной основной оси на русском языке элементы прижм
> сгруппировать объяснение под списком

Прости, но я не поняла эту формулировку. Можешь пояснить?

2021-02-09 17:24 UTC, pepelsbey commented on src/posts/css/doka/justify-content.md
> +- `end` — элементы прижимаются к краю, противоположному началу направления чтения на том языке, на котором отображается сайт. Например, при горизонтальной основной оси на русском языке элементы прижм
Чуть выше развернул, здесь и сразу после похожая ситуация:

> Разница между значениями `flex-start` и `start`, `flex-end` и `end` лишь в том, что второе значение «уважает» направление чтения выбранного языка.

2021-02-10 11:06 UTC, solarrust commented
@pepelsbey подправила

2021-02-10 11:14 UTC, pepelsbey approved these changes
Красота!

2021-02-10 11:16 UTC, merged