Добавляет статью про функцию attr()
Y-Doka/y-doka.site pull request #509
Opened 2021-02-05 18:11 UTC by ezhkov

Закрывает #105

2021-02-08 09:06 UTC, solarrust reviewed
В целом огонь!

2021-02-08 09:06 UTC, solarrust commented on src/posts/css/doka/attr.md
> +/* С указанием типа */
Давай разобъём код на несколько блоков и комментарии вынесем в текст. Так удобнее будет читать.

2021-02-08 09:06 UTC, solarrust commented on src/posts/css/doka/attr.md
> +💡 Функцию `attr()` можно использовать в качестве значения любого CSS-свойства, однако полностью поддерживается только свойство [`content`](/css/doka/content). Для остальных свойств поддержка эксперим
Тут бы дать ссылочку на caniuse, где можно проверять поддержку attr для конкретного свойства. Если такая возможность есть.

2021-02-08 09:06 UTC, solarrust commented on src/posts/css/doka/attr.md
> +💡 Написание с указанием единиц изерения или фолбека пока имеет статус экспериментальной технологии и не поддерживается браузерами, но потенциально это позволит гораздо сильнее расширить область приме
```suggestion
💡 Написание с указанием единиц изерения или фолбэка пока имеет статус экспериментальной технологии и не поддерживается браузерами, но потенциально это позволит гораздо сильнее расширить область применения функции `attr()`. Например, мы можем указать браузеру, что значение атрибута — это данные числового типа или одна из единиц измерения, допустимых в CSS:
```
1. https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#fallback
2. Два длинных сложных предложения. Получится разбить?

2021-02-08 09:06 UTC, solarrust commented on src/posts/css/doka/attr.md
> +Примеры записи с указанием типа или фолбека кажутся довольно перспективными, но к сожалению пока не поддерживаются ни одним из браузеров.
```suggestion
Примеры записи с указанием типа или фолбека кажутся довольно перспективными, но, к сожалению, пока не поддерживаются ни одним из браузеров.
```

2021-02-09 16:41 UTC, solarrust commented
@pepelsbey глянь, пожалуйста

2021-02-10 11:07 UTC, pepelsbey requested changes

2021-02-10 11:07 UTC, pepelsbey commented on src/posts/css/doka/attr.md
> +`attr()` — это CSS-функция, которая умеет получать значение любого атрибута у элемента, а потом использовать это значение прямо внутри таблицы стилей.
«Таблица стилей» это как «всемирная паутина» — слишком буквальный и малоупотребимый перевод. Лучше писать так, как говорят фронтендеры — стили.

```suggestion
`attr()` — это CSS-функция, которая умеет получать значение любого атрибута у элемента, а потом использовать это значение прямо в стилях.
```

2021-02-10 11:07 UTC, pepelsbey commented on src/posts/css/doka/attr.md
> +```
````suggestion
```css
.element::before {
  content: attr(data-title);
  content: attr(href);
}
```

С указанием типа:

```css
.element::before {
  content: attr(src url);
  content: attr(data-count number);
  content: attr(data-width px);
}
```

С указанием фолбэка, то есть запасного значения:

```css
.element::before {
  content: attr(data-count number, 0);
  content: attr(src url, "");
  content: attr(data-width px, inherit);
  content: attr(data-something, "default");
}
```
````

2021-02-10 11:07 UTC, pepelsbey commented on src/posts/css/doka/attr.md
> +Примеры записи с указанием типа или фолбека кажутся довольно перспективными, но, к сожалению, пока не поддерживаются ни одним из браузеров.
```suggestion
Примеры записи с указанием типа или фолбэка кажутся довольно перспективными, но, к сожалению, пока не поддерживаются ни одним из браузеров.
```

2021-02-10 11:07 UTC, pepelsbey commented on src/posts/css/doka/attr.md
> +```
Так пример проще будет считать, особенно на узких экранах

````suggestion
```html
<p>
  Подробнее о скидках и акциях можно узнать
  <a href="http://best-site.ru/sales">по ссылке</a>
</p>
```
````

2021-02-10 17:01 UTC, pepelsbey approved these changes

2021-02-11 16:26 UTC, solarrust approved these changes

2021-02-11 16:26 UTC, merged