Добавляет статью про white-space
Y-Doka/y-doka.site pull request #510
Opened 2021-02-07 16:11 UTC by ezhkov

Закрывает #117

2021-02-08 09:25 UTC, solarrust commented on src/posts/css/doka/white-space.md
> +Если текста в элементе много (больше, чем может вместить ширина элемента), то по уолчанию браузер пытается переносить слова на новую строку.
```suggestion
Если текста в элементе много (больше, чем может вместить ширина элемента), то по умолчанию браузер пытается переносить слова на новую строку.
```

2021-02-08 09:25 UTC, solarrust commented on src/posts/css/doka/white-space.md
> +Перенос в общем случае выполняется по символам пробела либо по символам переноса строк. Разговор сейчас идёт именно про форматирование текста прямо внутри HTML. Ведь мы можем в HTML длинный абзац ост
```suggestion
Перенос в общем случае выполняется по символам пробела либо по символам переноса строк. Разговор сейчас идёт именно про форматирование текста прямо внутри HTML. Ведь мы можем в HTML длинный абзац оставить одной строкой, а можем разбить на несколько строк, используя клавишу Enter. По умолчанию браузер игнорирует форматирование в HTML. Он ориентируется только на теги, и выводит текст на экран, опираясь на текущий способ обработки пробельных символов. Но мы можем изменить этот способ, используя различные значения свойства `white-space`.
```

2021-02-08 09:25 UTC, solarrust commented on src/posts/css/doka/white-space.md
> +<!-- На странице выведется всё в одну строку: Однажды в студёную зимнюю пору -->
Лучше убрать это из комментария и добавить визуальный пример.

2021-02-08 09:25 UTC, solarrust commented on src/posts/css/doka/white-space.md
> +💡 Принудительно организовать перенос текста вне зависимости от форматирования можно с использованием тега [`<br>`](/doka/html/br). Поведение текста при использовании этого тега одинаково при любых зн
Совет из разряда вредных 😈

2021-02-08 20:25 UTC, ezhkov commented on src/posts/css/doka/white-space.md
> +💡 Принудительно организовать перенос текста вне зависимости от форматирования можно с использованием тега [`<br>`](/doka/html/br). Поведение текста при использовании этого тега одинаково при любых зн
Не сказал бы, что это совет. Скорее, просто FYI. Но если принципиально, могу перефразировать, чтобы не звучало как совет)

2021-02-09 11:39 UTC, pepelsbey commented on src/posts/css/doka/white-space.md
> +💡 Принудительно организовать перенос текста вне зависимости от форматирования можно с использованием тега [`<br>`](/doka/html/br). Поведение текста при использовании этого тега одинаково при любых зн
`<br>` обычный тег для переноса текста, не вижу здесь вреда :)

2021-02-09 16:34 UTC, solarrust approved these changes

2021-02-10 10:55 UTC, pepelsbey requested changes

2021-02-10 10:55 UTC, pepelsbey commented on src/posts/css/doka/white-space.md
> +```
Выносит описание из кода и делает настоящий CSS, чтобы подсветка нормально сработала. Иначе это не CSS.

````suggestion
Ключевые слова:

```css
.element {
  white-space: normal;
  white-space: nowrap;
  white-space: pre;
  white-space: pre-wrap;
  white-space: pre-line;
  white-space: break-spaces;
}
```

Глобальные значения:

```css
.element {
  white-space: inherit;
  white-space: initial;
  white-space: unset;
}
```
````

2021-02-10 10:55 UTC, pepelsbey commented on src/posts/css/doka/white-space.md
> +Перенос в общем случае выполняется по символам пробела либо по символам переноса строк. Разговор сейчас идёт именно про форматирование текста прямо внутри HTML. Ведь мы можем в HTML длинный абзац ост
```suggestion
Если текста в элементе много (больше, чем может вместить ширина элемента), то по умолчанию браузер пытается переносить слова на новую строку. Перенос в общем случае выполняется по символам пробела либо по символам переноса строк. Разговор сейчас идёт именно про форматирование текста прямо внутри HTML. Ведь мы можем в HTML длинный абзац оставить одной строкой, а можем разбить на несколько строк, используя клавишу <kbd>Enter</kbd>. По умолчанию браузер игнорирует форматирование в HTML. Он ориентируется только на теги, и выводит текст на экран, опираясь на текущий способ обработки пробельных символов. Но мы можем изменить этот способ, используя различные значения свойства `white-space`.
```

2021-02-10 10:55 UTC, pepelsbey commented on src/posts/css/doka/white-space.md
> +```
Что здесь, что в демке и так видно, что строки переносятся. Подписывать «перенос строки» кажется избыточным (мы же не подписали пробелы во фразе). Плюс это усложняет демку: там и лишние пробелы, и перенос строки. Лучше упростить второй пример и убрать комментарии.

2021-02-10 10:55 UTC, pepelsbey commented on src/posts/css/doka/white-space.md
> +</figure>
- Нет особого смысла в `<figure>`, если нет `<figcaption>`
- Добавил высоту картинке, чтобы помочь браузеру
- Сделал более полезное описание на русском.

```suggestion
<img src="/assets/images/posts/white-space/white-space.png" width="800" height="397" alt="Сравнение рендеринга значений break-spaces и pre-wrap в браузере">
```

2021-02-10 16:38 UTC, pepelsbey approved these changes

2021-02-10 16:51 UTC, merged