Добавляет статью про placeholder-shown
Y-Doka/y-doka.site pull request #512
Opened 2021-02-08 21:15 UTC by ezhkov

Закрывает #129

2021-02-09 16:52 UTC, solarrust commented on src/posts/css/doka/placeholder-shown.md
> +Если полю ввода задан атрибут `placeholder`, то внутри поля будет показана текстовая подсказка. Она пропадёт, если пользователь введёт хотя бы один символ. По сути псевдокласс `:placeholder-shown` бу
```suggestion
Если полю ввода задан атрибут `placeholder` с каким-то значением, то внутри поля будет показана текстовая подсказка. Она пропадёт, если пользователь введёт хотя бы один символ. По сути псевдокласс `:placeholder-shown` будет применять стили к пустым полям ввода.
```

Тут, мне кажется, важно сказать, что у плейсхолдера должно быть значение, а не просто атрибут.

2021-02-09 16:52 UTC, solarrust commented on src/posts/css/doka/placeholder-shown.md
> +💡 Этот псевдокласс можно использовать совместно с псевдоклассом [`:invalid`](/doka/css/invalid-valid) для стилизации некорректно заполненных полей ввода
```suggestion
🛠 Этот псевдокласс можно использовать совместно с псевдоклассом [`:invalid`](/doka/css/invalid-valid) для стилизации некорректно заполненных полей ввода.
```

2021-02-09 16:52 UTC, solarrust commented on src/posts/css/doka/placeholder-shown.md
> +💡 Иногда длина плейсхолдера больше ширины текстового поля. В результате плейсхолдер некрасиво обрезается. Можно использовать псевдокласс `placeholder-shown`, чтобы сделать обрезку чуть симпатичнее:
```suggestion
🛠 Иногда длина плейсхолдера больше ширины текстового поля. В результате плейсхолдер некрасиво обрезается. Можно использовать псевдокласс `:placeholder-shown`, чтобы сделать обрезку чуть симпатичнее:
```

2021-02-09 16:53 UTC, solarrust commented
@pepelsbey загляни сюда

2021-02-10 11:13 UTC, pepelsbey requested changes

2021-02-10 11:13 UTC, pepelsbey commented on src/posts/css/doka/placeholder-shown.md
> +💡 Псевдокласс `:placeholder-shown` — это НЕ то же самое, что псевдоэлемент [`::placeholder`](/doka/css/placeholder). Псевдокласс применит стили к самому полю ввода. А стили, примененные к псевдоэлеме
Выделяет важное цивилизованно :)

```suggestion
💡 Псевдокласс `:placeholder-shown` — это **не то же самое**, что псевдоэлемент [`::placeholder`](/doka/css/placeholder). Псевдокласс применит стили к самому полю ввода. А стили, примененные к псевдоэлементу [`::placeholder`](/doka/css/placeholder), изменят внешний вид текста подсказки, но никак не затронут само поле ввода.
```

2021-02-10 11:13 UTC, pepelsbey commented on src/posts/css/doka/placeholder-shown.md
> +:placeholder-shown { ... }
Лучше писать настоящий код: так проще парсеру и читателю.

```suggestion
:placeholder-shown {
  color: teal;
}
```

2021-02-10 11:13 UTC, pepelsbey commented on src/posts/css/doka/placeholder-shown.md
> +<input type="text" placeholder="Можно искать по номеру телефона, фамилии или email" class="ellipsis"/>
```suggestion
<p>Обычная обрезка</p>
<input type="text" placeholder="Можно искать по номеру телефона, фамилии или email">

<p>Красивая обрезка</p>
<input type="text" placeholder="Можно искать по номеру телефона, фамилии или email" class="ellipsis">
```

2021-02-10 16:37 UTC, pepelsbey approved these changes

2021-02-10 16:53 UTC, solarrust approved these changes

2021-02-10 16:53 UTC, merged