Добавляет демо в раздел HTML
Y-Doka/y-doka.site pull request #52
Opened 2020-11-23 17:25 UTC by skorobaeus

2020-11-24 14:43 UTC, nlopin commented
@skorobaeus упала проверка. Один из ресурсов получаем по HTTP, браузер будет его блокировать. Проверь, что он доступен по HTTPS и поменяй урл, пожалуйста

2020-11-24 14:44 UTC, nlopin requested changes

2020-11-24 14:44 UTC, nlopin commented on src/demos/video/background.njk
> +    <source src="http://epic.spb.ru/biostorm2.av1.mkv" type="video/mp4">
вот этот видосик нужно запрашивать по https

2020-11-24 15:22 UTC, furtivite commented on src/demos/video/background.njk
> +    <source src="http://epic.spb.ru/biostorm2.av1.mkv" type="video/mp4">
@nlopin я думаю, мы его положим локально. Пока ещё смотрю всё, не мержи, плз.

2020-11-26 16:28 UTC, nlopin approved these changes

2020-11-26 18:11 UTC, furtivite commented
Есть пара видео, которые мы тащим извне. Принято решение перетащить их в свежесозданные папки и залить локально. Ожидаем выбор @skorobaeus о менее "тяжелых" видео.

2020-11-27 12:56 UTC, solarrust approved these changes

2020-11-28 11:48 UTC, merged