меняет картинки на обновлённые
Y-Doka/y-doka.site pull request #532
Opened 2021-02-11 07:48 UTC by furtivite

2021-02-15 13:41 UTC, pepelsbey commented
А нам точно нужны ведущие нули в названиях файлов? Чем проще, чем лучше, кажется. Нет какой-то договорённости как в датах, современные десктопные файловые системы нормально такое сортируют.

2021-02-15 13:47 UTC, furtivite commented
> А нам точно нужны ведущие нули в названиях файлов? Чем проще, чем лучше, кажется. Нет какой-то договорённости как в датах, современные десктопные файловые системы нормально такое сортируют.

Когда заливал, надо было отделить от старых файлов, да уберу ведущие нули. Они не нужны. В новых картинках их не будет.

2021-03-09 21:07 UTC, nlopin commented
@pepelsbey @furtivite мы это мержим?

2021-03-09 23:00 UTC, pepelsbey reviewed
У меня два вопроса к этому черновику, хотя он как бы черновик и не готов к ревью :)

1. Зачем мы храним старые картинки?
2. JPEG — это сжатая версия, давайте хранить исходники без потерь в PNG

Для скриншотов в принципе нужно использовать PNG, там от силы 128 цветов и без видимых потерь. А сейчас выходит JPEG с видимыми потерями. Неправильно это :)

2021-03-10 03:56 UTC, furtivite commented
> У меня два вопроса к этому черновику, хотя он как бы черновик и не готов к ревью :)
> 
> 1. Зачем мы храним старые картинки?
> 2. JPEG — это сжатая версия, давайте хранить исходники без потерь в PNG
> 
> Для скриншотов в принципе нужно использовать PNG, там от силы 128 цветов и без видимых потерь. А сейчас выходит JPEG с видимыми потерями. Неправильно это :)

@pepelsbey 
1) мы договорились старые не хранить, при переезде их переносить не надо будет. Если я забыл их удалить.
2) сейчас мы в процессе обсуждения с @ValyaBro способа получить более лёгкие картинки (прежде всего с изменением размера) и вообще про flow
3) может зальем, а там видно будет в дальнейшем? Ещё раз перепроверим.

2021-03-10 06:39 UTC, nlopin requested changes
Я не уверен, но кажется старые картинки не были удалены. Давай уберем

2021-03-10 06:39 UTC, nlopin commented on src/posts/js/long/deal-with-forms.md
> +![Представление всех элементов формы в консоли браузера](/assets/images/posts/js/deal-with-forms/1.jpg)
мы эти картинки заменили на текст. Смержи или ребейзни на мастер. В этой статье остались три последние картинки

2021-06-04 09:47 UTC, nlopin commented
Устарело

2021-06-04 09:47 UTC, closed without merging