Добавляет возможность устанавливать обложку статьи
Y-Doka/y-doka.site pull request #534
Opened 2021-02-11 08:12 UTC by furtivite

<img width="1392" alt="Снимок экрана 2021-02-11 в 11 01 55" src="https://user-images.githubusercontent.com/50330458/107613457-6a862f00-6c59-11eb-8a7a-bf62c52221a2.png">

Теперь можно добавлять обложку. Для этого в заголовочную часть поста нужно добавить переменную `cover` с относительным урлом картинки.

Пример:

```markdown
---
title: "Гайд по grid"
name: grid-guide
...
cover: '/assets/images/posts/grid-guide/cover.png'
---
```

Если в статье есть `cover`, то перед `<div class="article__title">` добавляется картинка с нужным классом. 

Чтобы не вставлять картинку с пустым `scr`, если элемента `cover` нет, осуществляется проверка на наличие. 

```njk
{% if cover | length > 1 %}
  <img src="{{ cover }}" class="article__cover" />
  {% endif%}
```

2021-02-11 08:14 UTC, furtivite commented
Блокер для #531

2021-02-11 08:18 UTC, solarrust commented
- [ ] Я бы добавила размеры картинке
- [ ] Надо бы про `alt` не забыть
- [ ] Не будет ли `picture` уместнее? С заделом на дальнейшую автоматическую нарезку картинок под разные формфакторы

2021-02-11 08:30 UTC, furtivite commented
Добавил alt = "Обложка для статьи + название статьи"
Добавил обёртку `<picture>` и возможность вставлять мобильную картинку, если такая есть.
Про размеры не понял 

```njk
{% if cover | length > 1 %}
  <picture>
    {% if coverMobile | length > 1 %}
    <source srcset="{{ coverMobile }}" media="(max-width: 425px)">
    {% endif%}
    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}"/>
  </picture>
  {% endif%}
```

2021-02-11 09:36 UTC, pepelsbey commented on src/posts/css/long/grid-guide.md
> +cover: '/assets/images/posts/grid-guide/cover.png'
Предлагаю упростить данные:

```yaml
cover:
  desktop: 'desktop.png'
  mobile: 'mobile.png'
```

Если обложки нет, то её не должно быть в MD-файле, тогда можно будет:

```njk
{% if cover %}
  {% if cover.desktop %}
    …
  {% endif%}
  {% if cover.mobile %}
    …
  {% endif%}
{% endif%}
```

У нас сейчас во многих статьях торчат пустые поля:

```yml
title: ":active"
name: active
author: ABatickaya
co-authors:
designers:
contributors:
```

Надо от них избавиться, но это другая задача


```yml
title: ":active"
name: active
author: ABatickaya
```

2021-02-11 09:39 UTC, pepelsbey commented on src/layouts/post.njk
> +    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}"/>
Если у нас нет возможности описать то, что нарисовано на картинке, например так:

```yaml
cover:
  desktop: 'desktop.png'
  mobile: 'mobile.png'
  alt: 'Умная собака подозрительно смотрит'
```

То лучше вывести `alt=""`, ценности в таком описании обложки нет.

2021-02-11 09:39 UTC, pepelsbey commented on src/layouts/post.njk
> +    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}"/>
```suggestion
    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}">
```

2021-02-11 09:46 UTC, solarrust commented
Картиночка в PNG, но без прозрачности. Может перегоним в JPG ради экономии и перформанса?

2021-02-11 09:48 UTC, furtivite commented
Предлагается, чтобы, если картинка не загрузилась делать примерно так: https://codepen.io/furtivite/pen/xxRRZYj?editors=1100 - спасибо @pepelsbey за наводку.

2021-02-11 09:49 UTC, furtivite commented on src/layouts/post.njk
> +    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}"/>
Мне нравится, но там пока длинные урлы будут, пока на новую инфраструктуру не переехали.

2021-02-11 09:50 UTC, furtivite commented on src/posts/css/long/grid-guide.md
> +cover: '/assets/images/posts/grid-guide/cover.png'
Заведёшь задачу?

2021-02-11 10:37 UTC, nlopin commented on src/assets/styles/components/_article.scss
> +    padding-top: 30px;
Нам точно нужно указывать размер именно в пикселях? Отступ справа для этого же элемента указан в `em`

2021-02-11 10:37 UTC, nlopin commented on src/layouts/post.njk
> +  {% if cover | length > 1 %}
без `length` ломается? Я бы попробовал `{% if cover %}`

2021-02-11 11:37 UTC, furtivite commented on src/layouts/post.njk
> +  {% if cover | length > 1 %}
Не ломается. В новом варианте будет этот вариант.

2021-02-11 11:42 UTC, furtivite commented on src/layouts/post.njk
> +    <img src="{{ cover }}" class="article__cover" alt="Обложка для статьи: {{ title }}"/>
Может добавим сюда ещё фоновый цвет, чтобы было понятно, почему текст ниже, что это картинка не прогрузилась, а не что-то ещё?

2021-02-11 12:03 UTC, furtivite commented on src/assets/styles/components/_article.scss
> +    padding-top: 30px;
Поправил.

2021-02-11 12:18 UTC, pepelsbey commented
> Картиночка в PNG, но без прозрачности. Может перегоним в JPG ради экономии и перформанса?

Дело не только в прозрачности, количество цветов важнее. Сделал картинку 74 Кб вместо 150 Кб (ограничил палитру до 32 цветов), JPEG получается 200 Кб в хоть каком-то приличном качестве.

2021-02-11 12:20 UTC, solarrust commented
> > Картиночка в PNG, но без прозрачности. Может перегоним в JPG ради экономии и перформанса?
> 
> Дело не только в прозрачности, количество цветов важнее. Сделал картинку 74 Кб вместо 150 Кб (ограничил палитру до 32 цветов), JPEG получается 200 Кб в хоть каком-то приличном качестве.

А WebP ещё зазорно использовать?

2021-02-11 12:20 UTC, pepelsbey commented on src/posts/css/long/grid-guide.md
> +  alt: Гайд по грид
```suggestion
```
Я бы лучше не добавлял описание в этому случае, оно не описывает картинку

2021-02-11 12:20 UTC, furtivite commented on src/posts/css/long/grid-guide.md
> +  alt: Гайд по грид
Можно и не добавлять,  принципе, я для примера завёл.

2021-02-11 12:21 UTC, furtivite commented
> > > Картиночка в PNG, но без прозрачности. Может перегоним в JPG ради экономии и перформанса?
> > 
> > 
> > Дело не только в прозрачности, количество цветов важнее. Сделал картинку 74 Кб вместо 150 Кб (ограничил палитру до 32 цветов), JPEG получается 200 Кб в хоть каком-то приличном качестве.
> 
> А WebP ещё зазорно использовать?

Мы можем это использовать через отдельный плагин, чуть позже, чтобы сейчас особо не запариваться. И вообще все картинки из PNG без прорзрачности конвертить в WebP + JPG

2021-02-11 12:22 UTC, pepelsbey requested changes

2021-02-11 12:22 UTC, pepelsbey commented on src/assets/styles/components/_article.scss
> +    padding-bottom: 59.66%;
Если обложка будет другого соотношения, что делать? Нужно дать картинке `width: 100%` и `height: auto`, паддинг-хак здесь не нужен.

2021-02-11 12:23 UTC, pepelsbey commented
> А WebP ещё зазорно использовать?

Сжал в WebP, получил хуже качество и 78 Кб 🤔
Иногда лучше руками и в PNG

2021-02-11 12:28 UTC, furtivite commented on src/assets/styles/components/_article.scss
> +    padding-bottom: 59.66%;
Но если `height: auto` разве будет ли резервироваться место? Ради чего и делалось. 
А обложку можно всегда запрашивать нужного нам размера. 
На крайний случай можно JS-ом брать размер, вычислять соотношение сторон и подставлять.

2021-02-11 13:13 UTC, pepelsbey commented on src/assets/styles/components/_article.scss
> +    padding-bottom: 59.66%;
> Но если height: auto разве будет ли резервироваться место?

Будет, если дать картинке размеры в атрибутах.

2021-02-11 13:16 UTC, pepelsbey commented on src/assets/styles/components/_article.scss
> +    padding-bottom: 59.66%;
В общем, решения:

1. Зафиксировать соотношение сторон и договориться, что обложка всегда с таким соотношением: прописать размеры в шаблоне и добавить `height: auto`
2. Допустить, что соотношение сторон может быть любым и добавить поля `cover.width` и `cover.height` с размерами — и всё равно добавить `height: auto`.

Не стоит использовать этот хак там, где его можно не использовать — это реально хак и сложный код. К тому же уже через полгода можно будет использовать `aspect-ratio`.

2021-02-12 10:07 UTC, furtivite commented on src/assets/styles/components/_article.scss
> +    padding-bottom: 59.66%;
Сделал первый вариант для десктопа, надо дописать его для мобильного тоже.

2021-02-12 22:07 UTC, nlopin approved these changes

2021-02-12 22:07 UTC, nlopin commented on src/layouts/post.njk
> +    <img src="{{ cover.desktop }}" width="900px" height="537px" class="article__cover-image" alt="{{ cover.alt }}">
здесь точно нужна длина и ширина в пикселях?

2021-02-12 22:16 UTC, solarrust commented on src/layouts/post.njk
> +    <img src="{{ cover.desktop }}" width="900px" height="537px" class="article__cover-image" alt="{{ cover.alt }}">
Да, чтобы браузер зарезервировал место пока грузит картинку и контент не прыгал.

2021-02-12 22:17 UTC, solarrust approved these changes

2021-02-15 13:31 UTC, pepelsbey requested changes

2021-02-15 13:31 UTC, pepelsbey commented on src/layouts/post.njk
> +    <img src="{{ cover.desktop }}" width="900px" height="537px" class="article__cover-image" alt="{{ cover.alt }}">
```suggestion
    <img src="{{ cover.desktop }}" width="900" height="537" class="article__cover-image" alt="{{ cover.alt }}">
```
Пиксели здесь не нужны

2021-02-15 13:32 UTC, pepelsbey commented on src/layouts/post.njk
> +    <img src="{{ cover.desktop }}" width="900px" height="537px" class="article__cover-image" alt="{{ cover.alt }}">
> здесь точно нужна длина и ширина в пикселях?

Нет, `px` здесь не нужны, но сами размеры — да.

2021-02-15 13:39 UTC, pepelsbey approved these changes

2021-02-15 13:39 UTC, merged

2021-02-15 13:39 UTC, pepelsbey commented
Ура!