Добавляет статью про :in-range/:out-of-range
Y-Doka/y-doka.site pull request #536
Opened 2021-02-11 15:49 UTC by ezhkov

Закрывает #132

2021-02-15 06:18 UTC, solarrust commented on src/posts/css/doka/in-range-out-of-range.md
> +title: ":in-range / :out-of-range"
```suggestion
title: ":in-range, :out-of-range"
```

2021-02-15 06:18 UTC, solarrust commented on src/posts/css/doka/in-range-out-of-range.md
> +Эти псевдоклассы используются для стилизации полей ввода, которые поддерживают атрибуты `min`/`max`.
```suggestion
Эти псевдоклассы используются для стилизации полей ввода, которые поддерживают атрибуты `min` и `max`.
```

2021-02-15 06:18 UTC, solarrust commented on src/posts/css/doka/in-range-out-of-range.md
> +- `:in-range` для полей, в которых введённое значение **попадает внутрь** диапазона `[min, max]`;
```suggestion
- `:in-range` для полей, в которых введённое значение **попадает внутрь** диапазона от `min` до `max`;
```

2021-02-15 06:18 UTC, solarrust commented on src/posts/css/doka/in-range-out-of-range.md
> +- `:out-of-range` для полей, в которых введённое значение **не попадает внутрь** диапазона `[min, max]`;
```suggestion
- `:out-of-range` для полей, в которых введённое значение **не попадает внутрь** диапазона от `min` до `max`;
```

2021-02-15 06:18 UTC, solarrust commented on src/posts/css/doka/in-range-out-of-range.md
> +Рассказываем о синтаксисте.
😅 кажется тут нужно дописать

2021-02-23 19:52 UTC, solarrust commented
Призываю @pepelsbey

2021-02-24 21:17 UTC, pepelsbey requested changes

2021-02-24 21:17 UTC, pepelsbey commented on src/posts/css/doka/in-range-out-of-range.md
> +- `:out-of-range` для полей, в которых введённое значение **не попадает внутрь** диапазона от `min` до `max`;
```suggestion
Эти псевдоклассы используются для стилизации полей ввода, которые поддерживают атрибуты `min` и `max`:

- `:in-range` для полей, в которых введённое значение **попадает внутрь** диапазона от `min` до `max`;
- `:out-of-range` для полей, в которых введённое значение **не попадает внутрь** диапазона от `min` до `max`.
```

2021-03-04 19:39 UTC, pepelsbey approved these changes

2021-03-04 20:01 UTC, solarrust approved these changes

2021-03-04 20:01 UTC, merged