Разделяет лонгрид по грибам на отдельные статьи
Y-Doka/y-doka.site pull request #538
Opened 2021-02-11 16:55 UTC by solarrust

2021-02-12 07:42 UTC, solarrust commented
@pepelsbey поревьюй, пожалуйста.

2021-02-15 17:53 UTC, pepelsbey requested changes
- Клетки заменяет на ячейки, чтобы последовательно
- Добавляет строки внутри колаутов
- Правит всякое и задаёт вопросы, где непонятно

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/display.md
>  Существует множество других значений, но большинство из них либо устарели, либо не имеют хорошей поддержки. Если встретите в коде следующие значения, то не пугайтесь: `inline`, `inline-table`, `list-
Очень неожиданное заявление. Все упомянутые значения имеют нормальную поддержку и не устарели. Если нужно получить поведение как внутри табличной ячейки — нет ничего плохого в том, чтобы написать `display: table-cell`, тем более `display: inline`.

Я бы лучше дропнул этот абзац, но могу отдельной задачей.

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/gap.md
> +Первым указывается значение отступа для рядов, за ним значение отступа для колонок.
```suggestion
Указываете два значения размера в любых единицах измерения, разделяя их слэшем. Первым указывается значение отступа для рядов, за ним значение отступа для колонок.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/gap.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-area.md
> +```
````suggestion
Пример с указанием на именованную область: блок `item1` займёт область `content` внутри грид-сетки.

```css
.item1 {
  grid-area: content;
}
```
````

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-area.md
> +```
Комментарий не соответствует порядку в коде и чуть выше уже есть пример, я бы не стал дублировать.

````suggestion
```css
.item2 {
  grid-area: 1 / col4-start / last-line / 6;
}
```
````

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-area.md
> +Вторая пара значений отвечает за конечные позиции: третье для `grid-row-end`, четвёртое для `grid-column-end`.
```suggestion
Важно указывать значения в правильном порядке. Первая пара значений к начальной позиции: первое для `grid-row-start`, второе для `grid-column-start`. Вторая пара значений отвечает за конечные позиции: третье для `grid-row-end`, четвёртое для `grid-column-end`.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-area.md
> +Или напишите ключевое слово, указывающее на именованную область внутри грид-разметки.
```suggestion
Или напишите ключевое слово, указывающее на именованную область внутри грид-раскладки.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-area.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-columns-rows.md
> +В случаях если вы не уверены в количестве элементов, вложенных в грид-контейнер, то стоит предусмотреть автоматические колонки или ряды.
```suggestion
Если вы не уверены в количестве элементов, вложенных в грид-контейнер, то стоит предусмотреть автоматические колонки или ряды.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-columns-rows.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-flow.md
> +```
Если уж не выносить текст, то хотя бы писать компактно для узких экранов.

````suggestion
```css
.container {
  display: grid;
  /* Три колонки */
  grid-template-columns: auto auto auto;
  /* Два ряда */
  grid-template-rows: auto auto;
  /* Отступы между ячейками */
  grid-gap: 10px;
  /* Автоматическое размещение в ряд */
  grid-auto-flow: row;

  /* Для красоты */
  padding: 10px;
  background: #f1f1f1;
}

.item {
  min-height: 50px;
  text-align: center;
  padding: 20px 0;
  font-size: 30px;
  line-height: 1;
  background: lightblue;
}

.item3 {
  /* Занимает один ряд и растягивается на две колонки */
  grid-column: span 2;
  background: pink;
}
```
````

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-flow.md
> +```
````suggestion
```css
.container {
  grid-template-columns: auto auto auto;
  /* Автоматическое размещение в ряд */
  grid-auto-flow: row dense;
}
```
````

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-flow.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-column-row.md
> +Элемент начинается с третьей линии по горизонтали и растягивается на 2 клетки. По вертикали элемент начинается от линии с именем `[third-line]` и заканчивается у четвёртой линии:
```suggestion
Элемент начинается с третьей линии по горизонтали и растягивается на 2 ячейки. По вертикали элемент начинается от линии с именем `[third-line]` и заканчивается у четвёртой линии:
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-column-row.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-start-end.md
> +- `auto` — означает автоматическое размещение, автоматический диапазон клеток или дефолтное растягивание элемента, равное одному.
```suggestion
- `[name]` или `1` — порядковый номер или название конкретной линии.
- `span 2` — элемент растянется на указанное количество ячеек.
- `span [name]` — элемент будет растягиваться до следующей указанной линии.
- `auto` — означает автоматическое размещение, автоматический диапазон ячеек или дефолтное растягивание элемента, равное одному.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-start-end.md
> +💡 Элементы могут перекрывать друг друга, накладываться друг на друга. Можно использовать свойство `z-index` для управления контекстом наложения.
```suggestion
💡 Элементы могут перекрывать друг друга, накладываться друг на друга. Можно использовать свойство `z-index` для управления порядком следования элементов.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-start-end.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-areas.md
> +- название — собственно название области. Может быть использовано абсолютно любое слово или даже эмоджи! 🤯
```suggestion
- `none` (значение по умолчанию) — области сетки не задано имя.
- `.` — означает пустую ячейку.
- `name` — собственно название области, может быть абсолютно любым словом или даже эмоджи! 🤯
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-areas.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-columns.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-columns.md
> +💡 Удобно использовать единицу измерения `fr` чтобы размеры колонок рассчитывались от размера родителя, а не были фиксированными.
`fr` это не проценты, это как `flex-grow`, соотношение.

```suggestion
💡 Удобно использовать единицу измерения `fr` чтобы указать в каких соотношениях колонки разделят свободное место.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-rows.md
> +💡 Удобно использовать единицу измерения `fr` чтобы размеры рядов рассчитывались от размера родителя, а не были фиксированными.
```suggestion
💡 Удобно использовать единицу измерения `fr` чтобы указать в каких соотношениях ряды разделят свободное место.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-rows.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template.md
> +🛠 В этом же свойстве можно задавать значение и для свойства `grid-template-areas`, но тогда код превращается в кашу и становится совершенно нечитабельным, на мой взгляд. Лучше всё же использовать это
> В этом же свойстве можно задавать значение и для свойства…

Тут либо опечатка, либо слишком сложно

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid.md
> +- [ auto-flow && dense? ] `grid-auto-rows`? / `grid-template-columns` — задаёт конкретные размеры колонкам. Если слева от слэша стоит ключевое слово `auto-flow`, то для свойства `grid-auto-flow` буде
> [ auto-flow && dense? ] grid-auto-rows? / grid-template-columns

Очень сложный синтаксис примеров внутри плотного списка. Нужно что-то придумать проще.

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/justify-items.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/justify-self.md
> +Возможные значения аналогичны значениям свойства [`justify-items`](/css/doka/justify-items)
```suggestion
Возможные значения аналогичны значениям свойства [`justify-items`](/css/doka/justify-items).
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/justify-self.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/place-items.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/place-self.md
> +:::
```suggestion
:::callout 📝

Полный список свойств гридов можно посмотреть в [гайде по grid](/css/long/grid-guide/).

:::
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-auto-flow.md
> +- `dense` — браузер старается заполнить _дырки_ (пустые клетки) в разметке, если размеры элементов позволяют. Можно сочетать с остальными значениями.
```suggestion
- `dense` — браузер старается заполнить _дырки_ (пустые ячейки) в разметке, если размеры элементов позволяют. Можно сочетать с остальными значениями.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-column-row.md
> +💡 Если опустить слэш и второе значение, то элемент будет размером в одну клетку.
```suggestion
💡 Если опустить слэш и второе значение, то элемент будет размером в одну ячейку.
```

2021-02-15 17:53 UTC, pepelsbey commented on src/posts/css/doka/grid-template-areas.md
> +Обратите внимание, что нужно называть каждую из клеток. Например, если шапка или подвал нашего сайта будет занимать все три существующие колонки, то нужно будет написать трижды называние этих областе
```suggestion
Обратите внимание, что нужно называть каждую из ячеек. Например, если шапка или подвал нашего сайта будет занимать все три существующие колонки, то нужно будет написать трижды называние этих областей. Удобнее всего будет подписывать области в виде некой таблицы. Подобный способ записи чем-то похож на [таблицы в Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables):
```

2021-02-15 18:17 UTC, solarrust commented on src/posts/css/doka/display.md
>  Существует множество других значений, но большинство из них либо устарели, либо не имеют хорошей поддержки. Если встретите в коде следующие значения, то не пугайтесь: `inline`, `inline-table`, `list-
Эта статья имеет опосредованное отношение к PR с разделением гайда про гридам на отдельные статьи. Лучше вынести в отдельную задачу.

2021-02-15 18:26 UTC, solarrust commented on src/posts/css/doka/grid-template.md
> +🛠 В этом же свойстве можно задавать значение и для свойства `grid-template-areas`, но тогда код превращается в кашу и становится совершенно нечитабельным, на мой взгляд. Лучше всё же использовать это
Подумаю как попроще =)

2021-02-15 18:26 UTC, solarrust commented on src/posts/css/doka/grid.md
> +- [ auto-flow && dense? ] `grid-auto-rows`? / `grid-template-columns` — задаёт конкретные размеры колонкам. Если слева от слэша стоит ключевое слово `auto-flow`, то для свойства `grid-auto-flow` буде
Такое свойство 🤷‍♀️

2021-02-16 09:14 UTC, pepelsbey commented on src/posts/css/doka/grid.md
> +- [ auto-flow && dense? ] `grid-auto-rows`? / `grid-template-columns` — задаёт конкретные размеры колонкам. Если слева от слэша стоит ключевое слово `auto-flow`, то для свойства `grid-auto-flow` буде
Я к тому, что ценность такого примера очень низкая — он мало что объясняет. Это синтаксис из спецификации или с MDN, а мы вроде стремимся понятно объяснить.

Я бы тут отдельно описал свойства (список сильно упростится) и потом отдельно описал бы значения для каждого свойства под заголовками. Иначе получется очень плотный и сложный список, который не помогает.

2021-02-18 18:55 UTC, solarrust commented on src/posts/css/doka/grid.md
> +- [ auto-flow && dense? ] `grid-auto-rows`? / `grid-template-columns` — задаёт конкретные размеры колонкам. Если слева от слэша стоит ключевое слово `auto-flow`, то для свойства `grid-auto-flow` буде
Вынесла в отдельную задачу чтоб не тормозить слияние: #568

2021-02-18 18:57 UTC, solarrust commented on src/posts/css/doka/grid-template.md
> +🛠 В этом же свойстве можно задавать значение и для свойства `grid-template-areas`, но тогда код превращается в кашу и становится совершенно нечитабельным, на мой взгляд. Лучше всё же использовать это
```suggestion
🛠 В этом же свойстве можно задавать значение и для `grid-template-areas`. Но, на мой взгляд, тогда код превращается в кашу и становится совершенно нечитабельным. Лучше всё же использовать это свойство отдельно:
```

2021-02-23 12:20 UTC, pepelsbey commented on src/posts/css/doka/grid-template.md
> +```
В маркдауне лучше чётко отбивать части: они так случайно не склеются и сразу по исходнику понятно, что тут будет сначала параграф, а потом блок кода.

````suggestion
Лучше так?

```css
.container {
  display: grid;
  grid-template:
    [row1-start] "header header header" 25px [row1-end]
    [row2-start] "footer footer footer" 25px [row2-end]
    / auto 50px auto;
}
```

Или так?

```css
.container {
  display: grid;
  grid-template:
    [row1-start] 25px [row1-end]
    [row2-start] 25px [row2-end]
    / auto 50px auto;
  grid-template-areas:
    "header header header"
    "footer footer footer";
}
```
````

2021-02-23 20:00 UTC, solarrust commented
@pepelsbey пинг

2021-02-24 09:10 UTC, pepelsbey approved these changes

2021-02-24 09:25 UTC, merged