Добавляет статью о техническом долге
Y-Doka/y-doka.site pull request #546
Opened 2021-02-15 16:42 UTC by bespoyasov

Закрывает https://github.com/Y-Doka/y-doka.site/issues/372.

2021-02-20 17:08 UTC, nlopin requested changes
Мне очень понравилась структура 👍

Мне кажется важным подчеркнуть, что работа с техдолгом имеет смысл только в проектах, которые будут работать и развиваться во времени. Нет смысла говорить о техдолге в проекте, который будет закрыт через месяц

2021-02-20 17:08 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +Можно принять волевое решение и переписать всё с нуля™️. Для этого придётся пройти много переговоров и договориться со всеми вокруг, что это действительно нужно и займёт столько-то времени.
```suggestion
Можно принять волевое решение и переписать всё с нуля™️. Для этого придётся пройти много переговоров и договориться со всеми вокруг, что это действительно нужно и займёт много времени.
```

2021-02-20 17:08 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +Можно принять волевое решение и переписать всё с нуля™️. Для этого придётся пройти много переговоров и договориться со всеми вокруг, что это действительно нужно и займёт столько-то времени.
я бы еще добавил, что даже плохая кодовая база хранит много знаний о бизнесе и краевых случаях. Всю эту информации при переписывании придется собирать заново и набивать шишки

2021-02-20 17:08 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +## Кратко
Получилось не кратко по теме, а введение к статье. Давай попробуем собрать самое важное в этом разделе. У нас уже есть «что», давай добавим абзац «зачем и как»: техдолг вредит проекту, с ним нужно работать — вовремя обновлять кодовую базу, добавлять тесты и переписывать устаревшие части.

2021-02-20 17:13 UTC, nlopin commented
@bespoyasov тема, конечно, щепетильная, поэтому мы много говорим про вероятности. Давай просмотрим статью и сделаем её чуть категоричнее, где это имеет смысл.

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +## Кратко
✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +При разработке программ часто не хватает времени на всё, что хотелось бы сделать. Разработчикам приходится выбирать самые важные задачи и делать в первую очередь их. Некоторые из оставшихся задач отн
✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +## Откуда взялась такая метафора
✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +Если мы изначально пишем всё в одном файле, вызываем как попало функции и непонятно называем сущности — это не технический долг, это плохо сделанная работа. Когда же нынешнее решение работает, но оно
Немного переписал ✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +### Неработоспособный продукт
Мне кажется, тут речь не о том. Проект в терминальной стадии больше похож на чёрный ящик: он как-то работает, но никто не знает, как.

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +### Закладывать время на то, чтобы сделать задачу без долга
Переписал ✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +Делать всё сразу сложно и долго. Поэтому в сроки можно закладывать большое количество времени на работу, связанную с задачей. Не всегда руководство будет согласно с таким сроком, поэтому стоит...
Дописал ✅

2021-02-21 14:28 UTC, bespoyasov commented on src/posts/js/long/technical-debt.md
> +### Добавить регулярные итерации с «выплатой»
✅

2021-02-22 22:32 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +### Неработоспособный продукт
для меня это метафора «изменишь какую-то мелочь и все развалится»

2021-02-22 22:40 UTC, nlopin approved these changes
Вливаю

2021-02-22 22:40 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +Тесты делают рефакторинг кода менее болезненным — если тесты проходят, то рефакторинг ничего не сломал. Без тестов такой уверенности нет, и желание трогать код пропадает. Из-за этого долга можно стат
```suggestion
Тесты делают рефакторинг кода менее болезненным — если тесты проходят, то рефакторинг ничего не сломал. Без тестов такой уверенности нет, и желание трогать код пропадает. Из-за этого долга может стать ещё больше.
```

2021-02-22 22:40 UTC, nlopin commented on src/posts/js/long/technical-debt.md
> +Бывают проекты, где о техническом долге не вспоминают годами. Например, разработчики могли не обновлять зависимости, и теперь все зависимости устарели на несколько мажорных версий. Обновление такого
```suggestion
Бывают проекты, где о техническом долге не вспоминают годами. Например, разработчики не обновляли зависимости, и теперь все зависимости устарели на несколько мажорных версий. Обновление такого проекта будет невероятно затратным.
```

2021-02-22 22:41 UTC, merged