Дописывает документацию про обложки и пустые поля
Y-Doka/y-doka.site pull request #550
Opened 2021-02-16 09:35 UTC by furtivite

В #534 мы добавили возможность использовать обложки в статьях. Нужно добавить информацию об этом в документацию. 

Дополнительно описать правило, которое хочет ввести @pepelsbey в #545.

2021-02-16 11:55 UTC, pepelsbey requested changes

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +summary: <!-- теги для работы поиска -->
```suggestion
summary: <!-- ключевые слова для работы поиска -->
```

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +  - align-content
Я бы сократил список, это всё-таки документация, здесь важно передать идею.

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +  mobile: 'mobile.png' <!-- адрес картинки для мобильной обложки -->
```suggestion
  desktop: 'desktop.png' <!-- адрес широкой картинки для десктопной обложки -->
  mobile: 'mobile.png' <!-- адрес узкой картинки для мобильной обложки -->
```

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +Используйте нужные поля там, где это необходимо. Если вы не хотите заполнять какое-либо поле, не оставляйте его пустым, а просто удалите его (#545).
```suggestion
Используйте поля только там, где это необходимо. Если вам нечем заполнить поле — удалите его, не оставляйте его пустым.
```

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +В #534 в Доке появилась возможность добавлять к статьям обложки. Выглядят они вот так:
```suggestion
К статье можно добавить обложку (хиро-картинку), которая предваряет контент:
```
Я бы не писал в документации новости (теперь появилось) и не ссылался на то как и почему появилось (пулреквесты, задачи). Нам важно кратко зафиксировать текущие возможности системы.

2021-02-16 11:55 UTC, pepelsbey commented on CONTRIBUTING.md
> +Используйте обложки там, где это необходимо.
```suggestion
Если вы хотите добавить обложку, призовите дизайнера и вам помогут её сделать.
```
Мы ведь так хотим, а не картинки со стоков?

2021-02-16 11:55 UTC, pepelsbey commented on EXAMPLE_article.md
> +  alt: Альтернативное описание для обложки
Шаблон не подсказывает формат записи полей (кавычки, название файла), у должен бы:

```suggestion
cover:
  desktop: 'desktop.png'
  mobile: 'mobile.png'
  alt: 'Альтернативное описание для обложки'
```

2021-02-16 11:55 UTC, pepelsbey commented on EXAMPLE_long-read.md
> +  alt: Альтернативное описание для обложки
```suggestion
cover:
  desktop: 'desktop.png'
  mobile: 'mobile.png'
  alt: 'Альтернативное описание для обложки'
```

2021-02-16 11:59 UTC, furtivite commented on CONTRIBUTING.md
> +В #534 в Доке появилась возможность добавлять к статьям обложки. Выглядят они вот так:
Почему-то показалось, что это имеет смысл. Оказалось — нет.

2021-02-16 12:03 UTC, furtivite commented on CONTRIBUTING.md
> +  - align-content
Согласен, убрал большую часть.

2021-02-16 12:03 UTC, pepelsbey commented on CONTRIBUTING.md
> +В #534 в Доке появилась возможность добавлять к статьям обложки. Выглядят они вот так:
Если хочется вести список изменений, то можно завести отдельный файл. Но я пока не придумал, зачем :)

2021-02-16 22:58 UTC, nlopin commented on CONTRIBUTING.md
> +Если вы хотите добавить обложку, призовите дизайнера и вам помогут её сделать.
Не actionable предложение. Как мне призвать дизайнера?

2021-02-16 22:58 UTC, nlopin commented on CONTRIBUTING.md
> +#### Обложки
я бы добавил рекомендации по альтернативному описанию обложки в поле `alt`

2021-02-17 06:23 UTC, furtivite commented on CONTRIBUTING.md
> +Если вы хотите добавить обложку, призовите дизайнера и вам помогут её сделать.
@nlopin @pepelsbey может заменим на «позовите [кого-нибудь из мейнтейнеров](https://github.com/Y-Doka/y-doka.site/blob/master/CODEOWNERS), мы закажем картинку у дизайнера»? Просто раз наши дизайнеры не на гитхабе, чтобы точно было к кому обращаться на случай, если это прочтут внешний авторы, ну или пусть на почту пишут, не знаю.

2021-02-17 06:28 UTC, nlopin commented on CONTRIBUTING.md
> +Если вы хотите добавить обложку, призовите дизайнера и вам помогут её сделать.
Да, так лучше

2021-02-17 13:13 UTC, pepelsbey commented on CONTRIBUTING.md
> +#### Обложки
У нас картинки не только в обложках, я бы сфокусировал рекомендации про альты в одном месте, а не писал это здесь. В общем, это отдельная задача.

2021-02-17 13:14 UTC, pepelsbey approved these changes

2021-02-22 17:06 UTC, pepelsbey approved these changes

2021-02-23 19:54 UTC, merged