Добавляет статью про transform-function
Y-Doka/y-doka.site pull request #572
Opened 2021-02-20 06:42 UTC by ezhkov

Закрывает #169

2021-02-23 19:45 UTC, solarrust reviewed
Мощно 🔥

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +title: "<transform-function>"
Почему тут треугольные скобочки? 0_0

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +co-authors:
Тоже давай потрём пустые поля

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +title: "<transform-function>"
UPD: поняла причину. Но если это не отдельное свойство, а набор значений, то может так и назовём «Функции CSS-трансформации»?

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +Функция трансформации указывается в качестве значения для свойства [`transform`](/css/doka/transform) и служит для дополнительных модификаций визуального представления элемента.
Кажется можно проще. Что-то в ключе «только так трансформация работает».

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +Часто бывает необходимо каким-то образом трансформировать визуальное представление элемента (масштабировать, повернуть, переместить) и при этом никак не затронуть соседние элементы в документе. Для п
```suggestion
Часто бывает необходимо каким-то образом трансформировать визуальное представление элемента (масштабировать, повернуть, переместить) и при этом никак не затронуть соседние элементы в документе. Для подобных преобразований используется свойство [`transform`](/css/doka/transform). В качестве значения выступают различные функции трансформации: `rotate`, `translate`, `scale`, `skew` и другие.
```

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +Функция используется для смещения элемента вверх-вниз или влево-вправо. В целом, ту же работу выполняют CSS-свойства `left`, `top`, `right`, `bottom` (далее - `LTRB`), но есть ряд важных отличий. `LT
```suggestion
Функция используется для смещения элемента вверх-вниз или влево-вправо. В целом, ту же работу выполняют CSS-свойства `left`, `top`, `right`, `bottom` (далее - **LTRB**), но есть ряд важных отличий. `LTRB` позиционируют элемент относительно соответствующих сторон родителя. То есть, `left: 20px` сместит элемент на 20 пикселей относительно левой границы родителя, а `translate(20px)` смещает элемент вправо относительно того места, где элемент находился до трансформации. В целом, `LTRB` и `translate` прекрасно сочетаются друг с другом. `LTRB` лучше использовать для изначального позиционирования элемента на странице, а `translate` применять, если нужно добавить анимации движения.
```

2021-02-23 19:45 UTC, solarrust commented on src/posts/css/doka/transform-function.md
> +Если нужно сместить элемент по всем трём осям, можно всё собрать в кучку и использовать эту функцию.
Не стоит ли тут упомянуть про `transform-style`?

2021-02-24 15:27 UTC, ezhkov commented on src/posts/css/doka/transform-function.md
> +Если нужно сместить элемент по всем трём осям, можно всё собрать в кучку и использовать эту функцию.
Не думаю. Трансформации не зависят напрямую от этого свойства. Использование перспективы гораздо важнее

2021-02-24 15:51 UTC, solarrust commented
@pepelsbey загляни и сюда

2021-02-25 10:40 UTC, pepelsbey requested changes
Кажется тут стоит упомянуть про [отдельные свойства](https://webkit.org/blog/11420/css-individual-transform-properties/) типа `rotate: 45deg`, которые позволяют задавать трансформации отдельно.

Также будет полезно рассказать про порядок применения трансформаций: внутри `transform-function` им можно управлять (показать зачем это может быть нужно), а если использовать отдельные свойства, то он будет зашит.

2021-02-25 10:40 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +Трансформации к элементу применяются при помощи свойства [`transform`](/css/doka/transform). А значением для этого свойства являются `функции трансформации`.
«функции трансформации» это не код, не надо их в бэктики :)

```suggestion
Трансформации к элементу применяются при помощи свойства [`transform`](/css/doka/transform). А значением для этого свойства являются функции трансформации.
```

2021-02-25 10:40 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +Функция используется для смещения элемента вверх-вниз или влево-вправо. В целом, ту же работу выполняют CSS-свойства `left`, `top`, `right`, `bottom` (далее - **LTRB**), но есть ряд важных отличий. `
Стоит ли нам придумывать новые термины? Свойства top, right, bottom, left конечно выполняют свою работу, но делают это только если элемент спозиционирован. То есть это позиционирование.

```suggestion
Функция используется для смещения элемента вверх-вниз или влево-вправо. В целом, ту же работу выполняют CSS-свойства `top`, `right`, `bottom`, `left` — например, для абсолютно (`position: absolute`) или относительно (`position: relative`) спозиционированных элементов. Но есть ряд важных отличий: элемент позиционируется относительно соответствующих сторон родителя. То есть, `left: 20px` сместит элемент на 20 пикселей относительно левой границы родителя, а `translate(20px)` смещает элемент вправо относительно того места, где элемент находился до трансформации. В целом, позиционирование и `translate` прекрасно сочетаются друг с другом. Позиционирование лучше использовать для изначального расположения элемента на странице, а `translate` применять, если нужно добавить анимации движения.
```

2021-02-25 10:40 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +Функция принимает два параметра: первый параметр отвечает за смещение вправо-влево, а второй параметр — вверх-вниз. Если передать только один параметр, тогда смещение будет только вправо-влево. Мы мо
Кажется важнее указать совсем разные единицы измерения, пиксели и ремы слишком похожи. И это хороше место, чтобы рассказать, относительно чего посчитаются эти 50%.

```suggestion
Функция принимает два параметра: первый параметр отвечает за смещение вправо-влево, а второй параметр — вверх-вниз. Если передать только один параметр, тогда смещение будет только вправо-влево. Мы можем использовать любые единицы измерения расстояния из CSS, например, абсолютные `10px` или относительные `50%`.
```

2021-02-25 10:40 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +Несмотря на то, что экран плоский, у нас всё равно есть возможность перемещать элемент вдоль оси `Z`. Она направлена перпендикулярно плоскости экрана в сторону пользователя. Если мы используем `trans
```suggestion
Несмотря на то, что экран плоский, у нас всё равно есть возможность перемещать элемент вдоль оси `Z`. Она направлена перпендикулярно плоскости экрана в сторону пользователя. Если мы используем `translateZ` просто так, то никакого перемещения ближе или дальше мы не увидим. Чтобы было ощущение движения к нам или от нас, элемент должен становиться крупнее или мельче. Стул, который стоит рядом с нами, будет визуально крупнее, чем стул, стоящий в конце комнаты. Эта разница в размерах — следствие _перспективы_. Элемент на экране может вести себя подобно объектам в реальном мире и менять размер при перемещении к нам или от нас. Чтобы это заработало, нужно элементу задать свойство [`perspective`](/css/doka/perspective). Это свойство необходимо применять при любых трансформациях, выходящих из плоскости экрана.
```

2021-03-04 19:40 UTC, pepelsbey commented
@solarrust я сделал ревью и по нему пока правки не внесли (или не ответили, что «нет»).

2021-03-04 20:00 UTC, solarrust commented
> @solarrust я сделал ревью и по нему пока правки не внесли (или не ответили, что «нет»).

Фальстарт 😅

2021-03-05 06:25 UTC, ezhkov commented
> @solarrust я сделал ревью и по нему пока правки не внесли (или не ответили, что «нет»).

Да, я пока собираюсь с мыслями. Тегну, как будет готово :)

2021-03-11 17:07 UTC, ezhkov commented
> Кажется тут стоит упомянуть про [отдельные свойства](https://webkit.org/blog/11420/css-individual-transform-properties/) типа `rotate: 45deg`, которые позволяют задавать трансформации отдельно.
> 
> Также будет полезно рассказать про порядок применения трансформаций: внутри `transform-function` им можно управлять (показать зачем это может быть нужно), а если использовать отдельные свойства, то он будет зашит.

@pepelsbey Добавил всё, кроме "показать, зачем это может быть нужно". Не придумал ситуацию. Мне кажется анимация в демке раскрывает принцип и порядок применения функций.

2021-03-15 10:35 UTC, solarrust commented
@pepelsbey приходи =)

2021-03-15 18:58 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +### Функции искажения
Давайте подберём перевод, который лучше передаёт суть? Skew это не совсем искажение, это у него есть определённые правила и можно найти [среди синонимов](https://www.multitran.com/m.exe?s=skew&l1=2&l2=1) подходящее. Мне кажется, что «наклон» довольно близко.

2021-03-23 17:20 UTC, ezhkov commented on src/posts/css/doka/transform-function.md
> +### Функции искажения
Да, «искажение» не очень. Мне кажется, «сдвиг» немного более точный, потому что skewY не создаёт эффект наклона.

2021-03-29 11:12 UTC, solarrust commented
@pepelsbey пинг?

2021-03-29 11:58 UTC, pepelsbey commented on src/posts/css/doka/transform-function.md
> +### Функции искажения
Проблема в том, что сдвиг — это `translate`, он как раз сдвигает элемент. Со сдвигом приходится объяснять, что это сдвиг сторон относительно друг друга. И это не очень интуитивно.

Призову @tachisis, чтобы обсудить варианты. Оля, что скажешь: как лучше перевести skew, чтобы передать суть происходящего? Были версии:

- Искажение: не передаёт сути трансформации
- Наклон: недостаток в том, что наклон влево-вправо понятен, а вверх-вниз не очень
- Сдвиг: недостаток в том, что приходится объяснять: сдвиг (сторон относительно друг друга)

Может есть среди [синонимов](https://www.multitran.com/m.exe?s=skew&l1=2&l2=1) что-то получше?

2021-03-29 12:51 UTC, tachisis commented on src/posts/css/doka/transform-function.md
> +### Функции искажения
Я посмотрела, как принято переводить это название свойства/инструмента в рунете, и в основном переводят как «наклон». В том числе в [официальной руссификации](https://helpx.adobe.com/ru/photoshop/using/transforming-objects.html) такого распространенного инструмента, как Photoshop. Думаю, при относительной равнозначности вариантов нам тоже следует выбрать перевод «наклон» как наиболее устоявшийся в вебе и около, ничего страшного про вверх-вниз (ну и кстати отражает, вверх-вниз тоже формирует наклоны, представьте себе дорогу в горку).

2021-03-29 14:58 UTC, ezhkov commented on src/posts/css/doka/transform-function.md
> +### Функции искажения
Спасибо, тогда остановимся на «наклоне» :)

2021-03-29 23:03 UTC, pepelsbey approved these changes

2021-03-30 08:17 UTC, solarrust approved these changes

2021-03-30 08:17 UTC, merged