Добавляет статью про transform-style
Y-Doka/y-doka.site pull request #578
Opened 2021-02-22 08:01 UTC by ezhkov

Закрывает #181

2021-02-23 19:22 UTC, solarrust commented on src/posts/css/doka/transform-style.md
> +<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="css,result" data-user="ezhkov" data-slug-hash="vYyeZmv" style="height: 265px; box-sizing: border-box; display: flex; align
Было бы космически заставить куб крутиться. Но можно это вынести в задачку по оформлению демки. Дай знать как удобнее.

2021-02-23 19:22 UTC, solarrust commented on src/posts/css/doka/transform-style.md
> +```
1. Стоит упомянуть, что свойство не наследуется.
2. Имеет смысл упомянуть, что без `transform` оно особого смысла не имеет.

2021-02-23 19:22 UTC, solarrust commented on src/posts/css/doka/transform-style.md
> +Свойство `transform-style` определяет, как будут вести себя потомки элемента в 3d-пространстве.
```suggestion
Свойство `transform-style` определяет, как будут вести себя потомки элемента в 3d-пространстве при трансформации.
```

Может быть так?

2021-02-24 14:36 UTC, ezhkov commented on src/posts/css/doka/transform-style.md
> +```
1. Добавил
2. По умолчанию значение `flat`, так что оно в любом случае будет задано) Пусть даже неявно

2021-02-24 15:50 UTC, solarrust commented
@pepelsbey приходи

2021-02-24 21:30 UTC, pepelsbey requested changes

2021-02-24 21:30 UTC, pepelsbey commented on src/posts/css/doka/transform-style.md
> +Свойство `transform-style` определяет, как будут вести себя потомки элемента в 3d-пространстве при трансформации.
Кажется корректнее будет писать 3D, [см. Википедию](https://ru.wikipedia.org/wiki/3D).

```suggestion
Свойство `transform-style` определяет, как будут вести себя потомки элемента в 3D-пространстве при трансформации.
```

2021-02-24 21:30 UTC, pepelsbey commented on src/posts/css/doka/transform-style.md
> +Допустим, есть родительский элемент, у которого есть потомки. Если задать родительскому элементу свойство `transform-style` со значением `preserve-3d`, то это позволит применять к дочерним элементам
```suggestion
Допустим, есть родительский элемент, у которого есть потомки. Если задать родительскому элементу свойство `transform-style` со значением `preserve-3d`, то это позволит применять к дочерним элементам нормальные 3D-трансформации. При нормальных 3D-трансформациях дочерний элемент сможет, допустим, при повороте пересечь родительский элемент. Если задать значение `flat`, то дочерние элементы всегда будут лежать в плоскости родителя и не смогут пересечь его ни при каких поворотах, масштабировании и прочих условиях.
```

2021-02-24 21:30 UTC, pepelsbey commented on src/posts/css/doka/transform-style.md
> +Получается, что при `transform-style: preserve-3d` каждый дочерний элемент получает независимую от родителя плоскость, к которой можно применять 3d-трансформации. При `transform-style: flat` существу
```suggestion
Получается, что при `transform-style: preserve-3d` каждый дочерний элемент получает независимую от родителя плоскость, к которой можно применять 3D-трансформации. При `transform-style: flat` существует ровно одна плоскость — плоскость родителя, и никакие трансформации не могут заставить дочерний элемент выйти из этой плоскости.
```

2021-02-24 21:30 UTC, pepelsbey commented on src/posts/css/doka/transform-style.md
> +🛠 Если нам нужно просто повернуть какой-то элемент в 3d-пространстве, то можно оставить `transform-style: flat` (либо вообще не задавать это свойство). Элемент всё равно будет поворачиваться, к нему
```suggestion
🛠 Если нам нужно просто повернуть какой-то элемент в 3D-пространстве, то можно оставить `transform-style: flat` (либо вообще не задавать это свойство). Элемент всё равно будет поворачиваться, к нему будет применяться перспектива, всё будет выглядеть красиво. `transform-style: preserve-3d` нужно задавать, когда мы хотим применять 3D-трансформации и к родителю, и к потомкам, и при этом учитывать их визуальное взаимодействие. Классическим примером такой ситуации является куб, собранный из шести элементов-сторон.
```

2021-02-24 21:30 UTC, pepelsbey commented on src/posts/css/doka/transform-style.md
> +```
````suggestion
```css
.parent {
  transform-style: flat; /* По умолчанию */
  transform-style: preserve-3d;
}
```

Глобальные значения:

```css
.parent {
  transform-style: inherit;
  transform-style: initial;
  transform-style: unset;
}
```
````

2021-03-04 19:41 UTC, pepelsbey approved these changes

2021-03-04 20:00 UTC, solarrust approved these changes

2021-03-04 20:00 UTC, merged