Добавляет статью про Docker
Y-Doka/y-doka.site pull request #582
Opened 2021-02-23 22:14 UTC by igsekor

Сделал первую статью про Docker. Вверху в разделе "Кратко" есть список кейсов, предлагаю его пункты использовать для перекрестных ссылок на другие статьи в Доке по теме Docker и не только.

2021-02-25 22:32 UTC, nlopin requested changes
Мне очень понравилась стартовая выжимка и направление мысли — рассказать о базовых понятиях.

Со стороны материала у нас всё есть, он очень хорошо структурирован, но мы сейчас не попадаем в аудиторию. Наша аудитория — студенты и начинающие разработчики без технического багажа за плечами. Если дать им сухую выжимку, то им будет сложно самим соединить точки и разобраться.

Представь, что ты встретил друга в баре и ему надо объяснить, что такое докер. Мы точно будем использовать минимум терминов и упрощать (СУБД → база данных). Чтобы шло еще легче, нужна история, повествование. Дополнительно мы отсыпем иллюстраций и схем, чтобы ментальная модель сложилась (у нас есть иллюстратор в команде).

Думаю мы решили рассказать слишком многое в таком коротком материале. Предлагаю сосредоточиться на ответе на вопрос «зачем это нужно?» и создании ментальной модели «как это работает» (образ → контейнер + может задеть тему образ на основе другого образа) 

Вот еще несколько упрощений на обсудить: 
* не углубляться в детальное описание служб. Сейчас очень детально написано про виртуализацию, LXC. Много терминов. Нужно объяснить высокоуровнево, что это такие виртуальные операционки внутри вашей, и дать ссылку на место, где можно копать вглубь.
* вынести работу с томами в отдельный материал, где мы объясним, что такое «том» и зачем нам ими управлять

Еще нужно развернуть `details` в заголовки. Мы стараемся минимально использовать html в текстах статей + лучше показать весь объем статьи сразу

2021-02-25 22:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +[Установите Docker на свой компьютер](https://docs.docker.com/engine/install/) (хост). Вы также можете поиграть с Docker в [песочнице](https://labs.play-with-docker.com). После запуска Docker в систе
Нужно точнее сказать, что ставить:
![image](https://user-images.githubusercontent.com/1469636/109224954-eeddc380-77bc-11eb-945a-2341e7b6aa17.png)

2021-02-25 22:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +[Установите Docker на свой компьютер](https://docs.docker.com/engine/install/) (хост). Вы также можете поиграть с Docker в [песочнице](https://labs.play-with-docker.com). После запуска Docker в систе
В песочнице мне не удалось поиграться без регистрации 🤷‍♂️ (у меня есть регистрация, но я играю роль новичка)

2021-02-25 22:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +После загрузки образа, сборки и запуска контейнера на его основе, вы можете открыть в браузере стартовую документацию Docker по адресу [http://localhost](localhost). Готовое веб-приложение — наиболее
```suggestion
После загрузки образа, сборки и запуска контейнера на его основе, вы можете открыть в браузере стартовую документацию Docker по адресу [http://localhost](http://localhost). Готовое веб-приложение — наиболее популярный кейс использования.
```

2021-02-25 22:40 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Docker — это технология, которая позволяет создавать и использовать приложения в изолированном окружении. В основе Docker лежит амбициозная идея: если работает у вас, будет работать где угодно.
Подумал, что это такой «компьютер в вакууме»

2021-02-25 22:50 UTC, nlopin commented
Почти все идеи мы рассказываем либо сильным упрощением в начале, либо постановкой проблемы через пример с последующим решением:
* высокоурвнево абстрактые идеи, такие как [API](https://y-doka.site/js/long/api/)
* с объяснения проблемы, как в статье [об асинхронности в JS](https://y-doka.site/js/long/async-in-js/) или [о версиях языка/транспайлерах](https://y-doka.site/js/long/language-versions/)

2021-02-26 14:47 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Docker — это технология, которая позволяет создавать и использовать приложения в изолированном окружении. В основе Docker лежит амбициозная идея: если работает у вас, будет работать где угодно.
Надо бы переписать. Действительно, странновато(

2021-02-26 14:47 UTC, igsekor commented on src/posts/js/tools/docker.md
> +[Установите Docker на свой компьютер](https://docs.docker.com/engine/install/) (хост). Вы также можете поиграть с Docker в [песочнице](https://labs.play-with-docker.com). После запуска Docker в систе
Уточню в новой редакции

2021-02-26 14:48 UTC, igsekor commented on src/posts/js/tools/docker.md
> +[Установите Docker на свой компьютер](https://docs.docker.com/engine/install/) (хост). Вы также можете поиграть с Docker в [песочнице](https://labs.play-with-docker.com). После запуска Docker в систе
Песочницу без регистрации надо бы найти, наверное. Хотя самая простая такая песочница – свой комп.

2021-02-27 07:30 UTC, igsekor commented
Примерная мысль того, что можно изобразить на первом рисунке (ментальная модель).

![mental-map](https://user-images.githubusercontent.com/13916521/109378816-97d40d80-78e6-11eb-8996-520694654648.png)

2021-02-27 09:11 UTC, nlopin requested changes
Стало хорошо, думаю еще итерация и мы закончим!

У нас еще есть опциональный раздел «В работе», где можно поделиться какими-нибудь штуками из опыта. Я бы туда унес информацию, что образы могут быть только на основе Linux. Может еще что=то придет в голову

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Хранение образов в [Docker Hub](https://hub.docker.com/) осуществляется с помощью службы [Docker Registry](https://docs.docker.com/registry/). Существуют и другие публичные реестры образов:
Давай предпочитать активный залог пассивному:

```suggestion
Опубликованные образы хранятся в [Docker Hub](https://hub.docker.com/). Существуют и другие публичные реестры образов:
```

Еще убрал ссылку на registry, потому что там о том, как развернуть реестр самому. Думаю, это усложнение. Если читатель на том уровне, то он будет читать официальную доку

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Официальные образы Docker, которые постоянно обновляются самой компанией, являются относительно безопасными. Для фронтенд-разработчика могут быть интересны:
```suggestion
Предпочитайте официальные образы Docker, которые обновляются самой компанией. Они являются относительно безопасными. Для фронтенд-разработчика могут быть интересны:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Консольный клиент содержит ряд команд для управления объектами Docker. Список основных команд можно прочитать в документации:
```suggestion
Консольный клиент содержит команды для управления объектами Docker. Список основных команд:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Ключи командного интерфейса Docker CLI хорошо проработаны, имеют подобное поведение с точностью до функции. Например, дополнительный ключ `prune` позволяет удалять неиспользуемые объекты. Ключ `rm` с
«с точностью до функции» скорее непонятно, чем понятно :(

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Если вы хотите увидеть не только запущенные в настоящий момент контейнеры, но и уже остановленные, необходимо использовать ключ `-a`:
```suggestion
Если хотите увидеть не только запущенные в настоящий момент контейнеры, но и уже остановленные, используйте ключ `-a`:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Если список запущенных в настоящий момент контейнеров или уже остановленных слишком большой, можно использовать ключ `-f` для фильтрации. Например, для фильтрации списка запущенных контейнеров по име
```suggestion
Если список запущенных контейнеров слишком большой, то можно использовать ключ `-f` для фильтрации. Например, для фильтрации списка запущенных контейнеров по именам, содержащим hello, выполните команду:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Запуск контейнеров;
```suggestion
### Запуск контейнеров
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Мониторинг запущенных контейнеров;
```suggestion
### Мониторинг запущенных контейнеров
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Для запуска контейнера, который доступен локально или на Docker Hub, необходимо выполнить команду:
```suggestion
Для запуска контейнера, который доступен локально или на Docker Hub, выполните команду:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Ключ `--name` используется для установки имени запущенного контейнера. Ключи -i и -t указывают, что для запуска контейнера будет использоваться [стандартный поток ввода](https://ru.wikipedia.org/wiki
```suggestion
Ключ `--name` используется для установки имени запущенного контейнера. Ключи -i и -t указывают, что для запуска контейнера будет использоваться [стандартный поток ввода](https://ru.wikipedia.org/wiki/Стандартные_потоки) и [терминал TTY](https://ru.wikipedia.org/wiki/TTY-абстракция) соответственно. Для того чтобы при запуске контейнера примонтировать том, который будет связан с папкой на вашем компьютере, а потом получить доступ к контейнеру через терминал, выполните команду:
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Управление контейнерами;
```suggestion
### Управление контейнерами
```

2021-02-27 09:11 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Управление томами.
```suggestion
### Управление томами
```

2021-02-27 09:45 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Docker — это технология, которая позволяет создавать и использовать приложения в "родном" окружении. В основе Docker лежит прогрессивная идея: если приложение работает у вас, оно будет работать где у
Круто! :) Очень рад!

2021-02-27 09:47 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Для начала необходимо установить Docker. Для Mac и Windows необходимо установить специальные приложения [Docker Desktop for Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac/) и [D
Ок. Почему бы и нет?

2021-02-27 09:48 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Docker чаще всего применяется для разработки, тестирования и развертывания серверных приложений, но может использоваться и в мире фронтенда:
Ну можно и так.

2021-02-27 09:51 UTC, igsekor commented on src/posts/js/tools/docker.md
> +После запуска Docker можно проверить его работоспособность с помощью графического интерфейса [Dashboard](https://docs.docker.com/desktop/dashboard/) (для Mac или Windows) или команды в терминале (для
Ня слишком осторожничаю. Согласен.

2021-02-27 09:52 UTC, igsekor commented on src/posts/js/tools/docker.md
> +У создателей Doсker есть готовая демка, которую можно запустить следующим образом:
Ну да :)

2021-02-27 09:59 UTC, igsekor commented on src/posts/js/tools/docker.md
> +### Мониторинг запущенных контейнеров;
Упс

2021-02-27 12:04 UTC, igsekor commented on src/posts/js/tools/docker.md
> +1. Docker нашел в реестре Docker Hub и загрузил приложение с именем `docker/getting-started`. Приложение уже было заботливо "упаковано" со всеми необходимыми ему утилитами и программами. Эта самая уп
Образ – это окружение с приложением внутри.

Рецепт – это Dockerfile. Так что, наверное, стоит оставить как есть.

2021-02-27 16:31 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Ключи командного интерфейса Docker CLI хорошо проработаны, имеют подобное поведение с точностью до функции. Например, дополнительный ключ `prune` позволяет удалять неиспользуемые объекты. Ключ `rm` с
Думаю, что лучше просто удалить. Суть не меняется.

2021-02-27 16:31 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Перед тем, как готовить упаковку приложения, необходимо пройтись по терминам, договориться лучше на берегу 😎.
Заменил. Стало лучше, кажется.

2021-02-27 16:46 UTC, igsekor commented on src/posts/js/tools/docker.md
> +2. Docker собрал контейнер (Docker Container) на основе образа.
Попробовал подыскать.

2021-02-27 17:05 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Готовое веб-приложение — наиболее популярный кейс использования. Демка Docker — самое простое, что можно сделать "из коробки". Вам не пришлось устанавливать и запускать веб-сервер, не пришлось разбир
Попробовал добавить кейс "Как было раньше". Может так?

2021-02-27 17:08 UTC, igsekor commented
Не думаю, что нужно уводить столько важный акцент в конец. Когда я только знакомился с Docker. Меня это ввело в заблуждение. А новичков, мне кажется, это серьезно озадачит. Они могут подумать, что виртуальные машины им больше не нужны. Но нет.

Однако идея с примером мне нравится. Можно попробовать что-то упаковать.

2021-02-27 21:01 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Готовое веб-приложение — наиболее популярный кейс использования. Демка Docker — самое простое, что можно сделать "из коробки". Вам не пришлось устанавливать и запускать веб-сервер, не пришлось разбир
ты не запушил? 

не вижу изменений не только тут, но и ниже по тексту. Например, в пункте 2 объяснения про `docker run`

2021-02-28 21:32 UTC, nlopin requested changes
последние штрихи 👨‍🎨

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Готовое веб-приложение — наиболее популярный кейс использования. Демка Docker — самое простое, что можно сделать "из коробки". Вам не пришлось устанавливать и запускать веб-сервер, не пришлось разбир
```suggestion
Запуск готового веб-приложения — наиболее популярный сценарий использования. Демка Docker — самое простое, что можно сделать "из коробки". Вам не пришлось устанавливать и запускать веб-сервер, не пришлось разбираться с настройками чего-либо, вы не трудились устанавливать у себя [Node.js](/js/tools/nodejs-tooling) и не столкнулись с какими-либо сложностями. Представьте, что вы передали проект другому разработчику и вам не приходится возиться с тем, чтобы проект запускался, не приходится говорить: "А у меня все работало 😞".
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Ситуация была бы еще сложнее, если бы у вас и другого разработчика операционные системы были бы разными. С Docker все намного проще! Вы создаете один раз конфигурацию. Она работает у вас, она работае
```suggestion
Ситуация будет еще сложнее, если вы и другой разработчик используете разные операционные системы. С Docker все намного проще! Вы создаете конфигурацию, и если она работает у вас, то заработает у всех.
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Вам нужно упаковать свое приложение так, чтобы счастлив был любой, кто его получит 😇. Давайте разберемся, что должен делать Docker с вашим приложением, какое окружение он должен подготовить?
```suggestion
Docker упаковывает приложение так, что будет счастлив любой, кто его получит 😇. Давайте разберемся, как это происходит. Что должен делать Docker с вашим приложением, какое окружение он должен подготовить?
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Разберемся с демкой от создателей Docker. Когда вы выполнили команду `docker run`, произошло следующее (показано на рисунке):
```suggestion
Рассмотрим пример с демкой от создателей Docker. Когда вы выполнили команду `docker run`, произошло следующее (показано на рисунке):
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +1. Docker нашел в реестре Docker Hub и загрузил приложение с именем `docker/getting-started`. Приложение уже было заботливо "упаковано" со всеми необходимыми ему утилитами и программами. Такая упаков
```suggestion
1. Docker нашел и загрузил приложение с именем `docker/getting-started` из реестра приложений Docker Hub . Приложение уже было заботливо "упаковано" со всеми необходимыми ему утилитами и программами. Такая упаковка называется _образ_ (Docker Image). Образ содержит в себе операционную систему на базе Linux, стартовую конфигурацию для установки служб, утилит, приложений, зависимостей проекта — все это называется окружением приложения.
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Перед тем, как готовить образ, необходимо пройтись по терминам. Договориться лучше на берегу 😎.
```suggestion
Перед тем, как мы научимся готовить образ, необходимо пройтись по терминам. Договориться лучше на берегу 😎.
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +**Движок Docker Engine** — приложение для управления объектами Docker и включает в себя три компонента: сервер(Docker Daemon), интерфейс(Docker API) и консольный клиент(Docker CLI).
```suggestion
**Движок Docker Engine** — приложение для управления объектами Docker. Оно включает в себя три компонента: сервер(Docker Daemon), интерфейс(Docker API) и консольный клиент(Docker CLI).
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Подобных образов достаточно много на [Docker Hub](https://hub.docker.com). Например, есть целый набор интересных от [gameprogressive](https://hub.docker.com/u/gameprogressive). Но есть среди всего мн
а чем они интересны? я зашел по ссылке и там образы без описаний

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Работа с движками сайтов
```suggestion
### Попробовать движок сайта без установки
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Работа с движками сайтов
в этом разделе классно давать четкие заголовки юзкейса, чтобы можно было быстро просмотреть

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Можно поиграть и с популярными CMS (Content Management System). CMS — это веб-приложение, которое позволяет управлять содержимым сайта и внешним видом через веб-интерфейс. Чтобы такое приложение рабо
```suggestion
Иногда нам нужно посмотреть, как работает та или иная CMS (Content Management System). CMS — это веб-приложение, которое позволяет управлять содержимым сайта и внешним видом через веб-интерфейс. Чтобы такое приложение заработало, нужно установить базу данных, веб-сервер и интерпретатор языка, на котором написана CMS. Но можно и ничего не устанавливать! Docker позволяет запустить CMS одной командой. После запуска вы сможете работать с CMS через веб-интерфейс в своем браузере или через терминал, если понадобится доступ к файлам и ресурсам приложения. Существуют официальные образы Wordpress и Drupal.
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Фронтенд-разработчику Docker дает возможность попробовать разные технологии без траты времени на установку и настройку чего-либо. Например, упаковать свое приложение на платформе [Node.js](/js/tools/
```suggestion
Фронтенд-разработчику Docker дает возможность попробовать разные технологии без траты времени на установку и настройку. Например, упаковать свое приложение на платформе [Node.js](/js/tools/nodejs) в контейнер не составит большого труда. Добавьте в проект файл Dockerfile:
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Точка в конце означает, что образ собирается из текущей папки. Именем конфигурационного файла по умолчанию является Dockerfile. После ключа `-t` вы можете задать имя образа:
```suggestion
Точка в конце означает, что образ собирается из текущей папки. По умолчанию для сборки используется файл с именем Dockerfile. После ключа `-t` можно задать имя образа:
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Вы можете начать проект на Angular.js, React.js или Vue.js, полностью переместив разработку внутрь контейнера. Популярные редакторы так или иначе поддерживают эту возможность. Такой подход позволит у
```suggestion
Вы можете начать проект на Angular.js, React.js или Vue.js, полностью переместив разработку внутрь контейнера. Популярные редакторы так или иначе поддерживают эту возможность. Такой подход позволит учитывать все особенности и тонкости настройки проекта не только вам, как автору, но и тем, кто будет работать с проектом в будущем. 

Не бойтесь, что каждый образ, каждая настройка будут занимать много места. Переиспользование — благо, от которого не уходят и разработчики Docker. Все слои образа, которые уже есть на вашем компьютере, будут переиспользованы. Тем не менее, за образами и контейнерами нужно следить, чтобы хранилище не разрасталось, а оперативная память не заканчивалась. Все это можно настроить с помощью [установки ограничений](https://docs.docker.com/config/containers/resource_constraints/).
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Приложение на Node.js
```suggestion
### Попробовать новый фреймворк
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +### Инструменты в контейнере
```suggestion
### Готовить картинки и другие ресурсы
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Вы можете поработать с картинками, воспользовавшись `imagemagick`. Например, чтобы изменить размеры картинки, нужно выполнить команду:
```suggestion
С помощью образа `imagemagick` можно работать с картинками. Например, чтобы изменить размеры картинки, выполните команду:
```

2021-02-28 21:32 UTC, nlopin commented on src/posts/js/tools/docker.md
> +Вам необходимо поработать со шрифтами? Например, для очень популярного инструмента `glyphhanger` есть готовый контейнер. С помощью Docker, вы можете запускать эту утилиту командой:
```suggestion
Необходимо поработать со шрифтами? Например, для очень популярного инструмента `glyphhanger` есть готовый образ. С помощью Docker, можно запускать эту утилиту командой:
```

2021-03-01 08:57 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Готовое веб-приложение — наиболее популярный кейс использования. Демка Docker — самое простое, что можно сделать "из коробки". Вам не пришлось устанавливать и запускать веб-сервер, не пришлось разбир
Звучит теперь лучше! :)

2021-03-01 08:57 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Ситуация была бы еще сложнее, если бы у вас и другого разработчика операционные системы были бы разными. С Docker все намного проще! Вы создаете один раз конфигурацию. Она работает у вас, она работае
Класс!

2021-03-01 08:58 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Вам нужно упаковать свое приложение так, чтобы счастлив был любой, кто его получит 😇. Давайте разберемся, что должен делать Docker с вашим приложением, какое окружение он должен подготовить?
Намного легче стало!

2021-03-01 08:58 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Разберемся с демкой от создателей Docker. Когда вы выполнили команду `docker run`, произошло следующее (показано на рисунке):
И правда, так лучше.

2021-03-01 08:59 UTC, igsekor commented on src/posts/js/tools/docker.md
> +1. Docker нашел в реестре Docker Hub и загрузил приложение с именем `docker/getting-started`. Приложение уже было заботливо "упаковано" со всеми необходимыми ему утилитами и программами. Такая упаков
Ох уж этот порядок. Стало лучше!

2021-03-01 09:00 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Вы можете начать проект на Angular.js, React.js или Vue.js, полностью переместив разработку внутрь контейнера. Популярные редакторы так или иначе поддерживают эту возможность. Такой подход позволит у
Это правильно!

2021-03-01 09:01 UTC, igsekor commented on src/posts/js/tools/docker.md
> +### Приложение на Node.js
Понял

2021-03-01 09:02 UTC, igsekor commented on src/posts/js/tools/docker.md
> +### Инструменты в контейнере
Намного понятнее

2021-03-01 09:02 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Вы можете поработать с картинками, воспользовавшись `imagemagick`. Например, чтобы изменить размеры картинки, нужно выполнить команду:
Ну так тоже можно. Попроще стало.

2021-03-01 09:03 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Вам необходимо поработать со шрифтами? Например, для очень популярного инструмента `glyphhanger` есть готовый контейнер. С помощью Docker, вы можете запускать эту утилиту командой:
Так лучше

2021-03-01 09:04 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Перед тем, как готовить образ, необходимо пройтись по терминам. Договориться лучше на берегу 😎.
Отлично!

2021-03-01 09:04 UTC, igsekor commented on src/posts/js/tools/docker.md
> +**Движок Docker Engine** — приложение для управления объектами Docker и включает в себя три компонента: сервер(Docker Daemon), интерфейс(Docker API) и консольный клиент(Docker CLI).
Да. Мои обрывки вариантов написания(

2021-03-01 09:05 UTC, igsekor commented on src/posts/js/tools/docker.md
> +### Работа с движками сайтов
Ну я понял.

2021-03-01 09:05 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Можно поиграть и с популярными CMS (Content Management System). CMS — это веб-приложение, которое позволяет управлять содержимым сайта и внешним видом через веб-интерфейс. Чтобы такое приложение рабо
Наверное, так лучше. Согласен.

2021-03-01 09:06 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Фронтенд-разработчику Docker дает возможность попробовать разные технологии без траты времени на установку и настройку чего-либо. Например, упаковать свое приложение на платформе [Node.js](/js/tools/
Ну да. Лишнее.

2021-03-01 09:07 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Точка в конце означает, что образ собирается из текущей папки. Именем конфигурационного файла по умолчанию является Dockerfile. После ключа `-t` вы можете задать имя образа:
Согласен.

2021-03-01 09:10 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Подобных образов достаточно много на [Docker Hub](https://hub.docker.com). Например, есть целый набор интересных от [gameprogressive](https://hub.docker.com/u/gameprogressive). Но есть среди всего мн
Надо бы найти, может, лучше пример. Эти образы интересны тем, что моделируют старые устройства. Например PSP. Можно просто убрать, к делу это не относится. К сожалению, я не нашел образов этого типа с нормальным описанием. Уж не знаю, почему из не делают нормально. Может, чтобы не прибили их?

2021-03-01 09:33 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Подобных образов достаточно много на [Docker Hub](https://hub.docker.com). Например, есть целый набор интересных от [gameprogressive](https://hub.docker.com/u/gameprogressive). Но есть среди всего мн
Думаю, что можно вообще заменить просто любопытными для фронтендера репозиториями. Например, есть всякие образы для оценки перформанса или тот же Lighthouse. Что думаете?

2021-03-01 10:22 UTC, igsekor commented on src/posts/js/tools/docker.md
> +Подобных образов достаточно много на [Docker Hub](https://hub.docker.com). Например, есть целый набор интересных от [gameprogressive](https://hub.docker.com/u/gameprogressive). Но есть среди всего мн
Вот примерный список кандидатов:
1. [nginx](https://hub.docker.com/_/nginx)
2. [httpd (Apache)](https://hub.docker.com/_/httpd)
3. [mongo-express](https://hub.docker.com/_/mongo-express)
4. [Sentry](https://hub.docker.com/_/sentry)
5. [sonarqube](https://hub.docker.com/_/sonarqube)
6. [lighthouse](https://hub.docker.com/r/femtopixel/google-lighthouse)

2021-03-02 18:30 UTC, nlopin approved these changes

2021-03-02 18:33 UTC, pepelsbey commented
Почитаю сегодня вечерком, если не против :)

2021-03-02 19:06 UTC, nlopin commented
@pepelsbey давай, присылай замечания

2021-03-02 21:14 UTC, pepelsbey requested changes

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +```
```suggestion
- `docker volume ls` — вывод всех томов.
- `docker volume ls -f name=hello` — вывод всех томов с фильтрацией по имени, например, `hello`.
- `docker volume create hello` — cоздание нового тома, например, `hello`.
- `docker volume inspect hello` — исчерпывающая информация о томе.
```

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +```
Лучше допустить сборку по умолчанию, а не комментировать

````suggestion
```bash
FROM node:12

# Создание директории приложения
WORKDIR /app

# Установка зависимостей, учитывая package.json и package-lock.json
COPY package*.json ./

RUN npm i

# Сборка проекта, если есть необходимость
RUN npm ci --only=production

# Копирование исходного кода приложения
COPY . .

EXPOSE 8080
CMD [ "node", "app.js" ]
```
````

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +Вы можете начать проект на Angular.js, React.js или Vue.js, полностью переместив разработку внутрь контейнера. Популярные редакторы так или иначе поддерживают эту возможность. Такой подход позволит у
```suggestion
Вы можете начать проект на Angular, React или Vue, полностью переместив разработку внутрь контейнера. Популярные редакторы так или иначе поддерживают эту возможность. Такой подход позволит учитывать все особенности и тонкости настройки проекта не только вам, как автору, но и тем, кто будет работать с проектом в будущем.
```

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +
```suggestion

```

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +Необходимо поработать со шрифтами? Например, для очень популярного инструмента `glyphhanger` есть готовый образ. С помощью Docker, можно запускать эту утилиту командой:
```suggestion
Необходимо поработать со шрифтами? Например, популярный инструмент [glyphhanger](https://github.com/filamentgroup/glyphhanger) требует нетривиальной установки. Но есть готовый Docker-образ и с его помощью, можно запустить эту утилиту командой:
```

2021-03-02 21:14 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +С помощью образа `imagemagick` можно работать с картинками. Например, чтобы изменить размеры картинки, выполните команду:
```suggestion
С помощью утилиты [ImageMagick](https://imagemagick.org/) можно работать с картинками в консоли. Вы можете установить её на свой компьютер или использовать готовый образ. Например, чтобы изменить размеры картинки, выполните команду:
```

2021-03-02 21:17 UTC, pepelsbey commented on src/posts/js/tools/docker.md
> +Docker — это технология, которая позволяет создавать и использовать приложения в "родном" окружении. В основе Docker лежит идея: если приложение работает у вас, то оно должно работать где угодно. Спо
```suggestion
Docker — это технология, которая позволяет создавать и использовать приложения в «родном» окружении. В основе Docker лежит идея: если приложение работает у вас, то оно должно работать где угодно. Способ этого добиться очень простой — нужно упаковать настройки окружения вместе с приложением.
```

2021-03-02 21:33 UTC, igsekor commented
Спасибо, Ник и Вадим! Все правки по делу. Постепенно вникаю.

2021-03-03 07:29 UTC, nlopin commented
@igsekor кажется докер стал поддерживать windows образы. Я наткнулся на [целый раздел в докер хабе](https://hub.docker.com/_/microsoft-windows-base-os-images)

2021-03-03 07:52 UTC, igsekor commented
@nlopin  Спасибо за наводку! Давай тогда допишу кусочек и про них, где про поддержку ОС. Вообще это дичь и убивает саму идею. Беда в том, что они работают только на Windows, переносимости нет даже внутри Windows ([ссылка на документацию](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-20H2%2Cwindows-10-20H2)). Чтобы они работали на Windows нужно вообще переключить окружение. Одновременно использовать Linux и Windows контейнеры нельзя. Я слышал про то, что Microsoft эту тему развивает, но работает это скверно. Хотя указать в документации стоит. Упустил из виду.

2021-03-03 08:39 UTC, nlopin commented
Давай тогда не будем писать про них, а уберем утверждение, что это всегда линукс. Напишем что-то в стиле "обычно это линукс"

2021-03-04 09:19 UTC, pepelsbey commented
Красота! Дождёмся небольшого обновления картинки и будем мёржить :)

2021-03-09 10:30 UTC, pepelsbey approved these changes

2021-03-09 10:35 UTC, merged