Добавляет статью про CSS-правило
Y-Doka/y-doka.site pull request #595
Opened 2021-02-26 08:15 UTC by solarrust

Закрывает #72 

Мёрджить после переноса статьи про комбинированные селекторы

2021-02-26 11:03 UTC, solarrust commented
@pepelsbey чекни эту статью, пожалуйста

2021-03-01 12:06 UTC, pepelsbey requested changes
Поправил ссылки и стиль написания списков, у нас больше распространён через дефисы (и они ближе на клавиатуре).

2021-03-01 12:06 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +Селекторы можно разным образом комбинировать между собой. Подробнее в статье про [комбинированные селекторы](/combined-selectors/).
```suggestion
Селекторы можно разным образом комбинировать между собой. Подробнее в статье про [комбинированные селекторы](/css/doka/combined-selectors/).
```

2021-03-01 12:06 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +* После каждого CSS-правила оставляйте пустую строку.
```suggestion
- Если перечисляете несколько селекторов, ставьте каждый из них на новую строку.
- После селектора перед открывающей фигурной скобкой ставьте пробел.
- Каждую пару свойство-значение пишите с новой строки.
- Свойства внутри фигурных скобок отбивайте от начала строки табом или двумя пробелами в зависимости от принятого стиля кода в вашей команде.
- После каждого CSS-правила оставляйте пустую строку.
```

2021-03-01 12:06 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +* [селектор по атрибуту](/attribute-selector/).
```suggestion
- [универсальный селектор](/css/doka/TODO) (в работе);
- [селекторы по тегу](/css/doka/tag-selector/);
- [селектор по классу](/css/doka/class-selector/);
- [селектор по идентификатору](/css/doka/TODO) (в работе);
- [селектор по атрибуту](/css/doka/attribute-selector/).
```

2021-03-01 12:06 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +* значение.
```suggestion
- селектор;
- свойство;
- значение.
```

2021-03-01 12:13 UTC, solarrust commented on src/posts/css/doka/css-rule.md
> +* [селектор по атрибуту](/attribute-selector/).
Сложная у нас структура, каждый раз забываю как правильно ссылки на соседние материалы прописывать 😔

2021-03-01 14:45 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +* [селектор по атрибуту](/attribute-selector/).
Есть вариант: `../article-link`, он простой и не требует помнить структуру. То есть это ссылка на статью рядом :) Можно нормализовать все такие ссылки потом.

2021-03-02 17:28 UTC, solarrust commented
@pepelsbey final check, plz =)

2021-03-02 18:19 UTC, pepelsbey requested changes

2021-03-02 18:19 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +Чтобы CSS свойства применялись только к определённым блокам на странице их оборачивают в фигурные скобки. Таким образом их зона влияния ограничивается стоящим перед открывающей скобкой селектором.
По этой реплике возникает ощущение, что если написать вот так без селектора:

```css
color:red
```

То свойство `color` применится ко всем элементам на странице. Свойства группируют не для того, чтобы они применились к определённым элементам, а потому, что CSS синтаксически так устроен. Боюсь, это может запутать новичков. Кажется можно проще:

```suggestion
К селектору применятся свойства, сгруппированные в фигурных скобках. Один и тот же селектор может повторяться не один раз. За то, какие свойства в итоге применятся к элементу, отвечает каскад.
```

Добавил ещё мысль про каскад. Надо бы добавить в планы лонгрид про него.

2021-03-02 18:19 UTC, pepelsbey commented on src/posts/css/doka/css-rule.md
> +- Свойства внутри фигурных скобок отбивайте от начала строки табом или двумя пробелами в зависимости от принятого стиля кода в вашей команде.
Бывает, что и 4 пробела :)

```suggestion
- Свойства внутри фигурных скобок отбивайте от начала строки табом или пробелами в зависимости от принятого стиля кода в вашей команде.
```

2021-03-03 14:30 UTC, pepelsbey approved these changes

2021-03-03 14:53 UTC, merged