Добавляет статью про комбинированные селекторы
Y-Doka/y-doka.site pull request #596
Opened 2021-02-26 09:56 UTC by furtivite

2021-02-26 11:03 UTC, solarrust commented
@pepelsbey приходи посмотреть.

2021-03-01 11:53 UTC, pepelsbey requested changes
Текст пока очень черновой, по сравнению с нашими типичными:

- Блоки «В работе» оформлены по-другому и по-разному
- Название селекторов не всегда удачные, [см. словарь](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#selector)

@solarrust получается немного логнрид, может про каждый селектор рассказать отдельно? Можно будет потом и демок наделать, и есть чем дополнить.

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +  - "Combined selectors"
```suggestion
  - комбинированный
  - селектор
  - combined
  - selector
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Иногда при написании стилей мы хотим обратиться к селектору более точно, чем просто по имени класса или тега. Можно использоваться различные «комбинации», основываясь на взаимном расположении одного
```suggestion
Иногда при написании стилей мы хотим обратиться к селектору более точно, чем просто по имени класса или тега. Можно использоваться различные комбинации, основываясь на взаимном расположении одного элемента относительно другого в HTML.
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```css
````suggestion
Если нескольким селекторам нужно задать одно и то же правило, то можно написать длинно:

```css
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Группировка (.element1, .element2)
```suggestion
## Группировка: `.element1, .element2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```css
````suggestion
А можно перечислить все селекторы через запятую и написать всего одно CSS-правило:

```css
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +— это значит, что свойство применится для трёх типов селекторов:
```suggestion
Это значит, что свойство применится для трёх типов селекторов:
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +---
Мы сейчас группируем блоки «В работе» в конце и оформляем иначе. Так ведь, @solarrust?

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Потомки (.element1 .element2)
```suggestion
## Потомки: `.element1 .element2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Последовательность селекторов отражает «вложенность» — каждый следующий селектор должен обязательно находится на каком-то уровне вложенности предыдущего селектора.
```suggestion
Последовательность селекторов отражает вложенность — каждый следующий селектор должен обязательно находится на каком-то уровне вложенности предыдущего селектора.
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Получается, что даже «невинный» пробел уже имеет значение, выбирая селектор на любом уровне вложенности:
```suggestion
Получается, что даже невинный пробел уже имеет значение при выборе селектор на любом уровне вложенности:
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Объединение (.class1.class2)
```suggestion
## Объединение: `.class1.class2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```css
````suggestion
Код ниже нельзя редактировать по каким-то причинам:

```css
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Увеличим специфичность, чтобы переопределить правило, описанное в «нередактируемой части» и потому имеющее бо́льший «вес»:
```suggestion
Увеличим специфичность, чтобы переопределить правило, описанное в нередактируемой части и потому имеющее бо́льший вес:
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Вложенные (.element1 > .element2)
```suggestion
## Непосредственно вложенные: `.element1 > .element2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Последовательность селекторов отражает «вложенность» — селектор справа от оператора должен быть прямым потомком селектора из левой части:
```suggestion
Последовательность селекторов отражает непосредственную вложенность — селектор справа от оператора должен быть прямым потомком селектора из левой части:
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
К `h3.article__heading` стили для `article > h3` не применятся, т. к. прямой потомок `<article>` — `div.article__header`, а не `<h3>`:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +        прямой потомок article — div.article__header, а не h3 -->
```suggestion
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
В этом примере стили к заголовку применяться, потому что `<h3>` является прямым потомком `<article>`:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
И тут тоже всё в порядке — `<h3>` по-прежнему является прямым потомком `<article>`, потому что располагается на ближайшем уровне вложенности, хоть и следует после `div.article__header`:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +---
```suggestion
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Смежные (.element1 + .element2)
```suggestion
## Смежные: `.element1 + .element2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Селектор справа от `+` должен следовать в HTML сразу за селектором слева от `+`. Проще говоря правый селектор должен быть _соседом_ левого селектора.
```suggestion
Элемент справа от `+` должен следовать в HTML сразу за элементом слева от `+`. Проще говоря, правый элемент должен быть _соседом_ левого элемента, чтобы селектор сработал.
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
К этому не применится, т. к. перед `<input>` идёт `<p>`:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
При такой разметке стиль применится только к первому `<input>`, но не ко второму:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
И тут правило не сработает. `<label>` и `<input>` — на разных уровнях вложенности:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +```html
````suggestion
К первому `<li>` стили не применятся, поскольку перед ним нет другого `<li>`:

```html
````

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +---
```suggestion
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +## Последующие (.element1 ~ .element2)
```suggestion
## Последующие: `.element1 ~ .element2`
```

2021-03-01 11:53 UTC, pepelsbey commented on src/posts/css/doka/combined-selectors.md
> +Но сейчас при наведении курсора будут выделиться все элементы *после* (т. е. справа). Чтобы это «исправить», мы изменим порядок следования элементов с помощью CSS-свойства `direction: rtl`:
```suggestion
Но сейчас при наведении курсора будут выделиться все элементы _после_ (т. е. справа). Чтобы это исправить, мы изменим порядок следования элементов с помощью CSS-свойства `direction: rtl`:
```

2021-03-01 12:08 UTC, solarrust commented
@pepelsbey это старый материал, просто переносим из Ноушена. Потом разделим на отдельные статьи, пока что в таком виде.

2021-03-01 12:10 UTC, solarrust commented on src/posts/css/doka/combined-selectors.md
> +---
Если тут вынести блоки в работе в самый конец, то может потеряться мысль. Не считаешь так?

2021-03-01 12:47 UTC, solarrust commented
BTW, мы так и не определились с именованием статей про селекторы.

2021-03-02 18:21 UTC, pepelsbey approved these changes

2021-03-02 18:34 UTC, solarrust approved these changes

2021-03-02 18:34 UTC, merged