Добавляет статью про атрибут autocomplete
Y-Doka/y-doka.site pull request #599
Opened 2021-02-28 12:26 UTC by lenaryan

2021-03-01 11:35 UTC, solarrust commented
@lenaryan падает тест, где-то лишний пробел в конце строки закрался.

2021-03-01 14:39 UTC, pepelsbey commented
@lenaryan поставь себе плагин [EditorConfig](https://editorconfig.org/) в редактор, тогда тесты всегда будут зелёные :)

2021-03-02 15:21 UTC, solarrust reviewed
Крутое начало 👍

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +co-authors:
пустые поля убираем

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +Атрибут, при помощи которого форма заполняется в один клик - браузер всё сделает за вас.
```suggestion
Атрибут, при помощи которого форма заполняется в один клик — браузер подставит значения в соответствующие поля.
```

Чуть подробнее раскрываем магию _всего_ что сделает за нас браузер =)

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +Когда вы заполняете формы, браузер предлагает вам сохранять те или иные данные - логины, пароли, адреса и e-mail. При заполнении очередной формы браузер идёт в список сохранённой информации, выуживае
```suggestion
Когда вы заполняете формы, браузер предлагает вам сохранять те или иные данные — логины, пароли, адреса и e-mail. При заполнении очередной формы браузер идёт в список сохранённой информации, выуживает оттуда данные, которые требуются для этой формы, и вставляет в соответствующие поля.
```

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`on`  - разрешает автозаполнение; если есть дочерние элементы ввода - то для них тоже.
```suggestion
`on` — значение по умолчанию. Разрешает автозаполнение. Если задать для `<form>`, то сработает для всех вложенных элементов формы.
```

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`off` - отключает автозаполнение.
```suggestion
`off` — отключает автозаполнение.
```

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +Кроме элемента [&lt;form>](/html/doka/form), вы можете указать этот атрибут для любого поля, которое требует ввода данных - [&lt;input>](/html/doka/input), принимающий на вход текст или число, [&lt;s
```suggestion
Кроме элемента [`<form>`](/html/doka/form), вы можете указать этот атрибут для любого поля, которое требует ввода данных — [`<input>`](/html/doka/input), принимающий на вход текст или число, [`<select>`](/html/doka/select) или [`<textarea>`](/html/doka/textarea).
```

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +Первый [&lt;input>](/html/doka/input) унаследует значение от родительского элемента [&lt;form>](/html/doka/form) и не будет заполняться автоматически. Для второго [&lt;input>](/html/doka/input) уже б
```suggestion
Первый `<input>` унаследует значение от родительского элемента `<form>` и не будет заполняться автоматически. Для второго `<input>` уже будет работать автозамена, поскольку для него прописан `autocomplete="on"`.
```

Достаточно сослаться на соседнюю статью один раз в тексте, не обязательно делать это каждый раз =)

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +  - у элементов [&lt;input>](/html/doka/input), [&lt;select>](/html/doka/select) и [&lt;textarea>](/html/doka/textarea) были прописаны атрибуты `name` и/или `id`;
```suggestion
  - у элементов `<input>`, `<select>` и `<textarea> были прописаны атрибуты `name` или `id`;
```

Мы не используем / для перечислений

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +  - они были обёрнуты в тег [&lt;form>](/html/doka/form);
```suggestion
  - они были обёрнуты в тег `<form>`;
```

2021-03-02 15:21 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +  - сама форма имела кнопку отправки - [&lt;input>](/html/doka/input) или [&lt;button>](/html/doka/button) с атрибутом `type="submit"`.
```suggestion
  - сама форма имела кнопку отправки — `<input>` или `<button>` с атрибутом `type="submit"`.
```

Используй дефис, а не тире для разделения частей предложения. В маркдауне разница не видна, а вот на сайте очень даже

2021-03-02 19:00 UTC, lenaryan commented on src/posts/html/doka/autocomplete.md
> +co-authors:
я сделяль

2021-03-02 19:12 UTC, solarrust commented
@pepelsbey приходи

2021-03-03 14:41 UTC, pepelsbey requested changes
Даже если наша задача сейчас написать базовую статью, то обязательно нужно написать про остальные значения атрибута, которые позволяют подсказывать браузеру и расширениям, какие данные автозаполняются. Это дико удобно и мало распространено, хотя отлично работает.

- `autocomplete="given-name"`
- `autocomplete="tel"`
- `autocomplete="cc-number"`

[И так далее](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values).

2021-03-03 14:41 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +Когда вы заполняете формы, браузер предлагает вам сохранять те или иные данные — логины, пароли, адреса и e-mail. При заполнении очередной формы браузер идёт в список сохранённой информации, выуживае
Часто браузер ничего не предлагает, а просто запоминает это сам.

```suggestion
Когда вы заполняете формы, браузер сохраняет те или иные данные — логины, пароли, адреса и e-mail. При заполнении очередной формы браузер идёт в список сохранённой информации, выуживает оттуда данные, которые требуются для этой формы, и вставляет в соответствующие поля.
```

2021-03-03 14:41 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +<form autocomplete="on | off">...</form>
Лучше без псевдосинтаксиса, новички доверчивые. Строчкой ниже говорится про возможные значения.

```suggestion
<form autocomplete="on">...</form>
```

2021-03-03 14:41 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +  <button type=”submit”>Отправить</button>
Выглядит как ловушка, кавычки не те!

```suggestion
  <button type="submit">Отправить</button>
```

2021-03-03 14:41 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +  - сама форма имела кнопку отправки — `<input>` или `<button>` с атрибутом `type="submit"`.
```suggestion
🛠 Для правильного автозаполнения желательно, чтобы:

- у элементов `<input>`, `<select>` и `<textarea>` были прописаны атрибуты `name` или `id`;
- они были обёрнуты в тег `<form>`;
- сама форма имела кнопку отправки — `<input>` или `<button>` с атрибутом `type="submit"`.
```

2021-03-03 14:52 UTC, solarrust commented
Ещё про `"new-password"` и `"one-time-code"`

2021-03-03 14:59 UTC, pepelsbey commented
Их там много, да: описать зачем это нужно и дать полный список с минимальным описанием. Кстати, можно мельком про [псевдокласс `:autofill`](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill) сказать (и запланировать отдельную статью).

2021-03-03 15:01 UTC, solarrust commented
Те, что я предложила, очень полезны. 
Значение нового пароля позволяет сгенерить пароль при помощи менеджера паролей. 
Значение кода позволяет подставлять код из смсок на мобилках.

2021-03-04 09:07 UTC, pepelsbey commented
Да, я сам очень радуюсь, когда вижу такое на сайтах :) Но я бы одинаково хорошо расписал все значения: это наши задачи такие, а бывают и другие: написать адрес доставки на сайте, автозаполнить данные карты из менеджера паролей и т.п. То есть не фокусировался бы на «самых важных», они все важные )

2021-03-04 15:02 UTC, lenaryan commented
> Даже если наша задача сейчас написать базовую статью, то обязательно нужно написать про остальные значения атрибута, которые позволяют подсказывать браузеру и расширениям, какие данные автозаполняются. Это дико удобно и мало распространено, хотя отлично работает.
> 
> * `autocomplete="given-name"`
> * `autocomplete="tel"`
> * `autocomplete="cc-number"`
> 
> [И так далее](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values).

Окай, приняла

2021-03-15 10:48 UTC, solarrust reviewed
Далеко не все из перечисленных значений действительно пригождаются. Давай в первую очередь опишем те, что пригодятся нашим читателям, а ниже, под заголовком «Остальные значения» или что-то вроде перечислим остальные.

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +Атрибут `autocomplete` пишется внутри открывающего тега, и в кавычках прописывается его значение - `on` или `off`.
Этот исходный блок только с двумя значениями слегка диссонирует с блоком с остальными значениями, идущим ниже. Надо бы их как-то привести в согласие.

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`honorific-prefix` — звание или префикс для уважительного обращения, например, "Mrs.", "Mr.", "Miss", "Ms.", "Dr.", "Mlle.".
```suggestion
`honorific-prefix` — звание или префикс для уважительного обращения, например, «Mrs.», «Mr.», «Miss», «Ms.», «Dr.», «Mlle.».
```

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`given-name` — имя (первое имя).
В русском языке нет такого понятия как «первое имя» =)

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`additional-name` — второе имя.
… и второе имя тоже не применяется в русском языке

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`honorific-suffix` — окончание имени, например, "Jr.", "B.Sc.", "PhD.", "IV", "мл.".
```suggestion
`honorific-suffix` — окончание имени, например, «Jr.», «B.Sc.», «PhD.», «IV», «мл.».
```

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`email` — адрес email.
```suggestion
`email` — адрес электронной почты.
```

2021-03-15 10:48 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +🛠 При создании нового аккаунта или изменении пароля следует использовать `autocomplete="new-password"` для полей "Введите новый пароль" и "Подтвердите новый пароль", но не для поля "Введите текущий п
```suggestion
🛠 При создании нового аккаунта или изменении пароля следует использовать `autocomplete="new-password"` для полей «Введите новый пароль» и «Подтвердите новый пароль», но не для поля «Введите текущий пароль». Это сделано, чтобы случайно не вписать существующий пароль, а также предложить помощь в создании безопасного пароля.
```

2021-03-15 18:43 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +`additional-name` — второе имя.
Понятно, что нет, но в спецификации есть и кто-то будет разрабатывать англоязычные интерфейсы. Это нужно описать, просто подобрать этому подходящие названия.

2021-03-15 18:46 UTC, pepelsbey commented
Меня пока не звали, но тут дискуссия, а не ревью и я выскажусь :)

> Далеко не все из перечисленных значений действительно пригождаются

Мы всё-таки энциклопедия и тут полнота перечисленных значений играет роль. Если кто-то поймёт, что на MDN есть все значения, а у нас только некоторые — это ударит по нашей репутации.

Ну и я не согласен с фомулировкой: в сложной или специальной форме пригодятся все значения и все их нужно описать. Длинно, сложно, но очень полезно.

2021-03-15 19:13 UTC, solarrust commented
@pepelsbey а я и не предлагала удалить редкие значения, я предложила немного переформатировать список, вынеся вперёд те, за которыми придут с большей вероятностью, а ниже дать остальные.

2021-03-15 19:14 UTC, solarrust commented on src/posts/html/doka/autocomplete.md
> +`additional-name` — второе имя.
Мой комментарий предполагает как раз подбор более подходящего термина, понятного русскоязычному человеку. В конце предложения можно написать «в английском это обычно называют вторым / первым именем».

2021-03-15 23:48 UTC, pepelsbey commented on src/posts/html/doka/autocomplete.md
> +`additional-name` — второе имя.
Так стало понятнее, ложная тревога :)

2021-03-15 23:49 UTC, pepelsbey commented
@solarrust согласен, некоторые можно подсветить. Я бы только не делал это в списке — лучше бы он остался полным и алфавитным, чтобы там проще было найти нужное. А в примере можно показать самые употребимые. Что скажешь? :)

2021-04-06 21:07 UTC, pepelsbey approved these changes
Немного похозяйничал, чтобы сократить количество итераций:

- Добавил правильно инклюды с авторами и ник в мету
- Сделал из списка значений натуально список
- Спрятал большой список в экспандер

2021-04-06 21:54 UTC, solarrust approved these changes

2021-04-06 21:54 UTC, merged