Добавляет обзорную-вводную статью о тестировании
Y-Doka/y-doka.site pull request #604
Opened 2021-03-03 08:55 UTC by bespoyasov

Майлстоуна и ишьи для PR нет, поэтому ничего не закрывает.

2021-03-04 22:51 UTC, nlopin requested changes
Классно получилось!

Расскажи, почему решил сначала привести пример тестов, а потом говорить про виды?

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Тесты делают код прочнее и более живучим. Одновременно с этим тесты — это отличная документация, которая не врёт и не устаревает. Также тесты можно использовать, как инструмент при разработке програм
Может так?
```suggestion
Тесты делают код более прочным и живучим. Одновременно с этим тесты — это отличная документация, которая не врёт и не устаревает. Также тесты можно использовать, как инструмент при разработке программы.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +В идеале хотелось бы, чтобы при изменении кода теста, он перезапускался сам. Чтобы было место для описания того, что мы тестируем. Специально для этого придумали инструменты для тестирования.
```suggestion
В идеале хотелось бы, чтобы при изменении кода тест запускался сам. Чтобы было место для описания того, что мы тестируем. Специально для этого придумали инструменты для тестирования.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +describe('When given 2 numbers', () => {
давай похоливарим об описании. Может в дидактияеских целях напишем его по-русски?

Кстати, многие русские компании описывают тесты по-русски. Например, Контур

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +describe('When given 2 numbers', () => {
На англйском меня триггерит `should`. Не понимаю, зачем его используют, это какой-то мусор. Мы же не говорим «хотелось бы чтобы тест вернул сумму двух чисел». 

Гораздо четче «it returns the sum of 10 and 5»

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +1. На строчках 3–6 мы прогоняем собственно сам тест.
Может так? Для меня «прогоняем тест» — это про выполнение теста 🤷‍♂️ 

```suggestion
1. На строчках 3–6 программируем тест.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Функция [`expect`](https://jestjs.io/docs/en/expect#expectvalue) помогает нам избежать работы с ошибками напрямую, а также предоставляет удобные методы для сравнения аргументов друг с другом.
```suggestion
Функция [`expect`](https://jestjs.io/docs/en/expect#expectvalue) помогает избежать работы с ошибками напрямую и предоставляет удобные методы для сравнения аргументов друг с другом.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Теперь разберём собственно код теста.
```suggestion
Теперь разберём, собственно, код теста.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Сам тест состоит из 3 строк:
```suggestion
Наш тест состоит из 3 строк:
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Его можно разделить на 3 стадии: *Arrange*, *Act* и *Assert*.
Давай сделаем русскую мнемонику ППП. 

Может даже замутим ПВП? «Проведение» звучит страннее, чем «Выполнение»

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +### Arrange (Подготовка)
Тут тоже предлагаю выверуть — сначала русское слово, а в скобках английское

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Идеальный тест полностью *отражает 3-актную структуру*. Часто — такой тест даже состоит из 3 строчек.
> 3-актную

трехактную? первым шагом хочется развернуть, а вторым подумать, можно ли сказать то же самое, но проще

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +*Регрессия* — это ошибка, которая возникает после чего-то. Этим «чем-то» может быть добавление новой функциональности в старый код.
Вроде так?
```suggestion
*Регрессия* — это ошибка, которая возникает в уже работающей части системы после чего-то. Этим «чем-то» может быть добавление новой функциональности в старый код.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Более того, даже если мы уверены, что полностью знаем кусок, который рефакторим, мы не застрахованы от более простых ошибок:
```suggestion
Даже если мы уверены, что полностью знаем кусок, который рефакторим, мы не застрахованы от более простых ошибок:
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +В примере кода выше второй случай будет всегда истинным, потому что в условии вместо сравнения — присвоение. Тесты уберегут от подобных ошибок.
```suggestion
Второй случай в примере выше всегда будет истинным, потому что в условии вместо сравнения — присваивание. Тесты уберегут от подобных ошибок.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Чтобы не запутаться во всех фиктивных объектах и данных, для них нужно организовать структуру. Чем удобнее структура,  тем проще писать тесты.
```suggestion
Чтобы не запутаться во всех фиктивных объектах и данных, для них нужно организовать структуру. Чем удобнее структура, тем проще писать тесты.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Тесты, как правило, в проекте существуют вместе с автоматическими задачами, которые их запускают. Они, например, могут отменять релиз, если при обновлении кода тесты не проходят.
```suggestion
Тесты в проекте существуют,  как правило, вместе с автоматическими задачами, которые их запускают. Они, например, могут отменять релиз, если при обновлении кода тесты не проходят.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +*Интеграционные* тесты проверяют, как между собой взаимодействуют 2 и более части программы, которые работают над одной задачей (то есть как они интегрированы друг с другом, отсюда название).
```suggestion
*Интеграционные* тесты проверяют, как между собой взаимодействуют две и более части программы, которые работают над одной задачей (то есть как они интегрированы друг с другом, отсюда название).
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Такие тесты играют роль пользователей, которые ходят по приложению и выполняют разные задания. Для таких тестов тоже необходим фреймворк, который бы умел манипулировать приложением, как это делают лю
```suggestion
Такие тесты играют роль пользователей, которые ходят по приложению и выполняют разные задания. Для этих тестов тоже необходим фреймворк, который бы умел манипулировать приложением, как это делают люди.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Например, мы можем захотеть полностью проверить, как работает регистрация на сайте. Мы можем написать сценарий для «робота», который будет ходить по сайту, заполнять формы и проверять, как прошла рег
```suggestion
Например, мы захотели полностью проверить, как работает регистрация на сайте. Мы можем написать сценарий для «робота», который будет ходить по сайту, заполнять формы и проверять, как прошла регистрация.
```

2021-03-04 22:51 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Во фронтенд-разработке они встречаются реже всех остальных, но часто используются при разработке десктопных программ или приложений для телефонов. У таких приложений чуть более долгий цикл отправки д
```suggestion
Во фронтенд-разработке они встречаются реже всех остальных, но часто используются при разработке десктопных программ или приложений для телефонов. У таких приложений более долгий цикл доставки до пользователя, поэтому приёмочные тесты обычно проходят перед релизом. В вебе цикл поставки короткий, и тесты стараются максимально полно автоматизировать.
```

2021-03-04 22:53 UTC, nlopin commented
Попробуй еще в разделе «Плюсы тестирования» вынести слово «Тест» из подзаголовков. Станет ли лучше?

«Тесты решают проблемы при обновлении зависимостей» → «Решают проблемы при обновлении зависимостей» и т.д.

2021-03-08 10:30 UTC, bespoyasov reviewed
> Расскажи, почему решил сначала привести пример тестов, а потом говорить про виды?

Трудно говорить о видах того, чего мы ещё не видели 😃 

В целом, хотелось показать механику некого абстрактного теста перед тем, как показывать разницу в том, что проверяют разные тесты.

> Попробуй еще в разделе «Плюсы тестирования» вынести слово «Тест» из подзаголовков. Станет ли лучше?

С некоторыми ухищрениями да, стало лучше 🙂

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +В идеале хотелось бы, чтобы при изменении кода теста, он перезапускался сам. Чтобы было место для описания того, что мы тестируем. Специально для этого придумали инструменты для тестирования.
Не, тут легко спутать «код теста» и «код, который он тестирует». Я переписал.

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +describe('When given 2 numbers', () => {
> На англйском меня триггерит should. Не понимаю, зачем его используют, это какой-то мусор. Мы же не говорим «хотелось бы чтобы тест вернул сумму двух чисел».

Да, согласен. Переделал.

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +describe('When given 2 numbers', () => {
> давай похоливарим об описании. Может в дидактияеских целях напишем его по-русски?

Я не уверен, что это хорошая идея. 

Меня даже комиты с кириллицей коробят, а код тестов для меня такой же код, как любой другой код проекта. То есть писать описания тестов на русском — это как назвать переменную кириллицей 😃 

Объясню, почему. (Все причины исключительно вкусовщина, конечно.) 

1. Такие описания тестов заставляют постоянно скакать между раскладками. Если тестов много, это задалбывает, а иногда и сбивает с мысли.
2. Часто внутри описания приходится указывать сущности из кода (Emitter, Publisher, MessageBus, etc). То есть кириллица внутри описания будет снова перебиваться на латиницу, придётся думать о согласовании русских и английских слов. Это тоже дополнительная когнитивная нагрузка.
3. Я не встречал ни одного проекта, где описание тестов было бы написано кириллицей :–) 

Дискасс?

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +1. На строчках 3–6 мы прогоняем собственно сам тест.
Заменил на «выполняем». Напрограммировали мы тест задолго до этого 😃

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +Его можно разделить на 3 стадии: *Arrange*, *Act* и *Assert*.
✅

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +### Arrange (Подготовка)
✅

2021-03-08 10:30 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +Идеальный тест полностью *отражает 3-актную структуру*. Часто — такой тест даже состоит из 3 строчек.
Переписал.

2021-03-08 16:19 UTC, nlopin requested changes

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Инструментов для тестирования много. Чтобы подобрать подходящий, нам надо определиться, какие тесты мы хотим писать. Подробнее о видах тестирования мы поговорим в конце статьи, а пока что посмотрим н
Мне кажется, что мы тут скливаем два понятия: тестовый фреймворк и test runner.

Джест — это тест раннер и он напрямую не связан с фремворками. Он дает только обвязку и инструменты сравнения. Им можно запускать и юнит тесты, и pupeteer

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +describe('When given 2 numbers', () => {
Я тоже за английское описание тестов. Я не особо задумывался над аргументами, но все твои полностью разделаю. Хорошо, что обсудили

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Разберём по строкам.
```suggestion
Разберём по строкам:
```

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +На стадии проверки мы сверяем полученный результат с ожидаемым. Хотя проверка может состоять из нескольких утверждений, хорошей практикой считается *проверять внутри одного теста только одно предполо
Такая формулировка как мне кажется чуть лучше читается потому что подлежащее и сказуемое ближе. Но опционально:
```suggestion
На стадии проверки мы сверяем полученный результат с ожидаемым. Хотя проверка может состоять из нескольких утверждений, хорошей практикой считается *внутри одного теста проверять только одно предположение*.
```

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +*Регрессия* — это ошибка, которая возникает в уже работающей части системы после чего-то. Этим «чем-то» может быть добавление новой функциональности в старый код.
Меня с прошлого раза смущала формулировка. Как тебе вот эта?

```suggestion
*Регрессия* — это ошибка, которая возникает в уже работающей части системы после изменений в коде. Это может быть добавление новой функциональности в старый код или доработка общих функций.
```

2021-03-08 16:19 UTC, nlopin commented on src/posts/js/long/how-to-test-and-why.md
> +Инструментов для тестирования много. Чтобы подобрать подходящий, нам надо определиться, какие тесты мы хотим писать. Подробнее о видах тестирования мы поговорим в конце статьи, а пока что посмотрим н
Не знаю, стоит ли тут про это рассказывать 🤔

2021-03-09 05:12 UTC, bespoyasov commented on src/posts/js/long/how-to-test-and-why.md
> +Инструментов для тестирования много. Чтобы подобрать подходящий, нам надо определиться, какие тесты мы хотим писать. Подробнее о видах тестирования мы поговорим в конце статьи, а пока что посмотрим н
Переписал.

2021-03-09 06:01 UTC, nlopin approved these changes
LGTM

2021-03-09 06:01 UTC, merged