Добавляет демо к статье "Псевдоэлементы"
Y-Doka/y-doka.site pull request #607
Opened 2021-03-03 14:49 UTC by skorobaeus

Закрывает #254

2021-03-03 14:57 UTC, pepelsbey requested changes

2021-03-03 14:57 UTC, pepelsbey commented on src/demos/pseudoelements/header-veil.css
> +    no-repeat center / cover;
```suggestion
  background: #999999 url("/assets/images/posts/pseudoelements/background.svg") no-repeat center / cover;
```

2021-03-03 14:57 UTC, pepelsbey commented on src/demos/pseudoelements/header.css
> +    no-repeat center / cover;
```suggestion
  background: #999999 url("/assets/images/posts/pseudoelements/background.svg") no-repeat center / cover;
```

2021-03-04 07:37 UTC, solarrust commented
Привет! 👋
Пример для `:first-line`: не срабатывает `text-indent` в Safari =( https://cln.sh/4Fu6wY

В остальном кайф =)

2021-03-04 14:51 UTC, skorobaeus commented
> Пример для `:first-line`: не срабатывает `text-indent` в Safari =( https://cln.sh/4Fu6wY

@solarrust Оказалось, в сафари работает, только если задать блочному элементу. Убрала вообще, статья не про него)

2021-03-04 14:58 UTC, pepelsbey approved these changes

2021-03-04 17:15 UTC, solarrust approved these changes

2021-03-04 17:15 UTC, merged