Добавляет статью Cookie
Y-Doka/y-doka.site pull request #619
Opened 2021-03-07 05:48 UTC by igorkamyshev

fixes #484

Немного залип на статье 🤦‍♂️, решил отправить вариант текущий — накидайте пожалуйста идей как сделать лучше 🙏

2021-03-08 06:21 UTC, nlopin requested changes
Так как это формат доки, а не лонгрида, то давай подумаем, с какими вопросами сюда может попасть читатель.

Скорее всего, он пытается что-то сделать с куками, но не понимает. У нас почти все есть для него, мне нравится структура, но не хватает четкого описания формата (что можно у каки задать) и его превращения в строку.

Возможно стоит еще сказать, что точно не получится сделать или кейсы, где лучше не применять.

2021-03-08 06:21 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +При разработке сайтов часто возникает необходимость получать доступ до какой-то информации о пользователе как в браузере, так и на сервере. Для этого используют **Cookie** (произносится «куки»). Брау
Давай добавим пару конкретных случаев применения

2021-03-08 06:21 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Получить доступ до кук в браузере очень просто — нужно обратиться к глобальному объекту `document.cookie`. В этом объекте лежит строка специального формата.
```suggestion
Описание установленых кук хранится в `document.cookie`. В этом свойстве глобального объекта лежит строка специального формата.
```

2021-03-08 06:21 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Получить доступ до кук в браузере очень просто — нужно обратиться к глобальному объекту `document.cookie`. В этом объекте лежит строка специального формата.
Кажется это хорошая подводка описать, для раздела «Формат», где расскажем из чего состоит кука и напишем, как она хранится в виде строки

Затем уже рассказать как записывать, читать и удалять.

2021-03-08 06:21 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Чтобы в браузере установить новую куку, нужно записать специальную строку в `document.cookie`, например, так:
```suggestion
Установить новую куку, можно записав специальную строку в `document.cookie`, например, так:
```

2021-03-08 06:22 UTC, nlopin commented
Я пока не нырял в правки самих абзацев, это в следующей итерации

2021-04-10 10:26 UTC, akellbl4 commented
Мне кажется сейчас не хватает важных моментов:
- `HttpOnly` - тут разработчик может вырвать себе все волосы не понимая почему не может причитать куку.
- `Secure` - тут можно не понять почему-то она, есть то ее нет.
- `SameSite` -  это не обязательный параметр, но хром на него ругается если не ставить, так же он предотвращает XSS атаки, что тоже важно упомятуть.

2021-05-23 12:11 UTC, akellbl4 commented
@nlopin PR открыт из форка, и к сожалению, я не могу туда пушить и закончить доку в этом PR. Поэтому взял изменения и открыл новый PR #725. Этот можно закрывать.

2021-05-23 12:11 UTC, closed without merging