Добавляет статью про Dockerfile
Y-Doka/y-doka.site pull request #638
Opened 2021-03-10 13:40 UTC by igsekor

Это черновик. Пока размышляю о необходимости раздела "В работе". Жду замечаний и предложений :)

@nlopin @pepelsbey @valyabro

2021-03-10 15:20 UTC, ValyaBro approved these changes
картинка ок

2021-03-11 23:34 UTC, nlopin requested changes
Я начал смотреть, но еще утром просмотрю со свежей головой

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +[Docker](/js/tools/docker) создает образы на основе инструкций, которые записаны в простом текстовом файле. По умолчанию, такой текстовый файл с именем `Dockerfile` хранится в папке с проектом/прилож
```suggestion
[Docker](/js/tools/docker) создает образы на основе инструкций, которые записаны в простом текстовом файле. По умолчанию такой текстовый файл называют `Dockerfile` и хранят его в папке проекта. Инструкции содержат информацию об операционной системе, выбранной платформе, фреймворках, библитеках, инструментах, которые нужно установить.
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +В `Dockerfile` описывают настройку окружения, необходимого для работы проекта или приложения. Образ Docker легче всего представить в виде слоеного пирога или бургера: новый слой — новая инструкция. О
Кажется прыгнули с места в карьер. Давай добавим абзац с описанием проблемы, которую докерфайл решает,  и заодно сошлемся на базовую статью?

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Инструкции записываются в следующем формате:
```suggestion
Инструкции записываются построчно. На первом месте указывается команда, которую нужно выполнить, а затем — список аргументов этой команды:
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +
Давай добавим простой пример и построчно ниже разберем?

Сейчас мы показываем формат, а потом сразу же говорим про базовый образ. Непонятно, как мне соотнести с кодом выше :(

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Работу с `Dockerfile` можно разбить на два этапа: описание инструкций (директив) и сборка образа. Набор инструкций — определенная последовательность действий, образ — конкретная реализация окружения
```suggestion
Работу с `Dockerfile` можно разбить на два этапа: описание инструкций (директив) и сборка образа. Набор инструкций — последовательность действий, чтобы собрать образ.
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +В терминале будет выведена информация об образе в формате JSON. В частности, по ключу `"Size"` можно увидеть размер образа в байтах. Большое внимание в технологии Docker уделяется скорости сборки и р
```suggestion
В терминале будет выведена информация об образе в формате JSON. По ключу `"Size"` можно увидеть размер образа в байтах. Большое внимание в технологии Docker уделяется скорости сборки и размеру образов. Именно поэтому рекомендуется использовать наименьший образ операционной системы, который обеспечивает весь набор инструментов и служб, необходимый для запускаемого приложения. Практически стандартом стало использование Alpine Linux в качестве базовой операционной системы. В официальном репозитории образов Node.js есть образ и на основе этой операционной системы: `node:lts-alpine`.
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +В терминале будет выведена информация об образе в формате JSON. В частности, по ключу `"Size"` можно увидеть размер образа в байтах. Большое внимание в технологии Docker уделяется скорости сборки и р
я бы про Alpine утащил в раздел «в работе», где рассказать что такое alpine (есть еще slim сборки)

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +При этом директива `COPY` предпочтительна, поскольку улучшает понимание того, что происходит при сборке образа. `COPY` только копирует указанную папку во внутреннюю папку образа, в то время как `ADD`
```suggestion
Предпочитайте использовать `COPY`, она только копирует указанную папку во внутреннюю папку образа. В то время как `ADD` может выполнять ряд дополнительных функций, например, скачивание файла из Интернета перед копированием или разархивацию.
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +CMD ["node", "/app/app.js"]
думаю в тексте нужно сказать, что `CMD` не выполнится при сборке, а только при старте контейнера

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Для определения рабочей папки приложения пригодится директива `WORKDIR`, которая определит папку проекта. Тогда можно внести в конфигурацию правки:
Не смог хорошо сформулировать, но надо сказать, что все операции будут происходить относительно нее

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Важной директивой является установка пользователя `USER`, от имени которого исполняются команды. Например, если вы хотите запускать приложение от имени пользователя `node_user`, то конфигурационный ф
```suggestion
Если приложение нужно запускать от имени пользователя системы, то используйте директиву USER с именем пользователя. Например, если вы хотите запускать приложение от имени пользователя `node_user`, то конфигурационный файл будет выглядеть так:
```

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Это бывает особенно полезно, когда в образе находится база данных или используется удаленный доступ на основе SSH. Если есть необходимость пробросить запущенное веб-приложение через порт к `localhost
вот тут надо разворачивать

2021-03-11 23:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Передавать данные можно с помощью аргументов команды `docker build` на этапе сборки образа. Во время сборки эти аргументы можно использовать как переменные, достаточно их определить директивой `ARG`.
Опять давай пойдем от проблемы. Есть ситуации, когда мы не можем указать все значения в докерфайле, поэтому придумали возможность переопределять эти значения через консоль

2021-03-12 18:54 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +CMD ["node", "/app/app.js"]
Хорошее предложение

2021-03-12 19:00 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Для определения рабочей папки приложения пригодится директива `WORKDIR`, которая определит папку проекта. Тогда можно внести в конфигурацию правки:
Попробовал переформулировать

2021-03-12 19:00 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +В `Dockerfile` описывают настройку окружения, необходимого для работы проекта или приложения. Образ Docker легче всего представить в виде слоеного пирога или бургера: новый слой — новая инструкция. О
Переписал

2021-03-12 19:04 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +
Это была одна из редакций. Издержки копипаста. Переместил в нужное место.

2021-03-12 19:11 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Передавать данные можно с помощью аргументов команды `docker build` на этапе сборки образа. Во время сборки эти аргументы можно использовать как переменные, достаточно их определить директивой `ARG`.
Попробовал переформулировать.

2021-03-12 19:23 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Это бывает особенно полезно, когда в образе находится база данных или используется удаленный доступ на основе SSH. Если есть необходимость пробросить запущенное веб-приложение через порт к `localhost
Попробовал расшифровать.

2021-03-13 00:09 UTC, nlopin requested changes

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +### Рекомендации
Давай это перенесем в конец, чтобы не нарушать объявленную нами структуру: «Работу с `Dockerfile` можно разбить на два этапа: описание инструкций (директив) и сборка образа»

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +docker build [OPTIONS] PATH | URL | –
тут мне кажется мы проваливаемся в излишнюю точность. Давай сделаем подборку того, что используется. Я ни разу не видел сборку, которая использует урл или stdin. Какой случай применения у этого?

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +С помощью этой команды собираться образ будет из текущей папки (`.` в конце), в которой должен быть `Dockerfile`. Чтобы указать другое имя для файла конфигурации или относительный путь внутри `PATH`,
Давай подзаголовок добавим? что-то типа «Использовать Dockerfile с другим именем при сборке»

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Файлы и папки проекта, исполняемый файл приложения, архив или репозиторий [Git](/js/tools/version-control) составляют `контекст` образа. Но Docker позволяет собирать образы без `контекста` из стандар
когда это может пригодиться?

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Если вам не нужно включать в образ какие-то папки или файлы из `контекста`, можно использовать файл исключений `.dockerignore`. В этом файле перечисляются в отдельных строках все пути или маски путей
Давай добавим заголовок

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Все объекты Docker обязательно имеют имя. Если оно не назначается пользователем, то в качестве имени используется хэш. Чтобы работать с образами было удобнее, лучше выбирать имя. Кроме имени можно та
эта часть как-то резко появилась. Предлагаю утащить в раздел «В работе»

2021-03-13 00:09 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +**Установка базового образа**
Давай эти разделы построим по принципу «название команды. описание»?  так будет проще навигироваться.

Заодно добавил четвертый уровень заголовков. У него сейчас нет стилей, но они придут

```suggestion
#### `FROM`. Установка базового образа**
```

2021-03-13 08:39 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +`Dockerfile` — это текстовый файл, в котором описан процесс создания образа [Docker](/js/tools/docker).  Информация об операционной системе, выбранной платформе, фреймворках, библитеках, инструментах
Да, кажется стало лучше :)

2021-03-13 08:53 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Работу с `Dockerfile` можно разбить на два этапа: описание инструкций (директив) и сборка образа. Набор инструкций — последовательность действий, чтобы собрать образ.
Да может и правда сменить на инструкцию. Как-то это не по-русски просто. Ладно. Я за соответствие документации.

2021-03-13 08:55 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Вы можете загрузить к себе образ `node` командой:
Надо обозначить более явно. Связано это с выбором образа. Попробую четче обозначить мотив.

2021-03-13 09:06 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Обычно для запуска приложения используется именно массив строк команды и ее параметров, но можно использовать и обычную строку. Команда после директивы `CMD` будет выполняться после запуска контейнер
Формы для этой инструкции на самом деле три. Первая — массив. Вторая — массив, но без самой команды (используется в случае применения инструкции ENTRYPOINT выше). Третья — обычная команда терминала в виде строки. Тонкость есть. Выполнение команды первого типа не вовлекает терминал в обычном виде, т.е. используется вне контекста shell скриптов. Переменные окружения тоже не работают. Рекомендация использование первого типа команд является желанием обезопасить от выстрела себе в ногу при сборке образа. Для обычных команд терминала используется инструкция RUN. Эти инструкции явно разделены по смыслу: стадия при сборки (коммит), стадия запуска службы / приложения / сборки и пр. Можно про это написать. Что скажешь?

2021-03-13 09:07 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Для запуска веб-приложения на компьютере вы используете веб-сервер, запущенный локально. Обычно веб-приложение становится доступным по адресу `http://localhost:8080`. Цифры в конце означают порт, отк
Да. Картинка помогла бы. Нарисую.

2021-03-13 09:08 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Во время сборки образа не всегда удобно, а иногда даже опасно, описывать все параметры внутри `Dockerfile`, поскольку этот файл обычно доступен в репозитории большинству разработчиков. В случае публи
Тогда мы уходим от логики. Мы обозначаем проблему, потом описываем решение. Если эта логика нарушится, то не повлияет ли это на скорость и легкость восприятия?

2021-03-13 09:10 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +### Рекомендации
Это не процесс сборки. Это описание стадий сборки.

2021-03-13 09:18 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +С помощью этой команды собираться образ будет из текущей папки (`.` в конце), в которой должен быть `Dockerfile`. Чтобы указать другое имя для файла конфигурации или относительный путь внутри `PATH`,
Давай.

2021-03-13 09:22 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +docker build [OPTIONS] PATH | URL | –
Загрузка из Интернет архива, который сразу превращается в образ — хорошая альтернатива использованию реестра. Применяется, как правило, именно для этого. Вдруг своего сервера с реестром нет, репозиториев несколько (т.е. нельзя сделать их приватными, а контроль над менеджментом аккаунтов важно сохранить) и нет желания делать их публичными. Это выход. Это вопросы к инфраструктуре, но люди на практике могут столкнуться.

Сборка с STDIN применяется при сборке "на лету". Когда сборке можно подсовывать сгенерированный только что Dockerfile. Это все к DevOps скорее. Можно убрать, но тогда вряд ли люди с этим столкнуться и вообще не будут об этом знать. Думаю, что это знание полезно, поэтому и включил. Все таки документация. Но можем и избавится от подробностей.

2021-03-13 09:23 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Файлы и папки проекта, исполняемый файл приложения, архив или репозиторий [Git](/js/tools/version-control) составляют `контекст` образа. Но Docker позволяет собирать образы без `контекста` из стандар
Описал выше

2021-03-13 09:23 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Если вам не нужно включать в образ какие-то папки или файлы из `контекста`, можно использовать файл исключений `.dockerignore`. В этом файле перечисляются в отдельных строках все пути или маски путей
Хорошо

2021-03-13 09:24 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Все объекты Docker обязательно имеют имя. Если оно не назначается пользователем, то в качестве имени используется хэш. Чтобы работать с образами было удобнее, лучше выбирать имя. Кроме имени можно та
Можно и так

2021-03-13 10:21 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Уже на этапе клонирования образа вы увидите его размер. После скачивания и установки можно получить информацию об образе с помощью команды:
Ок

2021-03-13 10:23 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Директива `FROM` используется для описания образа, на основе которого формируется новый. В качестве базового образа может использоваться образ «чистой» операционный системы, как в примере выше, или у
Ок

2021-03-13 10:58 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +`Dockerfile` — это текстовый файл, в котором описан рецепт создания образа Docker.  Рецепт состоит из инструкций, которые выполняются последовательно. Они содержат информацию об операционной системе,
```suggestion
`Dockerfile` — это текстовый файл, в котором описан рецепт создания образа Docker. Рецепт состоит из инструкций, которые выполняются последовательно. Они содержат информацию об операционной системе, выбранной платформе, фреймворках, библитеках, инструментах, которые нужно установить.
```

2021-03-13 10:58 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Во время сборки образа не всегда удобно, а иногда даже опасно, описывать все параметры внутри `Dockerfile`, поскольку этот файл обычно доступен в репозитории большинству разработчиков. В случае публи
Ты прав. 

Давай вынесем название команды в заголовок. Так будет удобно сканировать статью и высокоруовнево понимать, нужно мне в этот раздел проваливаться или нет.

2021-03-13 10:58 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +docker build [OPTIONS] PATH | URL | –
Я про stdin способ не знал. 

Давай оставим, но описание упростим. Мне не очень нравится показывать сигнатуру команды `as-is` из документации. Сам всегда путаюсь как ее читать, новичку будет совсем непонятно. 

Может ее уберем, ведь ниже приводятся примеры с каждым конкретным случаем

2021-03-13 10:58 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Обычно для запуска приложения используется именно массив строк команды и ее параметров, но можно использовать и обычную строку. Команда после директивы `CMD` будет выполняться после запуска контейнер
Давай попробуем явно проговорить отличие CMD от RUN, мы в начале про это говорим неявно.

2021-03-13 17:26 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +Во время сборки образа не всегда удобно, а иногда даже опасно, описывать все параметры внутри `Dockerfile`, поскольку этот файл обычно доступен в репозитории большинству разработчиков. В случае публи
Ok

2021-03-13 19:20 UTC, igsekor commented
@ValyaBro новая картинка в статье. Решили, что так будет лучше.

2021-03-13 22:21 UTC, nlopin requested changes

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Инструкция `ENTRYPOINT` используется для запуска приложения при старте контейнера. Отличие от инструкции `RUN` заключается в том, что эта команда полностью получает доступ к инфраструктуре терминала
```suggestion
Инструкция `ENTRYPOINT` используется для запуска приложения при старте контейнера. В отличие от инструкции `RUN` эта инструкция получает полный доступ к инфраструктуре терминала на компьютере пользователя. Вместе с командой запуска контейнера вы можете передавать параметры команде, которая прописана после `ENTRYPOINT` или пользоваться системой [сигналов Linux](https://ru.wikipedia.org/wiki/Сигнал_(Unix)). Например, внутрь образа можно положить программу, которая проверяет орфографию текстов, и запускать ее внутри контейнера, передавая через параметры текстовые файлы со своего компьютера.
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +```bash
Пример не бьется с абзацем выше. Можно представить что app.js проверяет орфографию, но как передавать через параметры текстовые файлы? Давай это добавим

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +`CMD` выполняется только в том случае, если пользователь вашего образа не прописывает в явном виде, что делать после сборки. Обычно `CMD` используется не совсем для запуска приложения по умолчанию, а
давай вот этот абзац соединим с абзацем «Инструкция `CMD` делает правктически тоже самое...»

Получится классная структура: сначала про каждую из команд, а потом калаутом подчеркиваем, их отличие и даем рекомендацию

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Существует две формы записи аргументов инструкций `ENTRYPOINT` и `CMD`: в виде строки и в виде массива строк. Первый вариант (так называемый __shell__ режим) используется редко, поскольку не позволяе
```suggestion
Есть две формы записи аргументов `ENTRYPOINT` и `CMD`: в виде строки и в виде массива строк. Первый вариант (так называемый __shell__ режим) используется редко, поскольку не позволяет гибко настраивать работу образа. Обычно используется второй вариант (так называемый  __exec__ режим) — массив строк, который может состоять из команды и ее параметров. Среди аргументов инструкции `CMD` строка с командой может и отстутствовать, если эта инструкция идет после инструкции `ENTRYPOINT`. В этом случае строки массива рассматриваются как аргументы по умолчанию для команды, обозначенной в `ENTRYPOINT`.
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +#### `WORKDIR`. Рабочая папка проекта / приложения
```suggestion
#### `WORKDIR`. Рабочая папка проекта
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Установка рабочей папки является частой практикой. Добавим ее нашу конфигурацию:
```suggestion
Устанавливать рабочую папку — хороший тон. Она позволяет явно указать место, где будет происходить вся работа. Добавим ее нашу конфигурацию:
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Это бывает также полезно, когда в образе находится база данных, доступ к которой нужен вне контейнера, или используется удаленный доступ по SSH. Для этого используется инструкция `EXPOSE`:
```suggestion
`EXPOSE` незаменим, когда в образе находится база данных и нам нужен доступ к ней вне контейнера. Для этого используется инструкция `EXPOSE`:
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Запись `EXPOSE 8080` в примере означает, что на компьютере, на котором запущен Docker, веб-приложение будет доступно по адресу `http://localhost:8080`.
```suggestion
Запись `EXPOSE 8080` означает, что на компьютере, на котором запущен Docker, веб-приложение будет доступно по адресу `http://localhost:8080`.
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +docker build .
может добавим еще пример, когда мы даем образу имя?

`docker build -t y-doka .` ?

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Если вам не нужно включать в образ какие-то папки или файлы из `контекста`, можно использовать файл исключений `.dockerignore`. В этом файле перечисляются в отдельных строках все пути или маски путей
```suggestion
Если вам не нужно включать в образ какие-то папки или файлы из `контекста`, добавьте в папку файл исключений `.dockerignore`. В этом файле перечисляются в отдельных строках все пути или маски путей, которые не должны быть помещены в образ. Пример файла:
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +При сборке образа Docker ищет файл с исключениями, исходя из имени основного файла конфигурации. Например, команда `docker build -f myapp.Dockerfile .` будет в первую очередь искать файл исключений п
```suggestion
🛠 При сборке образа Docker ищет файл с исключениями, исходя из имени основного файла конфигурации. Например, команда `docker build -f myapp.Dockerfile .` будет в первую очередь искать файл исключений по пути `myapp.Dockerfile.dockerignore`. Если такого файла не найдется, то при наличии будет использоваться `.dockerignore`.
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Все объекты Docker обязательно имеют имя. Если оно не назначается пользователем, то в качестве имени используется хэш. Чтобы работать с образами было удобнее, лучше выбирать имя. Кроме имени можно та
```suggestion
🛠  Все объекты Docker обязательно имеют имя. Если оно не назначается пользователем, то в качестве имени используется хэш. Чтобы работать с образами было удобнее, лучше выбирать имя. Кроме имени можно также использовать тэги. Обычно тэги указывают на версию или особенности той или иной сборки образа. Совокупность образов с одним именем, но разными тэгами, — это репозиторий образов. Например, можно собрать образ с указанием имени и тэга командой:
```

2021-03-13 22:21 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +Важно отслеживать размер образа, и пользоваться образами с умом. Вы можете загрузить к себе образ командой `pull`. Например, для образа Node.js:
```suggestion
🛠  Важно отслеживать размер образа, и пользоваться образами с умом. Вы можете загрузить к себе образ командой `pull`. Например, для образа Node.js:
```

2021-03-13 22:32 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +![Проброска портов образов Docker для веб-приложений](/assets/images/posts/js/dockerfile/docker-expose.png)
Картинка верная, но не доносит проблему, которая появляется, если порт не пробросить. Приложение будет жить внутри контейнера и доступа извне к нему не будет. Нужно это как-то обозначить. 

Мой вариант:
![Untitled-2020-11-03-1028(3)](https://user-images.githubusercontent.com/1469636/111051578-63b72b80-8454-11eb-8810-b15309d76841.png)

2021-03-13 22:34 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +![Проброска портов образов Docker для веб-приложений](/assets/images/posts/js/dockerfile/docker-expose.png)
много квадратиков, @ValyaBro может нам помочь

2021-03-14 07:46 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +```bash
Ну можно тогда добавить пример с [yaspeller](https://github.com/hcodes/yaspeller), чтобы не отвлекаться от JS. Упоминание Python ты все равно удалил.

2021-03-14 07:52 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +`CMD` выполняется только в том случае, если пользователь вашего образа не прописывает в явном виде, что делать после сборки. Обычно `CMD` используется не совсем для запуска приложения по умолчанию, а
Преобразовал несколько текст при переносе.

2021-03-14 07:54 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +docker build .
А у нас же есть чуть ниже пример с именем

2021-03-14 08:00 UTC, igsekor commented on src/posts/js/tools/dockerfile.md
> +![Проброска портов образов Docker для веб-приложений](/assets/images/posts/js/dockerfile/docker-expose.png)
Ник, мне кажется, это не правильно нарисовано. Речь идет о настройке посредника между хостом и контейнером. Читатель должен, мне кажется, сосредоточиться на архитектуре, чтобы не попасть в просак, а не на правилах. Сложно потом будет сориентироваться, когда столкнется с совместным взаимодействием нескольких контейнеров. Представлять как работает Docker, кажется, важнее, чем знать лишь один вариант использования, хоть и распространенный. Что думаешь?

2021-03-14 08:47 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +docker build .
ты прав, давай оставим базовый

2021-03-14 08:51 UTC, nlopin commented on src/posts/js/tools/dockerfile.md
> +![Проброска портов образов Docker для веб-приложений](/assets/images/posts/js/dockerfile/docker-expose.png)
Согласен. Но мне еще хочется показать, что контейнеры изолированы от комплюктера, на котором они запускаются, что это черная коробка. Мы говорим об этом текстом, но на картинке не совсем понятно.

2021-03-14 08:51 UTC, nlopin approved these changes

2021-03-14 08:52 UTC, merged