Добавляет статью о TDD
Y-Doka/y-doka.site pull request #656
Opened 2021-03-16 11:42 UTC by bespoyasov

Пока что я указываю источник картинки (codedream.me). Когда заменим картинку на свою, его можно будет убрать.

2021-03-17 21:20 UTC, nlopin requested changes
Офигенно! 

У меня появилась такая идея: а что если мы блоки текста, где мы находимся в той или иной зоне будем подкрашивать соответствующим бекграундом или нежной полоской справа? @ValyaBro что думаешь?

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Мы помним, что цикл разработки в TDD короткий, поэтому реализация должна быть максимально простой. (Иногда даже — топорной.)
не думал зафигачить в лоб `return 10 / 5`? это же вроде классический TDD. Или думаешь слишком радикально?

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Но ведь мы же не доедали функцию! Да, мы пока не сделали обработку ошибок и настройки, это правда. Но часто на начальных этапах проектирования детали менее важны, чем основная функциональность. К том
```suggestion
Но ведь мы же не доедали функцию! Да, мы пока не сделали обработку ошибок и настройки, это правда. Но часто на начальных этапах проектирования детали менее важны, чем основная функциональность. К тому же при обновлении функциональности в репозитории появятся и тесты к ней. Тесты помогут объяснить, что добавилось и что поменялось.
```

Но вообще фраза «К тому же при обновлении функциональности в репозитории появятся и тесты к ней» сложная, давай упростим

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +В примере выше мы создаём массив `testCases`, в котором держим пачку тестовых данных. Каждый объект внутри содержит аргументы для функции и ожидаемый результат, который функция должна вернуть при так
```suggestion
В примере выше мы создаём массив `testCases`, в котором держим пачку тестовых данных в виде объектов. Каждый объект содержит аргументы для функции и ожидаемый результат, который функция должна вернуть при таких аргументах.
```

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Каждый объект из пачки мы разбиваем на переменные `a`, `b` и `expected`, которые потом используем для проверки функции. Таким образом мы можем использовать написанный единожды тест для проверки его н
Добавил задачу расскзать о деструктурации

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Код тестов — такой же код, как и код самой функции. Его стоит держать в чистоте так же, как и любой продуктовый код. Если с тестами становится неудобно работать, стоит взять время на их рефакторинг и
можно еще сказать, что в тесте не должно быть логики. Код теста должен быть очевидным. Иначе придется писать тест, который тестирует тест

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +В начале статьи мы приводили примеры того, что функция будет уметь. Деление целых чисел мы с вами уже сделали. Давайте теперь перейдём к дробям.
```suggestion
В начале статьи мы приводили примеры того, что функция будет уметь. Деление целых чисел мы уже сделали. Давайте теперь перейдём к дробям.
```

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Проверим тесты... Ой! Новый тест не прошёл, ещё и старые упали:
🔥

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +Дальше мы проверяем, что функция-обёртка ``attempt` при вызове должна выбросить (`toThrow`) ошибку указанным сообщением.
```suggestion
Дальше мы проверяем, что функция-обёртка `attempt` при вызове должна выбросить (`toThrow`) ошибку указанным сообщением.
```

2021-03-17 21:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +divide(10, 0); // ERROR: I'm sorry, Dave. I'm afraid I can't do that.
![image](https://user-images.githubusercontent.com/1469636/111539816-9e7bd500-876e-11eb-943c-8d753f91ebff.png)

2021-03-17 21:24 UTC, nlopin commented
@bespoyasov @ValyaBro кажется будет прикольно выделить зону, в которой мы находимся по тексту. Что-то типа: 
<img width="2118" alt="image" src="https://user-images.githubusercontent.com/1469636/111540547-8fe1ed80-876f-11eb-967b-535d03cffd2a.png">

2021-03-18 09:40 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +Первый этап — красная зона. На нём мы пишем тест, который точно упадёт с _ожидаемой причиной_. Если причина падения теста не совпадает с ожидаемой, переходить к реализации функциональности рано.
✅

2021-03-18 09:40 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +В этом тесте мы случайно перепутали аргументы для функции `expect`,  поэтому это предположение будет всегда истинным, тест будет всегда проходить. Если тест никогда не сваливается, значит он ничего н
Мне кажется, «ломается» — это когда сам тест написан с ошибками, а «сваливается» (fails), когда функция не проходит тест ¯\_(ツ)_/¯

2021-03-18 09:40 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +Мы помним, что цикл разработки в TDD короткий, поэтому реализация должна быть максимально простой. (Иногда даже — топорной.)
В целом да, но я не вижу в этом никакой пользы, кроме слепого следования канону, если честно. Это только время отнимает.

Каноническое написание могло бы иметь смысл, если бы реализация функции была больше. Сейчас что написать `10 / 2`, что `a / b`, особо отличий нет. 

Дальше по тексту мы расширяем функциональность `divide` всё равно, так что само по себе `a / b` — это уже тривиальный пример.

2021-03-18 09:40 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +Но ведь мы же не доедали функцию! Да, мы пока не сделали обработку ошибок и настройки, это правда. Но часто на начальных этапах проектирования детали менее важны, чем основная функциональность. К том
Переписал.

2021-03-18 09:40 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +Код тестов — такой же код, как и код самой функции. Его стоит держать в чистоте так же, как и любой продуктовый код. Если с тестами становится неудобно работать, стоит взять время на их рефакторинг и
✅

2021-03-18 12:20 UTC, nlopin commented on src/posts/js/long/tdd.md
> +В этом тесте мы случайно перепутали аргументы для функции `expect`,  поэтому это предположение будет всегда истинным, тест будет всегда проходить. Если тест никогда не сваливается, значит он ничего н
Я с тобой согласен, но по тексту они выглядят взаимозаменяемыми:

> в красной зоне тесты сломаны

> Когда тест сломан, надо внимательно посмотреть на ошибку.

Даже в абзаце ниже написано «Такие тесты нам не нужны. Давайте сломаем его:»

2021-03-18 12:32 UTC, bespoyasov commented on src/posts/js/long/tdd.md
> +В этом тесте мы случайно перепутали аргументы для функции `expect`,  поэтому это предположение будет всегда истинным, тест будет всегда проходить. Если тест никогда не сваливается, значит он ничего н
Да, ты прав. Я сделал формулировки последовательными.

(«Сломан» — содержит непреднамеренную ошибку, «падает» — проверяет, что функция не соответствует предположению.)

2021-03-18 12:48 UTC, nlopin approved these changes
Вливаем

2021-03-18 12:48 UTC, merged

2021-03-19 05:19 UTC, ValyaBro commented
> @bespoyasov @ValyaBro кажется будет прикольно выделить зону, в которой мы находимся по тексту. Что-то типа:
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/1469636/111540547-8fe1ed80-876f-11eb-967b-535d03cffd2a.png">
> 
> Особенно классно это будет играть ниже по тексту, где мы явно не проговариваем зоны. Как думаете?

Давай попробуем сделать и посмотрим. Фон я бы не стала трогать, это может ухудшить читаемость. А индикация линией может хорошо сработать. Я бы сделала линию толщиной 2–3 px, в наших цветах. Красный — ED6742, зелёный — 49A16C. Расстояние от блока текста до линии на твоём скетче отличное.

2021-03-19 06:21 UTC, nlopin commented
> > @bespoyasov @ValyaBro кажется будет прикольно выделить зону, в которой мы находимся по тексту. Что-то типа:
> 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/1469636/111540547-8fe1ed80-876f-11eb-967b-535d03cffd2a.png">
> 
> > 
> 
> > Особенно классно это будет играть ниже по тексту, где мы явно не проговариваем зоны. Как думаете?
> 
> 
> 
> Давай попробуем сделать и посмотрим. Фон я бы не стала трогать, это может ухудшить читаемость. А индикация линией может хорошо сработать. Я бы сделала линию толщиной 2–3 px, в наших цветах. Красный — ED6742, зелёный — 49A16C. Расстояние от блока текста до линии на твоём скетче отличное.

Нужен ещё синий, тоже возьму наш