Добавляет статью про float
Y-Doka/y-doka.site pull request #663
Opened 2021-03-17 18:22 UTC by lenaryan

Не без вопросиков, конечно, но я там написала, в чём вопросы.

2021-03-22 09:06 UTC, solarrust reviewed
Поотвечала на вопросы =) 
Ещё пока читала увидела в голове потенциальную иллюстрацию: идёт поток людей, сбоку на тротуаре стоит баннер. Все люди его обходят — «обтекают». Что думаешь?

2021-03-22 09:06 UTC, solarrust commented on src/posts/css/doka/float.md
> +
Пример мы обычно пишем прямо кодом в тексте. Если нужно показать конечный результат, а не только синтаксис, то ниже через embed вставляем кодпенчик с демкой. 

Лучше в качестве примера привести наипростейшую ситуацию, решаемую описываемым свойством. В нашем случае _картинка_ в тексте будет самое то. Но лучше прямо картинку использовать, а не просто блок. Чтобы у студента закреплялось, что это свойство нужно для картиночек.

2021-03-22 09:06 UTC, solarrust commented on src/posts/css/doka/float.md
> +Иногда при вёрстке блока нужно, чтобы текст рядом с&nbsp;картинкой занимал всё оставшееся место, а&nbsp;после картинки располагался на&nbsp;всю ширину блока. Для таких ситуаций и&nbsp;создан `float`.
Начиная с HTML5 элементы больше не делятся на блочные и строчные https://html.spec.whatwg.org/multipage/dom.html#kinds-of-content

2021-03-22 09:06 UTC, solarrust commented on src/posts/css/doka/float.md
> +🛠 `float` не&nbsp;предназначен для создания сеток или табличной раскладки!
Можно раскрыть этот совет. Рассказать, что раньше не было другого способа поставить колонки рядом. А теперь есть как минимум флексбоксы, а вообще-то даже гриды. И дать ссылочки на лонгриды.

2021-03-22 09:06 UTC, solarrust commented on src/posts/css/doka/float.md
> +🛠 Чтобы прекратить влияние `float` и&nbsp;вернуться к&nbsp;обычному потоку, после блока с&nbsp;обтеканием можно вставить пустой элемент, обычно с&nbsp;классом `clearfix`, и&nbsp;прописать свойство `c
Да уж, этот чёртов клеарфикс и правда тянул бы на статью лет пять назад. Но теперь достаточно показать ситуацию, когда обтекаемая картинка выше контента родителя. И как решить эту проблему. Можно вскользь упомянуть, что не обязательно прямо блок-блок в разметке. Можно обойтись и псевдоэлементом. Что предпочтительнее =)

2021-03-22 15:41 UTC, ezhkov commented on src/posts/css/doka/float.md
> +Иногда при вёрстке блока нужно, чтобы текст рядом с&nbsp;картинкой занимал всё оставшееся место, а&nbsp;после картинки располагался на&nbsp;всю ширину блока. Для таких ситуаций и&nbsp;создан `float`.
Подробнее описано в статье про поток. Думаю, можно здесь добавить ссылку /css/doka/flow

@solarrust Про блочные и строчные дискутировали сегодня, мне кажется можно оставить такое условное деление. Либо уйти к контекстам и заменить строчные элементы на "элементы строчного контекста", а блочные — на "элементы блочного контекста"

2021-04-04 21:46 UTC, lenaryan commented on src/posts/css/doka/float.md
> +🛠 Чтобы прекратить влияние `float` и&nbsp;вернуться к&nbsp;обычному потоку, после блока с&nbsp;обтеканием можно вставить пустой элемент, обычно с&nbsp;классом `clearfix`, и&nbsp;прописать свойство `c
Что-то я не подумала, может, тут тоже надо демку? И с clearfix, и с flow-root?

2021-04-04 21:47 UTC, lenaryan commented
> Поотвечала на вопросы =)
> Ещё пока читала увидела в голове потенциальную иллюстрацию: идёт поток людей, сбоку на тротуаре стоит баннер. Все люди его обходят — «обтекают». Что думаешь?

Интересно, но там и так уже демка... Возможно, будет вторая (см. выше).

2021-04-05 14:13 UTC, solarrust commented
> > Поотвечала на вопросы =)
> > Ещё пока читала увидела в голове потенциальную иллюстрацию: идёт поток людей, сбоку на тротуаре стоит баннер. Все люди его обходят — «обтекают». Что думаешь?
> 
> Интересно, но там и так уже демка... Возможно, будет вторая (см. выше).

Это скорее картинка, чем демка. Если идея тебе нравится и ты считаешь, что она уместна в твоей статье, то мы можем унести её иллюстраторам.

2021-04-05 15:44 UTC, lenaryan commented
> > 
> > Интересно, но там и так уже демка... Возможно, будет вторая (см. выше).
> 
> Это скорее картинка, чем демка. Если идея тебе нравится и ты считаешь, что она уместна в твоей статье, то мы можем унести её иллюстраторам.

Я чуть выше предложила демку там, где говорю про clearfix

2021-04-05 16:36 UTC, solarrust commented on src/posts/css/doka/float.md
> +🛠 Чтобы прекратить влияние `float` и&nbsp;вернуться к&nbsp;обычному потоку, после блока с&nbsp;обтеканием можно вставить пустой элемент, обычно с&nbsp;классом `clearfix`, и&nbsp;прописать свойство `c
Да, давай сделаем, лишним точно не будет.

2021-04-07 18:11 UTC, pepelsbey requested changes
Стоит отдельно описать два кейса:

- Клиаринг флоатов на вложенном элементе
- Клиаринг флоатов на родительском блоке

2021-04-07 18:11 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +```
Самый первый пример не делает ничего. Я бы лучше написал `float: left` :)

2021-04-07 18:11 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +🛠 `float` не предназначен для создания сеток или табличной раскладки! Раньше не было другого способа разбить контент на колонки и поставить их рядом друг с другом. Но сейчас для этого есть [flexbox](
```suggestion
🛠 `float` не предназначен для создания сеток или табличной раскладки! Раньше не было другого способа разбить контент на колонки и поставить их рядом друг с другом. Но сейчас для этого есть [флексы](https://y-doka.site/css/long/flexbox-guide/) и [гриды](https://y-doka.site/css/long/grid-guide/), а `float` используется для «обтекания».
```
Я бы писал ровно так, как мы говорим: флексы, гриды.

2021-04-07 18:11 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +Также можно не вставлять отдельный элемент в разметку, а обойтись псевдоэлементом [::after](https://y-doka.site/css/doka/after/) - этот вариант предпочтительнее.
Я бы лучше рассказал, зачем это свойство в принципе нужно. Не для этого, чтобы «клиарить флоаты», а чтобы, например, задать это свойство заголовку в тексте и прикратить влияние флоатов для всего последующего контента. Сейчас совет относит нас скорее к сеткам на флоатах, а их лучше забыть.

Ну и аналогично демку переделать, чтобы нормализовать использование флоатов.

2021-04-07 18:11 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +🛠 Несколько лет назад для этой же цели появилось свойство `display: flow-root`. Достаточно применить его к блоку, внутри которого есть элемент с `float` — и влияние `float` не будет распространяться
```suggestion
🛠 Несколько лет назад для этой же цели появилось значение `flow-root` для свойства `display`. Достаточно применить его к блоку, внутри которого есть элемент с `float` — и влияние `float` не будет распространяться вне этого блока.
```

Я бы разделил два кейса:

- Клиарить флоаты для последующего контента (clear: both)
- Изолировать флоаты внутри блока (flow-root)

Это похожие задачи, но они по-разному работают. Для задачи изоляции флоатов в блоке также работает `overflow: hidden`, его обязательно стоит упомянуть. То есть это сразу тянет на два блока.

2021-04-07 20:28 UTC, lenaryan commented on src/posts/css/doka/float.md
> +```
Боже, какой идиот писал этот код...

2021-05-05 12:45 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +Также можно не вставлять отдельный элемент в разметку, а обойтись псевдоэлементом [::after](https://y-doka.site/css/doka/after/) - этот вариант предпочтительнее.
Всё хорошо, но мне всё ещё кажется, что нужно вынести `clear: both` из советов в тело статьи и рассказать, как прекратить обтекание. Флоаты и клиаринг важно описать вместе: если у вас текст поплыл вокруг картинки, то вам не нужно, чтобы вместе с ним плыл заголовок. И тут не `.clearfix` из сеток на флоатах, тут обычное свойство для организации текстового потока.

2021-05-05 12:45 UTC, pepelsbey requested changes
Всё хорошо, но мне всё ещё кажется, что нужно вынести `clear: both` из советов в тело статьи и рассказать, как прекратить обтекание. Флоаты и клиаринг важно описать вместе: если у вас текст поплыл вокруг картинки, то вам не нужно, чтобы вместе с ним плыл заголовок. И тут не `.clearfix` из сеток на флоатах, тут обычное свойство для организации текстового потока.

2021-05-05 12:50 UTC, pepelsbey commented on src/posts/css/doka/float.md
> +Свойство помогает «обтекать» картинки текстом.
```suggestion
Свойство помогает «обтекать» блоки текстом.
```

2021-06-07 16:02 UTC, closed without merging