Добавляет статью про поток
Y-Doka/y-doka.site pull request #672
Opened 2021-03-21 06:22 UTC by ezhkov

Закрывает #68

2021-03-22 08:44 UTC, solarrust reviewed
В этой статье сразу несколько абсолютно новых понятий. Предлагаю в конце раздела с новым понятием сделать коллаут и вынести в него понятие + короткое понятное определение. 

Ещё очень хочется примеров из жизни. Сейчас всё технически точно, но может быть не до конца понятно. Может быть приведём аналогии из реального мира? 

Демки просто 🔥  Спасибо тебе за них!

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Поток — это одно из важнейших базовых понятий в вёрстке. Это принцип организации элементов на странице при отсутствии стилей. Если мы просто напишем HTML из нескольких тегов и не напишем CSS, то коне
Дважды «это».

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Поток — это одно из важнейших базовых понятий в вёрстке. Это принцип организации элементов на странице при отсутствии стилей. Если мы просто напишем HTML из нескольких тегов и не напишем CSS, то коне
Кажется, что можно фразу «отображение в браузере» достать из скобок и заменить ею «конечный результат». Поскольку для вёрстки нет другого конечного результата =)

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Условно все элементы на странице можно разделить на две больших категории: блочные (block) и строчные (inline). Если вообще не применять никаких CSS-правил, браузер формирует из элементов **нормальны
Начиная с HTML5 элементы больше не делятся на блочные и строчные https://html.spec.whatwg.org/multipage/dom.html#kinds-of-content

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Во всех примерах далее будет рассматриваться направление письма, характерное для кирилицы и латиницы (слова — слева направо, блоки — сверху вниз). Но все те же объяснения можно применять и для другог
```suggestion
Во всех примерах далее будет рассматриваться направление письма, характерное для кириллицы и латиницы: слова — слева направо, блоки — сверху вниз. Но все те же объяснения можно применять и для другого направления письма.
```

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Строчные элементы располагаются друг за другом слева направо, как слова в предложении. Ширина и высота строчного элемента равна ширине и высоте содержимого. В отличие от блочного элемента, мы не може
```suggestion
Строчные элементы располагаются друг за другом слева направо, как слова в предложении. Ширина и высота строчного элемента равна ширине и высоте содержимого. В отличие от блочного элемента, мы не можем управлять шириной и высотой строчного элемента через CSS. Несколько строчных элементов будут стремиться находиться на одной строке, пока их все можно уместить в ширину родителя. Если ширины родителя не хватает, то лишний текст строчного элемента переносится на следующую строку.
```

2021-03-22 08:44 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Ранее мы выяснили, что все элементы по умолчанию находятся в нормальном потоке. Однако, существуют несколько CSS-свойств, изменение которых приводит к тому, что элемент перестаёт взаимодействовать с
Второе предложение не получается прочитать на одном дыхании. Давай переформатируем на пару предложений поменьше?

2021-03-22 09:56 UTC, solarrust commented on src/posts/html/doka/flow.md
> +Условно все элементы на странице можно разделить на две больших категории: блочные (block) и строчные (inline). Если вообще не применять никаких CSS-правил, браузер формирует из элементов **нормальны
В ходе дискуссии решили пояснить на основании чего производим это условное деление на блочные / строчные. 
«Условное деление на блочные и строчные мы производим на основании стандартных стилей тегов. Например, div будет блочным, а span или p — строчным. Поменять стандартное поведение можно при помощи CSS-свойства display.»

2021-03-22 15:44 UTC, ezhkov commented
> В этой статье сразу несколько абсолютно новых понятий. Предлагаю в конце раздела с новым понятием сделать коллаут и вынести в него понятие + короткое понятное определение.
> 
> Ещё очень хочется примеров из жизни. Сейчас всё технически точно, но может быть не до конца понятно. Может быть приведём аналогии из реального мира?
> 
> Демки просто 🔥 Спасибо тебе за них!

А какие конкретно понятия стоит вынести? Контексты?

2021-03-22 15:52 UTC, solarrust commented
> > В этой статье сразу несколько абсолютно новых понятий. Предлагаю в конце раздела с новым понятием сделать коллаут и вынести в него понятие + короткое понятное определение.
> > Ещё очень хочется примеров из жизни. Сейчас всё технически точно, но может быть не до конца понятно. Может быть приведём аналогии из реального мира?
> > Демки просто 🔥 Спасибо тебе за них!
> 
> А какие конкретно понятия стоит вынести? Контексты?

Нормальный поток и контекст наложения. Можно ещё что-то на твоё усмотрение.

2021-03-23 14:31 UTC, solarrust commented
@pepelsbey приходи посмотреть =)

2021-03-30 13:06 UTC, pepelsbey requested changes
Я бы здесь ещё раскрыл идею потока во флексах и в гридах. Хотя бы базово: во флексах он есть, а в гридах и есть, и нет.

2021-03-30 13:06 UTC, pepelsbey commented on src/posts/html/doka/flow.md
> +Правила расположения строчных и блочных элементов в нормальном потоке называются **контекстом форматирования**. Блочные элементы участвуют в формировании **блочного** контекста форматирования. Строчн
> Например, в кириллических языках или в латинице мы читаем и пишем слева направо

Я бы сформулировал более корректно, тут речь не про языки, а скорее системы письменности. @tachisis срочно нужен лингвист, тут человеку плохо!

Здесь и дальше в тексте.

2021-03-30 13:06 UTC, pepelsbey commented on src/posts/html/doka/flow.md
> +Строчные элементы располагаются друг за другом слева направо, как слова в предложении. Ширина и высота строчного элемента равна ширине и высоте содержимого. В отличие от блочного элемента, мы не може
```suggestion
Строчные элементы располагаются друг за другом от начала до конца строки, как слова в предложении. Если строка начинается слева, то слева направо, а если справа, то справа налево. Ширина и высота строчного элемента равна ширине и высоте содержимого. В отличие от блочного элемента, мы не можем управлять шириной и высотой строчного элемента через CSS. Несколько строчных элементов будут стремиться находиться на одной строке, пока их все можно уместить в ширину родителя. Если ширины родителя не хватает, то лишний текст строчного элемента переносится на следующую строку.
```

2021-03-30 13:06 UTC, pepelsbey commented on src/posts/html/doka/flow.md
> +- задать родителю вертикальное поле [`padding-top`](/css/doka/padding) или [`padding-bottom`](/css/doka/padding) в зависимости от того, с какой стороны мы хотим предотвратить выпадение;
```suggestion
- задать родителю вертикальный внутренний отступ [`padding-top`](/css/doka/padding) или [`padding-bottom`](/css/doka/padding) в зависимости от того, с какой стороны мы хотим предотвратить выпадение;
```

2021-03-30 13:06 UTC, pepelsbey commented on src/posts/html/doka/flow.md
> +- задать родителю верхнюю или нижнюю [границу](/css/doka/border) по такой же логике. Граница может быть прозрачной, главное, чтобы она была :);
```suggestion
- задать родителю верхнюю или нижнюю [рамку](/css/doka/border) по такой же логике. Граница может быть прозрачной, главное, чтобы она была :);
```

2021-03-30 13:06 UTC, pepelsbey commented on src/posts/html/doka/flow.md
> +
```suggestion

```

2021-03-31 16:39 UTC, ezhkov commented on src/posts/html/doka/flow.md
> +Строчные элементы располагаются друг за другом слева направо, как слова в предложении. Ширина и высота строчного элемента равна ширине и высоте содержимого. В отличие от блочного элемента, мы не може
Немного переформулировал с примерами. "От начала до конца строки" может вызвать ненужные вопросы о переносе элементов на следующую строку.

2021-03-31 17:52 UTC, tachisis commented on src/posts/html/doka/flow.md
> +Правила расположения строчных и блочных элементов в нормальном потоке называются **контекстом форматирования**. Блочные элементы участвуют в формировании **блочного** контекста форматирования. Строчн
Я бы предложила вообще заменить «в кириллических языках или в латинице» на «тексты на европейских языках», потому что алфавит, в целом, не имеет отношения к направлению письма.

2021-04-07 11:10 UTC, ezhkov commented on src/posts/html/doka/flow.md
> +Правила расположения строчных и блочных элементов в нормальном потоке называются **контекстом форматирования**. Блочные элементы участвуют в формировании **блочного** контекста форматирования. Строчн
Внёс небольшие правки. @pepelsbey, @tachisis гляньте, пожалуйста

2021-04-07 11:44 UTC, pepelsbey approved these changes

2021-04-07 11:47 UTC, solarrust approved these changes

2021-04-07 11:47 UTC, merged