Добавляет статью про Docker Compose
Y-Doka/y-doka.site pull request #673
Opened 2021-03-21 21:54 UTC by igsekor

Думаю над необходимостью рисунков. Может, надо что-то еще осветить. Но боюсь загрузить DevOps'ом. А может, что-то расписать подробнее?

@nlopin

2021-03-22 22:31 UTC, nlopin requested changes
Все круто, немного правок. 

В лонгридах структура может быть произвольной, а структуру можно использовать как ориентир. Мне показалос, что мы немного повторяемся в разделе «Как пишется», но это не выглядит лишним

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Docker Compose — это инструмент для запуска мультиконтейнерного приложения, которое полностью не зависит от платформы и обеспечивает поддержку всех необходимых для работы технологий из коробки. Конфи
```suggestion
Docker Compose — это инструмент для запуска мультиконтейнерного приложения, которое не зависит от платформы и содежит все необходимые для работы технологии и библиотеки. Конфигурация такого приложения записывается в одном текстовом файле в формате YAML. Запускается приложение одной командой в терминале.
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Если вы работаете на операционных системах Mac или Windows и установили Docker Desktop, вам ничего не нужно делать, Docker Compose у вас уже есть в распоряжении. Если вы работаете на операционной сис
```suggestion
Если вы работаете на операционных системах Mac или Windows и установили Docker Desktop, то Docker Compose уже установлен автоматически. Если вы работаете на операционной системе семейства Linux, вам необходимо его установить, предварительно скачав последний релиз из [репозитория](https://github.com/docker/compose/releases). До установки убедитесь, что Docker Engine на Linux уже установлен и готов к работе (подробнее в статье [«Что такое Docker?»](/js/tools/docker/#как-начать)). Процесс установки описан в [официальной документации Docker](https://docs.docker.com/compose/install/).
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +
```suggestion

:::callout 📚

В этой статье мы говорим про инструменты Docker. Если вам не очень понятно, зачем он нужен и как работает, прочитайте статью «[Что такое Docker](/js/tools/docker/)»

:::


```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Можно создать один образ с установленной базой данных, веб-сервером, интерпретатором PHP и движком Wordpress на борту. А можно сделать иначе.
вот тут классно будет схемка «было/стало»

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Веб-приложение — это, как правило, сложная система взаимодействующих частей — сервисов. Команда разработчиков Docker придерживается подхода: один сервис — один контейнер. Этот подход помогает легче о
Упростил первое преложение, как-то много тире
```suggestion
Веб-приложение — это, как правило, сложная система взаимодействующих частей, которые называют сервисами. Команда разработчиков Docker рекомендует подход: один сервис — один контейнер. Этот подход позволяет легче отлавливать ошибки, проще модернизировать сервисы, избегать работы над всем приложением сразу. При большой нагрузке на отдельные сервисы такой подход упрощает масштабирование с помощью перераспределения сетевых запросов (маршрутизатор можно поместить в отдельный контейнер). Мониторинг и поток ошибок можно осуществить также с помощью отдельного сервиса, запущенного в контейнере. Совокупность описанных сервисов называется мультиконтейнерным приложением.
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Веб-приложение — это, как правило, сложная система взаимодействующих частей — сервисов. Команда разработчиков Docker придерживается подхода: один сервис — один контейнер. Этот подход помогает легче о
тут глассно бы микровидосик масштабирования: стандартная схемка, потом появляется нагрузка и мы «клонируем» один из квадратиков. Что думаете @igsekor @ValyaBro ?

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Вернемся к примеру. Что нужно для запуска сайта на Wordpress? В самом простом случае мы можем такое веб-приложение разделить на два сервиса:
```suggestion
Вернемся к примеру. Что нужно для запуска сайта на Wordpress? В самом простом случае такое веб-приложение состоит из двух сервисов:
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Оба контейнера должны работать совместно. Мы можем написать [`Dockerfile`](/js/tools/dockerfile) для каждого из них и настроить взаимодействие друг с другом через виртуальную сеть Docker Network. Но
Хотим ли мы написать почему подход неудобен? Кажется основное неудобство в запуске вручную нескольких команд + надо работать с несколькими dockerfile

```suggestion
Оба контейнера должны работать совместно. Мы можем написать [`Dockerfile`](/js/tools/dockerfile) для каждого из них и настроить взаимодействие друг с другом через виртуальную сеть Docker Network. Но такой ручной подход не очень удобен. Docker Compose — это инструмент, который помогает конфигурировать запуск сразу нескольких контейнеров и указывать им, как работать совместно.
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +```
У нас есть вот такого формата схемки, где мы подписываем, что есть что:
![image](https://user-images.githubusercontent.com/1469636/112065550-18dc9880-8b65-11eb-9ec3-7f33d214d857.png)

Думаешь есть смысл что-то такое добавить сюда и показать два сервиса и связь, что wordpress зависит от db (остальные детали я бы опустил)? Если у нас выше в статье будет схема, то это поможет связать схему и конфиг

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +В подразделе `image` необходимо указать имя образа, который должен присутствовать локально на компьютере или в реестре. Можно установить и переменные окружения в подразделе `environment`, порты для п
```suggestion
В подразделе `image` необходимо указать имя образа, который должен присутствовать локально на компьютере или в реестре. Можно установить и переменные окружения в подразделе `environment`, порты для подключения к сервису (например, со стороны браузера) в подразделе `ports`, пути для монтирования томов в подразделе `volumes` и прочие параметры.
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). При остановке конте
```suggestion
Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). При остановке контейнеров все данные сохранятся, поскольку они хранятся в томе `db_data`. Вы сможете начать с того же места, перезапустив контейнеры с веб-сервером или базой данных вместе или по отдельности. В настройках `compose.yaml` указано, что если один из контейнеров упадет, то Docker Compose должен перезапустить его автоматически (`restart: always`).
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). При остановке конте
тут у нас провисает момент, почему данные сохранятся. Новичку вряд ли будет достаточно аргументации «потому что они в `db_data`»

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Поскольку Docker Compose работает с несколькими типами объектов Docker (образами, контейнерами, томами), то логично представить их настройки в виде дерева, что изящно воплощено в формате YAML, которы
Мы стараемся не давать оценочных суждений

```suggestion
Поскольку Docker Compose работает с несколькими типами объектов Docker (образами, контейнерами, томами), то логично представить их настройки в виде дерева, что воплощено в формате YAML, который очень часто применяется в файлах конфигурации. .
```

2021-03-22 22:31 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +  - container
```suggestion
  - container
  - приложение
  - докер
```

2021-03-23 12:55 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +Можно создать один образ с установленной базой данных, веб-сервером, интерпретатором PHP и движком Wordpress на борту. А можно сделать иначе.
Хорошая идея. Нарисую.

2021-03-23 12:56 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +```
Давай попробуем. Может интересно получиться.

2021-03-23 12:57 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). При остановке конте
Хорошо. Я допишу еще несколько слов об этом.

2021-03-23 12:58 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +Веб-приложение — это, как правило, сложная система взаимодействующих частей — сервисов. Команда разработчиков Docker придерживается подхода: один сервис — один контейнер. Этот подход помогает легче о
@ValyaBro , а формат какой? Набор кадров из Figma? Или какой-то специальный формат?

2021-03-23 12:58 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +
Вот это отлично!

2021-03-23 12:59 UTC, igsekor commented
> Мне показалось, что мы немного повторяемся в разделе «Как пишется», но это не выглядит лишним

Тоже сомневался насчет повторения. Но показалось, что так понятнее будет.

2021-03-23 12:59 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +Поскольку Docker Compose работает с несколькими типами объектов Docker (образами, контейнерами, томами), то логично представить их настройки в виде дерева, что изящно воплощено в формате YAML, которы
Ок

2021-03-23 13:00 UTC, igsekor commented on src/posts/js/tools/docker-compose.md
> +Оба контейнера должны работать совместно. Мы можем написать [`Dockerfile`](/js/tools/dockerfile) для каждого из них и настроить взаимодействие друг с другом через виртуальную сеть Docker Network. Но
Да вроде выше об этом речь шла. Стоит ли повторяться?

2021-03-23 21:12 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Веб-приложение — это, как правило, сложная система взаимодействующих частей — сервисов. Команда разработчиков Docker придерживается подхода: один сервис — один контейнер. Этот подход помогает легче о
Валя в отпуске кажется эту неделю, давай дождемся

2021-03-23 21:20 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +```
Думал о чём-то таком (цвета выбраны произвольно):
![](https://user-images.githubusercontent.com/1469636/112219836-d6c75b80-8c25-11eb-9607-0d631e26dea4.png)

2021-03-25 10:28 UTC, nlopin requested changes

2021-03-25 10:28 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +![Конфигурация мультиконтейнерного приложения для сайта на движке Wordpress](/assets/images/posts/js/docker-compose/docker-compose-config.png)
Давай оставим текстовое представление в теге `details` ниже картинки?

2021-03-25 10:28 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). В настройках `compo
```suggestion
Когда все образы будут загружены, тома включены, переменные окружения установлены, сайт на Wordpress окажется доступным по адресу [`http://localhost:8000`](http://localhost:8000). В настройках `compose.yaml` указано, что если один из контейнеров упадет, то Docker Compose должен перезапустить его автоматически (`restart: always`). Вы сможете начать с того же места. Появляется еще одна возможность — можно обновить базу данных и при следующем перезапуске запустится уже новая версия. То же самое можно делать и с веб-сервером, и движком.
```

2021-03-25 10:28 UTC, nlopin commented on src/posts/js/tools/docker-compose.md
> +![Разные пути создания сайта на движке Wordpress](/assets/images/posts/js/docker-compose/docker-compose-wordpress.png)
```suggestion
![Способы организации сайта на движке Wordpress с помощью Docker](/assets/images/posts/js/docker-compose/docker-compose-wordpress.png)
```

2021-03-28 19:43 UTC, nlopin approved these changes

2021-03-29 13:22 UTC, ValyaBro requested changes
надо схему привести в большее соответствие с нашим стилем. положила в фигму примеры.

2021-03-29 13:24 UTC, ValyaBro requested changes
сейчас сильный разброс по шрифтам, давай чуть причешем) можем обсудить в фигме

2021-03-30 08:19 UTC, ValyaBro approved these changes
картинка ок

2021-03-30 08:20 UTC, ValyaBro approved these changes
все картинки прекрасны :)

2021-03-30 15:08 UTC, merged

2021-03-30 15:08 UTC, nlopin commented
Все большие молодцы ❤️