Добавляет статью про <ol>
Y-Doka/y-doka.site pull request #679
Opened 2021-03-25 15:31 UTC by ezhkov

Закрывает #678

2021-03-26 07:43 UTC, solarrust reviewed
Кайф!
А давай найдём местечко и упомянем, что можно управлять типом нумерации или менять буллеты при помощи list-style-type?

2021-03-26 07:43 UTC, solarrust commented on src/posts/html/doka/ol.md
> +💡 Вложенным может быть как неупорядоченный список [&lt;ul>](/html/doka/ul), так и упорядоченный список `ol`.
```suggestion
💡 Вложенным может быть как неупорядоченный список [`<ul>`](/html/doka/ul), так и упорядоченный список `<ol>`.
```

2021-03-26 07:43 UTC, solarrust commented on src/posts/html/doka/ol.md
> +💡 Дочерними тегами **обязательно** должны быть `li`, в которые уже могут вложены любые другие теги.
```suggestion
💡 Дочерними тегами **обязательно** должны быть `<li>`, в которые уже могут быть вложены любые другие теги.
```

2021-03-26 07:43 UTC, solarrust commented on src/posts/html/doka/ol.md
> +💡 Как понять, где нужен список: если элементы несут один и тот же смысл, являются частью одной сущности, но явно или неявно подразумевается порядок в перечислении, то выбираем `<ol>`. Пример: план де
```suggestion
💡 Как понять, где нужен упорядоченный список: если элементы несут один и тот же смысл, являются частью одной сущности, но явно или неявно подразумевается порядок в перечислении, то выбираем `<ol>`. Пример: план дел на день. Каждое дело — это однотипный элемент, но при этом подразумевается, что дела будут выполнены в определенном порядке.
```

2021-03-26 07:43 UTC, solarrust commented on src/posts/html/doka/ol.md
> +Бывают ситуации, когда порядок неважен. Например, пункты меню или навигации на сайте. В этом случае выбираем [&lt;ul>](/html/doka/ul).
```suggestion
Бывают ситуации, когда порядок неважен. Например, пункты меню или навигации на сайте. В этом случае выбираем [`<ul>`](/html/doka/ul).
```

2021-03-30 08:22 UTC, solarrust commented
@pepelsbey приходи

2021-03-30 10:12 UTC, pepelsbey requested changes

2021-03-30 10:12 UTC, pepelsbey commented on src/posts/html/doka/ol.md
> +Тег `<ol>` является своеобразной обёрткой, указывающей браузеру на начало и конец списка. Сами пункты списка должны верстаться при помощи тега `<li>`. Таким образом, полностью список верстается с исп
```suggestion
Тег `<ol>` обозначает начало и конец списка. Сами пункты списка размечаются при помощи тега `<li>`. Таким образом, полностью список размечается с использованием обоих этих тегов:
```
Обычно вёрстка — это разметка и стили. Раз тут мы говорим просто про разметку, то лучше так и сказать. Плюс «является своеобразной обёрткой» кажется слишком усложняет простую идею: это список.

2021-03-30 10:12 UTC, pepelsbey commented on src/posts/html/doka/ol.md
> +Обратите внимание, что дочерними тегами для тега `<ol>` могут быть исключительно теги `<li>`. Любые другие теги обязательно должны находиться внутри пунктов списка `<li>`. Например, вложенный список
```suggestion
Обратите внимание, что дочерними тегами для тега `<ol>` могут быть исключительно теги `<li>` (ещё можно теги `<script>`, но это редкость). Любые другие теги обязательно должны находиться внутри пунктов списка `<li>`. Например, вложенный список должен верстаться так:
```

2021-03-30 10:12 UTC, pepelsbey commented on src/posts/html/doka/ol.md
> +Тег упорядоченного списка `<ol>` используется для вёрстки перечня однотипных элементов, когда важен их порядок. Частным случаем упорядоченного списка является нумерованный список.
> Частным случаем упорядоченного списка является нумерованный список.

Сложновато, как по мне. Не уверен, что это значит, есть только догадки. Может переформулировать или оставить объяснение, которое идёт ниже?

2021-03-30 10:12 UTC, pepelsbey commented on src/posts/html/doka/ol.md
> +```
Я бы тут лучше рассказал про то, как оформить номера упорядоченного списка (`::before`, `content`, `::marker`), кажется это важнее и чаще встречается, чем маскировка упорядоченных списков в неупорядоченные.

2021-04-07 17:35 UTC, pepelsbey approved these changes

2021-04-07 17:57 UTC, solarrust approved these changes

2021-04-07 17:57 UTC, merged