Добавляет статью про <br>
Y-Doka/y-doka.site pull request #680
Opened 2021-03-25 20:38 UTC by ezhkov

Закрывает #98

2021-03-26 18:44 UTC, solarrust reviewed
У тебя очень классно разобрать противоречивую тему. Супер 🔥

2021-03-26 18:44 UTC, solarrust commented on src/posts/html/doka/br-cons-pros.md
> +С переходом стандарта HTML на версию 5 из перечня тегов были исключены практически все, используемые для задания внешнего вида (например, `<small>` или `<font>`). Вместе с тем разработчики стандарта
Можно дать ссылочку на статью про устаревшие теги https://y-doka.site/html/long/deprecated-tags/

2021-03-26 18:44 UTC, solarrust commented on src/posts/html/doka/br-cons-pros.md
> +```html
Давай разделим этот блок на два и вынесем «Плохо» и «Хорошо» текстом перед блоками

2021-03-26 18:44 UTC, solarrust commented on src/posts/html/doka/br-cons-pros.md
> +<img src="/assets/images/posts/br-cons-pros/article.png" alt="Искусственный разрыв заголовка дизайнером" width="494"/>
```suggestion
![Искусственный разрыв заголовка дизайнером](/assets/images/posts/br-cons-pros/article.png)
```

2021-03-26 18:44 UTC, solarrust commented on src/posts/html/doka/br-cons-pros.md
> +И часто по незнанию, либо по невнимательности верстальщик воплощает задумку дизайнера, добавляя `<br>` в заголовок, чтобы вёрстка смотрелась в точности, как в макете. Ведь при адаптивной вёрстке слов
Чуть-чуть потерялась логическая связь между предложениями в этом абзаце. Давай попробуем их склеить =)

2021-03-29 14:49 UTC, ezhkov commented on src/posts/html/doka/br-cons-pros.md
> +И часто по незнанию, либо по невнимательности верстальщик воплощает задумку дизайнера, добавляя `<br>` в заголовок, чтобы вёрстка смотрелась в точности, как в макете. Ведь при адаптивной вёрстке слов
Перефразировал, спасибо)

2021-03-30 08:23 UTC, solarrust commented
@pepelsbey приходи

2021-03-30 10:00 UTC, pepelsbey requested changes
~Я немного запутался: по содержанию это либо лонгрид, либо совет «в работе», то есть рассматривается не формальные свойства и задачи тега, а звучит рассуждение о его современной роли.~

Давайте попробуем пригасить недовольство тем, что иногда нужно переносить текст в заголовках. Слишком уж эта задача маргинализируется, как будто этого нельзя хотеть, а дизайнеры «нафантазировали тут».

2021-04-07 11:18 UTC, ezhkov commented on src/posts/html/doka/br-cons-pros.md
> +### Фантазии дизайнера
Прошу прощения, если это выглядит издевательски. Никого не хотел задеть) Переформулировал и немного перегруппировал, вынеся кейс с переносами в заголовках в отдельный раздел

2021-04-07 11:46 UTC, pepelsbey commented
@solarrust в итоге делаем так?

```diff
- html/doka/br-pros-cons.md
+ html/long/br-pros-cons.md
```

2021-04-07 11:48 UTC, solarrust commented
> @solarrust в итоге делаем так?
> 
> ```diff
> - html/doka/br-pros-cons.md
> + html/long/br-pros-cons.md
> ```

Да, пока можно положить в лонги. При переносе положу в articles =)

2021-04-07 17:26 UTC, pepelsbey commented on src/posts/html/long/br-pros-cons.md
> +```
````suggestion
```html
<p>
  Мой дядя самых честных правил,<br>
  Когда не в шутку занемог,<br>
  Он уважать себя заставил<br>
  И лучше выдумать не мог.
</p>
```

Ещё одним примером может служить верстка почтового адреса, когда принципиально разнести части адреса по разным строкам:

```html
<address>
  432000<br>
  г. Ульяновск<br>
  ул. Ленина, д. 34
</address>
```
````

Если написать `слово∙<br>⏎слово`, фактически это `слово∙<br>∙слово` — то есть перед переносом зачем-то ещё один пробел. Может быть упростим до `слово<br>⏎слово`? Удивлён таким написанием, никогда его не встречал и в примерах дальше его тоже нет.

2021-04-07 17:28 UTC, pepelsbey commented on src/posts/html/long/br-pros-cons.md
> +```
Ну то есть прямо в браузере если выделить текст, то скопируется:
```
Мой дядя самых честных правил,∙
Когда не в шутку занемог,∙
Он уважать себя заставил∙
И лучше выдумать не мог.
```
Кажется это не нужно.

2021-05-04 16:32 UTC, ezhkov commented on src/posts/html/long/br-pros-cons.md
> +```
@pepelsbey Согласен, пропустил этот момент. Поправлено.

2021-05-05 07:45 UTC, solarrust approved these changes

2021-05-05 12:39 UTC, pepelsbey commented on src/posts/html/long/br-pros-cons.md
> +С переходом стандарта HTML на версию 5 из перечня тегов были исключены практически все, используемые для задания внешнего вида (например, `<small>` или `<font>`). Вместе с тем разработчики стандарта
```suggestion
По мере развития стандарта HTML в него добавлялись новые теги и убирались [неактуальные](/html/long/deprecated-tags/). В HTML5 большой упор был сделан на семантический смысл тегов, а всё, что касалось визуальной составляющей, было отдано на откуп CSS. То есть, теперь использование тех или иных тегов диктовалось их функциональным назначением, а не тем, как тег влияет на внешний вид элемента.

С переходом на стандарт HTML5 из перечня тегов были исключены практически все, используемые для задания внешнего вида (например, `<small>` или `<font>`). Вместе с тем разработчики стандарта оставили довольно спорный тег `<br>`. Основной причиной его спорности в настоящее время является не совсем полное понимание случаев, в которых он должен применяться.
```

Мне кажется, что все настолько привыкли к написанию HTML5, что разворачивать это в более сложные фразы не стоит.

2021-05-05 12:39 UTC, pepelsbey commented on src/posts/html/long/br-pros-cons.md
> +Например, при адаптивной вёрстке слова в заголовке перестроятся, а разрыв строки никуда не денется. В результате заголовок будет вести себя неестественно, перенося слова там, где не должен.
```suggestion
Например, при адаптивной вёрстке слова в заголовке перестроятся, а разрыв строки никуда не денется. В результате заголовок будет вести себя неестественно: слова перенесутся не там, где должны.
```
Кажется не заголовок переносит слова, а они сами (при участии браузера).

2021-06-05 09:31 UTC, akellbl4 commented
Случайно зашел в материал, очень круто получилось (теперь буду кидать ссылку на эту статью в PR/MR когда опять встречу неверное использование тега).

Единственное, что смутило – в примере показано как ломается верстка при использовании `<br>`, но мне так же было бы интересно увидеть как сделать правильно. Просто я встречал такое что люди добавляют класс на `br` и потом при адаптивности скрывают `br` вроде ничего страшного, но выглядит не очень.

2021-06-05 10:35 UTC, ezhkov commented
@akellbl4 Тут проблема довольно разносторонняя. С одной стороны, мы можем принудительно перенести строки в заголовке, прикинуть, при каких разрешениях всё сломается, сделать медиа-запросы на эти точки и спрятать перенос: 
```css
br { 
  display: none;
}
```
Всё кажется логичным до тех пор, пока пользователь не решит отмасштабировать текст на странице. И вот в этом случае всё пойдёт не так, как было задумано. Поэтому, лучше бы так совсем не делать. Но само собой, жизнь не идеальна, и часто вёрстку мы делаем без оглядки на нестандартные случаи )

2021-06-07 09:21 UTC, pepelsbey approved these changes

2021-06-07 15:59 UTC, closed without merging