Добавляет статью Управление данными в Docker
Y-Doka/y-doka.site pull request #686
Opened 2021-03-31 22:01 UTC by igsekor

Посмотрите, пожалуйста :)

@nlopin @ValyaBro

2021-04-02 12:56 UTC, ValyaBro requested changes
Хочется немного причесать всё. 
Предлагаю сделать блоки пошире и увеличить шрифт в блоах на чёрном фоне, чтобы улучшить читаемость. 
Тёмный шрифт на синем фоне не чоень хорошо читается, давай заменим на зелёный.
Сейчас потерялась логика в расстоянии между элементами, хочется сделать все расстояния более логичными. Чтобы расстояния между сущностями были одинаковыми и увеличивались по мере увеличения смыслового расстояния между сущностями. 
Нижняя часть чуть отлетела, давай поднимем ее повыше к верхней части.

2021-04-02 14:20 UTC, igsekor commented
> Хочется немного причесать всё.
> Предлагаю сделать блоки пошире и увеличить шрифт в блоах на чёрном фоне, чтобы улучшить читаемость.
> Тёмный шрифт на синем фоне не чоень хорошо читается, давай заменим на зелёный.
> Сейчас потерялась логика в расстоянии между элементами, хочется сделать все расстояния более логичными. Чтобы расстояния между сущностями были одинаковыми и увеличивались по мере увеличения смыслового расстояния между сущностями.
> Нижняя часть чуть отлетела, давай поднимем ее повыше к верхней части.

Стало лучше! Класс! Спасибо! :)

> Сейчас не понятно смысловая нагрузка надписи "хост". Это подпись одного из блоков или заголовок всей схемы? Хочется найти ей место.

Эта надпись должна обозначать, что то, что в разовых рамках лежит на хосте. Можно наверное сделать так, как я положил в фигме.

2021-04-03 21:48 UTC, nlopin reviewed
Очень большая статья получилась. Сделаю еще один проход. 

Где-то к середине мне стало сложно следить за структурой. Мы здесь построили объяснение слоями, сначала рассказываем три концепта, потом рассказываем про применение каждого, потом детали. Получается, чтобы разобраться с одним подходом, мне нужно прочитать всю статью. Плюс к конце мы начинаем повторять плюсы и минусы.

Как думаешь, не будет ли лучше если мы отойдем от стандартной структуры и  сгруппируем: сначала расскажем концепт каждого подхода, а потом по большому детальному разделу, для каждый?

Получается вместо «Как выбрать», «в работе», сразу будут большие разделы «связанные папки» , «тома» ...

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +name: docker
Имя `docker` уже занято основной статьей
```suggestion
name: docker-data-management
```

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Механизм bind mounts подразумевает, что данные могут быть изменены в любое время как из подключенного контейнера, так и непосредственно на хосте.
Давай сначала скажем, в чем смысл, а потом скажем зачем? Мы обычно идем от задачи, но сейчас задача тоже непонятна.

Я бы сказал что-то типа «Связанные папки — это когда мы подключаем папку на файловой системе хоста к контейнеру. Её можно редактировать как из контейнера, так и из хоста»

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Механизм bind mounts подразумевает, что данные могут быть изменены в любое время как из подключенного контейнера, так и непосредственно на хосте.
Давай еще напомним, что такое хост здесь, или выше по тексту

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Использовать связанные папки для работы с конфигурационными файлами не безопасно. Файловая система и структура папок могут сильно отличаться на разных компьютерах. Правила описания путей также не кро
Мы много говорим чего не делать, но не говорим, для чего ее использовать. Может перефразируем в кейсы, когда это нужно? в конец, конечно, скажем, что использовать папки для работы с конфигами опасно

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Тома являются наилучшим типом управления данных при использовании Docker. Только объекты или службы Docker должны иметь доступ к изменению данных, расположенных в томах. Конечно, это просто файлы и п
хороший абзац, но в нем много мыслей, давай попробуем разбить на два?

В первом скажем, что тома — это типа связанные папки, но доступ к ним только у докера. (мне кажется лишним говорить, что ты всё равно можешь руками залезть с хоста. зачем? но давай обсудим)

Во втором, что тома круты тем, что подключать можно не только папки с хоста, но и папки из облака и вот это вот все

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Когда том примонтирован к контейнеру, он изолирован от ядра операционной системы хоста. Плюсом является то, что том существует самостоятельно и не зависит от жизненного цикла контейнеров. Docker упра
Изолирован === недоступен? если да, то недоступен слово попроще

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Тома могут быть созданы при сборке контейнера (с помощью [Dockerfile](/js/tools/docker) или [Docker Compose](/js/tools/docker-compose)) или вручную с помощью Docker Engine. Тома могут иметь имя, назн
> Механизм управления томами также поддерживает концепцию драйвера, что позволяет использовать их не только на локальном хосте.

я не понял :(

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Механизм `tmpfs` mount в операционной системе Linux позволяет выделить часть оперативной памяти хоста для хранения данных. Данные при таком типе не сохраняются в файловой системе хоста. При этом, пол
```suggestion
Механизм `tmpfs` mount в операционной системе Linux позволяет выделить часть оперативной памяти хоста для хранения данных. Данные не сохраняются в файловой системе и получается быстрое хранилище. Примонтированная папка `tmpfs` работает, пока существует контейнер, поэтому не стоит использовать этот способ для хранения настроек и результатов работы приложения.
```

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Для пользователей операционной системы Windows существует еще один тип управления данными — `npipe` mount. Этот тип позволяет получить доступ к хосту Docker из контейнера и в основном используется дл
я не понял. чем это отличается от связанных папок?

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +**Работа с исходным кодом и артефактами сборок.** Можно использовать системы сборки для исходного кода внутри контейнера, а можно использовать уже собранные [бандлы](js/tools/bundlers) для тестирован
добавим, что можно изменять код, и он будет автоматом подхватываться докером?

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +### Используем связанные папки (bind mounts)
Давай попробуем согласовать пункты ниже с заголовком, чтобы читалось как предложение. Сейчас получается странновато: «Используем связанные папки использование одних и тех же...»

Может:
«Используем связанные папки когда нужно иметь одинаковый файл и на хосте, и в контейнере»
«Используем связанные папки для работы с исходным кодом и артефактами сборок»
...

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Если вы примонтируете **_не_ пустую связанную папку** или **_не_ пустой том** к определенной папке внутри контейнера, которая уже имеет содержимое, оно и будет отображаться в этой папке. Содержимое н
> оно и будет отображаться в этой папке

То есть будет отображаться старое содержимое, а не содержимое примонтированной папки?

2021-04-03 21:48 UTC, nlopin commented on src/posts/js/tools/docker-volume.md
> +Третье поле поддерживает следующие опции: `rprivate`, `private`, `rshared`, `shared`, `rslave`, `slave`, `ro`, `z` и `Z`.
добавим микропример?

2021-04-03 21:49 UTC, nlopin commented
Связанные папки и тома очень похожи. Может для томов показать, что к одному тому можно привязать несколько контейнеров? (кстати, разве связанные папки нельзя?)

2021-04-03 21:50 UTC, nlopin commented
В управлением данных для докера я полный профан, поэтому смотрю из шкуры студента

2021-04-05 10:06 UTC, ValyaBro commented
> > Хочется немного причесать всё.
> > Предлагаю сделать блоки пошире и увеличить шрифт в блоах на чёрном фоне, чтобы улучшить читаемость.
> > Тёмный шрифт на синем фоне не чоень хорошо читается, давай заменим на зелёный.
> > Сейчас потерялась логика в расстоянии между элементами, хочется сделать все расстояния более логичными. Чтобы расстояния между сущностями были одинаковыми и увеличивались по мере увеличения смыслового расстояния между сущностями.
> > Нижняя часть чуть отлетела, давай поднимем ее повыше к верхней части.
> 
> Стало лучше! Класс! Спасибо! :)
> 
> > Сейчас не понятно смысловая нагрузка надписи "хост". Это подпись одного из блоков или заголовок всей схемы? Хочется найти ей место.
> 
> Эта надпись обозначает: что находится в розовых рамках, лежит на хосте. Можно наверное сделать так, как я положил в фигме.
> 
> @ValyaBro

аааа поняла твою идею :) предложила вариант как показать в фигме

2021-04-06 16:26 UTC, igsekor commented on src/posts/js/tools/docker-volume.md
> +Если вы примонтируете **_не_ пустую связанную папку** или **_не_ пустой том** к определенной папке внутри контейнера, которая уже имеет содержимое, оно и будет отображаться в этой папке. Содержимое н
Да

2021-04-06 16:38 UTC, igsekor commented on src/posts/js/tools/docker-volume.md
> +**Работа с исходным кодом и артефактами сборок.** Можно использовать системы сборки для исходного кода внутри контейнера, а можно использовать уже собранные [бандлы](js/tools/bundlers) для тестирован
Да

2021-04-06 16:40 UTC, igsekor commented on src/posts/js/tools/docker-volume.md
> +Для пользователей операционной системы Windows существует еще один тип управления данными — `npipe` mount. Этот тип позволяет получить доступ к хосту Docker из контейнера и в основном используется дл
> позволяет выделить часть оперативной памяти хоста для хранения данных. Данные при таком типе не сохраняются в файловой системе хоста.

tmpfs — это виртуальная папка, а не физическая, которая на самом деле просто кусок оперативной памяти.

2021-04-06 17:40 UTC, igsekor commented
@nlopin  и @ValyaBro , посмотрите, пожалуйста :)

2021-04-07 06:45 UTC, ValyaBro approved these changes
отлично

2021-04-14 22:26 UTC, nlopin approved these changes
Я перенес раздел "В работе" в конец статьи. Норм?

2021-04-14 22:26 UTC, nlopin commented on src/posts/js/tools/docker-data-management.md
> +Если вы примонтируете **_не_ пустую связанную папку** или **_не_ пустой том** к определенной папке внутри контейнера, которая уже имеет содержимое, оно и будет отображаться в этой папке. Содержимое н
> Содержимое на хосте будет скрыто до тех пор, пока контейнер использует папку в файловой системе хоста.

Не могу понять фразу. В ней нет ошибки?

Я так понимаю: Контейнер продолжит видеть свой контент, а не контент примонтированной папки, но до каких пор?

2021-04-14 22:26 UTC, nlopin commented on src/posts/js/tools/docker-data-management.md
> +Если вы примонтируете **_не_ пустую связанную папку** или **_не_ пустой том** к определенной папке внутри контейнера, которая уже имеет содержимое, оно и будет отображаться в этой папке. Содержимое н
> Содержимое на хосте будет скрыто до тех пор, пока контейнер использует папку в файловой системе хоста.

Не могу понять фразу. В ней нет ошибки?

Я так понимаю: Контейнер продолжит видеть свой контент, а не контент примонтированной папки, но до каких пор?

2021-04-14 23:33 UTC, igsekor commented
> Я перенес раздел "В работе" в конец статьи. Норм?

@nlopin я не против. Тут как со стороны, свежий взгляд точно лучше, чем замыленный мой. У меня была мысль сначала общую часть написать (по сути, все одной командой запускается), а затем уже углубиться в каждый из вариантов.

2021-04-15 10:34 UTC, igsekor commented on src/posts/js/tools/docker-data-management.md
> +Если вы примонтируете **_не_ пустую связанную папку** или **_не_ пустой том** к определенной папке внутри контейнера, которая уже имеет содержимое, оно и будет отображаться в этой папке. Содержимое н
Все верно. Пока контейнер не будет отключен от папки. Работает также, как примонтированные ресурсы в Linux. Если флэшку примонтировать в уже существующую и наполненную содержимым папку, то это содержимое не будет видно до тех пор, пока флэшку не отмонтировать.

2021-04-18 13:31 UTC, nlopin approved these changes

2021-04-18 13:32 UTC, merged