Добавляет доку про Local Storage
Y-Doka/y-doka.site pull request #696
Opened 2021-04-12 11:47 UTC by akellbl4

Решает #485

- [ ] проверить грамматику и орфографию

2021-04-12 11:48 UTC, akellbl4 commented
@nlopin в целом уже можно глянуть по содержанию

2021-04-12 14:42 UTC, pepelsbey requested changes

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +  avatarUrl: "https://y-doka.site/assets/images/mainpage/mascot-doka.svg"
```suggestion
  avatarUrl: "mascot-doka.svg"
```
Если полный путь не принципиален, то лучше проще — он лучше считывается.

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +🛠 Иногда нам нужно сохранить не просто текст, а целую структуру данных, и в этом нам поможет `JSON.stringify`
```suggestion
🛠 Иногда нам нужно сохранить не просто текст, а целую структуру данных, и в этом нам поможет `JSON.stringify`.
```

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +- `key` - ключ, который был изменен (при вызове метода `clear()`, ключ будет `null`);
```suggestion
Событие содержит поля:

- `key` - ключ, который был изменен (при вызове метода `clear()`, ключ будет `null`);
```

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +При чтении ранее записанных данных по ключу `name` мы получим `Doka Dog`
```suggestion
При чтении ранее записанных данных по ключу `name` мы получим `Doka Dog`.
```

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +💡 максимальный объем данных ограничен размером 5MB;
```suggestion
- Позволяет сохранять текстовую информацию (при попытке сохранения других типов данных они будут приведены к строке. Из этого следует, что после сохранения числа, при попытке его получить, нам вернется число, записанное в строку).
- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
- Максимальный объем данных ограничен размером 5MB.
```

Тут надо определиться: либо это список, тогда просто дефисы в начале. Либо это несколько отдельных параграфов с советами — тогда отбить их и в начале каждого по эможди. Сейчас гибрид и рендериться он будет совсем не так, как выглядит в маркдауне.

2021-04-12 14:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +})
```suggestion
function changePageFontSize(size) {
  document.style.fontSize = `${size}px`
}

window.addEventListener('storage', function (evt) {
  if (evt.key === 'pageFontSize) {
    changePageFontSize(evt.newValue)
  }
})
```

2021-04-12 14:51 UTC, pepelsbey commented
@akellbl4 а давай закинем автора из #697 в этом же ПР? Кажется этот ПР без автора будет мёржить некорректно. И тогда тот ПР прикроем. Что скажешь? :)

2021-04-12 15:34 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +})
@pepelsbey мы не ставим `;`?

2021-04-12 21:42 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +})
Ага, такой [код-стайл](https://github.com/Y-Doka/y-doka.site/blob/master/.prettierrc#L2) для JS во всех остальных доках и демках.

2021-04-12 21:44 UTC, pepelsbey commented
> @pepelsbey можно, не стал смешивать просто.

Как я понял, мы тут ПР между ветками обычно не открываем, только в master, чтобы было понятнее, что происходит.

2021-04-13 07:04 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +})
Ясно, видел где-то что используется AirBnb а у них они вроде есть ;)

2021-04-13 13:47 UTC, pepelsbey commented on src/posts/js/doka/local-storage.md
> +  if (evt.key === 'pageFontSize) {
```suggestion
  if (evt.key === 'pageFontSize') {
```

Я бы ещё нормализовал одиночные и двойные кавычки. @nlopin у нас какие?

2021-04-13 13:50 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +  if (evt.key === 'pageFontSize) {
Важно чтобы везде были одинаковые конечно. Я старался везде делать двойные, но сам люблю одинарные в JS, поэтому так вышло :) держу в курсе

2021-04-13 13:51 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +window.addEventListener('storage', function (evt) {
```suggestion
window.addEventListener("storage", function (evt) {
```

2021-04-13 13:51 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +window.addEventListener('storage', function (evt) {
```suggestion
window.addEventListener("storage", function (evt) {
```

2021-04-13 13:52 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +window.addEventListener('storage', function (evt) {
```suggestion
window.addEventListener("storage", function (evt) {
```

2021-04-13 13:53 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +  if (evt.key === 'pageFontSize) {
```suggestion
  if (evt.key === "pageFontSize") {
```

2021-04-13 22:24 UTC, pepelsbey approved these changes

2021-04-15 14:05 UTC, nlopin requested changes
Класс! Давай еще добавим в конец «Кратко», что есть аналогичное хранилище для SessionStorage и сошлемся на вторую статью?

2021-04-15 14:05 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +Запись производит метод `setItem("ключ", "значение")`, который принимает два строковых параметра: ключ, по которому будет сохранено значение, и само значение.
```suggestion
Для записи используйте метод `setItem("ключ", "значение")`, который принимает два строковых параметра: ключ, по которому будет сохранено значение, и само значение.
```

2021-04-15 14:05 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +За чтение отвечает `getItem("ключ")` c одним параметром, который указывает на ключ для чтения и возвращает полученное значение из хранилища, если до этого значение не было записано по этому ключу, то
```suggestion
За чтение отвечает `getItem("ключ")` c одним параметром, который указывает на ключ для чтения и возвращает полученное значение из хранилища. Если по этому ключу нет значения, то метод вернет `null`.
```

2021-04-15 14:05 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +Удаляет запись из хранилища `removeItem("ключ")`. Так же успешно выполнится даже, если указанного ключа не существует в хранилище.
```suggestion
Удаляет запись из хранилища `removeItem("ключ")`. Он успешно выполнится даже если указанного ключа не существует в хранилище.
```

2021-04-15 14:05 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +При установке значения в хранилище срабатывает глобальное событие, с помощью которого можно отслеживать изменения в хранилище.
```suggestion
При установке значения в хранилище срабатывает глобальное событие `storage`, с помощью которого можно отслеживать изменения в хранилище.
```

2021-04-15 14:05 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +🛠 Иногда нам нужно сохранить не просто текст, а целую структуру данных, и в этом нам поможет `JSON.stringify`.
🔥

2021-04-15 20:54 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +- Максимальный объем данных ограничен размером 5MB.
это с mdn, спека не регламентирует размер

2021-04-20 08:09 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
уууу, чо за подстава

2021-04-21 09:44 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +💡 Событие происходит только других открытых страницах текущего сайта.
```suggestion
💡 Событие происходит только на других открытых страницах текущего сайта.
```

2021-04-21 09:47 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +Метод `key()` может получать ключ по индексу.
Так как значения в хранилище хранятся в порядке их добавления, то значение добавленное первым будет храниться в позиции `0` и так далее.

2021-04-21 09:48 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +Метод `key()` может получать ключ по индексу.
@nlopin что то такое смог придумал.

2021-04-21 10:05 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
```suggestion
- Не имеет ограничений по времени хранения, может быть очищен пользователем вручную или браузером при переполнении автоматически (браузеры основанные на WebKit, например Safari, очищают Local Storage если к нему не обрашались в течении 7 дней).
```

2021-04-22 06:57 UTC, nlopin commented on src/posts/js/doka/local-storage.md
> +- Максимальный объем данных ограничен размером 5MB.
Я посмотрел исходники хромиума и кажется они сейчас дают квоту на сторедж, а не на ключ.

Попробую сделать эксперимент

2021-04-22 07:09 UTC, akellbl4 commented on src/posts/js/doka/local-storage.md
> +- Максимальный объем данных ограничен размером 5MB.
Тут как раз имеется в виду весь сторадж, а не один ключ

2021-04-22 19:09 UTC, nlopin approved these changes

2021-04-22 19:09 UTC, merged

2021-04-23 09:11 UTC, akellbl4 commented
Huray!