Добавляет доку по Session Storage
Y-Doka/y-doka.site pull request #698
Opened 2021-04-12 15:30 UTC by akellbl4

2021-04-12 22:12 UTC, pepelsbey requested changes
В коде `;`, которые мы не ставим по стилю, ну и по мелочи.

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +author: Pavel Mineev
```suggestion
author: akellbl4
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +- Максимальный объем данных ограничен размером 5MB;
```suggestion
- Сессия страницы создается при открытии новой вкладки браузера и остается активной до тех пор пока не была закрыта, состояние сессии сохраняется между перезагрузками вкладки. Открыти новой вкладки с таким же адресом приводит к созданию новой сессии.
- Позволяет сохранять текстовую информацию (при попытке сохранения других типов данных они будут приведены к строке. Из этого следует, что после сохранения числа, при попытке его получить, нам вернется число, записанное в строку).
- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
- Максимальный объем данных ограничен размером 5MB.
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +
```suggestion
}
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +  // Если вдруг в хранилище оказался не валидный JSON предохраняемся от этого
```suggestion
  // Если вдруг в хранилище оказался невалидный JSON, предохраняемся от этого
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +🛠 Иногда нам нужно сохранить не просто текст, а целую структуру данных, и в этом нам поможет `JSON.stringify`
```suggestion
🛠 Иногда нам нужно сохранить не просто текст, а целую структуру данных, и в этом нам поможет `JSON.stringify`.
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +При чтении ранее записанных данных по ключу `name` мы получим `Doka Dog`
```suggestion
При чтении ранее записанных данных по ключу `name` мы получим `Doka Dog`.
```

2021-04-12 22:12 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +Это объект, хранящийся в `window`, который позволяет сохранять данные в браузере на время сессии. Данный тип хранилища очень похож на (localStorage)[/js/doka/local-storage] Представлен как хранилище
```suggestion
Это объект, хранящийся в `window`, который позволяет сохранять данные в браузере на время сессии. Данный тип хранилища очень похож на (`localStorage`)[/js/doka/local-storage] Представлен как хранилище данных в формате ключ-значение, т.е. при сохранении данных мы указываем имя поля, в которое должны быть сохранены данные, и далее используем это имя для их получения.
```

2021-04-13 07:01 UTC, akellbl4 commented
@pepelsbey спасибо за правки и за тепрение, потому что некоторые ошибки переехали из соседней статьи :)

2021-04-13 13:42 UTC, pepelsbey approved these changes

2021-04-13 13:49 UTC, pepelsbey approved these changes

2021-04-15 20:44 UTC, nlopin commented
@akellbl4 учтешь в этой статье комментарии из локалстореджа?

2021-04-19 07:54 UTC, akellbl4 commented on src/posts/js/doka/session-storage.md
> +- Сессия страницы создается при открытии новой вкладки браузера и остается активной до тех пор пока не была закрыта, состояние сессии сохраняется между перезагрузками вкладки. Открыти новой вкладки с
Да, значит именно это

2021-04-29 00:09 UTC, pepelsbey commented on src/posts/js/doka/session-storage.md
> +Так как значения в хранилище хранятся в порядке их добавления, то значение добавленное первым будет храниться в позиции `0` и так далее.
```suggestion
Метод `key()` может получать ключ по индексу. Так как значения в хранилище хранятся в порядке их добавления, то значение добавленное первым будет храниться в позиции `0` и так далее.
```

Стоит определиться: это один абзац или два? Кажется один :)

2021-04-29 18:23 UTC, akellbl4 commented on src/posts/js/doka/session-storage.md
> +Так как значения в хранилище хранятся в порядке их добавления, то значение добавленное первым будет храниться в позиции `0` и так далее.
Хорошо ;) тогда надо будет в local storage тоже поправить

2021-05-02 09:34 UTC, nlopin requested changes
Все отлично, думаю не хватает упоминания cookie как похожей технологии

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +Это объект, хранящийся в `window`, который позволяет сохранять данные в браузере на время сессии. Данный тип хранилища очень похож на (`localStorage`)[/js/doka/local-storage] Работает как хранилище д
```suggestion
Это объект, хранящийся в `window`, который позволяет сохранять данные в браузере на время сессии. Этот тип хранилища очень похож на (`localStorage`)[/js/doka/local-storage] и работает как хранилище данных в формате ключ-значение. При сохранении данных мы указываем имя поля, в которое должны быть сохранены данные, и затем используем это имя для их получения.
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +- Сессия страницы создается при открытии новой вкладки браузера и остается активной до тех пор пока она не была закрыта, состояние сессии сохраняется между перезагрузками вкладки. Открыти новой вклад
```suggestion
- Сессия страницы создается при открытии новой вкладки браузера. Сессия остается активной до тех пор пока открыта вкладка, а состояние сессии сохраняется между перезагрузками. Открытие новой вкладки с таким же адресом приводит к созданию новой сессии.
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +- Значения хранятся в виде строк. При попытке сохранения других типов данных, они будут приведены к строке. Например, если записать число, то при чтении нам вернется число, записанное в строку
```suggestion
- Значения хранятся в виде строк. При попытке сохранения других типов данных, они будут приведены к строке. Например, если записать число, то при чтении нам вернется число, записанное в строку.
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
мне кажется здесь неверный посыл. Лучше сказать, что хранит данные столько времени, сколько открыта вкладка

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +Метод `key()` может получать ключ по индексу. Так как значения в хранилище хранятся в порядке их добавления, то значение добавленное первым будет храниться в позиции `0` и так далее.
```suggestion
Метод `key()` получает ключ по индексу. Значения в хранилище хранятся в порядке их добавления, поэтому значение добавленное первым будет храниться в позиции `0` и так далее.
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +widow.sessionStorage.key(0) // вернет "name"
Давай тут докинем второй ключ, чтобы было более иллюстративно:
```suggestion
window.sessionStorage.setItem("name", "Doka Dog")
window.sessionStorage.setItem("id", "5ac9bc9d1984")
widow.sessionStorage.key(0) // вернет "name"
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +Таким образом, используя количество ключей в хранилище и получение ключа по индексу, можно организовать перебор всех значений в хранилище.
```suggestion
Таким образом, используя количество ключей в хранилище и получение ключа по индексу, можно перебрать все значения в хранилище.
```

2021-05-02 09:34 UTC, nlopin commented on src/posts/js/doka/session-storage.md
> +🛠 Session Storage в реальныйх проектах используется достаточно редко, но иногда может быть достаточно полезен. Например, если мы не хотим терять данные если пользователь случайно обновил страницу.
```suggestion
🛠 Session Storage в реальных проектах используется достаточно редко, но иногда может быть полезен. Например, если мы не хотим терять данные если пользователь случайно обновил страницу.
```

может тут еще сказать, что данные должны быть большими, чтобы уже не влазить в куки, но еще влазить в session storage? Они же очень похожи, странно, что мы про куки нигде не упомниаем в статье.

Если я не путаю, то в части браузеров ограничение на куки что-то типа 4 килобайта

2021-05-03 07:35 UTC, akellbl4 commented on src/posts/js/doka/session-storage.md
> +🛠 Session Storage в реальныйх проектах используется достаточно редко, но иногда может быть достаточно полезен. Например, если мы не хотим терять данные если пользователь случайно обновил страницу.
Только куки все таки живут намного дольше, конечно им про это надо сказать но все таки

2021-05-03 07:38 UTC, akellbl4 commented on src/posts/js/doka/session-storage.md
> +- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
Да, кажется это я случайно перенес из LS

2021-05-03 07:38 UTC, akellbl4 commented on src/posts/js/doka/session-storage.md
> +- Не имеет ограничений по времени хранения (может быть очищен пользователем вручную или браузером при переполнении автоматически).
```suggestion
```

2021-05-03 18:48 UTC, nlopin approved these changes

2021-05-03 18:49 UTC, merged