Добавляет статью про CSS-переменные
Y-Doka/y-doka.site pull request #706
Opened 2021-04-19 19:53 UTC by ezhkov

Закрывает #108

2021-04-20 06:26 UTC, solarrust reviewed
Очень классная статья, спасибо! 🖤

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +Обратите внимание, как в примере мы переопределяем значение переменной для карточки с классом `.card--primary`, и все дочерние элементы меняют цвет. В этом и кроется основная мощь CSS-переменных. Изм
Стоит вынести код примера в текст. Поскольку позже демка будет переделана так, что кода не будет видно совсем. Можно не весь код, а только ту часть, о которой пойдёт речь.

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +```css
Стоит разбить блок кода и дать короткие пояснения, что во втором случае не сработает

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +## В работе
Я бы добавила подсказку о том, что переменная вычисляется на клиенте. А так же акцентировала бы внимание на синтаксисе объявления, на особенностях именования.

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +## В работе
Можно ли использовать переменные в других функциях? Например, `calc()`

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="result" data-user="ezhkov" data-slug-hash="jOyvJdQ" style="height: 265px; box-sizing: border-box; display: flex; align-ite
Надо бы кнопочке добавить `cursor: pointer`

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +🛠 Можно даже применять CSS-переменные в инлайновых стилях
```suggestion
🛠 Можно даже применять CSS-переменные в инлайновых стилях:
```

2021-04-20 06:26 UTC, solarrust commented on src/posts/css/long/css-variables.md
> +Но что, если мы заренее не знаем, какой будет вложенность элементов? Можно задать CSS-свойство корневому элементу страницы `<body>`, и тогда оно гарантированно будет доступно в каждом элементе страни
```suggestion
Но что, если мы заренее не знаем, какой будет вложенность элементов? Можно задать CSS-свойство корневому элементу страницы `<body>`, и тогда оно гарантированно будет доступно в каждом элементе страницы. Но обычно для этих целей используют псевдокласс [`:root`](/html/doka/root) (в работе):
```

2021-05-05 12:30 UTC, pepelsbey requested changes
Предлагаю отказаться от «пользовательских» свойств в пользу «кастомных». Во-первых, это прямая калька (custom properties) и очень легко отследить оригинальный термин (user properties не существует). Во вторых, начинается путаница: есть автор (разработчик сайта), а есть пользователь (сайта) и тут автор становится пользователем.

2021-05-05 12:30 UTC, pepelsbey commented on src/posts/css/long/css-variables.md
> +Но что, если мы заренее не знаем, какой будет вложенность элементов? Можно задать CSS-свойство корневому элементу страницы `<body>`, и тогда оно гарантированно будет доступно в каждом элементе страни
```suggestion
Но что, если мы заренее не знаем, какой будет вложенность элементов? Можно задать CSS-свойство корневому элементу страницы `<html>`, и тогда оно гарантированно будет доступно в каждом элементе страницы. Но обычно для этих целей используют псевдокласс [`:root`](/html/doka/root) (в работе), который является псевдонимом `<html>`:
```

2021-05-05 12:30 UTC, pepelsbey commented on src/posts/css/long/css-variables.md
> +p.text {
```suggestion
.text {
```
См. выше.

2021-05-05 12:30 UTC, pepelsbey commented on src/posts/css/long/css-variables.md
> +У пользовательских свойств всё иначе. Значения CSS-переменных вычисляются в браузере непосредственно перед отрисовкой страницы. Браузер заранее не знает, в каком месте будет применена CSS-переменная,
```suggestion
У пользовательских свойств всё иначе. Значения CSS-переменных вычисляются в браузере непосредственно перед отрисовкой страницы. Браузер заранее не знает, в каком месте будет применена CSS-переменная, поэтому по умолчанию считает любую переменную корректной. И только после подстановки значения переменной браузер узнаёт, правильно ли мы её применили. Для такого поведения есть причины, рассмотрим пример:
```

2021-05-05 12:30 UTC, pepelsbey commented on src/posts/css/long/css-variables.md
> +.element.inverted {
```suggestion
.element--inverted {
```
Немного БЭМа

2021-05-07 09:33 UTC, tachisis reviewed
Немного правочек

2021-05-07 09:33 UTC, tachisis commented on src/posts/css/long/css-variables.md
> +Давайте предположим, что у нас есть веб-страница, на которой много элементов c текстом одного и того же цвета. Дизайнер нарисовал фирменный стиль, руководство утвердило, мы начали верстать. Наш CSS м
```suggestion
Давайте предположим, что у нас есть веб-страница, на которой много элементов c текстом одного и того же цвета. Дизайнер создал фирменный стиль, руководство утвердило, мы начали верстать. Наш CSS мог бы выглядеть примерно так:
```

2021-06-04 11:20 UTC, solarrust commented
Закрывает #https://github.com/Y-Doka/content/issues/797

2021-06-05 06:17 UTC, ezhkov commented on src/posts/css/long/css-variables.md
> +      <li class="benefits-item">2 ГБ трафика</li>
Не согласен с исправлением) Гб — это "гигабит". В нашем случае мы говорим про "гигабайт", а у него есть устоявшееся обозначение — ГБ.

2021-06-07 15:59 UTC, closed without merging