Добавляет статью "Интерфейс командной строки"
Y-Doka/y-doka.site pull request #707
Opened 2021-04-20 16:01 UTC by igsekor

2021-04-21 12:32 UTC, ValyaBro requested changes
Очень хорошо получилось! Сбалансированно и не сжато. Я бы доработала два момента: 1. хочется использовать более нейтральные цвета. Красный и зелёный уже несут в себе смысловую нагрузку (неправильно / правильно, не работает / работает). Кажется тут этот слой смыслов от цвета – лишний. И давай попробуем увеличить ширину блоков, чтобы текст был максимум на три строчки? Сейчас получаеться сильная лесенка и становиться сложно читать

2021-04-21 14:02 UTC, pepelsbey requested changes
У нас в гайде [по типографике](https://github.com/Y-Doka/content/blob/master/docs/typography.md) есть про шорткаты:

> Шорткаты оборачивайте в тег `<kbd>`, названия кнопок пишите через пробел, а не через плюс

2021-04-21 14:06 UTC, igsekor commented
> У нас в гайде [по типографике](https://github.com/Y-Doka/content/blob/master/docs/typography.md) есть про шорткаты:
> 
> > Шорткаты оборачивайте в тег `<kbd>`, названия кнопок пишите через пробел, а не через плюс

Да, точно же! Забыл :)

2021-04-21 14:28 UTC, igsekor commented
> Очень хорошо получилось! Сбалансированно и не сжато. Я бы доработала два момента: 1. хочется использовать более нейтральные цвета. Красный и зелёный уже несут в себе смысловую нагрузку (неправильно / правильно, не работает / работает). Кажется тут этот слой смыслов от цвета – лишний. И давай попробуем увеличить ширину блоков, чтобы текст был максимум на три строчки? Сейчас получаеться сильная лесенка и становиться сложно читать

Я попробовал изменить.

@ValyaBro

2021-04-25 12:19 UTC, igsekor commented
Еще забыл статью с ишью связать, чтобы потом не забыть закрыть. Исправляю: https://github.com/Y-Doka/content/issues/315

2021-04-25 16:14 UTC, tachisis requested changes

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Последовательность символов важна: `r` может стоять только на первом месте, `w` — на втором, а `x` — на третьем. Первый символ `-` в начале строки показывает, что перед нами обычный файл. Если он буд
Неясно, кто равен.

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Цифры переводятся в восьмеричную систему счисления из флагов, записанных в двоичной системе. Если вы будете пользоваться цифрами то легко запомнить, что положение букв в символьной записи и чисел дво
```suggestion
Цифры переводятся в восьмеричную систему счисления из флагов, записанных в двоичной системе. Если вы будете пользоваться цифрами, то легко запомнить, что положение букв в символьной записи и чисел двоичного кода связано. Например, выражение `rw-` является аналогом `110`, что в восьмеричной системе будет равно `6`. Вы можете посмотреть полный список в [таблице](https://ru.wikipedia.org/wiki/Chmod).
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Таким образом, каждому файлу ставится в соответствие владелец и группа владельцев (UID и GID), а также три числа для указания прав, которые есть у владельца (UID), группы владельцев (GID) и всех оста
```suggestion
Таким образом каждому файлу ставится в соответствие владелец и группа владельцев (UID и GID), а также три числа для указания прав, которые есть у владельца (UID), группы владельцев (GID) и всех остальных пользователей. Чтобы узнать имя вашего пользователя, выполните:
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Создавние нового пользователя <username> и одноименной папки в /home
```suggestion
# Создание нового пользователя <username> и одноименной папки в /home
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Если что-то пошло не так (например поехали шрифты или временно применились не те настройки), можно произвести реинициализацию терминала без его перезагрузки:
```suggestion
Если что-то пошло не так (например, поехали шрифты или временно применились не те настройки), можно произвести реинициализацию терминала без его перезагрузки:
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Можно найти команду, которая была выполнена ранее, введя часть символов, предварительно нажав <kbd>Ctrl r</kbd> (на некоторых операционных системах <kbd>Ctrl Shift r</kbd>). Вы сможете ввести последо
```suggestion
Выполненную ранее команду можно найти, нажав <kbd>Ctrl R</kbd> (на некоторых операционных системах <kbd>Ctrl Shift R</kbd>) и введя несколько символов. После этого наиболее подходящая команда будет показана. Если вы нажмете <kbd>Enter</kbd>, то она выполнится, если воспользуетесь стрелками <kbd>→</kbd>, <kbd>←</kbd>, то можно будет ее отредактировать. Повторное нажатие сочетания клавиш <kbd>Ctrl R</kbd> (на некоторых операционных системах <kbd>Ctrl Shift R</kbd>) продолжит поиск, и будут показаны другие варианты, подходящие под поисковый запрос.
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 1: Выполняется предыдущая команда
```suggestion
# Пример 1: выполняется предыдущая команда
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 2: Использование текста предыдущей команды
```suggestion
# Пример 2: использование текста предыдущей команды
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 3: Использование при отказе в доступе
```suggestion
# Пример 3: использование при отказе в доступе
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +... Access denided
```suggestion
... Access denied
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 4: Замена части текста в предыдущей команде
```suggestion
# Пример 4: замена части текста в предыдущей команде
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +```
Возможно, имеет смысл разбить эту простыню на 4 разных вставки кода, вынести названия из комментария и убрать «Пример»

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 1: Использование значения последнего аргумента
```suggestion
# Пример 1: использование значения последнего аргумента
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 2: Создание директории с похожим именем
```suggestion
# Пример 2: создание директории с похожим именем
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Пример 3: Подстановка всех аргументов
```suggestion
# Пример 3: подстановка всех аргументов
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +```
С этой простыней так же.

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Выполнить нескольких команд подряд можно так
```suggestion
Выполнить нескольких команд подряд можно так:
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +# Выполнение несокльких команд последовательно
```suggestion
# Выполнение нескольких команд последовательно
```

2021-04-25 16:14 UTC, tachisis commented on src/posts/js/tools/cli.md
> +`<number>` — номер фонового процесса. Число, которое соответствует `<PID>` можно использовать для мониторинга и управления. Пример:
```suggestion
`<number>` — номер фонового процесса. Число, которое соответствует `<PID>`, можно использовать для мониторинга и управления. Пример:
```

2021-04-25 17:47 UTC, igsekor commented on src/posts/js/tools/cli.md
> +Последовательность символов важна: `r` может стоять только на первом месте, `w` — на втором, а `x` — на третьем. Первый символ `-` в начале строки показывает, что перед нами обычный файл. Если он буд
Поправил.

2021-04-25 17:57 UTC, igsekor commented on src/posts/js/tools/cli.md
> +```
Сделал

2021-04-25 17:57 UTC, igsekor commented on src/posts/js/tools/cli.md
> +```
Сделал

2021-04-25 19:06 UTC, tachisis requested changes

2021-04-25 19:06 UTC, tachisis commented on src/posts/js/tools/cli.md
> +Выполнить предыдущую команда:
```suggestion
Выполнить предыдущую команду:
```

2021-04-25 19:06 UTC, tachisis commented on src/posts/js/tools/cli.md
>  Выполнить нескольких команд подряд можно так:
```suggestion
Выполнить несколько команд подряд можно так:
```

2021-04-26 08:14 UTC, tachisis approved these changes

2021-04-26 20:12 UTC, pepelsbey reviewed
Тут такое дело: приглашение командной строки в виде префикса `>` это хорошая деталь для интро (кстати, она иногда $), но показывать её в примерах — это плохая практика. Дело в том, что не все понимают, что примеры нужно копировать **без неё.** И в итоге это мешает новичкам и даже усложняет копирование, если ты хочешь потренироваться.

Я бы убрал её из примеров к этой статье и добавил к нам правило, что в примерах CLI мы не пишем никаких приглашений — только саму команду. @tachisis норм?

Даже больше: когда я редактировал [статью про Докер](https://web-standards.ru/articles/docker-unboxing-1/) для Веб-стандартов, где тоже много ввода-вывода, я инвертировал схему:

1. Команда отображается как есть
2. Каждая строка вывода префиксуется с помощью `>`

```sh
docker run hello-world

> Unable to find image 'hello-world:latest' locally
> latest: Pulling from library/hello-world
> 0e03bdcc26d7: Pull complete
> Digest: sha256:e7c70bb24b462baa86c102610182e3efcb12a04854e8c582838d92970a09f323
> Status: Downloaded newer image for hello-world:latest
>
> Hello from Docker!
```

Это помогает явно отличить, что есть команда, а что вывод. Плюс есть традиция показывать вывод в JS в консоль с помощью угловой скобки.

2021-04-26 20:21 UTC, pepelsbey reviewed
Если говорить про выводы примеров команд, то я бы избегал цельных блоков кода, где текст выпрямлен в строку и не переносится и набран (как типичный комментарий) бледным цветом:

```
# Создавние нового <username> пользователя
> useradd <username>

# Создание нового пользователя <username> и одноименной папки в /home
> useradd -m <username>

# Посмотреть всех пользователей
> cut -d: -f1 /etc/passwd

# Изменение пароля пользователя
> passwd

# Создание новой группы пользователей <usergroup>
> groupadd <usergroup>

# Добавление пользователя <username> в группу пользователей <usergroup>
> usermod -a -G <usergroup> <username>

# Удаление пользователя <username> из группы пользователей <usergroup>
> gpasswd -d <username> <usergroup>

# Удаление группы пользователей
> groupdel

# Посмотреть все группы, в которых состоит пользователь
> groups

# Посмотреть все группы пользователей
> cut -d: -f1 /etc/group
```

Лучше сделать вот так:

- `useradd <username>` — cоздавние нового `<username>` пользователя
- `useradd -m <username>` — создание нового пользователя `<username>` и одноименной папки в `/home`
- `cut -d: -f1 /etc/passwd` —  посмотреть всех пользователей.

…и так далее.

Так мы возвращаемся к тексту с примерами кода (команд) и уходим от цельного куска кода, который неудобно читать. @tachisis что скажешь?

2021-04-26 21:05 UTC, igsekor commented
> Это помогает явно отличить, что есть команда, а что вывод. Плюс есть традиция показывать вывод в JS в консоль с помощью угловой скобки.

Я не против. Исправлю, как решим. Но есть и возражения, на основании которых я сделал именно так, как сделал. В этой статье про командную строку важно подчеркнуть, что всегда есть приглашение командной строки. Тот стиль описания команд я выбрал абсолютно умышленно.  Важно научить человека понимать, что приглашение командной строки всегда присутствует. Вот зачем я сделал так. Если это по-прежнему неудачное решение, то я все исправлю.

@pepelsbey @tachisis @nlopin что думаете?

2021-04-26 21:06 UTC, igsekor commented
> Если говорить про выводы примеров команд, то я бы избегал цельных блоков кода, где текст выпрямлен в строку и не переносится и набран (как типичный комментарий) бледным цветом:
> 
> ```
> # Создавние нового <username> пользователя
> > useradd <username>
> 
> # Создание нового пользователя <username> и одноименной папки в /home
> > useradd -m <username>
> 
> # Посмотреть всех пользователей
> > cut -d: -f1 /etc/passwd
> 
> # Изменение пароля пользователя
> > passwd
> 
> # Создание новой группы пользователей <usergroup>
> > groupadd <usergroup>
> 
> # Добавление пользователя <username> в группу пользователей <usergroup>
> > usermod -a -G <usergroup> <username>
> 
> # Удаление пользователя <username> из группы пользователей <usergroup>
> > gpasswd -d <username> <usergroup>
> 
> # Удаление группы пользователей
> > groupdel
> 
> # Посмотреть все группы, в которых состоит пользователь
> > groups
> 
> # Посмотреть все группы пользователей
> > cut -d: -f1 /etc/group
> ```
> 
> Лучше сделать вот так:
> 
> * `useradd <username>` — cоздавние нового `<username>` пользователя
> * `useradd -m <username>` — создание нового пользователя `<username>` и одноименной папки в `/home`
> * `cut -d: -f1 /etc/passwd` —  посмотреть всех пользователей.
> 
> …и так далее.
> 
> Так мы возвращаемся к тексту с примерами кода (команд) и уходим от цельного куска кода, который неудобно читать. @tachisis что скажешь?

2021-04-26 21:07 UTC, igsekor commented
> Так мы возвращаемся к тексту с примерами кода (команд) и уходим от цельного куска кода, который неудобно читать. @tachisis что скажешь?

Жду тогда решения.

2021-04-26 21:22 UTC, nlopin commented on src/posts/js/tools/cli.md
> +![Структура интерфейса командной строки](assets/images/posts/js/cli/cli-command.png)
```suggestion
![Структура интерфейса командной строки](/assets/images/posts/js/cli/cli-command.png)
```

2021-04-26 21:22 UTC, nlopin commented on src/posts/js/tools/cli.md
> +![Типы ссылок в Unix-подобных системах](assets/images/posts/js/cli/cli-links.png)
```suggestion
![Типы ссылок в Unix-подобных системах](/assets/images/posts/js/cli/cli-links.png)
```

2021-04-26 21:22 UTC, nlopin commented on src/posts/js/tools/cli.md
> +![Схема проверки доступа к файлу или директории](assets/images/posts/js/cli/cli-access.png)
```suggestion
![Схема проверки доступа к файлу или директории](/assets/images/posts/js/cli/cli-access.png)
```

2021-04-27 00:06 UTC, pepelsbey commented
Приглашение командной строки — не часть команды, это интерфейс конкретной оболочки. Приглашение может быть любым — как настроишь его вывод, какую ОС выберешь. На macOS это будет `$`. В этой статье есть примеры кода, которые буквально говорят «вот эта команда делает вот это», но каждая из них содержит символ, который в этой команде не нужен и уже есть в твоей консоли.

Рассказать, что приглашение значит и что они бывают разные — важно, тут я не спорю. Но вот выводить его как часть каждой команды — это путать новичков, которые первый раз читают статью про CLI. Это нам не нужно :)

2021-04-27 07:52 UTC, igsekor commented
Ну не нужно, значит не нужно. Исправляю. :)

2021-04-27 10:38 UTC, pepelsbey commented on src/posts/js/tools/cli.md
> +```
````suggestion
Разархивация большого архива в приоритетном режиме:

```bash
tar xf archive.zip
```

Разархивация большого архива в фоновом режиме:

```bash
tar xf archive.zip &
> [<number>] <PID>
```
````

2021-04-27 11:18 UTC, pepelsbey approved these changes

2021-04-28 15:57 UTC, nlopin commented
На мой взгляд, приглашение `>` очень хорошо выделяло команды, но я согласен, что оно мешает копированию.

Меня беспокоит раздел «Группы и пользователи». 

Он очень важен в контексте доступа к операциям, но эта часть дана очень быстро. Мы говорим только про одну запись `rwx`, но не говорим о числовом представлении (777 и всё такое).

С другой стороны, очень подробно освещены части, связанные с добавлением пользователя в группы, просмотр групп. Я, как разработчик, писал эти команды может с десяток раз за всю карьеру, ограничиваясь `chown` и `chmod`. Насколько знание `gpasswd` и  `usermod` поможет начинающему? какой юзкейс у этих команд?

2021-04-28 16:16 UTC, igsekor commented
> На мой взгляд, приглашение `>` очень хорошо выделяло команды, но я согласен, что оно мешает копированию.

Есть два полярных мнения. Мы либо выкручиваемся с выводом команд, либо выкручиваемся с их копированием и вставкой. Наверное, Вадим прав с точки зрения удобства читателя. Но выглядит все не так, как в терминале. Это хорошо в интерфейсе npm работает, но при работе с командной строкой приходится чем-то жертвовать.

> Он очень важен в контексте доступа к операциям, но эта часть дана очень быстро. Мы говорим только про одну запись `rwx`, но не говорим о числовом представлении (777 и всё такое).

@nlopin я описал коды. Более того, хотел еще спец. табличку вставить, но не придумал, как это сделать классно (картинка, табличка, список). Подскажите, как быть @pepelsbey @tachisis

2021-04-29 00:05 UTC, pepelsbey commented
> Более того, хотел еще спец. табличку вставить, но не придумал, как это сделать классно

Если это с текстом, то лучше табличку :)

2021-04-29 12:22 UTC, igsekor commented
Добавил табличку.

2021-04-29 21:53 UTC, pepelsbey commented
Мы сегодня в мастере починили спеллер и надо бы его сюда подмёржить, чтобы адекватно оценить состояние статьи :)

2021-04-30 12:55 UTC, ValyaBro requested changes
классное прогресс по картинкам! Хочется чуть привести в систему цвета и немного повысить читабельность (укрупнить шрифты и т.п.) добавила комментарии и версии в фигму.

2021-04-30 13:49 UTC, igsekor commented
> классное прогресс по картинкам! Хочется чуть привести в систему цвета и немного повысить читабельность (укрупнить шрифты и т.п.) добавила комментарии и версии в фигму.

А вот и правда классно стало! :) Спасибо @ValyaBro

2021-04-30 14:24 UTC, igsekor commented
> Мы сегодня в мастере починили спеллер и надо бы его сюда подмёржить, чтобы адекватно оценить состояние статьи :)

Сначала подумал, что он прямо сюда прикручен, но нет :) Прикрутил руками, проверил, исправил (пару опечаток и слова с ё). Наверное надо еще добавить слова в `.yaspeller.json` или заменить на аналоги? Вот список, но похоже, что это устоявшиеся термины:
- автодополнение;
- отмонтировать;
- реинициализацию.

2021-04-30 22:30 UTC, pepelsbey commented
Мне «реинициализация» кажется сложноватым, остальные два вроде устоялись и я бы их добавил в исключения.

@tachisis что скажешь?

2021-05-01 12:28 UTC, igsekor commented
> Мне «реинициализация» кажется сложноватым (повторная инициализация?)

Перефразировал

2021-05-02 09:43 UTC, nlopin commented on src/posts/js/tools/cli.md
> +![Структура интерфейса командной строки](/assets/images/posts/js/cli/cli-command.png)
@ValyaBro @igsekor  А может на картинке приведем пример? 

Меня смущает `prompt`. В формулировке, что мы показываем структуру интерфейса, это верно, но мы хотим именно эту ментальную модель транслировать читателю? Не ментальную модель «структура команды в терминале»?

2021-05-02 09:44 UTC, nlopin commented on src/posts/js/tools/cli.md
> +
вот сюда бы пример различных приглашений

2021-05-02 09:46 UTC, igsekor commented on src/posts/js/tools/cli.md
> +![Структура интерфейса командной строки](/assets/images/posts/js/cli/cli-command.png)
@nlopin предлагаю тогда после рисунка добавить примеров, как может выглядеть prompt. Что скажешь?

2021-05-02 09:53 UTC, nlopin commented on src/posts/js/tools/cli.md
> +Сочетание клавиш <kbd>Ctrl A</kbd> позволяет переместиться к началу строки, <kbd>Ctrl E</kbd> — к концу. Нажав <kbd>Ctrl L</kbd> вы сможете очистить экран, переместив строку приглашения на верх окна.
Я запишу микроскринкаст сюда

2021-05-02 09:57 UTC, nlopin commented on src/posts/js/tools/cli.md
> +Управлять пользователями и группами пользователей в операционных системах семейства Linux можно с помощью набора команд:
Давай только самые основные оставим:
* добавить пользователя, посмотреть всех пользователей
* добавим `chmod` и `chown`. Мы их используем в примерах и они очень часто используются, но я не нашел их описания в статье

2021-05-02 09:58 UTC, nlopin requested changes

2021-05-02 09:58 UTC, nlopin commented on src/posts/js/tools/cli.md
> +На Mac, например, управлять пользователями можно не только через графический интерфейс, но и с помощью консольной утилиты `dscl`:
Давай уберем, чтобы не перегружать

2021-05-02 10:32 UTC, pepelsbey approved these changes

2021-05-02 12:32 UTC, nlopin commented on src/posts/js/tools/cli.md
> +Сочетание клавиш <kbd>Ctrl A</kbd> позволяет переместиться к началу строки, <kbd>Ctrl E</kbd> — к концу. Нажав <kbd>Ctrl L</kbd> вы сможете очистить экран, переместив строку приглашения на верх окна.
записал, но закину уже когда статья будет в репе `content`

2021-05-04 21:36 UTC, igsekor commented on src/posts/js/tools/cli.md
> +Управлять пользователями и группами пользователей в операционных системах семейства Linux можно с помощью набора команд:
@nlopin они описаны чуть выше выделенного фрагмента.

2021-05-04 21:40 UTC, igsekor commented on src/posts/js/tools/cli.md
> +На Mac, например, управлять пользователями можно не только через графический интерфейс, но и с помощью консольной утилиты `dscl`:
Убрал.

2021-05-05 07:14 UTC, ValyaBro approved these changes
картинки ок

2021-05-05 21:46 UTC, nlopin approved these changes

2021-05-05 21:46 UTC, merged