Дополняет статью про <link>
Y-Doka/y-doka.site pull request #708
Opened 2021-04-21 21:45 UTC by corocoto

### Изменения:

1. Произведены небольшие правки по описанию тега;
2. Дополнено описание атрибута `media`;
3. Добавлены новые атрибуты и описание по ним;
4. Добавлен раздел об оптимизации

2021-04-21 22:12 UTC, pepelsbey commented
Спасибо за дополнение! Немного привёл к тому, как мы сейчас пишем код и форматируем тексты.

2021-04-22 05:33 UTC, corocoto commented
С утра заметил небольшие недочеты по тексту (опечатки и т.д.). Решил поправить.

2021-04-22 06:12 UTC, solarrust requested changes
Огромное спасибо за доработку статьи 🖤
Оставила несколько стилистических предложений.

2021-04-22 06:12 UTC, solarrust commented on src/posts/html/doka/link.md
> +2. Вы планируете ускорить подключение более чем к 4−6 доменам: тег `<link rel="preconnect">` не рекомендуется использовать более чем с 4−6 доменами. `<link rel="dns-prefetch">` потребляет меньше ресу
```suggestion
1. Вы планируете ускорить подключение более чем к 4−6 доменам: тег `<link rel="preconnect">` не рекомендуется использовать более чем с 4−6 доменами. `<link rel="dns-prefetch">` потребляет меньше ресурсов, поэтому в случае необходимости используйте его.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +  Также атрибут `media` может определять то, какую тему использует ваша ОС. Благодаря этому можно произвести небольшие оптимизации. Например, если у нас есть два разделенных CSS-файла, каждый из кото
```suggestion
  Также атрибут `media` может определять, какая тема используется в ОС. Благодаря этому можно произвести небольшие оптимизации. Например, если у нас есть два разделенных CSS-файла, каждый из которых содержит стили для одной из тем, то приоритет при загрузке будет отдаваться именно тому файлу, который относится к выбранной системной теме:
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +`link` — очень мощный и гибко настраиваемый тег. С его помощью можно производить ряд возможных оптимизаций, давайте их рассмотрим.
```suggestion
`link` — очень мощный и гибко настраиваемый тег. С его помощью можно многое оптимизировать, давайте посмотрим, как.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +### Условная загрузка ресурсов с медиазапросами:
```suggestion
### Условная загрузка ресурсов с медиазапросами
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +Вы можете предоставить тип медиа или запрос внутри атрибута `media`. Этот ресурс будет загружен только в том случае, если прописанные условия соответствуют действительности.
```suggestion
Вы можете обозначить тип или условие внутри атрибута `media`. Этот ресурс будет загружен только в том случае, если прописанные условия соответствуют действительности.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +`<link rel="preload">` говорит браузеру как можно скорее загрузить и кэшировать ресурс (например, скрипт или таблицу стилей). Это полезно, когда ресурс понадобится через несколько секунд после загруз
```suggestion
`<link rel="preload">` говорит браузеру как можно скорее загрузить и кэшировать ресурс (например, скрипт или таблицу стилей). Это полезно, когда ресурс понадобится через несколько секунд после загрузки страницы, и вы хотите ускорить процесс.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +### Предварительное подключение к домену (`preconnect`):
```suggestion
### Предварительное подключение к домену (`preconnect`)
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +Используйте этот тег, чтобы немного ускорить загрузку стороннего скрипта или стиля за счёт предварительной установки соединения. Но не забывайте о том, что установка и поддержание соединения — дорого
```suggestion
Используйте этот тег, чтобы немного ускорить загрузку стороннего скрипта или стилей за счёт предварительной установки соединения. Но не забывайте о том, что установка и поддержание соединения — дорогостоящая операция как для клиента, так и для сервера. Поэтому используйте `preconnect` максимум для 4-6 доменов.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +### Предварительное разрешение записи DNS (`dns-prefetch`):
```suggestion
### Предварительное разрешение записи DNS (`dns-prefetch`)
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +Использовать их вместе для одного домена обычно не имеет смысла, так как `<link rel="preconnect">` уже включает в себя `<link rel="dns-prefetch">` и многое другое. Это можно оправдать в двух случаях:
```suggestion
Использовать их вместе для одного домена обычно не имеет смысла, так как `<link rel="preconnect">` уже включает в себя `<link rel="dns-prefetch">` и многое другое. Это может быть оправданным в двух случаях:
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +1. Вы планируете поддерживать старые браузеры: ипользуйте `<link rel="dns-prefetch">` в качестве запасного варианта для `<link rel="preconnect">`.
```suggestion
1. Вы планируете поддерживать старые браузеры: используйте `<link rel="dns-prefetch">` в качестве запасного варианта для `<link rel="preconnect">`.
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +### Предзагрузка и пререндер страницы (`prerender`):
```suggestion
### Предзагрузка и пререндер страницы (`prerender`)
```

2021-04-22 11:41 UTC, tachisis commented on src/posts/html/doka/link.md
> +Но не злоупотребялйте такой возможностью! Предварительный рендеринг чрезвычайно дорого обходится с точки зрения трафика и памяти. Поэтому не используйте `<link rel="prerender">` более чем для одной с
```suggestion
Но не злоупотребляйте такой возможностью! Предварительный рендеринг чрезвычайно дорого обходится с точки зрения трафика и памяти. Поэтому не используйте `<link rel="prerender">` более чем для одной страницы.
```

2021-04-23 16:45 UTC, corocoto commented on src/posts/html/doka/link.md
> +В качестве примера рассмотрим два наиболее часто встречаемых случая:
@tachisis, принял изменения, указанные @solarrust https://github.com/Y-Doka/y-doka.site/pull/708#discussion_r618099361.

Мне кажется, больше не стоит править эту фразу. Сейчас она сформирована идеально (кратко и доходчиво). 

P.S. Если не согласен, с радостью готов обсудить

2021-04-23 16:46 UTC, corocoto commented on src/posts/html/doka/link.md
> +В качестве примера рассмотрим два наиболее часто встречаемых случая:
И да, спасибо за правки 🙃

2021-04-23 18:44 UTC, corocoto commented on src/posts/html/doka/link.md
> +  Также атрибут `media` может определять то, какую тему использует ваша ОС. Благодаря этому можно произвести небольшие оптимизации. Например, если у нас есть два разделенных CSS-файла, каждый из кото
@solarrust, принял изменения, указанные @tachisis https://github.com/Y-Doka/y-doka.site/pull/708#discussion_r618318037

Если есть что добавить или поправить в этом разделе, с радостью готов обсудить 🙂

2021-04-23 21:55 UTC, pepelsbey commented on src/posts/html/doka/link.md
> +Рассмотрим два наиболее часто встречаемых случая:
```suggestion
Рассмотрим два наиболее часто встречающихся случая:
```
Так правда лучше, по следам ревью @tachisis

2021-04-24 06:06 UTC, corocoto commented on src/posts/html/doka/link.md
> +Рассмотрим два наиболее часто встречаемых случая:
@pepelsbey, хм, похоже, что да. 

И да, спасибо за правки🙂

2021-04-24 06:11 UTC, corocoto commented on src/posts/html/doka/link.md
> +В качестве примера рассмотрим два наиболее часто встречаемых случая:
https://github.com/Y-Doka/y-doka.site/pull/708#discussion_r619514492

2021-04-26 06:37 UTC, solarrust approved these changes

2021-04-26 08:13 UTC, tachisis approved these changes

2021-04-26 20:06 UTC, pepelsbey approved these changes

2021-04-27 08:29 UTC, merged