Добавляет статью про тег <picture>
Y-Doka/y-doka.site pull request #712
Opened 2021-04-25 13:29 UTC by ezhkov

Закрывает #637

2021-04-26 06:48 UTC, solarrust reviewed
Класс, спасибо за статью!

Кажется, важно сказать про несколько специфичных вещей для этого тега:
1. В каком порядке нужно указывать борцы внутри пикчи. Вычисление идёт сверху вниз. У многих новичков с этим затыка.
2. Важно сказать, что пикча — не контейнер в полном смысле слова. Все стили надо применять к вложенной картинке. Пикча просто помощник для браузера при выборе пути до картинки.
3. Было бы круто сказать про то, загружает ли браузер в фоне ненужные картинки из сорцов.

2021-04-26 06:48 UTC, solarrust commented on src/posts/html/doka/picture.md
> +Одна и та же страница может быть открыта на разных устройствах и в окнах разной ширины. У телефона небольшой экран и бы круто не грузить полноразмерные фотки с большим разрешением. В CSS мы можем изм
Надо уточнить о каких окнах речь =)

2021-04-26 06:48 UTC, solarrust commented on src/posts/html/doka/picture.md
> +Одна и та же страница может быть открыта на разных устройствах и в окнах разной ширины. У телефона небольшой экран и бы круто не грузить полноразмерные фотки с большим разрешением. В CSS мы можем изм
```suggestion
Одна и та же страница может быть открыта на разных устройствах и в окнах разной ширины. У телефона небольшой экран и было бы круто не грузить полноразмерные картинки с большим разрешением. В CSS мы можем изменять фон элемента ([`background-image`](/css/doka/background-image)) в зависимости от ширины экрана, используя медиа-выражения. Но если изображение является контентным, вставлено в HTML при помощи тега [`<img>`](/html/doka/img), то CSS нам уже не поможет. Мы должны использовать теги `<picture>` и [`<source>`](/html/doka/source).
```

2021-04-26 06:48 UTC, solarrust commented on src/posts/html/doka/picture.md
> +В общем случае внутри тега `<picture>` обязательно должен находиться тег [`<img>`](/html/doka/img), и опционально — теги [`<source>`](/html/doka/source).
```suggestion
Внутри тега `<picture>` обязательно должен находиться тег [`<img>`](/html/doka/img), и опционально — теги [`<source>`](/html/doka/source).
```

2021-04-26 06:48 UTC, solarrust commented on src/posts/html/doka/picture.md
> +В этом примере при помощи атрибута `media` в теге [`<source>`](/html/doka/source) мы задаём медиа-условие по аналогии с медиа-выражением `@media` в CSS. Если медиа-условие определяется как ложное, то
```suggestion
В этом примере при помощи атрибута `media` в теге [`<source>`](/html/doka/source) мы задаём условие по аналогии с медиавыражением [`@media`](/css/doka/media) (в работе) в CSS. Если условие определяется как ложное, то элемент `<source>` пропускается.
```

2021-04-28 10:50 UTC, solarrust commented on src/posts/html/doka/picture.md
> +  <img src="/some/url/to/other-image-640.jpg" alt="" />
```suggestion
  <img src="/some/url/to/other-image-640.jpg" alt="Абстрактное изображение">
```

2021-04-28 10:57 UTC, solarrust approved these changes

2021-04-28 12:36 UTC, pepelsbey reviewed
У меня есть пара предложений:

1. Не использовать внешние сервисы с картинками в примерах к статье: они могут закрыться и вообще тянут данные наших пользователей через свои ресурсы. И грузятся медленнее, кстати. Понимаю, что на CodePen выбора нет. Но можно начать [делать демки по-новому](https://github.com/Y-Doka/content/blob/master/docs/demos.md) ;)
2. Поменять примеры в коде на минимально достаточные.

Например: `/some/url/to/other-image-640.jpg` избыточный, достаточно `640.jpg`, но лучше, чтобы не было сомнений, что это ширина: `640x320.jpg`.

```html
<picture>
  <source srcset="320x160.jpg" media="(max-width: 800px)">
  <img src="640x320.jpg" alt="">
</picture>
```

Если бы речь шла про пути к картинкам, то это было бы оправдано. Но здесь лучше сфокусироваться на важном. Минимальный префикс `images/640x320.jpg` кажется уместным, особенно если это буквальное содержимое демки.

Что скажете?

2021-04-29 11:12 UTC, tachisis reviewed
Немножко правочек

2021-04-29 11:12 UTC, tachisis commented on src/posts/html/doka/picture.md
> +💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения разных устройствах. Пользователи мобильных телефонов будут вам очень багодарны, если для них вы будет
```suggestion
💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения на разных устройствах. Пользователи мобильных телефонов будут вам очень багодарны, если для них вы будете готовить картинки с меньшим разрешением. В то же время пользователям настольных ПК с экранами высокой чёткости можно показывать картинки с увеличенным разрешением:
```

2021-04-29 11:12 UTC, tachisis commented on src/posts/html/doka/picture.md
> +В этом примере пользователи с обычными экранами увидят картинку с надписью `768x400`. Пользователи, у которых retina-дисплеи, увидят надпись `1536x800`
```suggestion
В этом примере пользователи с обычными экранами увидят картинку с надписью `768x400`. Пользователи, у которых retina-дисплеи, увидят картинку с надписью `1536x800`
```

2021-04-29 11:12 UTC, tachisis commented on src/posts/html/doka/picture.md
> +Одна из частых ошибок при работе с тегом `<picture>` — забытый тег `<img>`. Помните, что браузер показывает изображение **исключительно** при помощи тега `<img>`, а теги `<source>` только помогают вы
```suggestion
Одна из частых ошибок при работе с тегом `<picture>` — забытый тег `<img>`. Помните, что браузер показывает изображение **исключительно** при помощи тега `<img>`, а теги `<source>` только помогают выбрать нужный URL картинки для текущих условий. Поэтому если внутри `<picture>` не будет тега `<img>`, то и показывать браузеру будет нечего.
```

2021-05-05 11:39 UTC, pepelsbey requested changes

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +  <img src="/some/url/to/other-image-640.jpg" alt="Абстрактное изображение">
```suggestion
  <source srcset="320.jpg" media="(max-width: 800px)">
  <img src="640.jpg" alt="Абстрактное изображение">
```

Пути здесь не добавляют полезной информации, думаю достаточно имени файла.

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +Одна и та же страница может быть открыта на разных устройствах и в браузерных окнах разной ширины. У телефона небольшой экран, и было бы круто не грузить полноразмерные картинки с большим разрешением
```suggestion
Одна и та же страница может быть открыта на разных устройствах и в браузерных окнах разной ширины. У телефона небольшой экран, и было бы круто не грузить полноразмерные картинки с большим разрешением. В CSS мы можем изменять фон элемента ([`background-image`](/css/doka/background-image)) в зависимости от ширины экрана, используя медиавыражения. Но если изображение является контентным, вставлено в HTML при помощи тега [`<img>`](/html/doka/img), то CSS нам уже не поможет. Мы должны использовать теги `<picture>` и [`<source>`](/html/doka/source).
```

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +Браузер анализирует каждый тег [`<source>`](/html/doka/source) по порядку, останавливается на первом подходящем под текущие условия и отображает картинку из атрибута `src`. Другие теги [`<source>`](/
```suggestion
Браузер анализирует каждый тег [`<source>`](/html/doka/source) по порядку, останавливается на первом подходящем под текущие условия и отображает картинку из атрибута `srcset`. Другие теги [`<source>`](/html/doka/source) не анализируются. Если тег `<picture>` не поддерживается браузером или ни один из тегов [`<source>`](/html/doka/source) не подходит под условия, то отображается картинка из тега [`<img>`](/html/doka/img).
```

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения на разных устройствах. Пользователи мобильных телефонов будут вам очень багодарны, если для них вы бу
```suggestion
💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения на разных устройствах. Пользователи мобильных телефонов будут вам очень благодарны, если для них вы будете готовить картинки с меньшим разрешением. В то же время пользователям настольных ПК с экранами высокой чёткости можно показывать картинки с увеличенным разрешением:
```

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения на разных устройствах. Пользователи мобильных телефонов будут вам очень багодарны, если для них вы бу
@tachisis я бы придумал, как нам нормализовать терминологию: настольные ПК, десктопные компьютеры, компьютеры, десктопы? Кажется ноутбук уже не настольный и свой Мак никто ПК не назовёт.

2021-05-05 11:39 UTC, pepelsbey commented on src/posts/html/doka/picture.md
> +В этом примере пользователи с обычными экранами увидят картинку с надписью `768x400`. Пользователи, у которых retina-дисплеи, увидят картинку с надписью `1536x800`
```suggestion
В этом примере пользователи с обычными экранами увидят картинку с надписью `768x400`. Пользователи, у которых ретиновые дисплеи, увидят картинку с надписью `1536x800`
```

2021-05-07 09:40 UTC, tachisis commented on src/posts/html/doka/picture.md
> +💡 Старайтесь при вёрстке всегда готовить несколько версий одной и той же картинки для отображения на разных устройствах. Пользователи мобильных телефонов будут вам очень багодарны, если для них вы бу
Я согласна, у нас вообще много устаревшей терминологии типа «веб-сайт», «веб-страница». В данном случае, думаю, «десктоп» нормально.

Допишу в руководство по стилю что-то вроде:

> Используйте современные термины — те, которые вы употребили бы в разговоре с коллегой.

Плохо: настольный ПК
Хорошо: десктоп

2021-05-11 18:19 UTC, tachisis reviewed
Еще немножко правочек (и надо принять те, которые от Вадима)

2021-06-07 09:12 UTC, pepelsbey approved these changes

2021-06-07 15:05 UTC, closed without merging