Cтатья о координатах
Y-Doka/y-doka.site pull request #713
Opened 2021-04-25 17:08 UTC by Windrushfarer

Closes #442

2021-04-25 17:10 UTC, Windrushfarer commented
У нас конечно не хватает статьи про position и getBoundingClientRect, я бы на них мог отлично сослаться. Я их затронул чуть-чуть, но не стал раскрывать, потому не уверен насколько хорошо получилось.

2021-04-25 17:12 UTC, Windrushfarer commented on src/posts/js/doka/coordinates.md
> +Позицинирование относительно документа так же можно понять, если посмотреть как располгается элемент с `position: absolute`. При прокрутке окна этот элемент будет смещаться вместе с ним.
Я тут конечно немного не прав, в том плане что `position: absolute` позиционируется относительно близжайшего `relative`. Но я не уверен как тут правильно акцентировать внимание на документе.

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Позиционирование с помощь координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего доку
```suggestion
Позиционирование с помощью координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего документа. Объекты события мыши и touch-события содержат координаты места на экране и в документе, где событие произошло: `pageX/pageY` – для документа, `clientX/clientY` – для экрана.
```

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Позиционирование с помощь координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего доку
На первый взгляд не очень понятна разница между «углом экрана» и «углом документа», кажется, что это одно и то же. Может сразу перефразировать или нарисовать проскролленное окно и разницу между началами координат? (До следующей секции можно не дочитать.)

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Координатами элемента является смещение в пикселях от его левого верхнего угла до осей системы координат. С помощью метода элемента `getBoundingClientRect` можно получить подробные данные о координат
> от его левого верхнего угла до осей системы координат

До положения элемента? (Проекций его положения на оси?)

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Позицинионирование относительно окна гораздо проще понять, если посмотреть как располагется элемент с `position: fixed`. Элемент с этим свойством будет находится в окне в одних и те же координатах, в
```suggestion
Позицинионирование относительно окна гораздо проще понять, если посмотреть, как располагается элемент с `position: fixed`. Элемент с этим свойством будет находиться в окне в одних и те же координатах, вне зависимости от того насколько прокручен документ.
```

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Информацию о том как элемент расположен относительно документа нельзя узнать из какого-то свойства или метода, ее необходимо вычислять самостоятельно. Самым простым способом это можно сделать сложив
```suggestion
Информацию о том, как элемент расположен относительно документа нельзя узнать из какого-то свойства или метода, ее необходимо вычислять самостоятельно. Самым простым способом это можно сделать сложив координаты относительно окна из метода `getBoundingClientRect` со смещением самого окна относительно документа. Смещение окна браузера можно узнать из полей `window.pageXOffset` и `window.pageYOffset` – это число пикселей на которое прокручен документ по горизонтали и вертикали.
```

2021-04-26 06:19 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Позицинирование относительно документа так же можно понять, если посмотреть как располгается элемент с `position: absolute`. При прокрутке окна этот элемент будет смещаться вместе с ним.
Можно в коллаут закинуть.

2021-04-26 08:35 UTC, Windrushfarer commented on src/posts/js/doka/coordinates.md
> +Позиционирование с помощь координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего доку
Да, я рисунок как раз приготовил для этого. Там должно быть все наглядно. Но улучшить текст я бы тоже хотел, если это улучшит восприятие

2021-04-26 11:44 UTC, bespoyasov commented on src/posts/js/doka/coordinates.md
> +Позиционирование с помощь координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего доку
Я там видел в следующей секции хорошее описание разницы:

> Начало системы координат можно отсчитывать относительно окна браузера, либо относительно всего документа. Когда страница не прокручена, то начала этих осей совпадают в левом верхнем углу окна. Если прокручивать страницу вниз, то соответсвенно начало координат документа останется таким же, а начало оси координат окно будет смещаться.

Может быть, получится прям его использовать? (Я не уверен, правда, можно ли его сократить и надо ли 😃)

2021-04-26 19:58 UTC, Windrushfarer commented on src/posts/js/doka/coordinates.md
> +Координатами элемента является смещение в пикселях от его левого верхнего угла до осей системы координат. С помощью метода элемента `getBoundingClientRect` можно получить подробные данные о координат
И правда, кажется я путаю с проекцией.

2021-04-26 20:19 UTC, Windrushfarer commented on src/posts/js/doka/coordinates.md
> +Позиционирование с помощь координат может быть относительно окна браузера или относительно отдельного элемента, т.е начало системы координат может считать как от угла экрана, так и от угла всего доку
Я все же попробовал объяснить здесь :)

2021-04-27 08:30 UTC, solarrust commented
_статья про `position` есть в новом репозитории_ @nlopin можно проставить ссылку при переносе

2021-04-27 10:13 UTC, bespoyasov reviewed
Вроде, всё ок. Что думаешь, @nlopin?

2021-04-27 10:14 UTC, bespoyasov commented
Картинки классные ^_^

2021-04-27 11:08 UTC, pepelsbey requested changes

2021-04-27 11:08 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +  console.log('Смещение Y относительно документа:', rect.y + pageYOffset)
```suggestion
const rect = element.getBoundingClientRect()

console.log('Смещение X относительно документа:', rect.x + pageXOffset)
console.log('Смещение Y относительно документа:', rect.y + pageYOffset)
```

2021-04-27 11:08 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +const foundElement = document.elementFromPoint(x, y);
```suggestion
const x = 1
const y = 0

const foundElement = document.elementFromPoint(x, y)
```

Лучше писать реальный код, который можно запустить. Плюс в JS есть очень похожий на `...` оператор ;)

2021-04-27 11:08 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +summary:
```suggestion
```

Пустые поля лучше дропнуть, а если какие-то из них нужны — заполнить. Например, `summary` кажется полезным.

2021-04-27 11:08 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +💡 Метод вернет самый глубоко вложенный в DOM-дереве по этим координатам, что может быть не тем изначально не элементом, что вам нужен
```suggestion
💡 Метод вернёт самый глубоко вложенный элемент в DOM-дереве по этим координатам, который может оказаться не тем, что вам нужен.
```

2021-04-27 11:08 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +🛠 Коррдинаты чаще всего используются для создания поведения перетаскивания элементов по экрану. Используя `clientX/clientY` или `pageX/pageY` из события можно менять координаты самого элемента.
```suggestion
🛠 Координаты чаще всего используются для создания поведения перетаскивания элементов по экрану. Используя `clientX/clientY` или `pageX/pageY` из события можно менять координаты самого элемента.
```

2021-04-27 12:55 UTC, tachisis commented on src/posts/js/doka/coordinates.md
> +Чтобы перемещать и [позиционировать](/js/long/element-positioning-js/) элементы на экране в браузере имеется система координат. Оси координат начинаются в левом верхнем углу экрана и идут вправо для
Насколько я вижу, принятое в математике правило набора: оси обозначаются «ось _x_» (с маленькой, италиком), точка — заглавной. Так что было правильно.

2021-04-27 17:53 UTC, pepelsbey commented on src/posts/js/doka/coordinates.md
> +Чтобы перемещать и [позиционировать](/js/long/element-positioning-js/) элементы на экране в браузере имеется система координат. Оси координат начинаются в левом верхнем углу экрана и идут вправо для
О, спасибо. Отказываюсь от показаний )

2021-04-29 00:12 UTC, pepelsbey approved these changes

2021-04-29 10:50 UTC, tachisis approved these changes

2021-04-29 11:03 UTC, bespoyasov approved these changes

2021-05-01 22:26 UTC, nlopin commented on src/posts/js/doka/coordinates.md
> +Система координат в браузера аналогична плоской системе координат из школьной алгебры. Есть две оси: ось _y_ и ось _x_, на этой плоскости располагатся все элементы сайта. Единственным отличием от кла
```suggestion
Система координат в браузера аналогична плоской системе координат из школьной алгебры. Есть две оси: ось _y_ и ось _x_, на этой плоскости располагатся все элементы сайта. Единственным отличием от классической системы координат является то, что положительное направление оси _y_ в браузере повернуто вниз. Это значит, что элементы с положительным значением по оси _y_ будут находится внизу относительно оси _y_, а с отрицательным – наверху.
```

2021-05-02 16:42 UTC, Windrushfarer commented on src/posts/js/doka/coordinates.md
> +Система координат в браузера аналогична плоской системе координат из школьной алгебры. Есть две оси: ось _y_ и ось _x_, на этой плоскости располагатся все элементы сайта. Единственным отличием от кла
Тут же верно написано. Ось _x_ находится сверху, потому что ось _y_ идёт вниз. И элементы _под ней_ будут иметь положительную координату. Взгляни например на рисунок мой.

2021-05-02 20:11 UTC, nlopin commented on src/posts/js/doka/coordinates.md
> +Система координат в браузера аналогична плоской системе координат из школьной алгебры. Есть две оси: ось _y_ и ось _x_, на этой плоскости располагатся все элементы сайта. Единственным отличием от кла
ты прав

2021-05-02 20:12 UTC, nlopin commented
Что дмаешь о демке? Мне кажется она очень поможет. Перенесу сюда комментарий из телеги:

> Демку бы туда: отрисовать обе оси координат и сделать длинную страницу с прокруткой, чтобы можно было покрутить и понять.
> Можно еще кнопку разместить по координатам, скажем 100, 100 и сделать переключалку, относительно какой системы координат рисовать

2021-05-05 08:41 UTC, Windrushfarer commented
@nlopin я добавил демку, но помоги мне ее настроить нормально. Из-за того, что контент внутри с большой высотой она растягивается на такое количество пикселей. Я не понял как ее сделать высотой в 300.
<img width="592" alt="Снимок экрана 2021-05-05 в 11 39 20" src="https://user-images.githubusercontent.com/8125574/117116262-d11d7380-ad96-11eb-9900-b1148b6f0881.png">

2021-05-05 22:08 UTC, nlopin commented
У нас автоматом растягивалось по вертикали. Добавил опцию, чтобы можно было это отключить

2021-05-06 21:56 UTC, nlopin approved these changes

2021-05-06 21:56 UTC, merged