Добавляет доку по Cookie
Y-Doka/y-doka.site pull request #725
Opened 2021-05-23 12:09 UTC by akellbl4

2021-05-26 10:35 UTC, nlopin requested changes
Класс, можно мержить, как этот раунд снимем

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +При разработке сайтов часто возникает необходимость сохранять различную информацию и иметь доступ к ней как в браузере, так и на сервере. Для этого используют **Cookie** (произносится «куки»).
Стоит дать немного контекста, что это обычно за информация. 

Мой вариант:
```suggestion
При разработке сайтов часть информации (например, токен авторизации или данные пользователя) нужно хранить и читать как в браузере, так и на сервере. Для этого используют **Cookie** (произносится «куки»).
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Стоит учитывать, что куки передаются в виде HTTP-заголовка, что накладывает на них многие ограничения. Например, размер в 4096 байт или отсутствие в содержимом пробелов или запятых. Чтобы обезопасить
Мы рекомендуем всегда вызывать `encodeURIComponent` или только когда есть пробелы? 

```suggestion
Куки передаются в виде HTTP-заголовка, это накладывает на них ограничения. Например, максимальный размер куки в 4096 байт или отсутствие в содержимом пробелов или запятых. Чтобы обезопасить содержимое, можно закодировать его с помощью функции `encodeURIComponent()`
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Также при установке cookie можно указывать не только ее название и значение, но и другие параметры, все они являются необязятельными и разделяются через `;`
```suggestion
При установке cookie можно указывать не только ее название и значение, но и другие параметры, все они являются необязательными и разделяются точкой с запятой `;`
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Запись куки с разрешением передавать ее только по HTTP и только для текущего домена, cо временем жизни в 1 час будет выглядеть как приведено ниже:
```suggestion
Запись куки с разрешением передавать ее только по HTTP и только для текущего домена, cо временем жизни в 1 час будет выглядеть так:
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +(картинка со всеми параметрами)
сможешь набросать скетч или описать?

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +### Чтение
насоклько помню, калауту нужны пустые строки вокруг

```suggestion

### Чтение
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Учитывая, что мы уже дважды записывали cookie, при вызове команды выше в консоли выведется `counter=1; sidebar=true;`.
мы выше ещё ветвистый `sidebar` устанавливаем. Давай длинную версию сюда добавим?

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Для кук не предусмотрено специального метода удаления, поэтому для этого используется трюк с установкой кук с параметром `expires` который указывает на дату в прошлом поэтому браузер сразу же считает
```suggestion
Для кук не предусмотрено специального метода удаления, поэтому для этого используется трюк с установкой кук с параметром `expires` который указывает на дату в прошлом. Браузер сразу же считает такую куку устаревшей и удаляет ее:
```

2021-05-26 10:35 UTC, nlopin commented on src/posts/js/doka/cookie.md
> +Будьте внимательнее, пытаясь получить куки, так как JavaScript имеет доступ не ко всем кукам. Если сервер устанавливает куки с параметром HttpOnly (доступен только для установки сервером), то такие c
Классный совет, я чуть перефразировал

```suggestion
Есть куки, которые нельзя прочитать или записать из JavaScript. Если сервер устанавливает куки с параметром HttpOnly (доступен только для установки сервером), то такие cookie будут недоступны в `document.cookie`. Как правило, такие куки используются для хранения чувствительной информации, как, например, токены для авторизации. Проверка авторизации происходит с помощью запроса с текущим авторизованным пользователем и считается при успешном ответе сервера.
```

2021-05-27 19:02 UTC, akellbl4 commented on src/posts/js/doka/cookie.md
> +(картинка со всеми параметрами)
Я скидывал в чатик, воткну ;)

2021-05-27 19:08 UTC, akellbl4 commented on src/posts/js/doka/cookie.md
> +Учитывая, что мы уже дважды записывали cookie, при вызове команды выше в консоли выведется `counter=1; sidebar=true;`.
эм, мы там ставим его с параметром и параметры потом не считываются, кажется это надо добавить :)

2021-05-27 21:06 UTC, pepelsbey commented
@nlopin а может мы сразу в контент ПР сделаем? Там и словарь есть, и точно все процессы норм.

2021-05-31 21:17 UTC, closed without merging